package gqlgenguard

import (
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	markedExec     = "// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.\n\npackage gen\n\nconst Exec = \"tree\"\n"
	markedModel    = "// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.\n\npackage model\n\nconst Model = \"tree\"\n"
	markedResolver = "package gen\n\n// This file will not be regenerated automatically.\n\ntype Resolver struct{}\n"

	guardConfig = `
schema: [schema.graphql]
exec: {filename: gen/generated.go, package: gen}
model: {filename: gen/model/models_gen.go, package: model}
resolver: {layout: single-file, filename: gen/resolver.go, package: gen}
`
)

// guardFixture is the tree every behavioural test starts from: three declared
// outputs that already carry gqlgen's provenance notices, and one hand-written
// file that is not an output and must never move.
func guardFixture(t *testing.T) *fixture {
	t.Helper()
	return newFixture(t, map[string]string{
		"gqlgen.yml":                guardConfig,
		"schema.graphql":            fixtureSchema,
		"gen/generated.go":          markedExec,
		"gen/model/models_gen.go":   markedModel,
		"gen/resolver.go":           markedResolver,
		"gen/handwritten_helper.go": "package gen\n\nfunc Helper() string { return \"untouched\" }\n",
		"unrelated/notes.md":        "not an output\n",
	})
}

func guardOptions(f *fixture, gen Generator) Options {
	return Options{
		ModuleDir:  f.dir,
		ConfigPath: "gqlgen.yml",
		DriftPath:  "contracts/expected-drift.record",
		Generator:  gen,
		TempParent: f.t.TempDir(),
		Report:     io.Discard,
	}
}

// rewriteOutputs is the ordinary case: the generator rewrites every declared
// output with new content.
func rewriteOutputs(body string) func(workDir string) error {
	return func(workDir string) error {
		for _, rel := range []string{"gen/generated.go", "gen/model/models_gen.go"} {
			if err := writeIn(workDir, rel, strings.Replace(bodyFor(rel), "tree", body, 1)); err != nil {
				return err
			}
		}
		return nil
	}
}

func bodyFor(rel string) string {
	switch rel {
	case "gen/generated.go":
		return markedExec
	case "gen/model/models_gen.go":
		return markedModel
	default:
		return markedResolver
	}
}

// TestGuardRefusesAndLeavesTheTreeUntouched covers every reason the guard
// refuses to trust a generation. Each row asserts three things at once: that
// the refusal happened, that it NAMED its reason, and that the working tree is
// byte for byte what it was -- because a refusal that still wrote something is
// the failure this whole design exists to prevent.
func TestGuardRefusesAndLeavesTheTreeUntouched(t *testing.T) {
	cases := []struct {
		name string
		// setup runs against the fixture before the guard does.
		setup func(t *testing.T, f *fixture)
		// gen is the generator behaviour under test.
		gen func(workDir string) error
		// wantErr is a substring the refusal must contain.
		wantErr string
		// wantGeneratorRan says whether the generator should have been reached
		// at all. A refusal that happens BEFORE generation is a stronger
		// property than one that happens after, and the two are otherwise
		// indistinguishable from the caller's side.
		wantGeneratorRan bool
	}{
		{
			name:             "the generator exits non-zero",
			gen:              func(string) error { return errors.New("exit status 1") },
			wantErr:          "generator failed",
			wantGeneratorRan: true,
		},
		{
			name: "the generator writes a file the configuration does not declare",
			gen: func(workDir string) error {
				if err := rewriteOutputs("generated")(workDir); err != nil {
					return err
				}
				return writeIn(workDir, "gen/surprise.go", "package gen\n")
			},
			wantErr:          "gen/surprise.go",
			wantGeneratorRan: true,
		},
		{
			name: "the generator writes an unexpected file with a NON-.go extension",
			gen: func(workDir string) error {
				return writeIn(workDir, "gen/surprise.txt", "not go\n")
			},
			// A guard that scanned only *.go would report success here.
			wantErr:          "gen/surprise.txt",
			wantGeneratorRan: true,
		},
		{
			name: "the generator writes an unexpected file in a NESTED directory",
			gen: func(workDir string) error {
				return writeIn(workDir, "gen/deeply/nested/surprise.go", "package nested\n")
			},
			// A scan bounded to one directory level would not reach this.
			wantErr:          "gen/deeply/nested/surprise.go",
			wantGeneratorRan: true,
		},
		{
			name: "the generator reports success but deleted a checked-in output",
			gen: func(workDir string) error {
				return os.Remove(filepath.Join(workDir, "gen", "generated.go"))
			},
			wantErr:          "removed \"gen/generated.go\"",
			wantGeneratorRan: true,
		},
		{
			name: "a declared output is a hand-written file with no provenance notice",
			setup: func(t *testing.T, f *fixture) {
				f.write("gen/generated.go", "package gen\n\n// written by a person, not a generator\n")
			},
			wantErr:          "hand-written",
			wantGeneratorRan: false,
		},
		{
			name: "a declared output is a symbolic link in the working tree",
			setup: func(t *testing.T, f *fixture) {
				full := filepath.Join(f.dir, "gen", "generated.go")
				if err := os.Remove(full); err != nil {
					t.Fatalf("remove the output: %v", err)
				}
				if err := os.Symlink("model/models_gen.go", full); err != nil {
					t.Fatalf("plant the symbolic link: %v", err)
				}
			},
			wantErr:          "symbolic link",
			wantGeneratorRan: false,
		},
		{
			name: "the configuration names an output outside the module",
			setup: func(t *testing.T, f *fixture) {
				f.write("gqlgen.yml", strings.Replace(guardConfig,
					"exec: {filename: gen/generated.go, package: gen}",
					"exec: {filename: ../escaped/generated.go, package: gen}", 1))
			},
			wantErr:          "resolves outside the module root",
			wantGeneratorRan: false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			f := guardFixture(t)
			if tc.setup != nil {
				tc.setup(t, f)
			}
			before := f.digests()

			gen := &fakeGenerator{name: "fake", fn: tc.gen}
			_, err := CheckDrift(context.Background(), guardOptions(f, gen))
			if err == nil {
				t.Fatalf("expected a refusal containing %q, got success", tc.wantErr)
			}
			if !strings.Contains(err.Error(), tc.wantErr) {
				t.Fatalf("refusal does not name its reason:\n  got  %v\n  want it to contain %q", err, tc.wantErr)
			}
			if gen.ran != tc.wantGeneratorRan {
				t.Fatalf("generator ran = %v, want %v (a refusal before generation is a different, stronger property)",
					gen.ran, tc.wantGeneratorRan)
			}
			assertUnchanged(t, before, f.digests(), "CheckDrift refusal")

			// The same refusal must hold for the verb that DOES write.
			f2 := guardFixture(t)
			if tc.setup != nil {
				tc.setup(t, f2)
			}
			before2 := f2.digests()
			gen2 := &fakeGenerator{name: "fake", fn: tc.gen}
			if _, err := Generate(context.Background(), guardOptions(f2, gen2)); err == nil {
				t.Fatalf("Generate accepted what CheckDrift refused (%q)", tc.wantErr)
			}
			assertUnchanged(t, before2, f2.digests(), "Generate refusal")
		})
	}
}

// TestAnEscapingSymbolicLinkIsReproducedAndStaysUnreadable is the executed
// form of the confinement claim.
//
// A link whose target is absolute, or leaves the tree, is copied VERBATIM
// rather than refused -- refusing would make the guard unusable in any checkout
// carrying a virtual environment or a toolchain cache, both of which are full
// of absolute links. What makes that safe is not a rule about targets: every
// read the guard performs goes through an *os.Root, and the operating system
// refuses to traverse such a link at all. This asserts BOTH halves.
func TestAnEscapingSymbolicLinkIsReproducedAndStaysUnreadable(t *testing.T) {
	f := guardFixture(t)
	secret := filepath.Join(t.TempDir(), "outside.txt")
	if err := os.WriteFile(secret, []byte("must never be read through the link\n"), 0o600); err != nil {
		t.Fatalf("seed: %v", err)
	}
	for name, target := range map[string]string{
		"absolute.txt": secret,
		"relative.txt": "../../../../etc/hostname",
	} {
		if err := os.Symlink(target, filepath.Join(f.dir, name)); err != nil {
			t.Fatalf("plant %s: %v", name, err)
		}
	}
	gen := &fakeGenerator{fn: func(workDir string) error {
		// The copy carries the links, as links, with their target text intact.
		for name, want := range map[string]string{
			"absolute.txt": secret,
			"relative.txt": "../../../../etc/hostname",
		} {
			got, err := os.Readlink(filepath.Join(workDir, name))
			if err != nil {
				return err
			}
			if got != want {
				return errors.New(name + " was not reproduced: " + got)
			}
		}
		return rewriteOutputs("generated")(workDir)
	}}

	opts := guardOptions(f, gen)
	if _, err := UpdateDriftRecord(context.Background(), opts); err != nil {
		t.Fatalf("the guard refused a tree containing ordinary absolute links: %v", err)
	}
	if !gen.ran {
		t.Fatal("the generator never ran")
	}

	before := f.digests()
	if _, err := CheckDrift(context.Background(), guardOptions(f, &fakeGenerator{fn: gen.fn})); err != nil {
		t.Fatalf("the drift check refused a tree containing ordinary absolute links: %v", err)
	}

	// The links are recorded as links, never as their targets' content.
	root, err := os.OpenRoot(f.dir)
	if err != nil {
		t.Fatalf("open the fixture root: %v", err)
	}
	defer root.Close()
	snap, err := TakeSnapshot(root, skipVCS)
	if err != nil {
		t.Fatalf("snapshot: %v", err)
	}
	if got := snap["absolute.txt"].Digest; got != "symlink:"+secret {
		t.Fatalf("the absolute link was digested as %q, not as a link", got)
	}

	// And the guard cannot read through them: this is the confinement itself,
	// executed, not asserted.
	if _, err := ReadThroughRoot(root, "absolute.txt"); err == nil {
		t.Fatal("the guard read a file outside the module through a symbolic link")
	}
	if _, err := ReadThroughRoot(root, "relative.txt"); err == nil {
		t.Fatal("the guard read a file outside the module through a relative escaping link")
	}

	assertUnchanged(t, before, f.digests(), "a tree containing escaping links")
}

// TestModuleFilesAreNeverCopiedBack pins the property that makes a tidy
// harmless: the generator may rewrite go.mod and go.sum inside its own copy
// (gqlgen runs `go mod tidy` unless told not to, and in a reduced module that
// tidy removes most of the require block), and the real module still comes out
// byte for byte identical.
func TestModuleFilesAreNeverCopiedBack(t *testing.T) {
	f := guardFixture(t)
	f.write("go.mod", "module example.com/fixture\n\ngo 1.27.0\n\nrequire example.com/kept v1.0.0\n")
	f.write("go.sum", "example.com/kept v1.0.0 h1:abc=\n")

	beforeMod := f.read("go.mod")
	beforeSum := f.read("go.sum")
	before := f.digests()

	gen := &fakeGenerator{name: "tidying fake", fn: func(workDir string) error {
		if err := rewriteOutputs("generated")(workDir); err != nil {
			return err
		}
		// Exactly what a tidy does in a reduced module: drop the requires.
		if err := writeIn(workDir, "go.mod", "module example.com/fixture\n\ngo 1.27.0\n"); err != nil {
			return err
		}
		return writeIn(workDir, "go.sum", "")
	}}

	res, err := Generate(context.Background(), guardOptions(f, gen))
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if len(res.ModuleFileRewrites) != 2 {
		t.Fatalf("expected the tidy to be reported for go.mod and go.sum, got %v", res.ModuleFileRewrites)
	}
	if got := f.read("go.mod"); got != beforeMod {
		t.Fatalf("go.mod changed:\n got  %q\n want %q", got, beforeMod)
	}
	if got := f.read("go.sum"); got != beforeSum {
		t.Fatalf("go.sum changed:\n got  %q\n want %q", got, beforeSum)
	}

	// Only the declared outputs moved. Everything else, module files included,
	// is exactly as it was.
	after := f.digests()
	for rel, b := range before {
		if rel == "gen/generated.go" || rel == "gen/model/models_gen.go" {
			continue
		}
		if after[rel] != b {
			t.Fatalf("%s changed but is not a declared output", rel)
		}
	}
}

// TestGenerateCopiesBackOnlyTheDeclaredOutputsThatChanged pins the write half:
// what lands, what does not, and that an untouched output is not rewritten.
func TestGenerateCopiesBackOnlyTheDeclaredOutputsThatChanged(t *testing.T) {
	f := guardFixture(t)
	before := f.digests()

	gen := &fakeGenerator{fn: func(workDir string) error {
		// Rewrite one output, leave the second byte-identical, do not touch
		// the third at all.
		return writeIn(workDir, "gen/generated.go", strings.Replace(markedExec, "tree", "regenerated", 1))
	}}

	res, err := Generate(context.Background(), guardOptions(f, gen))
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if len(res.Applied) != 1 || res.Applied[0] != "gen/generated.go" {
		t.Fatalf("applied %v, want exactly [gen/generated.go]", res.Applied)
	}
	if got := f.read("gen/generated.go"); !strings.Contains(got, "regenerated") {
		t.Fatalf("the changed output was not copied back: %q", got)
	}

	after := f.digests()
	for rel, b := range before {
		if rel == "gen/generated.go" {
			if after[rel] == b {
				t.Fatalf("gen/generated.go did not change")
			}
			continue
		}
		if after[rel] != b {
			t.Fatalf("%s changed and should not have", rel)
		}
	}
	if got := f.read("gen/handwritten_helper.go"); !strings.Contains(got, "untouched") {
		t.Fatalf("a hand-written file beside the outputs was rewritten: %q", got)
	}
}

// TestCheckDriftComparesTheRecordByteForByte covers the drift comparison in
// both directions and the states around it.
func TestCheckDriftComparesTheRecordByteForByte(t *testing.T) {
	t.Run("no record committed", func(t *testing.T) {
		f := guardFixture(t)
		before := f.digests()
		_, err := CheckDrift(context.Background(), guardOptions(f, &fakeGenerator{fn: rewriteOutputs("generated")}))
		if err == nil || !strings.Contains(err.Error(), "no expected-drift record") {
			t.Fatalf("expected a refusal naming the missing record, got %v", err)
		}
		assertUnchanged(t, before, f.digests(), "CheckDrift with no record")
	})

	t.Run("matching record passes and writes nothing", func(t *testing.T) {
		f := guardFixture(t)
		opts := guardOptions(f, &fakeGenerator{fn: rewriteOutputs("generated")})
		if _, err := UpdateDriftRecord(context.Background(), opts); err != nil {
			t.Fatalf("update the record: %v", err)
		}
		before := f.digests()
		if _, err := CheckDrift(context.Background(), opts); err != nil {
			t.Fatalf("check against the record just written: %v", err)
		}
		assertUnchanged(t, before, f.digests(), "CheckDrift against a matching record")
	})

	t.Run("NEW drift is refused", func(t *testing.T) {
		f := guardFixture(t)
		if _, err := UpdateDriftRecord(context.Background(), guardOptions(f, &fakeGenerator{fn: rewriteOutputs("generated")})); err != nil {
			t.Fatalf("update the record: %v", err)
		}
		// A later generation produces different output than the record says.
		_, err := CheckDrift(context.Background(), guardOptions(f, &fakeGenerator{fn: rewriteOutputs("something else")}))
		if err == nil {
			t.Fatal("expected a refusal for new drift")
		}
		if !strings.Contains(err.Error(), "does not match") || !strings.Contains(err.Error(), "digests that moved") {
			t.Fatalf("the refusal does not report the moved digests: %v", err)
		}
	})

	t.Run("a VANISHED hand-edit is refused, not only new drift", func(t *testing.T) {
		f := guardFixture(t)
		// The record is taken while the tree carries a hand-edit the generator
		// reverts.
		if _, err := UpdateDriftRecord(context.Background(), guardOptions(f, &fakeGenerator{fn: rewriteOutputs("generated")})); err != nil {
			t.Fatalf("update the record: %v", err)
		}
		// Now the hand-edit is gone: the tree matches a fresh generation, so
		// there is NO drift at all. A subset check would pass here; that is
		// exactly the direction a nullability ruling silently reverts in.
		f.write("gen/generated.go", strings.Replace(markedExec, "tree", "generated", 1))
		f.write("gen/model/models_gen.go", strings.Replace(markedModel, "tree", "generated", 1))

		_, err := CheckDrift(context.Background(), guardOptions(f, &fakeGenerator{fn: rewriteOutputs("generated")}))
		if err == nil {
			t.Fatal("expected a refusal: the recorded hand-edits vanished")
		}
		if !strings.Contains(err.Error(), "does not match") {
			t.Fatalf("unexpected refusal: %v", err)
		}
	})

	t.Run("a hand-edited record is refused", func(t *testing.T) {
		f := guardFixture(t)
		opts := guardOptions(f, &fakeGenerator{fn: rewriteOutputs("generated")})
		if _, err := UpdateDriftRecord(context.Background(), opts); err != nil {
			t.Fatalf("update the record: %v", err)
		}
		record := f.read("contracts/expected-drift.record")
		f.write("contracts/expected-drift.record", strings.Replace(record, "digest drift", "digest same", 1))
		if _, err := CheckDrift(context.Background(), opts); err == nil {
			t.Fatal("expected a refusal for a hand-edited record")
		}
	})

	t.Run("a record with its explanation deleted is refused", func(t *testing.T) {
		f := guardFixture(t)
		opts := guardOptions(f, &fakeGenerator{fn: rewriteOutputs("generated")})
		if _, err := UpdateDriftRecord(context.Background(), opts); err != nil {
			t.Fatalf("update the record: %v", err)
		}
		record := f.read("contracts/expected-drift.record")
		f.write("contracts/expected-drift.record", strings.TrimPrefix(record, recordHeader))
		if _, err := CheckDrift(context.Background(), opts); err == nil {
			t.Fatal("expected a refusal after the record's explanation was removed")
		}
	})

	t.Run("no drift at all still produces a comparable record", func(t *testing.T) {
		f := guardFixture(t)
		opts := guardOptions(f, &fakeGenerator{fn: func(string) error { return nil }})
		res, err := UpdateDriftRecord(context.Background(), opts)
		if err != nil {
			t.Fatalf("update the record: %v", err)
		}
		if res.Drifted() {
			t.Fatal("a generator that wrote nothing produced drift")
		}
		if !strings.Contains(res.Record, "no drift") {
			t.Fatalf("the record does not say there is no drift:\n%s", res.Record)
		}
		if _, err := CheckDrift(context.Background(), opts); err != nil {
			t.Fatalf("check a no-drift record: %v", err)
		}
	})
}

// TestCancellationLeavesTheTreeUntouched covers the in-process half of
// interrupt safety: a context cancelled at any stage refuses, and the tree is
// what it was. The signal half -- a real SIGINT to a real process running the
// real generator -- is TestInterruptingTheBinaryLeavesTheTreeUntouched.
func TestCancellationLeavesTheTreeUntouched(t *testing.T) {
	stages := []struct {
		name   string
		cancel func(cancel context.CancelFunc, workDir string) error
	}{
		{
			name: "cancelled before the guard starts",
			cancel: func(context.CancelFunc, string) error {
				return nil
			},
		},
		{
			name: "cancelled while the generator is running",
			cancel: func(cancel context.CancelFunc, workDir string) error {
				// Write the outputs first, so a guard that ignored the
				// cancellation would have something real to copy back and the
				// assertion below would catch it.
				if err := rewriteOutputs("generated")(workDir); err != nil {
					return err
				}
				cancel()
				return nil
			},
		},
	}

	for _, st := range stages {
		t.Run(st.name, func(t *testing.T) {
			f := guardFixture(t)
			before := f.digests()

			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			if st.name == "cancelled before the guard starts" {
				cancel()
			}

			gen := &fakeGenerator{fn: func(workDir string) error { return st.cancel(cancel, workDir) }}
			_, err := Generate(ctx, guardOptions(f, gen))
			if err == nil {
				t.Fatal("expected a refusal after cancellation")
			}
			if !errors.Is(err, context.Canceled) {
				t.Fatalf("the refusal does not carry the cancellation: %v", err)
			}
			assertUnchanged(t, before, f.digests(), st.name)
		})
	}
}

// TestAGeneratorThatIGNORESCancellationStillWritesNothing reaches the guard's
// own post-generation refusal.
//
// Every other cancellation test exercises the path where the GENERATOR reports
// the failure. A generator that does not watch its context -- and a real one
// killed a microsecond too late is exactly that -- returns success, and the
// guard has to be the thing that refuses. Measured: with this test absent, a
// mutant removing that refusal survived the whole suite.
func TestAGeneratorThatIGNORESCancellationStillWritesNothing(t *testing.T) {
	f := guardFixture(t)
	before := f.digests()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	gen := (&fakeGenerator{fn: func(workDir string) error {
		if err := rewriteOutputs("generated")(workDir); err != nil {
			return err
		}
		cancel()
		// Reports SUCCESS despite the cancellation.
		return nil
	}}).ignoresCancellation()

	_, err := Generate(ctx, guardOptions(f, gen))
	if err == nil {
		t.Fatal("the guard wrote the outputs of a run that was cancelled")
	}
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("the refusal does not carry the cancellation: %v", err)
	}
	if !gen.ran {
		t.Fatal("the generator never ran, so this proves nothing")
	}
	assertUnchanged(t, before, f.digests(), "a cancelled run whose generator reported success")
}

// TestSplitLinesKeepsExactlyTheFilesLines pins the record's line splitting.
//
// difflib's own SplitLines appends a newline to its last element, which for a
// file that ends in one produces a phantom empty line. That difference does not
// always change a hunk, so the record comparison alone does not see it --
// measured: a mutant swapping this function for difflib's survived every other
// test. This is the test that reads the function itself.
func TestSplitLinesKeepsExactlyTheFilesLines(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want []string
	}{
		{"empty", "", nil},
		{"one line with a trailing newline", "a\n", []string{"a\n"}},
		{"one line with NO trailing newline", "a", []string{"a\n"}},
		{"two lines", "a\nb\n", []string{"a\n", "b\n"}},
		{"a blank final line is a real line", "a\n\n", []string{"a\n", "\n"}},
		{"only a newline", "\n", []string{"\n"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := splitLines(tc.in)
			if len(got) != len(tc.want) {
				t.Fatalf("splitLines(%q) = %q, want %q", tc.in, got, tc.want)
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Fatalf("splitLines(%q)[%d] = %q, want %q", tc.in, i, got[i], tc.want[i])
				}
			}
		})
	}
}

// TestAtomicWriteCannotLeaveItsRoot pins the confinement of the one operation
// that writes to the working tree.
func TestAtomicWriteCannotLeaveItsRoot(t *testing.T) {
	dir := t.TempDir()
	outside := filepath.Join(dir, "outside.txt")
	if err := os.WriteFile(outside, []byte("original\n"), 0o644); err != nil {
		t.Fatalf("seed: %v", err)
	}
	inner := filepath.Join(dir, "module")
	if err := os.Mkdir(inner, 0o755); err != nil {
		t.Fatalf("create the module dir: %v", err)
	}
	root, err := os.OpenRoot(inner)
	if err != nil {
		t.Fatalf("open root: %v", err)
	}
	defer root.Close()

	for _, rel := range []string{"../outside.txt", "../../outside.txt", "/etc/hostname"} {
		if err := AtomicWrite(root, rel, []byte("overwritten\n"), 0o644); err == nil {
			t.Fatalf("AtomicWrite accepted %q, which leaves the root", rel)
		}
	}
	if got, _ := os.ReadFile(outside); string(got) != "original\n" {
		t.Fatalf("a file outside the root was modified: %q", got)
	}
}

// TestSnapshotRefusesToFollowASymbolicLinkOutOfTheTree pins that the digest
// walk records a link as a link rather than following it, so a link swapped in
// for a real file is drift rather than an invisible substitution.
func TestSnapshotRefusesToFollowASymbolicLinkOutOfTheTree(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "real.txt"), []byte("content\n"), 0o644); err != nil {
		t.Fatalf("seed: %v", err)
	}
	if err := os.Symlink("/etc/hostname", filepath.Join(dir, "link.txt")); err != nil {
		t.Fatalf("plant the link: %v", err)
	}
	root, err := os.OpenRoot(dir)
	if err != nil {
		t.Fatalf("open root: %v", err)
	}
	defer root.Close()
	snap, err := TakeSnapshot(root, skipVCS)
	if err != nil {
		t.Fatalf("snapshot: %v", err)
	}
	if got := snap["link.txt"].Digest; got != "symlink:/etc/hostname" {
		t.Fatalf("a symbolic link was digested as its target's content: %q", got)
	}
}
