"""Admin API schemas package.

Re-exports everything from the flat schemas.py module so that existing
``from dev_health_ops.api.admin.schemas import ...`` imports continue to work
now that schemas/ is a package directory.
"""

from __future__ import annotations

# Re-export the entire flat module's public surface.
from dev_health_ops.api.admin.schemas_flat import *  # noqa: F401, F403
from dev_health_ops.api.admin.schemas_flat import (  # noqa: F401
    JOB_RUN_STATUS_LABELS,
    ApproveChangesRequest,
    AuditLogFilter,
    AuditLogListResponse,
    AuditLogResponse,
    BackfillRequest,
    ConfirmInferredMemberAction,
    ConfirmInferredMembersRequest,
    ConfirmInferredMembersResponse,
    ConfirmMemberLink,
    ConfirmMembersRequest,
    ConfirmMembersResponse,
    DeletionResultResponse,
    DeletionScopeResponse,
    DiscoveredMember,
    DiscoveredRepo,
    DiscoveredReposResponse,
    DiscoveredTeam,
    DismissChangesRequest,
    FeatureFlagResponse,
    FeatureFlagUpdateRequest,
    FeatureOverrideCreate,
    FeatureOverrideResponse,
    FeatureOverrideUpdate,
    FlaggedChange,
    IdentityMappingCreate,
    IdentityMappingResponse,
    IdentityMappingUpdate,
    ImpersonateTargetUser,
    ImpersonationStatusResponse,
    InferredMember,
    IntegrationCredentialCreate,
    IntegrationCredentialResponse,
    IntegrationCredentialUpdate,
    IPAllowlistCreate,
    IPAllowlistListResponse,
    IPAllowlistResponse,
    IPAllowlistUpdate,
    IPCheckRequest,
    IPCheckResponse,
    JiraActivityInferenceResponse,
    JobRunResponse,
    LLMSettingsResponse,
    LLMSettingsStatusResponse,
    LLMSettingsUpsert,
    LLMSpendLegacyUsage,
    LLMSpendResponse,
    LLMSpendRun,
    MemberMatchResult,
    MembershipCreate,
    MembershipResponse,
    MembershipUpdateRole,
    OrganizationCreate,
    OrganizationResponse,
    OrganizationUpdate,
    OrgInviteCreate,
    OrgInviteResponse,
    OwnershipTransfer,
    PendingChangesResponse,
    PlatformStatsResponse,
    RetentionExecuteRequest,
    RetentionExecuteResponse,
    RetentionPolicyCreate,
    RetentionPolicyListResponse,
    RetentionPolicyResponse,
    RetentionPolicyUpdate,
    SettingCreate,
    SettingResponse,
    SettingsListResponse,
    SettingUpdate,
    StartImpersonationRequest,
    StartImpersonationResponse,
    StopImpersonationResponse,
    SyncConfigBatchCreate,
    SyncConfigBatchResponse,
    SyncConfigCreate,
    SyncConfigRepositorySelection,
    SyncConfigRepositorySelectionUpdate,
    SyncConfigResponse,
    SyncConfigUpdate,
    SyncCoverageDataset,
    SyncCoverageOverall,
    SyncCoverageRange,
    SyncCoverageSource,
    SyncCoverageSummaryResponse,
    SyncRunJobEnrichment,
    TeamDiscoverResponse,
    TeamImportRequest,
    TeamImportResponse,
    TeamMappingCreate,
    TeamMappingResponse,
    TeamMappingUpdate,
    TeamMembersDiscoverResponse,
    TestConnectionRequest,
    TestConnectionResponse,
    UserCreate,
    UserResponse,
    UserSetPassword,
    UserUpdate,
)
