package aggflame

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"
	"time"

	dhclickhouse "github.com/full-chaos/dev-health-go/clickhouse"
)

// fixtureRowScanner replays a fixed slice of pre-built rows -- same shape
// as internal/quadrant/golden_test.go's fixtureRowScanner, extended with a
// *uint64 case for this package's sum()/uniqExact()-typed columns.
type fixtureRowScanner struct {
	rows  [][]any
	index int
}

func (s *fixtureRowScanner) Next() bool {
	if s.index >= len(s.rows) {
		return false
	}
	s.index++
	return true
}

func (s *fixtureRowScanner) Scan(dest ...any) error {
	row := s.rows[s.index-1]
	for i, d := range dest {
		switch typed := d.(type) {
		case *time.Time:
			*typed = row[i].(time.Time)
		case *string:
			*typed = row[i].(string)
		case *float64:
			*typed = row[i].(float64)
		case *uint64:
			*typed = row[i].(uint64)
		}
	}
	return nil
}

func (s *fixtureRowScanner) Err() error   { return nil }
func (s *fixtureRowScanner) Close() error { return nil }

type fakeQueryClient struct {
	t       *testing.T
	handler func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error)
}

func (c fakeQueryClient) Query(_ context.Context, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
	return c.handler(c.t, query, bindings)
}

func day(y int, m time.Month, d int) time.Time {
	return time.Date(y, m, d, 0, 0, 0, 0, time.UTC)
}

// loadGolden decodes a testdata JSON file generated by this package's own
// uncommitted capture script (see this package's own doc comment's
// TEST-EVIDENCE-cited command) into a Response. DisallowUnknownFields
// makes a field-name mismatch (Python emitted a key this Go type does not
// declare) a hard test failure rather than a silent drop.
func loadGolden(t *testing.T, name string) Response {
	t.Helper()
	data, err := os.ReadFile("testdata/" + name)
	if err != nil {
		t.Fatalf("read golden %s: %v", name, err)
	}
	var resp Response
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&resp); err != nil {
		t.Fatalf("decode golden %s: %v", name, err)
	}
	return resp
}

func assertGolden(t *testing.T, got *Response, goldenName string) {
	t.Helper()
	want := loadGolden(t, goldenName)
	if !reflect.DeepEqual(*got, want) {
		t.Fatalf("response mismatch\n got:  %+v\n want: %+v", *got, want)
	}
}

// assertBindingValue fails the test unless bindings carries exactly one
// entry named name with the given string value -- a fixture handler's own
// proof that a filter's bound value reached the query, not just that some
// binding with that name exists.
func assertBindingValue(t *testing.T, bindings []dhclickhouse.Binding, name, want string) {
	t.Helper()
	for _, b := range bindings {
		if b.Name == name {
			if b.Value != want {
				t.Fatalf("binding %q: got %v, want %q", name, b.Value, want)
			}
			return
		}
	}
	t.Fatalf("no binding named %q (have %+v)", name, bindings)
}

// TestGoldenCycleBreakdownBasic replays testdata/cycle_breakdown_basic.json:
// fetch_cycle_breakdown returns five rows across four live categories (one
// filtered out for total_hours<=0), team_id/work_scope_id filters set,
// provider absent. The handler asserts both filter clauses are actually IN
// the query text and both values actually reached the bindings -- not just
// that Params.TeamID/WorkScopeID were set -- so this test fails if either
// `AND team_id = ...`/`AND work_scope_id = ...` clause in fetchCycleBreakdown
// (clickhouse.go) is ever deleted or its binding dropped.
func TestGoldenCycleBreakdownBasic(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		if !strings.Contains(query, "FROM work_item_state_durations_daily") {
			t.Fatalf("unexpected query for cycle_breakdown_basic fixture:\n%s", query)
		}
		if !strings.Contains(query, "AND team_id = {team_id:String}") {
			t.Fatalf("cycle_breakdown_basic fixture: query missing the team_id filter clause:\n%s", query)
		}
		if !strings.Contains(query, "AND work_scope_id = {work_scope_id:String}") {
			t.Fatalf("cycle_breakdown_basic fixture: query missing the work_scope_id filter clause:\n%s", query)
		}
		assertBindingValue(t, bindings, "team_id", "team-a")
		assertBindingValue(t, bindings, "work_scope_id", "scope-1")
		return &fixtureRowScanner{rows: [][]any{
			{"in_progress", 120.5, uint64(10)},
			{"Blocked", 40.0, uint64(3)},
			{"review", 80.25, uint64(5)},
			{"custom_status", 15.0, uint64(1)},
			{"ready", 0.0, uint64(2)},
		}}, nil
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Mode: "cycle_breakdown", StartDay: day(2024, 1, 1), EndDay: day(2024, 1, 31),
		TeamID: "team-a", WorkScopeID: "scope-1", Limit: 500, MinValue: 1,
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	assertGolden(t, got, "cycle_breakdown_basic.json")
}

// TestGoldenCycleBreakdownMilestoneFallback replays testdata/
// cycle_breakdown_milestone_fallback.json: fetch_cycle_breakdown returns
// no rows, fetch_cycle_milestones returns two, both remapped into the
// "Other" category and multiplied avg_hours*total_items.
func TestGoldenCycleBreakdownMilestoneFallback(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		switch {
		case strings.Contains(query, "FROM work_item_state_durations_daily"):
			return &fixtureRowScanner{}, nil
		case strings.Contains(query, "FROM work_item_cycle_milestones_daily"):
			return &fixtureRowScanner{rows: [][]any{
				{"design", 10.0, uint64(4)},
				{"build", 5.5, uint64(8)},
			}}, nil
		default:
			t.Fatalf("unexpected query for cycle_breakdown_milestone_fallback fixture:\n%s", query)
			return nil, nil
		}
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Mode: "cycle_breakdown", StartDay: day(2024, 2, 1), EndDay: day(2024, 2, 15),
		Provider: "prov-x", Limit: 500, MinValue: 1,
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	assertGolden(t, got, "cycle_breakdown_milestone_fallback.json")
}

// TestGoldenCycleBreakdownEmpty replays testdata/cycle_breakdown_empty.json:
// both readers return no rows -- zero-value root, no notes, no filters.
func TestGoldenCycleBreakdownEmpty(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		return &fixtureRowScanner{}, nil
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Mode: "cycle_breakdown", StartDay: day(2024, 3, 1), EndDay: day(2024, 3, 5),
		Limit: 500, MinValue: 1,
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	assertGolden(t, got, "cycle_breakdown_empty.json")
}

// TestGoldenCodeHotspotsBasic replays testdata/code_hotspots_basic.json:
// two repos, a nested directory tree under repo-1, a single top-level file
// under repo-2, both repo names resolved via fetch_repo_names.
func TestGoldenCodeHotspotsBasic(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		switch {
		case strings.Contains(query, "FROM file_metrics_daily"):
			return &fixtureRowScanner{rows: [][]any{
				{"repo-1", "src/app/main.rs", uint64(50)},
				{"repo-1", "src/app/utils.rs", uint64(30)},
				{"repo-1", "src/lib/helper.rs", uint64(20)},
				{"repo-2", "README.md", uint64(5)},
			}}, nil
		case strings.Contains(query, "FROM repos FINAL"):
			return &fixtureRowScanner{rows: [][]any{
				{"repo-1", "Alpha Repo"},
				{"repo-2", "Beta Repo"},
			}}, nil
		default:
			t.Fatalf("unexpected query for code_hotspots_basic fixture:\n%s", query)
			return nil, nil
		}
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Mode: "code_hotspots", StartDay: day(2024, 1, 1), EndDay: day(2024, 2, 1),
		Limit: 500, MinValue: 1,
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	assertGolden(t, got, "code_hotspots_basic.json")
}

// TestGoldenCodeHotspotsEmpty replays testdata/code_hotspots_empty.json:
// fetch_code_hotspots returns no rows -- fetch_repo_names is never called
// (build_aggregated_flame_response's own `if not rows` short circuit).
func TestGoldenCodeHotspotsEmpty(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		if !strings.Contains(query, "FROM file_metrics_daily") {
			t.Fatalf("unexpected query for code_hotspots_empty fixture (fetch_repo_names should never run):\n%s", query)
		}
		return &fixtureRowScanner{}, nil
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Mode: "code_hotspots", StartDay: day(2024, 4, 1), EndDay: day(2024, 4, 5),
		RepoID: "repo-9", Limit: 500, MinValue: 1,
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	assertGolden(t, got, "code_hotspots_empty.json")
}

// TestGoldenThroughputTyped replays testdata/throughput_typed.json:
// fetch_throughput_by_type returns rows for two work types directly, no
// fallback to fetch_throughput.
func TestGoldenThroughputTyped(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		if !strings.Contains(query, "wct.completed_at") {
			t.Fatalf("unexpected query for throughput_typed fixture (fetch_throughput should never run):\n%s", query)
		}
		return &fixtureRowScanner{rows: [][]any{
			{"feature", "Team Alpha", uint64(12)},
			{"feature", "Team Beta", uint64(20)},
			{"bug", "Unassigned", uint64(5)},
		}}, nil
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Mode: "throughput", StartDay: day(2024, 5, 1), EndDay: day(2024, 5, 31),
		RepoID: "repo-5", Limit: 500, MinValue: 1,
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	assertGolden(t, got, "throughput_typed.json")
}

// TestGoldenThroughputBothEmpty replays testdata/throughput_both_empty.json:
// fetch_throughput_by_type AND its fetch_throughput fallback both return
// no rows -- two notes, "inferred" approximation, zero-value root.
func TestGoldenThroughputBothEmpty(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		if !strings.Contains(query, "wct.completed_at") && !strings.Contains(query, "wct.day") {
			t.Fatalf("unexpected query for throughput_both_empty fixture:\n%s", query)
		}
		return &fixtureRowScanner{}, nil
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Mode: "throughput", StartDay: day(2024, 6, 1), EndDay: day(2024, 6, 10),
		TeamID: "team-z", Limit: 500, MinValue: 1,
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	assertGolden(t, got, "throughput_both_empty.json")
}
