-- CHAOS-4321 (chris, 2026-08-26 10:39 PT): "Admin is an override, not a
-- default. It's the sync config [mapping] but admin can override it in the
-- panel. It's just a mapping." teams.members is written by BOTH the admin
-- Identities screen AND provider auto-import (team_autoimport_github.py and
-- its gitlab/jira siblings write unreviewed provider-discovered rosters
-- straight into it for any row that does not conflict with an existing
-- manual override) -- confirmed via a codex adversarial review round 1 HIGH
-- finding: treating ALL of teams.members as an authoritative, no-fallthrough
-- admin override let a provider-imported roster entry from one provider
-- become authoritative for a DIFFERENT provider's work item sharing the same
-- identity string.
--
-- manual_members is the provenance marker this ticket adds to close that
-- gap: written ONLY by ClickHouseTeamAdminService.add_members/
-- remove_members/set_members -- the functions the admin Identities screen
-- and the drift-approval flow (clickhouse_identity_drift.py) call. Provider
-- auto-import (ClickHouseTeamDriftProjector.project_team's
-- AUTO_APPLY_POLICY branch) carries the EXISTING value forward unchanged on
-- every sync write and never sets it, per chris's "sync must not clear it."
--
-- Legacy teams.members entries predate this column and carry no provenance
-- information, so this migration cannot backfill manual_members from them --
-- an org's admin-added members stay in the provider-fallback tier (unchanged
-- attribution, no worse than before this ticket) until re-saved from the
-- admin panel, which now also writes manual_members. See
-- docs/contribute/architecture/team-attribution.md s0 for the read-side
-- treatment.
ALTER TABLE teams ADD COLUMN IF NOT EXISTS manual_members Array(String) DEFAULT [] AFTER members;
