package repouser

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/google/uuid"
)

// TestCodeOwnershipGiniMatchesLivePythonBitExact is the CHAOS-4824 regression
// test for CodeOwnershipGini's naive-loop-vs-compensated-sum() fix: CPython's
// `sum()` over floats is Neumaier-compensated since 3.12, so a Go `total +=
// x` loop is not equivalent (16% disagreement on random 2-8 element inputs,
// see pythonparity.Sum's doc comment). Every corpus case has >= 3 authors --
// below that the compensation is always zero and the test would prove
// nothing.
//
// Expectations come from tests/fixtures/pysum_golden.json, generated by
// IMPORTING and calling the live production
// dev_health_ops.metrics.knowledge.compute_code_ownership_gini
// (tests/fixtures/generate_pysum_golden.py), never hand-derived.
func TestCodeOwnershipGiniMatchesLivePythonBitExact(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "..", "tests", "fixtures", "pysum_golden.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		Gini []struct {
			Churns       []float64 `json:"churns"`
			ExpectedBits string    `json:"expected_bits"`
		} `json:"gini"`
	}
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if len(fixture.Gini) == 0 {
		t.Fatal("fixture has no gini cases")
	}

	repoID := uuid.MustParse("00000000-0000-4000-8000-00000000000a")

	mismatches := 0
	for _, testCase := range fixture.Gini {
		windowStats := make([]CommitStatRow, len(testCase.Churns))
		for i, churn := range testCase.Churns {
			windowStats[i] = CommitStatRow{
				RepoID:      repoID,
				CommitHash:  "c" + strconv.Itoa(i),
				AuthorEmail: "a" + strconv.Itoa(i) + "@example.com",
				FilePath:    "src/f.py",
				Additions:   int(churn),
			}
		}
		got := CodeOwnershipGini(repoID, windowStats)
		wantBits, err := strconv.ParseUint(strings.TrimPrefix(testCase.ExpectedBits, "0x"), 16, 64)
		if err != nil {
			t.Fatalf("parse expected_bits %q: %v", testCase.ExpectedBits, err)
		}
		gotBits := math.Float64bits(got)
		if gotBits != wantBits {
			mismatches++
			t.Errorf("CodeOwnershipGini(churns=%v) = %v (bits %#x), want bits %#x (%v)",
				testCase.Churns, got, gotBits, wantBits, math.Float64frombits(wantBits))
		}
	}
	if mismatches > 0 {
		t.Errorf("%d of %d cases mismatched", mismatches, len(fixture.Gini))
	}
}
