package repouser

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/google/uuid"
)

// TestCodeOwnershipGiniMatchesLivePythonBitExact is the CHAOS-4824 regression
// test for CodeOwnershipGini. Python's Gini formula is exact integer
// arithmetic until ONE final true division, correctly rounded to float64;
// Go now mirrors that (math/big.Int accumulation + big.Rat.Float64()) rather
// than converting churn totals to float64 early, which lost precision at
// two different, increasingly extreme points found across two codex rounds
// on PR #2107 (round 1: an accumulated numerator crossing 2**53 across many
// representable per-author totals; round 2: a SINGLE author's own total
// exceeding 2**53 before summation even began). The corpus below varies
// both author COUNT and per-author MAGNITUDE, deliberately including values
// at and past 2**53 and 2**63 (see generate_pysum_golden.py), so both prior
// constructions and the general mechanism are covered by one fix.
//
// Expectations come from tests/fixtures/pysum_golden.json, generated by
// IMPORTING and calling the live production
// dev_health_ops.metrics.knowledge.compute_code_ownership_gini
// (tests/fixtures/generate_pysum_golden.py), never hand-derived.
//
// Churns are decoded as int64, NOT float64: the fixture's largest values
// are near int64 max (2**63-1), and round-tripping them through a Go
// []float64 field silently rounds two adjacent large integers to the SAME
// float64 (exactly the class of precision loss this test exists to catch)
// before CodeOwnershipGini ever sees them -- a test-harness bug that would
// have hidden a real corpus case, found and fixed in-session.
func TestCodeOwnershipGiniMatchesLivePythonBitExact(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "..", "tests", "fixtures", "pysum_golden.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		Gini []struct {
			Churns       []int64 `json:"churns"`
			ExpectedBits string  `json:"expected_bits"`
		} `json:"gini"`
	}
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if len(fixture.Gini) == 0 {
		t.Fatal("fixture has no gini cases")
	}

	repoID := uuid.MustParse("00000000-0000-4000-8000-00000000000a")

	mismatches := 0
	for _, testCase := range fixture.Gini {
		windowStats := make([]CommitStatRow, len(testCase.Churns))
		for i, churn := range testCase.Churns {
			windowStats[i] = CommitStatRow{
				RepoID:      repoID,
				CommitHash:  "c" + strconv.Itoa(i),
				AuthorEmail: "a" + strconv.Itoa(i) + "@example.com",
				FilePath:    "src/f.py",
				Additions:   int(churn),
			}
		}
		got := CodeOwnershipGini(repoID, windowStats)
		wantBits, err := strconv.ParseUint(strings.TrimPrefix(testCase.ExpectedBits, "0x"), 16, 64)
		if err != nil {
			t.Fatalf("parse expected_bits %q: %v", testCase.ExpectedBits, err)
		}
		gotBits := math.Float64bits(got)
		if gotBits != wantBits {
			mismatches++
			if mismatches <= 10 {
				t.Errorf("CodeOwnershipGini(churns=%v) = %v (bits %#x), want bits %#x (%v)",
					testCase.Churns, got, gotBits, wantBits, math.Float64frombits(wantBits))
			}
		}
	}
	if mismatches > 10 {
		t.Errorf("... and %d more mismatches (total %d of %d cases)", mismatches-10, mismatches, len(fixture.Gini))
	}
}

// TestCodeOwnershipGiniMultiRowMatchesLivePythonBitExact is the CHAOS-4824
// regression test for codex round 4's finding (P2, EXECUTED): the ACCUMULATOR
// itself, not just the aggregated value, needs to be unbounded. The main
// gini corpus (TestCodeOwnershipGiniMatchesLivePythonBitExact) uses one row
// per author, so it can only ever exercise the value AFTER aggregation --
// codex constructed 2.1 BILLION int32-max rows for one author, overflowing a
// native int64 ACCUMULATOR mid-sum (wrapping negative, silently dropping the
// author at the `> 0` filter) even though every individual row and the true
// total are each representable. This test builds MULTIPLE rows per author
// (tests/fixtures/generate_pysum_golden.py's `gini_multi_row` family, same
// live-Python generation discipline as every other golden here) so the
// accumulation step itself is exercised, not just its result.
func TestCodeOwnershipGiniMultiRowMatchesLivePythonBitExact(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "..", "tests", "fixtures", "pysum_golden.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		GiniMultiRow []struct {
			AuthorRows   [][]int64 `json:"author_rows"`
			ExpectedBits string    `json:"expected_bits"`
		} `json:"gini_multi_row"`
	}
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if len(fixture.GiniMultiRow) == 0 {
		t.Fatal("fixture has no gini_multi_row cases")
	}

	repoID := uuid.MustParse("00000000-0000-4000-8000-00000000000a")

	for caseIndex, testCase := range fixture.GiniMultiRow {
		var windowStats []CommitStatRow
		for authorIndex, rowValues := range testCase.AuthorRows {
			for rowIndex, value := range rowValues {
				windowStats = append(windowStats, CommitStatRow{
					RepoID:      repoID,
					CommitHash:  "a" + strconv.Itoa(authorIndex) + "c" + strconv.Itoa(rowIndex),
					AuthorEmail: "a" + strconv.Itoa(authorIndex) + "@example.com",
					FilePath:    "src/f.py",
					Additions:   int(value),
				})
			}
		}
		got := CodeOwnershipGini(repoID, windowStats)
		wantBits, err := strconv.ParseUint(strings.TrimPrefix(testCase.ExpectedBits, "0x"), 16, 64)
		if err != nil {
			t.Fatalf("case %d: parse expected_bits %q: %v", caseIndex, testCase.ExpectedBits, err)
		}
		gotBits := math.Float64bits(got)
		if gotBits != wantBits {
			t.Errorf("case %d CodeOwnershipGini(author_rows=%v) = %v (bits %#x), want bits %#x (%v)",
				caseIndex, testCase.AuthorRows, got, gotBits, wantBits, math.Float64frombits(wantBits))
		}
	}
}
