package quadrant

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"
	"time"

	dhclickhouse "github.com/full-chaos/dev-health-go/clickhouse"
)

// fixtureRowScanner replays a fixed slice of pre-built rows -- same shape
// as investmentexplain/explain_golden_test.go's fixtureRowScanner.
type fixtureRowScanner struct {
	rows  [][]any
	index int
}

func (s *fixtureRowScanner) Next() bool {
	if s.index >= len(s.rows) {
		return false
	}
	s.index++
	return true
}

func (s *fixtureRowScanner) Scan(dest ...any) error {
	row := s.rows[s.index-1]
	for i, d := range dest {
		switch typed := d.(type) {
		case *time.Time:
			*typed = row[i].(time.Time)
		case *string:
			*typed = row[i].(string)
		case *float64:
			*typed = row[i].(float64)
		}
	}
	return nil
}

func (s *fixtureRowScanner) Err() error   { return nil }
func (s *fixtureRowScanner) Close() error { return nil }

func day(y int, m time.Month, d int) time.Time {
	return time.Date(y, m, d, 0, 0, 0, 0, time.UTC)
}

// loadGolden decodes a testdata JSON file generated by
// testdata/generate_quadrant_golden.py (the real Python
// build_quadrant_response, monkeypatched ClickHouse layer, dumped via
// model_dump(mode="json")) into a Response. DisallowUnknownFields makes a
// field-name mismatch (Python emitted a key this Go type does not declare)
// a hard test failure rather than a silent drop.
func loadGolden(t *testing.T, name string) Response {
	t.Helper()
	data, err := os.ReadFile("testdata/" + name)
	if err != nil {
		t.Fatalf("read golden %s: %v", name, err)
	}
	var resp Response
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&resp); err != nil {
		t.Fatalf("decode golden %s: %v", name, err)
	}
	return resp
}

// TestGoldenCycleThroughputTeamAttributionQuirk replays
// testdata/cycle_throughput_team.json: cycle_throughput at team scope,
// both axes via the primary-team-attribution reader, one team with a real
// two-window trajectory and a resolved catalog label, one team with a
// single window and no catalog label (falls back to its own entity_id).
func TestGoldenCycleThroughputTeamAttributionQuirk(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		switch {
		case strings.Contains(query, "FROM teams FINAL"):
			return &fixtureRowScanner{rows: [][]any{{"team-a", "Team Alpha"}}}, nil
		case strings.Contains(query, "WITH team_activity AS") && strings.Contains(query, "uniqExact(work_item_id)"):
			return &fixtureRowScanner{rows: [][]any{
				{day(2024, 1, 1), "team-a", "team-a", 5.0},
				{day(2024, 1, 8), "team-a", "team-a", 9.0},
				{day(2024, 1, 1), "team-b", "team-b", 3.0},
			}}, nil
		case strings.Contains(query, "WITH team_activity AS") && strings.Contains(query, "avg(cycle_time_hours)"):
			return &fixtureRowScanner{rows: [][]any{
				{day(2024, 1, 1), "team-a", "team-a", 48.0},
				{day(2024, 1, 8), "team-a", "team-a", 24.0},
				{day(2024, 1, 1), "team-b", "team-b", 72.0},
			}}, nil
		default:
			t.Fatalf("unexpected query for cycle_throughput team fixture:\n%s", query)
			return nil, nil
		}
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Type: "cycle_throughput", ScopeType: "team", RangeDays: 30, Bucket: "week",
		StartDate: timePtr(day(2024, 1, 1)), EndDate: timePtr(day(2024, 1, 8)),
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	want := loadGolden(t, "cycle_throughput_team.json")
	if !reflect.DeepEqual(*got, want) {
		t.Fatalf("response mismatch\n got:  %+v\n want: %+v", *got, want)
	}
}

// TestGoldenChurnThroughputForcesRepoGrain replays
// testdata/churn_throughput_team_forces_repo.json: churn_throughput
// requested at team scope resolves (CHAOS-2079) to repo grain, both axes
// via repo_metrics_daily.
func TestGoldenChurnThroughputForcesRepoGrain(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		switch {
		case strings.Contains(query, "FROM teams FINAL"):
			t.Fatal("team-label resolution must not run for repo-grain churn")
		case strings.Contains(query, "total_loc_touched"):
			return &fixtureRowScanner{rows: [][]any{{day(2024, 1, 1), "checkout-service", "checkout-service", 4200.0}}}, nil
		case strings.Contains(query, "prs_merged"):
			return &fixtureRowScanner{rows: [][]any{{day(2024, 1, 1), "checkout-service", "checkout-service", 12.0}}}, nil
		}
		t.Fatalf("unexpected query for churn_throughput fixture:\n%s", query)
		return nil, nil
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Type: "churn_throughput", ScopeType: "team", RangeDays: 30, Bucket: "week",
		StartDate: timePtr(day(2024, 1, 1)), EndDate: timePtr(day(2024, 1, 8)),
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	want := loadGolden(t, "churn_throughput_team_forces_repo.json")
	if !reflect.DeepEqual(*got, want) {
		t.Fatalf("response mismatch\n got:  %+v\n want: %+v", *got, want)
	}
}

// TestGoldenReviewLoadLatencyRepo replays
// testdata/review_load_latency_repo.json: review_load_latency requested
// directly at repo scope, plain path (no attribution quirk), one repo with
// a real two-window trajectory.
func TestGoldenReviewLoadLatencyRepo(t *testing.T) {
	client := fakeQueryClient{t: t, handler: func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
		switch {
		case strings.Contains(query, "FROM teams FINAL"):
			t.Fatal("team-label resolution must not run for repo scope")
		case strings.Contains(query, "reviews_given"):
			return &fixtureRowScanner{rows: [][]any{
				{day(2024, 1, 1), "api-gateway", "api-gateway", 6.0},
				{day(2024, 1, 8), "api-gateway", "api-gateway", 10.0},
			}}, nil
		case strings.Contains(query, "pr_first_review_p50_hours"):
			return &fixtureRowScanner{rows: [][]any{
				{day(2024, 1, 1), "api-gateway", "api-gateway", 5.5},
				{day(2024, 1, 8), "api-gateway", "api-gateway", 3.25},
			}}, nil
		}
		t.Fatalf("unexpected query for review_load_latency fixture:\n%s", query)
		return nil, nil
	}}

	got, err := BuildResponse(context.Background(), client, "org-1", Params{
		Type: "review_load_latency", ScopeType: "repo", RangeDays: 30, Bucket: "week",
		StartDate: timePtr(day(2024, 1, 1)), EndDate: timePtr(day(2024, 1, 8)),
	})
	if err != nil {
		t.Fatalf("BuildResponse: %v", err)
	}
	want := loadGolden(t, "review_load_latency_repo.json")
	if !reflect.DeepEqual(*got, want) {
		t.Fatalf("response mismatch\n got:  %+v\n want: %+v", *got, want)
	}
}

type fakeQueryClient struct {
	t       *testing.T
	handler func(t *testing.T, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error)
}

func (c fakeQueryClient) Query(_ context.Context, query string, bindings []dhclickhouse.Binding) (dhclickhouse.RowScanner, error) {
	return c.handler(c.t, query, bindings)
}

func timePtr(t time.Time) *time.Time { return &t }
