package goapiproof

// CHAOS-5486: the Go reader for the Python edge's registered-document
// catalog.
//
// WHY THE GO VERBS NEED A PYTHON-SIDE FILE AT ALL. Reachability through
// the product edge is a conjunction, and each half is owned by a
// different plane:
//
//   - the RUNNING query-api decides which operations it will serve, and
//     under which document digest -- read from GET /registry;
//   - the PYTHON EDGE decides which incoming request maps to which
//     `selected_operation` at all, and it does that through
//     `api/graphql/go_api_operations.json` (go_api_operation_catalog.py).
//     An operation the catalog does not name can never be dispatched to
//     Go no matter what the routing row says.
//
// So enabling an operation the catalog does not carry writes a row that
// nothing will ever look up -- the same shape of silent, unreported dead
// row as CHAOS-5416's stale schema digest, arrived at from the other
// direction. The Python verb refuses on it (`_resolve_requested_operations`
// errors on an operation missing from the catalog), and so does this.
//
// The file is a CHECKED-IN artifact regenerated by
// scripts/go_api/generate_operation_catalog.py from registrydump; it is
// never hand-maintained and never regenerated at runtime.

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode/utf8"
)

// DefaultCatalogPath is where the checked-in catalog lives, relative to
// the repository root. It is a default rather than a constant reached
// directly, because an operator running this binary from somewhere other
// than the checkout must be able to say where the file is -- and because
// a wrong path has to be a refusal, never a silently empty catalog.
const DefaultCatalogPath = "src/dev_health_ops/api/graphql/go_api_operations.json"

// ErrCatalogUnusable reports that the catalog could not be read or made
// sense of.
//
// It is deliberately ONE error for "missing", "malformed" and "empty":
// every one of them means this process cannot say which operations the
// edge can dispatch, and a verb that treated an unreadable catalog as an
// empty one would report "no operations" with exit 0 -- the precise
// "two states, one silence" failure the whole go_api_cli surface exists
// to end (go_api_operation_catalog.py's `_catalog_load_ok` makes the same
// distinction on the Python side).
var ErrCatalogUnusable = errors.New("goapiproof: the registered-operation catalog is unusable")

// ErrEmptyOperationFilter refuses an --operations value that names
// nothing -- an empty string, whitespace, or separators only.
//
// "Every operation" must be asked for out loud, and `all-registered` is
// the only way to ask. Reading any other value that names nothing as "all
// of them" is a write verb silently widening its own blast radius from
// what the operator typed.
var ErrEmptyOperationFilter = errors.New("goapiproof: --operations names no operation: pass 'all-registered' to select every row")

// SplitOperations parses an --operations value. It is exported so
// cmd/go-api-routing shares this one parser rather than keeping a second
// copy of the rule.
//
// Returns (nil, nil) ONLY for the literal `all-registered` -- the single
// spelling of "every operation" -- and an error for any value that names
// nothing.
//
// AN EMPTY VALUE REFUSES, and that is the r1 finding's second half. The
// original fix (CHAOS-5486 r1, F1) closed the separators-only case
// (`","`) and left `""` reading as "all", one input away -- so
// `-operations ”` still silently widened a write verb from what the
// operator typed to everything. The flag's DEFAULT is `all-registered`,
// so an empty value can only arrive because somebody passed one, which is
// the operator naming nothing. A codex round found it by probing the
// binary; the test that should have caught it asserted the defective
// behaviour instead, which is why the first fix looked complete.
func SplitOperations(raw string) ([]string, error) {
	if strings.TrimSpace(raw) == "all-registered" {
		return nil, nil
	}
	var names []string
	for _, name := range strings.Split(raw, ",") {
		if name := strings.TrimSpace(name); name != "" {
			names = append(names, name)
		}
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("%w (got %q)", ErrEmptyOperationFilter, raw)
	}
	return names, nil
}

// catalogFileEntry is decoded BY HAND from raw keys, not by struct tags.
//
// encoding/json matches struct field names CASE-INSENSITIVELY, and there
// is no option to turn that off. The Python edge loader subscripts
// `entry["operation"]`, which is case-SENSITIVE. So a catalog written with
// `Operation` / `Digest` was accepted by Go and raised KeyError in Python
// -- executed, on the real binary and the real loader, against the same
// file:
//
//	go-api-routing enable -catalog uppercase.json ... -> would enable total=1, exit 0
//	python: KeyError 'digest' -> the edge cannot dispatch this operation at all
//
// That is the exact direction this file's own comment says must never
// happen: a catalog Python REJECTS but Go ACCEPTS lets a Go `enable`
// write rows the edge's own loader refuses to use -- a row nothing will
// ever look up, which is CHAOS-5416's shape reached from a third
// direction. An adversarial round found 574 non-canonical key spellings
// with this disagreement, so this is a whole CLASS, not the one spelling
// anybody happened to try.
//
// Extra keys stay ACCEPTED, deliberately: Python's subscript ignores
// them, so accepting them is agreement, and refusing them would be the
// same defect pointing the other way.
type catalogFileEntry struct {
	Operation string
	Digest    string
}

// catalogEntryKey pulls one EXACTLY-spelled key out of a raw entry and
// requires its value to be a JSON string.
//
// The value's type is checked here rather than left to a struct decode
// because the two failures need different sentences: a missing key means
// the generator wrote the wrong shape, a non-string value means it wrote
// the wrong type, and an operator can only fix the file if the refusal
// says which.
func catalogEntryKey(raw map[string]json.RawMessage, key, path string, index int) (string, error) {
	value, present := raw[key]
	if !present {
		return "", fmt.Errorf("%w: %s entry %d has no %q key. The Python edge loader subscripts this key exactly, so a differently-spelled one (%q, say) is a catalog Go could read and the edge cannot dispatch",
			ErrCatalogUnusable, path, index, key, strings.Title(key)) //nolint:staticcheck // the deprecated-but-exact spelling of "the capitalised variant", for the message only
	}
	var decoded string
	if err := json.Unmarshal(value, &decoded); err != nil {
		return "", fmt.Errorf("%w: %s entry %d has a non-string %q value (%s)", ErrCatalogUnusable, path, index, key, value)
	}
	return decoded, nil
}

// LoadOperationCatalog reads go_api_operations.json and returns
// operation -> registered document digest.
//
// Every guard the Python loader carries is repeated here, because the two
// readers must agree about which files are acceptable: a catalog Python
// rejects but Go accepts would let a Go `enable` write rows the edge's own
// loader refuses to use.
//
// ONE GUARD IS STRICTER THAN PYTHON'S, declared rather than left to be
// rediscovered (codex r1, F9): this refuses a duplicate OPERATION NAME,
// and `go_api_operation_catalog.py` does not -- its map is keyed by
// digest, so it only notices a duplicate digest. The asymmetry is safe in
// this direction: a file Go refuses and Python accepts costs an operator
// a clear refusal, where the reverse would let Go write rows against
// whichever of two entries happened to win. A duplicate operation name in
// a registrydump-generated artifact is a broken generator either way.
func LoadOperationCatalog(path string) (map[string]string, error) {
	raw, err := os.ReadFile(path) //nolint:gosec // operator-supplied path to the checked-in catalog
	if err != nil {
		return nil, fmt.Errorf("%w: read %s: %w", ErrCatalogUnusable, path, err)
	}
	// r2 P1 (reproduced): the Python edge loads this file with
	// `Path.read_text()`, which decodes the WHOLE file as UTF-8 and raises
	// UnicodeDecodeError on the FIRST bad byte anywhere in it --
	// `catalog_loaded_successfully=False`, the operation undispatchable.
	// `encoding/json` has no opinion on byte validity inside a JSON string;
	// it happily decodes invalid UTF-8 (0xFF, a lone continuation byte, an
	// overlong encoding, a surrogate) into a Go string, which let `enable`
	// write a row the edge's own loader could never produce. The check is
	// over the RAW FILE, not per-field after decode: Python rejects the
	// whole file on one bad byte anywhere in it, including in a key this
	// program never even reads, so per-value validation after JSON decode
	// would silently accept invalid bytes Python's reader never gets past.
	if !utf8.Valid(raw) {
		return nil, fmt.Errorf("%w: %s is not valid UTF-8 -- the Python edge loader decodes this file as text and refuses the WHOLE file on one bad byte anywhere in it, so a Go reader that decoded past it would write rows nothing can dispatch",
			ErrCatalogUnusable, path)
	}
	var rawEntries []map[string]json.RawMessage
	if err := json.Unmarshal(raw, &rawEntries); err != nil {
		return nil, fmt.Errorf("%w: decode %s (expected a JSON array of {operation,digest}): %w", ErrCatalogUnusable, path, err)
	}
	var entries []catalogFileEntry
	for index, rawEntry := range rawEntries {
		operation, err := catalogEntryKey(rawEntry, "operation", path, index)
		if err != nil {
			return nil, err
		}
		digest, err := catalogEntryKey(rawEntry, "digest", path, index)
		if err != nil {
			return nil, err
		}
		entries = append(entries, catalogFileEntry{Operation: operation, Digest: digest})
	}
	if rawEntries != nil && entries == nil {
		// An array that decoded but produced no entries can only be `[]`,
		// which the next check names properly.
		entries = []catalogFileEntry{}
	}
	// `[]` and `null` are DIFFERENT files and get different sentences.
	// Both decode into a nil slice, so one message covered both and told
	// an operator holding a `null` catalog to look for an empty array --
	// executed evidence, CHAOS-5486's input-domain sweep:
	//
	//	-catalog json-null -> "...null.json is an empty array"
	//
	// The whole purpose of these refusals is that the operator can fix the
	// file, and a refusal that misdescribes the file cannot be acted on.
	if rawEntries == nil {
		return nil, fmt.Errorf("%w: %s decodes to JSON null, not to a list of {operation,digest} entries -- regenerate it with scripts/go_api/generate_operation_catalog.py", ErrCatalogUnusable, path)
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("%w: %s is an empty array -- regenerate it with scripts/go_api/generate_operation_catalog.py", ErrCatalogUnusable, path)
	}

	byOperation := make(map[string]string, len(entries))
	// A duplicate DIGEST is rejected as well as a duplicate operation.
	// go_api_operation_catalog.py keys its dispatch map BY DIGEST, so two
	// operations sharing one digest make the edge's mapping ambiguous --
	// and whichever entry happened to win would decide which routing row
	// a request consults.
	byDigest := make(map[string]string, len(entries))
	for _, entry := range entries {
		if entry.Operation == "" || entry.Digest == "" {
			return nil, fmt.Errorf("%w: %s carries an entry with an empty operation or digest", ErrCatalogUnusable, path)
		}
		if previous, seen := byOperation[entry.Operation]; seen {
			return nil, fmt.Errorf("%w: %s lists operation %q twice (digests %s and %s)", ErrCatalogUnusable, path, entry.Operation, previous, entry.Digest)
		}
		if previous, seen := byDigest[entry.Digest]; seen {
			return nil, fmt.Errorf("%w: %s gives digest %s to both %q and %q -- the edge keys its dispatch map by digest, so this mapping is ambiguous", ErrCatalogUnusable, path, entry.Digest, previous, entry.Operation)
		}
		byOperation[entry.Operation] = entry.Digest
		byDigest[entry.Digest] = entry.Operation
	}
	return byOperation, nil
}

// CatalogOperations returns the catalog's operation names, sorted.
func CatalogOperations(catalog map[string]string) []string {
	names := make([]string, 0, len(catalog))
	for operation := range catalog {
		names = append(names, operation)
	}
	sort.Strings(names)
	return names
}

// ErrUnknownOperation reports an --operations name the catalog does not
// carry.
//
// An unknown name is an error rather than a silent skip, for the reason
// the Python resolver gives: an operator who typos one operation should
// be told, not handed a successful-looking run that enabled everything
// EXCEPT the one they cared about.
var ErrUnknownOperation = errors.New("goapiproof: operation is not in the registered-operation catalog")

// ResolveOperations turns an --operations value into a concrete, sorted,
// catalog-validated list.
//
// `all-registered` is the only value meaning "every catalog operation";
// anything that names nothing at all is refused rather than widened
// (CHAOS-5486 r1 F1 and its second half).
func ResolveOperations(requested string, catalog map[string]string) ([]string, error) {
	names, err := SplitOperations(requested)
	if err != nil {
		return nil, err
	}
	if names == nil {
		return CatalogOperations(catalog), nil
	}
	var unknown []string
	unique := map[string]bool{}
	for _, name := range names {
		if _, ok := catalog[name]; !ok {
			unknown = append(unknown, name)
			continue
		}
		unique[name] = true
	}
	if len(unknown) > 0 {
		sort.Strings(unknown)
		return nil, fmt.Errorf("%w: %v -- known: %v (regenerate with scripts/go_api/generate_operation_catalog.py)",
			ErrUnknownOperation, unknown, CatalogOperations(catalog))
	}
	resolved := make([]string, 0, len(unique))
	for name := range unique {
		resolved = append(resolved, name)
	}
	sort.Strings(resolved)
	return resolved, nil
}
