package clickhouse

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The self-hosted compose stack declares the api's own ClickHouse login the way
// prod and bigboy do: a users.d file with the grants of APIPosture and nothing
// else. The file is docker/clickhouse-users.d/dho_api_ch.xml, mounted read-only
// into the `clickhouse` service of compose.yml (CHAOS-8361). It holds no
// password and no hash: ClickHouse reads the password from its own environment
// (`from_env`), and go-api logs in with the same value.
//
// The api's readiness check (CheckAPIClickHouseAuthorization) refuses a login
// whose grants are not exactly the manifest, so the file must follow the
// manifest in the change that moves it. This test holds the file equal, byte
// for byte, to what the manifest renders: a grant that is added, dropped or
// changed on either side fails it. To regenerate after a deliberate manifest
// change: UPDATE_COMPOSE_API_USERS_FILE=1 go test -run TestComposeUsersFileIsTheAPIPosture .
const (
	// composeAPIUsersFile is relative to this package.
	composeAPIUsersFile = "../../../docker/clickhouse-users.d/dho_api_ch.xml"
	// composeAPIUser is the login go-api connects as (DEV_HEALTH_CH_API_USER in
	// compose.yml), and composeAPIUserPasswordEnv the variable of the
	// `clickhouse` service that ClickHouse reads its password from.
	composeAPIUser            = "dho_api_ch"
	composeAPIUserPasswordEnv = "DHO_API_CH_PASSWORD"
)

// renderComposeAPIUsersFile is the one valid content of the file for posture.
// The grants are the statements GrantStatements issues, without the "TO
// <role>" suffix: the declaration already names the user.
func renderComposeAPIUsersFile(t *testing.T, posture Posture) string {
	t.Helper()
	var out strings.Builder
	out.WriteString("<clickhouse>\n")
	out.WriteString("  <!-- GENERATED from the api posture (internal/storage/clickhouse/authorization.go, func APIPosture).\n")
	out.WriteString("       Do not edit this file. To regenerate, in internal/storage/clickhouse:\n")
	out.WriteString("         UPDATE_COMPOSE_API_USERS_FILE=1 go test -run TestComposeUsersFileIsTheAPIPosture .\n")
	out.WriteString("       The api's own ClickHouse login of the self-hosted compose stack. No password and no hash is\n")
	out.WriteString("       in this file: ClickHouse reads the password from its environment. -->\n")
	out.WriteString("  <users>\n")
	out.WriteString("    <" + composeAPIUser + ">\n")
	out.WriteString("      <password from_env=\"" + composeAPIUserPasswordEnv + "\"/>\n")
	out.WriteString("      <networks><ip>::/0</ip></networks>\n")
	out.WriteString("      <profile>default</profile>\n")
	out.WriteString("      <quota>default</quota>\n")
	out.WriteString("      <access_management>0</access_management>\n")
	out.WriteString("      <grants>\n")
	suffix := " TO " + composeAPIUser
	statements := GrantStatements(composeAPIUser, posture)
	if len(statements) == 0 {
		t.Fatal("the posture produced no grants: the file would declare a login with every privilege")
	}
	for _, statement := range statements {
		if !strings.HasSuffix(statement, suffix) || strings.ContainsAny(statement, "<>&") {
			t.Fatalf("statement %q cannot be written into the file", statement)
		}
		out.WriteString("        <query>" + strings.TrimSuffix(statement, suffix) + "</query>\n")
	}
	out.WriteString("      </grants>\n")
	out.WriteString("    </" + composeAPIUser + ">\n")
	out.WriteString("  </users>\n")
	out.WriteString("</clickhouse>\n")
	return out.String()
}

func TestComposeUsersFileIsTheAPIPosture(t *testing.T) {
	want := renderComposeAPIUsersFile(t, APIPosture("default"))
	path := filepath.FromSlash(composeAPIUsersFile)
	if os.Getenv("UPDATE_COMPOSE_API_USERS_FILE") == "1" {
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != want {
		t.Fatalf("%s is not what the api posture renders (%d bytes on disk, %d rendered). go-api's readiness check refuses a login whose grants are not exactly the manifest. If the manifest change is deliberate, regenerate the file (UPDATE_COMPOSE_API_USERS_FILE=1 go test -run TestComposeUsersFileIsTheAPIPosture .) and review the diff", composeAPIUsersFile, len(got), len(want))
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	// clickhouse-server runs as its own uid in the container and exits on a
	// mounted users.d file it cannot read.
	if info.Mode().Perm()&0o004 == 0 {
		t.Fatalf("%s is mode %v, not world-readable: ClickHouse cannot read it when it is mounted", composeAPIUsersFile, info.Mode().Perm())
	}
}

// TestComposeUsersFileFollowsEveryGrantChange changes the manifest one grant at
// a time and requires that the file no longer matches: a grant that is added,
// dropped or changed in the manifest cannot leave the test green.
func TestComposeUsersFileFollowsEveryGrantChange(t *testing.T) {
	path := filepath.FromSlash(composeAPIUsersFile)
	onDisk, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	base := APIPosture("default")
	if len(base.RequiredTables) < 2 {
		t.Fatal("the posture has fewer than two tables: nothing to change")
	}
	clone := func() Posture {
		return Posture{RequiredTables: append([]TableGrant(nil), base.RequiredTables...)}
	}
	for name, change := range map[string]func(*Posture){
		"a grant added": func(p *Posture) {
			p.RequiredTables = append(p.RequiredTables, TableGrant{Database: "default", Table: "planted_table", AllowSelect: true})
		},
		"a grant dropped": func(p *Posture) { p.RequiredTables = p.RequiredTables[1:] },
		"a privilege changed": func(p *Posture) {
			p.RequiredTables[0].AllowSelect = !p.RequiredTables[0].AllowSelect
		},
		"a table renamed": func(p *Posture) { p.RequiredTables[len(p.RequiredTables)-1].Table += "_x" },
	} {
		t.Run(name, func(t *testing.T) {
			changed := clone()
			change(&changed)
			if renderComposeAPIUsersFile(t, changed) == string(onDisk) {
				t.Fatalf("the manifest changed (%s) and the file still matches", name)
			}
		})
	}
}
