#!/usr/bin/env bash
# cut-contents.sh <old-sha> <cut-sha> [pg-expect-out]: which conditional group items are IN the cut (subject/file evidence from ops git history).
# Writes the PG grants expectation file (only for PRs in the cut) to pg-expect-out and prints the item table for the PR body.
set -u; OLD=${1:?}; NEW=${2:?}; OUTF=${3:-/dev/null}; O=/home/ubuntu/devhealth/ops
git -C $O fetch -q origin main 2>/dev/null
LOG=$(git -C $O log --format='%h %s' $OLD..$NEW)
has() { echo "$LOG" | grep -qE "$1"; }
files() { git -C $O diff --name-only $OLD $NEW; }
echo "commits in range: $(echo "$LOG" | wc -l)"
: > "$OUTF"; echo "# generated by cut-contents.sh for $NEW" >> "$OUTF"
item() { if has "$2"; then echo "IN   $1"; else echo "OUT  $1"; fi; }
item "CHAOS-6622 sync_watermarks (PG domain +DELETE, api +UPDATE)" "CHAOS-6622" "devhealth_domain sync_watermarks DELETE
devhealth_api sync_watermarks UPDATE"
item "CHAOS-6666 byo_llm_budget_reservations (PG api +SELECT)" "CHAOS-6666" "devhealth_api byo_llm_budget_reservations SELECT"
item "CHAOS-6673 #3083 scheduled_sync_occurrences + sync_manual_triggers (PG api +INSERT)" "CHAOS-6673|3083" "devhealth_api scheduled_sync_occurrences INSERT
devhealth_api sync_manual_triggers INSERT"
item "CHAOS-6260 (#2999) email_verification_tokens/password_reset_tokens/org_invites grants (PG api)" "CHAOS-6260" "devhealth_api email_verification_tokens INSERT,DELETE
devhealth_api password_reset_tokens INSERT,DELETE
devhealth_api org_invites UPDATE"
item "CHAOS-6501 #3051 telemetry_signal_bucket (CH INSERT)" "CHAOS-6501|3051"
item "CHAOS-6474 #3066 usersd directory mount" "CHAOS-6474"
item "#3043 migration 0139 (refunds)" "CHAOS-6632|3043"
item "#3048 migration 0140 (invoices)" "3048"
# PG api/domain posture deltas, computed from the manifest itself (RequiredTables {table, insert,
# update, delete}; SELECT implied): every privilege ADDED between $OLD and $NEW becomes an
# expectation `devhealth_<role> <table> <PRIV>` (has_table_privilege read-back). Replaces the
# by-name item matching for PG grants. Extracted to sibling files, not inline here-documents
# (CHAOS-3362/CHAOS-6964: both bodies are well over the 400-byte here-document pipe budget).
HERE=$(cd "$(dirname "$0")" && pwd)
python3 "$HERE/cut-contents-pg-api-posture.py" "$OLD" "$NEW" "$OUTF"
python3 "$HERE/cut-contents-pg-domain-posture.py" "$OLD" "$NEW" "$OUTF"
echo "alembic versions added in range: $(files | grep -E 'alembic/versions/' | sed 's#.*/##' | tr '\n' ' ')"
echo "APIPosture (CH) delta: $(git -C $O diff $OLD $NEW -- internal/storage/clickhouse/authorization.go | grep -E '^\+.*Table:' | sed -E 's/.*Table: "(\w+)".*/\1/' | tr '\n' ' ')"
echo "PG posture (api) files changed: $(files | grep -E 'internal/storage/postgres/.*authorization' | tr '\n' ' ')"
