package apiservice

import "testing"

// wantResponseModelRoutes is the response-model table exactly as it stood in
// responsemodel.go before CHAOS-6722 split it into per-family files (230 keys,
// sorted; CHAOS-6882 added the sync-config trigger and backfill routes). The runtime table after package init must equal it: a route dropped,
// duplicated into a wrong value, or flipped in any per-family file fails here.
// Adding a route legitimately means adding it here too, in the same PR.
var wantResponseModelRoutes = map[string]bool{
	"DELETE /api/v1/admin/credentials/{provider}/{name}":                               true,
	"DELETE /api/v1/admin/ip-allowlist/{entry_id}":                                     true,
	"DELETE /api/v1/admin/llm-settings":                                                true,
	"DELETE /api/v1/admin/orgs/{org_id}":                                               true,
	"DELETE /api/v1/admin/orgs/{org_id}/feature-overrides/{override_id}":               false,
	"DELETE /api/v1/admin/orgs/{org_id}/members/{user_id}":                             true,
	"DELETE /api/v1/admin/retention-policies/{policy_id}":                              true,
	"DELETE /api/v1/admin/settings/{category}/{key}":                                   true,
	"DELETE /api/v1/admin/sync-configs/{config_id}":                                    false,
	"DELETE /api/v1/admin/teams/{team_id}":                                             true,
	"DELETE /api/v1/admin/users/{user_id}":                                             true,
	"DELETE /api/v1/auth/sso/providers/{provider_id}":                                  false,
	"DELETE /api/v1/billing/plans/{plan_id}":                                           true,
	"GET /api/v1/admin/audit-logs":                                                     true,
	"GET /api/v1/admin/audit-logs/resource/{resource_type}/{resource_id}":              true,
	"GET /api/v1/admin/audit-logs/user/{user_id}":                                      true,
	"GET /api/v1/admin/audit-logs/{log_id}":                                            true,
	"GET /api/v1/admin/backfill-jobs":                                                  false,
	"GET /api/v1/admin/backfill-jobs/{job_id}":                                         false,
	"GET /api/v1/admin/credentials":                                                    true,
	"GET /api/v1/admin/credentials/{provider}/{name}":                                  true,
	"GET /api/v1/admin/customer-push/batches/{ingestion_id}":                           true,
	"GET /api/v1/admin/customer-push/schemas":                                          true,
	"GET /api/v1/admin/customer-push/schemas/{schema_version}":                         true,
	"GET /api/v1/admin/customer-push/sources":                                          true,
	"GET /api/v1/admin/customer-push/sources/{source_id}":                              true,
	"GET /api/v1/admin/customer-push/sources/{source_id}/batches":                      true,
	"GET /api/v1/admin/customer-push/sources/{source_id}/tokens":                       true,
	"GET /api/v1/admin/customer-push/tokens":                                           true,
	"GET /api/v1/admin/feature-flags":                                                  true,
	"GET /api/v1/admin/identities":                                                     true,
	"GET /api/v1/admin/impersonate/status":                                             true,
	"GET /api/v1/admin/integrations":                                                   true,
	"GET /api/v1/admin/integrations/pagerduty/services":                                true,
	"GET /api/v1/admin/integrations/pagerduty/status":                                  true,
	"GET /api/v1/admin/integrations/pagerduty/webhook-bindings/{binding_id}":           true,
	"GET /api/v1/admin/integrations/{integration_id}":                                  true,
	"GET /api/v1/admin/integrations/{integration_id}/datasets":                         true,
	"GET /api/v1/admin/integrations/{integration_id}/sources":                          true,
	"GET /api/v1/admin/ip-allowlist":                                                   true,
	"GET /api/v1/admin/ip-allowlist/{entry_id}":                                        true,
	"GET /api/v1/admin/llm-settings":                                                   true,
	"GET /api/v1/admin/llm-settings/budget":                                            true,
	"GET /api/v1/admin/llm-settings/spend":                                             true,
	"GET /api/v1/admin/orgs":                                                           true,
	"GET /api/v1/admin/orgs/{org_id}":                                                  true,
	"GET /api/v1/admin/orgs/{org_id}/feature-overrides":                                true,
	"GET /api/v1/admin/orgs/{org_id}/members":                                          true,
	"GET /api/v1/admin/platform/audit-logs":                                            true,
	"GET /api/v1/admin/platform/stats":                                                 true,
	"GET /api/v1/admin/retention-policies":                                             true,
	"GET /api/v1/admin/retention-policies/resource-types":                              true,
	"GET /api/v1/admin/retention-policies/{policy_id}":                                 true,
	"GET /api/v1/admin/settings/categories":                                            true,
	"GET /api/v1/admin/settings/{category}":                                            true,
	"GET /api/v1/admin/settings/{category}/{key}":                                      true,
	"GET /api/v1/admin/setup/status":                                                   true,
	"GET /api/v1/admin/sync-configs":                                                   true,
	"GET /api/v1/admin/sync-configs/auto-import-capabilities":                          true,
	"GET /api/v1/admin/sync-configs/{config_id}":                                       true,
	"GET /api/v1/admin/sync-configs/{config_id}/coverage":                              true,
	"GET /api/v1/admin/sync-configs/{config_id}/jobs":                                  true,
	"GET /api/v1/admin/sync-configs/{config_id}/repositories":                          true,
	"GET /api/v1/admin/sync-runs/{run_id}":                                             true,
	"GET /api/v1/admin/sync-runs/{run_id}/units":                                       true,
	"GET /api/v1/admin/sync-targets":                                                   true,
	"GET /api/v1/admin/teams":                                                          true,
	"GET /api/v1/admin/teams/discover":                                                 true,
	"GET /api/v1/admin/teams/pending-changes":                                          true,
	"GET /api/v1/admin/teams/{team_id}":                                                true,
	"GET /api/v1/admin/teams/{team_id}/discover-members":                               true,
	"GET /api/v1/admin/teams/{team_id}/infer-members":                                  true,
	"GET /api/v1/admin/users":                                                          true,
	"GET /api/v1/admin/users/{user_id}":                                                true,
	"GET /api/v1/auth/me":                                                              true,
	"GET /api/v1/auth/me/organizations":                                                true,
	"GET /api/v1/auth/oauth/{provider_type}/authorize":                                 true,
	"GET /api/v1/auth/onboarding/state":                                                true,
	"GET /api/v1/auth/saml/{provider_id}/metadata":                                     true,
	"GET /api/v1/auth/sso/providers":                                                   true,
	"GET /api/v1/auth/sso/providers/{provider_id}":                                     true,
	"GET /api/v1/auth/verify":                                                          true,
	"GET /api/v1/billing/audit":                                                        true,
	"GET /api/v1/billing/audit/{audit_id}":                                             true,
	"GET /api/v1/billing/entitlements/{org_id}":                                        true,
	"GET /api/v1/billing/invoices":                                                     true,
	"GET /api/v1/billing/invoices/{invoice_id}":                                        true,
	"GET /api/v1/billing/plans":                                                        true,
	"GET /api/v1/billing/plans/{plan_id}":                                              true,
	"GET /api/v1/billing/refunds":                                                      true,
	"GET /api/v1/billing/refunds/{refund_id}":                                          true,
	"GET /api/v1/billing/subscriptions":                                                true,
	"GET /api/v1/billing/subscriptions/history":                                        true,
	"GET /api/v1/billing/subscriptions/list":                                           true,
	"GET /api/v1/external-ingest/availability":                                         true,
	"GET /api/v1/external-ingest/batches":                                              true,
	"GET /api/v1/external-ingest/batches/{ingestion_id}":                               true,
	"GET /api/v1/external-ingest/schemas":                                              true,
	"GET /api/v1/external-ingest/schemas/{schema_version}":                             true,
	"GET /api/v1/internal/acr/entitlements/{org_id}":                                   true,
	"GET /api/v1/internal/acr/health":                                                  true,
	"GET /api/v1/licensing/entitlements/{org_id}":                                      true,
	"GET /api/v1/orgs/me":                                                              true,
	"GET /api/v1/telemetry/status":                                                     true,
	"GET /api/v1/webhooks/health":                                                      true,
	"GET /health":                                                                      true,
	"GET /health/workers":                                                              false,
	"GET /ready":                                                                       false,
	"HEAD /health":                                                                     true,
	"HEAD /health/workers":                                                             false,
	"HEAD /ready":                                                                      false,
	"PATCH /api/v1/admin/credentials/{provider}/{name}":                                true,
	"PATCH /api/v1/admin/customer-push/sources/{source_id}":                            true,
	"PATCH /api/v1/admin/feature-flags/{flag_id}":                                      true,
	"PATCH /api/v1/admin/integrations/{integration_id}":                                true,
	"PATCH /api/v1/admin/integrations/{integration_id}/datasets":                       true,
	"PATCH /api/v1/admin/integrations/{integration_id}/sources/{source_id}":            true,
	"PATCH /api/v1/admin/ip-allowlist/{entry_id}":                                      true,
	"PATCH /api/v1/admin/orgs/{org_id}":                                                true,
	"PATCH /api/v1/admin/orgs/{org_id}/feature-overrides/{override_id}":                true,
	"PATCH /api/v1/admin/orgs/{org_id}/members/{user_id}":                              true,
	"PATCH /api/v1/admin/retention-policies/{policy_id}":                               true,
	"PATCH /api/v1/admin/sync-configs/{config_id}":                                     true,
	"PATCH /api/v1/admin/teams/{team_id}":                                              true,
	"PATCH /api/v1/admin/users/{user_id}":                                              true,
	"PATCH /api/v1/auth/oauth/providers/{provider_id}":                                 true,
	"PATCH /api/v1/auth/sso/providers/{provider_id}":                                   true,
	"PATCH /api/v1/orgs/me":                                                            true,
	"POST /api/v1/admin/credentials":                                                   true,
	"POST /api/v1/admin/credentials/test":                                              true,
	"POST /api/v1/admin/customer-push/sources":                                         true,
	"POST /api/v1/admin/customer-push/sources/{source_id}/tokens":                      true,
	"POST /api/v1/admin/customer-push/sources/{source_id}/validate":                    true,
	"POST /api/v1/admin/customer-push/tokens":                                          true,
	"POST /api/v1/admin/customer-push/tokens/{token_id}/revoke":                        true,
	"POST /api/v1/admin/customer-push/tokens/{token_id}/rotate":                        true,
	"POST /api/v1/admin/identities":                                                    true,
	"POST /api/v1/admin/impersonate":                                                   true,
	"POST /api/v1/admin/impersonate/stop":                                              true,
	"POST /api/v1/admin/integrations":                                                  true,
	"POST /api/v1/admin/integrations/github/install-callback":                          true,
	"POST /api/v1/admin/integrations/github/install-url":                               true,
	"POST /api/v1/admin/integrations/pagerduty/api-token":                              true,
	"POST /api/v1/admin/integrations/pagerduty/authorize":                              true,
	"POST /api/v1/admin/integrations/pagerduty/callback":                               true,
	"POST /api/v1/admin/integrations/pagerduty/client-credentials":                     true,
	"POST /api/v1/admin/integrations/pagerduty/disconnect":                             true,
	"POST /api/v1/admin/integrations/pagerduty/preflight":                              true,
	"POST /api/v1/admin/integrations/pagerduty/webhook-bindings":                       true,
	"POST /api/v1/admin/integrations/pagerduty/webhook-bindings/{binding_id}/activate": true,
	"POST /api/v1/admin/integrations/pagerduty/webhook-bindings/{binding_id}/revoke":   true,
	"POST /api/v1/admin/integrations/pagerduty/webhook-bindings/{binding_id}/rotate":   true,
	"POST /api/v1/admin/integrations/{integration_id}/backfill":                        true,
	"POST /api/v1/admin/integrations/{integration_id}/discover":                        true,
	"POST /api/v1/admin/integrations/{integration_id}/sync":                            true,
	"POST /api/v1/admin/ip-allowlist":                                                  true,
	"POST /api/v1/admin/ip-allowlist/check":                                            true,
	"POST /api/v1/admin/orgs":                                                          true,
	"POST /api/v1/admin/orgs/{org_id}/feature-overrides":                               true,
	"POST /api/v1/admin/orgs/{org_id}/invites":                                         true,
	"POST /api/v1/admin/orgs/{org_id}/members":                                         true,
	"POST /api/v1/admin/retention-policies":                                            true,
	"POST /api/v1/admin/retention-policies/{policy_id}/execute":                        true,
	"POST /api/v1/admin/settings":                                                      true,
	"POST /api/v1/admin/sync-configs":                                                  true,
	"POST /api/v1/admin/sync-configs/batch":                                            true,
	"POST /api/v1/admin/sync-configs/{config_id}/backfill":                             true,
	"POST /api/v1/admin/sync-configs/{config_id}/trigger":                              true,
	"POST /api/v1/admin/teams":                                                         true,
	"POST /api/v1/admin/teams/import":                                                  true,
	"POST /api/v1/admin/teams/{team_id}/approve-changes":                               true,
	"POST /api/v1/admin/teams/{team_id}/confirm-inferred-members":                      true,
	"POST /api/v1/admin/teams/{team_id}/confirm-members":                               true,
	"POST /api/v1/admin/teams/{team_id}/dismiss-changes":                               true,
	"POST /api/v1/admin/users":                                                         true,
	"POST /api/v1/admin/users/{user_id}/password":                                      true,
	"POST /api/v1/auth/accept-invite":                                                  true,
	"POST /api/v1/auth/forgot-password":                                                true,
	"POST /api/v1/auth/login":                                                          true,
	"POST /api/v1/auth/logout":                                                         true,
	"POST /api/v1/auth/oauth/providers":                                                true,
	"POST /api/v1/auth/oauth/{provider_id}/authorize":                                  true,
	"POST /api/v1/auth/oauth/{provider_id}/callback":                                   true,
	"POST /api/v1/auth/oidc/{provider_id}/authorize":                                   true,
	"POST /api/v1/auth/oidc/{provider_id}/callback":                                    true,
	"POST /api/v1/auth/onboard":                                                        true,
	"POST /api/v1/auth/onboarding/skip-integration":                                    true,
	"POST /api/v1/auth/refresh":                                                        true,
	"POST /api/v1/auth/register":                                                       true,
	"POST /api/v1/auth/resend-verification":                                            true,
	"POST /api/v1/auth/reset-password":                                                 true,
	"POST /api/v1/auth/saml/{provider_id}/acs":                                         true,
	"POST /api/v1/auth/saml/{provider_id}/initiate":                                    true,
	"POST /api/v1/auth/social-login":                                                   true,
	"POST /api/v1/auth/sso/providers":                                                  true,
	"POST /api/v1/auth/sso/providers/{provider_id}/activate":                           true,
	"POST /api/v1/auth/sso/providers/{provider_id}/deactivate":                         true,
	"POST /api/v1/auth/switch-org":                                                     true,
	"POST /api/v1/auth/validate":                                                       true,
	"POST /api/v1/billing/audit/{audit_id}/resolve":                                    true,
	"POST /api/v1/billing/checkout":                                                    true,
	"POST /api/v1/billing/invoices/{invoice_id}/void":                                  true,
	"POST /api/v1/billing/plans":                                                       true,
	"POST /api/v1/billing/plans/pull-stripe":                                           true,
	"POST /api/v1/billing/plans/{plan_id}/sync-stripe":                                 true,
	"POST /api/v1/billing/portal":                                                      true,
	"POST /api/v1/billing/reconcile":                                                   true,
	"POST /api/v1/billing/refunds":                                                     true,
	"POST /api/v1/billing/subscriptions/cancel":                                        true,
	"POST /api/v1/billing/subscriptions/change-plan":                                   true,
	"POST /api/v1/billing/subscriptions/reactivate":                                    true,
	"POST /api/v1/billing/webhooks/stripe":                                             true,
	"POST /api/v1/external-ingest/batches":                                             false,
	"POST /api/v1/external-ingest/validate":                                            true,
	"POST /api/v1/ingest/commits":                                                      true,
	"POST /api/v1/ingest/deployments":                                                  true,
	"POST /api/v1/ingest/incidents":                                                    true,
	"POST /api/v1/ingest/pull-requests":                                                true,
	"POST /api/v1/ingest/telemetry":                                                    true,
	"POST /api/v1/ingest/work-items":                                                   true,
	"POST /api/v1/product-telemetry/events":                                            true,
	"POST /api/v1/telemetry/opt-in":                                                    true,
	"POST /api/v1/telemetry/opt-out":                                                   true,
	"POST /api/v1/telemetry/report":                                                    true,
	"POST /api/v1/webhooks/github":                                                     true,
	"POST /api/v1/webhooks/gitlab":                                                     true,
	"POST /api/v1/webhooks/jira":                                                       true,
	"POST /api/v1/webhooks/pagerduty/{binding_id}":                                     false,
	"PUT /api/v1/admin/llm-settings":                                                   true,
	"PUT /api/v1/admin/settings/{category}/{key}":                                      true,
	"PUT /api/v1/admin/sync-configs/{config_id}/repositories":                          true,
	"PUT /api/v1/billing/plans/{plan_id}":                                              true,
}

func TestResponseModelRoutesEqualPreSplitTable(t *testing.T) {
	for key, want := range wantResponseModelRoutes {
		got, ok := responseModelRoutes[key]
		if !ok {
			t.Errorf("route %q is missing from the runtime response-model table", key)
			continue
		}
		if got != want {
			t.Errorf("route %q = %t, want %t", key, got, want)
		}
	}
	for key := range responseModelRoutes {
		if _, ok := wantResponseModelRoutes[key]; !ok {
			t.Errorf("route %q is in the runtime table but not in wantResponseModelRoutes", key)
		}
	}
	if len(responseModelRoutes) != len(wantResponseModelRoutes) {
		t.Errorf("runtime table has %d routes, want %d", len(responseModelRoutes), len(wantResponseModelRoutes))
	}
}
