// Code generated by go run ./internal/queryapi/server/testdata/chaos-8509/home_coverage_policy_generate.go -root . -write; DO NOT EDIT.
//go:build integration

package server

// The fixture-only capture source is hosted venue run 37413067348, job 112105594511, artifact 11390701993 at 9c438f9ca4e59eaecfb790448731a7e72177aaf3. The capture path records equal status and non-content-length headers before it writes a body.
// It is synthetic harness data only: no local-org data, credentials, or personal data is represented here.
var chaos8509HomeCapturePolicyOrder = []chaos8169HomeNoDataLedgerKey{
	{Oracle: "dict-order", Case: "home no data"},
	{Oracle: "graphql-edge", Case: "POST home"},
	{Oracle: "graphql-edge", Case: "GET home"},
}

var chaos8509HomeCapturePolicies = map[chaos8169HomeNoDataLedgerKey]chaos8509HomeCapturePolicy{
	{Oracle: "dict-order", Case: "home no data"}: {
		File:                   "dict-order-home-no-data.json",
		FixtureSHA256:          "a2c77bf9662fd68f572da39c07e3b4e8a47fffe24605d729de73d17ee1551be7",
		PythonSHA256:           "7c7be2be95ee48f42a1b2eced15e71d0a72344a06c1fefa9ebdf35f34d8f60be",
		GoSHA256:               "db314b2d10a6c2e26af35885f97b427a153548f7e6bc0cd39e2378f6598a8b45",
		SourceHead:             "9c438f9ca4e59eaecfb790448731a7e72177aaf3",
		SourceRun:              "37413067348",
		SourceJob:              "112105594511",
		SourceArtifact:         "11390701993",
		SourceReceiptSHA256:    "08a379f6ccf122291b1ff0997aaba0589cc750958663a6f6d36f0ba057c84dd1",
		ExpectedStatus:         200,
		HeadersEqual:           true,
		DifferenceLeaves:       197,
		LegacyDifferenceLeaves: 192,
		Entries: []chaos8509HomeCaptureEntry{
			{Path: "/freshness/coverage/repos_covered_pct", Python: "0.0", Go: "null"},
			{Path: "/freshness/coverage/prs_linked_to_issues_pct", Python: "0.0", Go: "null"},
			{Path: "/freshness/coverage/issues_with_cycle_states_pct", Python: "0.0", Go: "null"},
			{Path: "/data_confidence/coverage_pct", Python: "0.0", Go: "null"},
			{Path: "/data_confidence/caveats/0", Python: "\"Coverage appears partial; treat cockpit signals as directional.\"", Go: "\"Coverage could not be computed from available lineage fields.\""},
		},
	},
	{Oracle: "graphql-edge", Case: "POST home"}: {
		File:                   "graphql-edge-post-home.json",
		FixtureSHA256:          "7b901c0c452e3b667bc826e9b41b1a8c5fe65e78d91a4ebc1728f0b28de86bb9",
		PythonSHA256:           "8c147f53f2269790870f834351e8211bd2a061024dc452243a1efccb33f76d6e",
		GoSHA256:               "ecab10997fcd97956f32cd4f11ba7676a07efea203144da5a3c6d621a46ed352",
		SourceHead:             "9c438f9ca4e59eaecfb790448731a7e72177aaf3",
		SourceRun:              "37413067348",
		SourceJob:              "112105594511",
		SourceArtifact:         "11390701993",
		SourceReceiptSHA256:    "08a379f6ccf122291b1ff0997aaba0589cc750958663a6f6d36f0ba057c84dd1",
		ExpectedStatus:         200,
		HeadersEqual:           true,
		DifferenceLeaves:       204,
		LegacyDifferenceLeaves: 199,
		Entries: []chaos8509HomeCaptureEntry{
			{Path: "/freshness/coverage/reposCoveredPct", Python: "0", Go: "null"},
			{Path: "/freshness/coverage/prsLinkedToIssuesPct", Python: "0", Go: "null"},
			{Path: "/freshness/coverage/issuesWithCycleStatesPct", Python: "0", Go: "null"},
			{Path: "/dataConfidence/coveragePct", Python: "0", Go: "null"},
			{Path: "/dataConfidence/caveats/0", Python: "\"Coverage appears partial; treat cockpit signals as directional.\"", Go: "\"Coverage could not be computed from available lineage fields.\""},
		},
	},
	{Oracle: "graphql-edge", Case: "GET home"}: {
		File:                   "graphql-edge-get-home.json",
		FixtureSHA256:          "d892082ebe74f71bc05397e180ff2b21fb6615d394008c78b7aa655e8e882607",
		PythonSHA256:           "8c147f53f2269790870f834351e8211bd2a061024dc452243a1efccb33f76d6e",
		GoSHA256:               "ecab10997fcd97956f32cd4f11ba7676a07efea203144da5a3c6d621a46ed352",
		SourceHead:             "9c438f9ca4e59eaecfb790448731a7e72177aaf3",
		SourceRun:              "37413067348",
		SourceJob:              "112105594511",
		SourceArtifact:         "11390701993",
		SourceReceiptSHA256:    "08a379f6ccf122291b1ff0997aaba0589cc750958663a6f6d36f0ba057c84dd1",
		ExpectedStatus:         200,
		HeadersEqual:           true,
		DifferenceLeaves:       204,
		LegacyDifferenceLeaves: 199,
		Entries: []chaos8509HomeCaptureEntry{
			{Path: "/freshness/coverage/reposCoveredPct", Python: "0", Go: "null"},
			{Path: "/freshness/coverage/prsLinkedToIssuesPct", Python: "0", Go: "null"},
			{Path: "/freshness/coverage/issuesWithCycleStatesPct", Python: "0", Go: "null"},
			{Path: "/dataConfidence/coveragePct", Python: "0", Go: "null"},
			{Path: "/dataConfidence/caveats/0", Python: "\"Coverage appears partial; treat cockpit signals as directional.\"", Go: "\"Coverage could not be computed from available lineage fields.\""},
		},
	},
}
