package server

// mcpInputClassesFile is the class table of mcp_person_policy.go: one line per
// position a request value can land on -- an argument of an allow-listed root
// field (or of a field reachable from one), a field of an input object, an enum
// value -- as "<kind> <position> <person|other>". Reviewed by PR: a position
// that is not listed is refused by the MCP listener as unclassified, and
// TestMCPInputClassesCoverEveryReachablePositionExactly fails the build for it.
// It is Go source (not an embedded data file) so that a change to it triggers
// the Go workflow like any other code change.
const mcpInputClassesFile = `arg Query.analytics.batch other
arg Query.analytics.orgId other
arg Query.capacityForecast.input other
arg Query.capacityForecast.orgId other
arg Query.capacityForecasts.filters other
arg Query.capacityForecasts.orgId other
arg Query.catalog.dimension other
arg Query.catalog.filters other
arg Query.catalog.orgId other
arg Query.cognitiveLoad.input other
arg Query.complexityTimeseries.input other
arg Query.compoundingRisk.filter other
arg Query.compoundingRisk.orgId other
arg Query.hotspots.input other
arg Query.securityAlerts.filters other
arg Query.securityAlerts.orgId other
arg Query.securityAlerts.pagination other
arg Query.securityOverview.filters other
arg Query.securityOverview.orgId other
arg Query.throughputForecast.input other
arg Query.throughputForecast.orgId other
arg Query.workGraphArtifacts.filters other
arg Query.workGraphArtifacts.orgId other
arg Query.workGraphEdges.filters other
arg Query.workGraphEdges.orgId other
arg Query.workGraphFlow.filters other
arg Query.workGraphFlow.orgId other
enum BucketIntervalInput.DAY other
enum BucketIntervalInput.MONTH other
enum BucketIntervalInput.WEEK other
enum ComplexityScope.FILE other
enum ComplexityScope.REPO other
enum CompoundingRiskScope.REPO other
enum CompoundingRiskScope.TEAM other
enum DimensionInput.AUTHOR person
enum DimensionInput.REPO other
enum DimensionInput.SUBCATEGORY other
enum DimensionInput.TEAM other
enum DimensionInput.THEME other
enum DimensionInput.WORK_TYPE other
enum MeasureInput.CHURN_LOC other
enum MeasureInput.COUNT other
enum MeasureInput.COVERAGE_BRANCH_PCT other
enum MeasureInput.COVERAGE_DELTA_PCT other
enum MeasureInput.COVERAGE_LINE_PCT other
enum MeasureInput.CYCLE_TIME_HOURS other
enum MeasureInput.FLAG_ACTIVATION_RATE other
enum MeasureInput.FLAG_COVERAGE_RATIO other
enum MeasureInput.FLAG_ERROR_RATE_DELTA other
enum MeasureInput.FLAG_FRICTION_DELTA other
enum MeasureInput.PIPELINE_DURATION_P95 other
enum MeasureInput.PIPELINE_FAILURE_RATE other
enum MeasureInput.PIPELINE_QUEUE_TIME other
enum MeasureInput.PIPELINE_RERUN_RATE other
enum MeasureInput.PIPELINE_SUCCESS_RATE other
enum MeasureInput.PR_REWORK_RATIO other
enum MeasureInput.TEST_FAILURE_RATE other
enum MeasureInput.TEST_FLAKE_RATE other
enum MeasureInput.TEST_PASS_RATE other
enum MeasureInput.TEST_SUITE_DURATION_P95 other
enum MeasureInput.THROUGHPUT other
enum ScopeLevelInput.DEVELOPER person
enum ScopeLevelInput.ORG other
enum ScopeLevelInput.REPO other
enum ScopeLevelInput.SERVICE other
enum ScopeLevelInput.TEAM other
enum SecuritySeverityInput.CRITICAL other
enum SecuritySeverityInput.HIGH other
enum SecuritySeverityInput.LOW other
enum SecuritySeverityInput.MEDIUM other
enum SecuritySeverityInput.UNKNOWN other
enum SecuritySourceInput.ADVISORY other
enum SecuritySourceInput.CODE_SCANNING other
enum SecuritySourceInput.DEPENDABOT other
enum SecuritySourceInput.GITLAB_DEPENDENCY other
enum SecuritySourceInput.GITLAB_VULNERABILITY other
enum SecurityStateInput.CONFIRMED other
enum SecurityStateInput.DETECTED other
enum SecurityStateInput.DISMISSED other
enum SecurityStateInput.FIXED other
enum SecurityStateInput.OPEN other
enum SecurityStateInput.RESOLVED other
enum TimeGranularity.DAY other
enum TimeGranularity.WEEK other
enum WorkGraphEdgeTypeInput.BLOCKS other
enum WorkGraphEdgeTypeInput.CHILD_OF other
enum WorkGraphEdgeTypeInput.CONFIG_CHANGED_BY other
enum WorkGraphEdgeTypeInput.CONTAINS other
enum WorkGraphEdgeTypeInput.DEPLOYS other
enum WorkGraphEdgeTypeInput.DUPLICATES other
enum WorkGraphEdgeTypeInput.FIXES other
enum WorkGraphEdgeTypeInput.GENERATES other
enum WorkGraphEdgeTypeInput.GUARDS other
enum WorkGraphEdgeTypeInput.HAS_AI_WORKFLOW other
enum WorkGraphEdgeTypeInput.HAS_REVIEW_OUTCOME other
enum WorkGraphEdgeTypeInput.IMPACTS other
enum WorkGraphEdgeTypeInput.IMPLEMENTS other
enum WorkGraphEdgeTypeInput.INTRODUCED_BY other
enum WorkGraphEdgeTypeInput.IS_BLOCKED_BY other
enum WorkGraphEdgeTypeInput.IS_DUPLICATE_OF other
enum WorkGraphEdgeTypeInput.IS_RELATED_TO other
enum WorkGraphEdgeTypeInput.LINKED_INCIDENT other
enum WorkGraphEdgeTypeInput.PARENT_OF other
enum WorkGraphEdgeTypeInput.REFERENCES other
enum WorkGraphEdgeTypeInput.RELATES other
enum WorkGraphEdgeTypeInput.TOUCHES other
enum WorkGraphNodeTypeInput.AI_WORKFLOW_RUN other
enum WorkGraphNodeTypeInput.COMMIT other
enum WorkGraphNodeTypeInput.DEPLOYMENT other
enum WorkGraphNodeTypeInput.DIFF other
enum WorkGraphNodeTypeInput.FEATURE_FLAG other
enum WorkGraphNodeTypeInput.FILE other
enum WorkGraphNodeTypeInput.INCIDENT other
enum WorkGraphNodeTypeInput.ISSUE other
enum WorkGraphNodeTypeInput.PR other
enum WorkGraphNodeTypeInput.RELEASE other
enum WorkGraphNodeTypeInput.REVIEW_OUTCOME other
input AnalyticsRequestInput.breakdowns other
input AnalyticsRequestInput.evidenceQualityGroupBy other
input AnalyticsRequestInput.filters other
input AnalyticsRequestInput.flowMatrix other
input AnalyticsRequestInput.sankey other
input AnalyticsRequestInput.timeseries other
input AnalyticsRequestInput.useInvestment other
input BreakdownRequestInput.dateRange other
input BreakdownRequestInput.dimension other
input BreakdownRequestInput.measure other
input BreakdownRequestInput.topN other
input CapacityForecastFilterInput.fromDate other
input CapacityForecastFilterInput.limit other
input CapacityForecastFilterInput.teamId other
input CapacityForecastFilterInput.toDate other
input CapacityForecastFilterInput.workScopeId other
input CapacityForecastInput.historyDays other
input CapacityForecastInput.simulations other
input CapacityForecastInput.targetDate other
input CapacityForecastInput.targetItems other
input CapacityForecastInput.teamId other
input CapacityForecastInput.teamIds other
input CapacityForecastInput.workScopeId other
input CognitiveLoadInput.orgId other
input CognitiveLoadInput.repoId other
input CognitiveLoadInput.sinceDate other
input CognitiveLoadInput.teamId other
input CognitiveLoadInput.untilDate other
input ComplexityTimeseriesInput.granularity other
input ComplexityTimeseriesInput.limit other
input ComplexityTimeseriesInput.orgId other
input ComplexityTimeseriesInput.repoIds other
input ComplexityTimeseriesInput.scope other
input ComplexityTimeseriesInput.sinceUtc other
input ComplexityTimeseriesInput.teamIds other
input ComplexityTimeseriesInput.untilUtc other
input CompoundingRiskFilterInput.breakout other
input CompoundingRiskFilterInput.day other
input CompoundingRiskFilterInput.repoIds other
input CompoundingRiskFilterInput.teamIds other
input CompoundingRiskFilterInput.trendDays other
input DateRangeInput.endDate other
input DateRangeInput.startDate other
input FilterInput.how other
input FilterInput.scope other
input FilterInput.what other
input FilterInput.who person
input FilterInput.why other
input FlowMatrixRequestInput.dateRange other
input FlowMatrixRequestInput.dimension other
input FlowMatrixRequestInput.maxEdges other
input FlowMatrixRequestInput.maxNodes other
input FlowMatrixRequestInput.measure other
input FlowMatrixRequestInput.useInvestment other
input HotspotsInput.limit other
input HotspotsInput.orgId other
input HotspotsInput.repoIds other
input HotspotsInput.sinceUtc other
input HotspotsInput.teamIds other
input HotspotsInput.untilUtc other
input HowFilterInput.flowStage other
input SankeyRequestInput.dateRange other
input SankeyRequestInput.maxEdges other
input SankeyRequestInput.maxNodes other
input SankeyRequestInput.measure other
input SankeyRequestInput.path other
input SankeyRequestInput.useInvestment other
input ScopeFilterInput.ids other
input ScopeFilterInput.level other
input SecurityAlertFilterInput.openOnly other
input SecurityAlertFilterInput.repoIds other
input SecurityAlertFilterInput.search other
input SecurityAlertFilterInput.severities other
input SecurityAlertFilterInput.since other
input SecurityAlertFilterInput.sources other
input SecurityAlertFilterInput.states other
input SecurityAlertFilterInput.until other
input SecurityPaginationInput.after other
input SecurityPaginationInput.first other
input ThroughputForecastInput.backlogSize other
input ThroughputForecastInput.historyWeeks other
input ThroughputForecastInput.teamIds other
input ThroughputForecastInput.workScopeId other
input TimeseriesRequestInput.dateRange other
input TimeseriesRequestInput.dimension other
input TimeseriesRequestInput.interval other
input TimeseriesRequestInput.measure other
input WhatFilterInput.repos other
input WhatFilterInput.services other
input WhoFilterInput.developers person
input WhoFilterInput.roles other
input WhyFilterInput.issueType other
input WhyFilterInput.workCategory other
input WorkGraphEdgeFilterInput.allowScopedPartial other
input WorkGraphEdgeFilterInput.edgeType other
input WorkGraphEdgeFilterInput.edgeTypes other
input WorkGraphEdgeFilterInput.limit other
input WorkGraphEdgeFilterInput.nodeId other
input WorkGraphEdgeFilterInput.repoIds other
input WorkGraphEdgeFilterInput.sourceType other
input WorkGraphEdgeFilterInput.subcategory other
input WorkGraphEdgeFilterInput.targetType other
input WorkGraphEdgeFilterInput.theme other
`
