package synclog

// exportedAPI is the EXACT exported surface of this package (CHAOS-7933, D4315): every exported var, type, function and method
// with its full signature, and every struct field with its export state. TestTheExportedAPIIsPinned compares the package's
// real surface to this list, so a function added, removed or whose signature changed (a []byte, a map or a func() string where a
// typed value was) fails until this list is edited in the same diff, and a reviewer sees the change.
var exportedAPI = []string{
	"field Attr.attr log/slog.Attr exported=false",
	"field ID.text string exported=false",
	"field Key.text string exported=false",
	"field Label.text string exported=false",
	"field Logger.inner *log/slog.Logger exported=false",
	"field Msg.text string exported=false",
	"func (*synclog.Logger).Debug(ctx context.Context, message synclog.Msg, attrs ...synclog.Attr)",
	"func (*synclog.Logger).Error(ctx context.Context, message synclog.Msg, attrs ...synclog.Attr)",
	"func (*synclog.Logger).Info(ctx context.Context, message synclog.Msg, attrs ...synclog.Attr)",
	"func (*synclog.Logger).Warn(ctx context.Context, message synclog.Msg, attrs ...synclog.Attr)",
	"func synclog.Count[N ~int | ~int64](key synclog.Key, value N) synclog.Attr",
	"func synclog.Default() *synclog.Logger",
	"func synclog.Dispatch(id synclog.ID) synclog.Attr",
	"func synclog.Elapsed(key synclog.Key, value time.Duration) synclog.Attr",
	"func synclog.Failure(err error) synclog.Attr",
	"func synclog.Flag(key synclog.Key, value bool) synclog.Attr",
	"func synclog.Group(key synclog.Key, attrs ...synclog.Attr) synclog.Attr",
	"func synclog.IDs(key synclog.Key, ids []synclog.ID) synclog.Attr",
	"func synclog.Instant(key synclog.Key, value time.Time) synclog.Attr",
	"func synclog.Integration(id synclog.ID) synclog.Attr",
	"func synclog.New(inner *slog.Logger) *synclog.Logger",
	"func synclog.Org(id synclog.ID) synclog.Attr",
	"func synclog.ParseID(value string) synclog.ID",
	"func synclog.ParseIDs(values []string) []synclog.ID",
	"func synclog.ParseLabel(value string) synclog.Label",
	"func synclog.Provider(value synclog.Label) synclog.Attr",
	"func synclog.Run(id synclog.ID) synclog.Attr",
	"func synclog.Source(id synclog.ID) synclog.Attr",
	"func synclog.Text(key synclog.Key, value synclog.Label) synclog.Attr",
	"func synclog.Unit(id synclog.ID) synclog.Attr",
	"type synclog.Attr struct{attr slog.Attr}",
	"type synclog.ID struct{text string}",
	"type synclog.Key struct{text string}",
	"type synclog.Label struct{text string}",
	"type synclog.Logger struct{inner *slog.Logger}",
	"type synclog.Msg struct{text string}",
	"var synclog.KeyAdmissionCapHeavy synclog.Key",
	"var synclog.KeyAdmissionCapLight synclog.Key",
	"var synclog.KeyAdmissionCapMedium synclog.Key",
	"var synclog.KeyAdmissionCapHeavySource synclog.Key",
	"var synclog.KeyAdmissionCapLightSource synclog.Key",
	"var synclog.KeyAdmissionCapMediumSource synclog.Key",
	"var synclog.KeyAdmissionClamp synclog.Key",
	"var synclog.KeyAdmissionClampSource synclog.Key",
	"var synclog.KeyAssertedEpisode synclog.Key",
	"var synclog.KeyAvailableAt synclog.Key",
	"var synclog.KeyBucket synclog.Key",
	"var synclog.KeyBudgetDeferrals synclog.Key",
	"var synclog.KeyBudgetKey synclog.Key",
	"var synclog.KeyBudgetLimit synclog.Key",
	"var synclog.KeyBudgetLimitHeavy synclog.Key",
	"var synclog.KeyBudgetLimitLight synclog.Key",
	"var synclog.KeyBudgetLimitMedium synclog.Key",
	"var synclog.KeyCappedCount synclog.Key",
	"var synclog.KeyClaimDeferredOutsideSnapshot synclog.Key",
	"var synclog.KeyClaimDeferredUnitIdSample synclog.Key",
	"var synclog.KeyConfidence synclog.Key",
	"var synclog.KeyConsideredUnits synclog.Key",
	"var synclog.KeyCostClass synclog.Key",
	"var synclog.KeyCount synclog.Key",
	"var synclog.KeyCountdown synclog.Key",
	"var synclog.KeyCredentialFingerprint synclog.Key",
	"var synclog.KeyDatasetKey synclog.Key",
	"var synclog.KeyDecision synclog.Key",
	"var synclog.KeyDeferredUnits synclog.Key",
	"var synclog.KeyDimension synclog.Key",
	"var synclog.KeyDroppedObservationFields synclog.Key",
	"var synclog.KeyError synclog.Key",
	"var synclog.KeyErrorCategory synclog.Key",
	"var synclog.KeyErrorCode synclog.Key",
	"var synclog.KeyEstimatedUnits synclog.Key",
	"var synclog.KeyFailedPlannedUnits synclog.Key",
	"var synclog.KeyFailedStaleDispatchingUnits synclog.Key",
	"var synclog.KeyGroupCount synclog.Key",
	"var synclog.KeyGuardActiveCount synclog.Key",
	"var synclog.KeyGuardCappedNew synclog.Key",
	"var synclog.KeyGuardCappedStale synclog.Key",
	"var synclog.KeyGuardReclaimedStale synclog.Key",
	"var synclog.KeyGuardSlotHeadroom synclog.Key",
	"var synclog.KeyHost synclog.Key",
	"var synclog.KeyInFlightUnits synclog.Key",
	"var synclog.KeyInvalidClaimUnits synclog.Key",
	"var synclog.KeyLockWaitBudget synclog.Key",
	"var synclog.KeyNextDeferredAt synclog.Key",
	"var synclog.KeyOrgId synclog.Key",
	"var synclog.KeyOutcome synclog.Key",
	"var synclog.KeyPath synclog.Key",
	"var synclog.KeyPendingUnits synclog.Key",
	"var synclog.KeyPhase synclog.Key",
	"var synclog.KeyPriorAvailableAt synclog.Key",
	"var synclog.KeyProjectedUnits synclog.Key",
	"var synclog.KeyProvider synclog.Key",
	"var synclog.KeyQueuedUnits synclog.Key",
	"var synclog.KeyRateLimitDeferrals synclog.Key",
	"var synclog.KeyFactsDerived synclog.Key",
	"var synclog.KeyFactsUnchanged synclog.Key",
	"var synclog.KeyReason synclog.Key",
	"var synclog.KeyRepoCount synclog.Key",
	"var synclog.KeyRestoredAvailableAt synclog.Key",
	"var synclog.KeyRouteFamily synclog.Key",
	"var synclog.KeyRowsRetracted synclog.Key",
	"var synclog.KeyRowsWritten synclog.Key",
	"var synclog.KeyRunningUnits synclog.Key",
	"var synclog.KeySourceId synclog.Key",
	"var synclog.KeyStrict synclog.Key",
	"var synclog.KeySuggestedAvailableAt synclog.Key",
	"var synclog.KeySyncRunId synclog.Key",
	"var synclog.KeyTerminalDeliveryPublishes synclog.Key",
	"var synclog.KeyTerminalized synclog.Key",
	"var synclog.KeyTotalUnits synclog.Key",
	"var synclog.KeyUnitId synclog.Key",
	"var synclog.KeyUnitLastErrorCategory synclog.Key",
	"var synclog.KeyUnroutableUnits synclog.Key",
	"var synclog.LabelCooldownActive synclog.Label",
	"var synclog.LabelCooldownLandedAfterAdmission synclog.Label",
	"var synclog.LabelFailed synclog.Label",
	"var synclog.LabelInsufficientSurplus synclog.Label",
	"var synclog.LabelInvalid synclog.Label",
	"var synclog.LabelNoConcurrencySlot synclog.Label",
	"var synclog.LabelNoPriorAvailableAt synclog.Label",
	"var synclog.LabelPostClaim synclog.Label",
	"var synclog.LabelPreCapacity synclog.Label",
	"var synclog.LabelReclaimedUnitsWhoseDeliveriesAreAlreadyTerminalNothingWasDel synclog.Label",
	"var synclog.MsgDispatchGuardBucketDecision synclog.Msg",
	"var synclog.MsgDispatchSyncRunBlockedOnReferenceDiscovery synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetEstimateUnitFailed synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetGuardActiveConsumptionFanout synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetGuardActiveEstimateFailed synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetGuardAllowed synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetGuardDeferred synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetGuardDryRun synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetGuardDryRunFailed synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetGuardEnforceFailed synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetSurplusAdmitted synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetSurplusCandidatesTruncated synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetSurplusPulledForward synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetSurplusSkipped synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetSurplusWithdrawalLostRace synclog.Msg",
	"var synclog.MsgDispatchSyncRunBudgetSurplusWithdrawn synclog.Msg",
	"var synclog.MsgDispatchSyncRunClaimDeferredOutsideGuardSnapshot synclog.Msg",
	"var synclog.MsgDispatchSyncRunConcurrencyCapped synclog.Msg",
	"var synclog.MsgDispatchSyncRunCooldownObservationReadFailed synclog.Msg",
	"var synclog.MsgDispatchSyncRunCooldownObservationRowMalformed synclog.Msg",
	"var synclog.MsgDispatchSyncRunDeferred synclog.Msg",
	"var synclog.MsgDispatchSyncRunDenied synclog.Msg",
	"var synclog.MsgDispatchSyncRunDeniedWithActiveUnits synclog.Msg",
	"var synclog.MsgDispatchSyncRunDispatched synclog.Msg",
	"var synclog.MsgDispatchSyncRunFeatureDisabled synclog.Msg",
	"var synclog.MsgDispatchSyncRunInvalidClaimUnitsTerminalized synclog.Msg",
	"var synclog.MsgDispatchSyncRunLockBusyRequeued synclog.Msg",
	"var synclog.MsgDispatchSyncRunMissing synclog.Msg",
	"var synclog.MsgDispatchSyncRunNoProgress synclog.Msg",
	"var synclog.MsgDispatchSyncRunNoop synclog.Msg",
	"var synclog.MsgDispatchSyncRunNoopFinalize synclog.Msg",
	"var synclog.MsgDispatchSyncRunPublishHitTerminalDelivery synclog.Msg",
	"var synclog.MsgDispatchSyncRunRateLimitCooldownDeferred synclog.Msg",
	"var synclog.MsgDispatchSyncRunRateLimitCooldownReconfirmed synclog.Msg",
	"var synclog.MsgDispatchSyncRunRedispatchRearmFailed synclog.Msg",
	"var synclog.MsgDispatchSyncRunRedispatchRearmed synclog.Msg",
	"var synclog.MsgDispatchSyncRunTerminalDeliveryPublishes synclog.Msg",
	"var synclog.MsgDispatchSyncRunTerminalVerdictRefused synclog.Msg",
	"var synclog.MsgDispatchSyncRunUnitTerminalized synclog.Msg",
	"var synclog.MsgDispatchSyncRunUnroutableUnitsTerminalized synclog.Msg",
	"var synclog.MsgDispatchSyncRunWaitingInflight synclog.Msg",
	"var synclog.MsgFinalizeSyncRunComputeCheckpointUnitFailed synclog.Msg",
	"var synclog.MsgFinalizeSyncRunCoverageCacheInvalidated synclog.Msg",
	"var synclog.MsgFinalizeSyncRunCoverageCacheInvalidationFailed synclog.Msg",
	"var synclog.MsgFinalizeSyncRunZeroUnitFinalized synclog.Msg",
	"var synclog.MsgPostSyncFanout synclog.Msg",
	"var synclog.MsgPostSyncTeamAutoimportHandoffDropped synclog.Msg",
	"var synclog.MsgPostSyncTeamRepoOwnershipDerivationHandoffDropped synclog.Msg",
	"var synclog.MsgRunSyncReferenceDiscoveryHeartbeatFailed synclog.Msg",
	"var synclog.MsgSyncDispatchAdmissionCaps synclog.Msg",
	"var synclog.MsgSyncRunAuthFingerprintMismatch synclog.Msg",
	"var synclog.MsgSyncRunRollupBumped synclog.Msg",
	"var synclog.MsgTeamRepoOwnershipDerivation synclog.Msg",
}
