package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/analytics"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/authctx"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/cognitiveload"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/complexitytimeseries"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/featureflags"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/graph/model"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/hotspots"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/operatingreview"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/reviewedges"
	"github.com/full-chaos/dev-health-ops/cmd/query-api/internal/workgraph"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateSavedReport is the resolver for the createSavedReport field.
func (r *mutationResolver) CreateSavedReport(ctx context.Context, orgID string, input model.CreateSavedReportInput) (*model.SavedReportType, error) {
	panic(fmt.Errorf("not implemented: CreateSavedReport - createSavedReport"))
}

// UpdateSavedReport is the resolver for the updateSavedReport field.
func (r *mutationResolver) UpdateSavedReport(ctx context.Context, orgID string, reportID string, input model.UpdateSavedReportInput) (*model.SavedReportType, error) {
	panic(fmt.Errorf("not implemented: UpdateSavedReport - updateSavedReport"))
}

// DeleteSavedReport is the resolver for the deleteSavedReport field.
func (r *mutationResolver) DeleteSavedReport(ctx context.Context, orgID string, reportID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteSavedReport - deleteSavedReport"))
}

// CloneSavedReport is the resolver for the cloneSavedReport field.
func (r *mutationResolver) CloneSavedReport(ctx context.Context, orgID string, input model.CloneSavedReportInput) (*model.SavedReportType, error) {
	panic(fmt.Errorf("not implemented: CloneSavedReport - cloneSavedReport"))
}

// TriggerReport is the resolver for the triggerReport field.
func (r *mutationResolver) TriggerReport(ctx context.Context, orgID string, reportID string) (*model.ReportRunType, error) {
	panic(fmt.Errorf("not implemented: TriggerReport - triggerReport"))
}

// DevScopeSearch is the resolver for the devScopeSearch field.
func (r *queryResolver) DevScopeSearch(ctx context.Context, orgID string, input model.DevScopeSearchInput) (*model.DevScopeSearchResult, error) {
	panic(fmt.Errorf("not implemented: DevScopeSearch - devScopeSearch"))
}

// DevMetricCatalog is the resolver for the devMetricCatalog field.
func (r *queryResolver) DevMetricCatalog(ctx context.Context, orgID string, input *model.DevMetricCatalogInput) (*model.DevMetricCatalog, error) {
	panic(fmt.Errorf("not implemented: DevMetricCatalog - devMetricCatalog"))
}

// DevMetric is the resolver for the devMetric field.
func (r *queryResolver) DevMetric(ctx context.Context, orgID string, input model.DevMetricQueryInput) (*model.DevMetricResult, error) {
	panic(fmt.Errorf("not implemented: DevMetric - devMetric"))
}

// DevEvidenceSearch is the resolver for the devEvidenceSearch field.
func (r *queryResolver) DevEvidenceSearch(ctx context.Context, orgID string, input model.DevEvidenceSearchInput) (*model.DevEvidenceSearchResult, error) {
	panic(fmt.Errorf("not implemented: DevEvidenceSearch - devEvidenceSearch"))
}

// DevDataHealth is the resolver for the devDataHealth field.
func (r *queryResolver) DevDataHealth(ctx context.Context, orgID string, input model.DevDataHealthInput) (*model.DevDataHealthResult, error) {
	panic(fmt.Errorf("not implemented: DevDataHealth - devDataHealth"))
}

// DevStatusSnapshot is the resolver for the devStatusSnapshot field.
func (r *queryResolver) DevStatusSnapshot(ctx context.Context, orgID string, input model.DevStatusSnapshotInput) (*model.DevStatusSnapshot, error) {
	panic(fmt.Errorf("not implemented: DevStatusSnapshot - devStatusSnapshot"))
}

// DevChangeSummary is the resolver for the devChangeSummary field.
func (r *queryResolver) DevChangeSummary(ctx context.Context, orgID string, input model.DevChangeSummaryInput) (*model.DevChangeSummary, error) {
	panic(fmt.Errorf("not implemented: DevChangeSummary - devChangeSummary"))
}

// DevWorkGraphNeighbors is the resolver for the devWorkGraphNeighbors field.
func (r *queryResolver) DevWorkGraphNeighbors(ctx context.Context, orgID string, input model.DevWorkGraphNeighborsInput) (*model.DevWorkGraphNeighborsResult, error) {
	panic(fmt.Errorf("not implemented: DevWorkGraphNeighbors - devWorkGraphNeighbors"))
}

// Catalog is the resolver for the catalog field.
func (r *queryResolver) Catalog(ctx context.Context, orgID string, dimension *model.DimensionInput, filters *model.FilterInput) (*model.CatalogResult, error) {
	panic(fmt.Errorf("not implemented: Catalog - catalog"))
}

// Analytics is the resolver for the analytics field (CHAOS-4506,
// non-investment path only -- see internal/analytics's package doc
// comment for the full scope split).
//
// The two-branch org-id check below is COPIED IN SHAPE from
// FeatureFlags above (schema.resolvers.go:146-164), not invented here --
// `analytics` is not the first ported resolver to take a client-supplied
// `orgId` argument (nine others already do: FeatureFlags plus the
// Catalog/DevMetric/DevScopeSearch/etc. stubs), and FeatureFlags already
// implements the reject-on-mismatch check Python's OrgIdAuthExtension
// (extensions.py:109-169) performs for its non-superuser branch. Message
// text is NOT copied -- FeatureFlags's mismatch string ("org_id is
// required for all analytics queries") is itself a copy-paste artifact
// that predates this field and is not fixed here (out of this PR's
// scope; not propagated forward either).
//
// KNOWN GAP, pre-existing and epic-wide, not introduced here: Python's
// OrgIdAuthExtension lets a verified superuser cross-org query by
// rebinding context.org_id when the requested org differs
// (extensions.py:159-168); Go's authctx.Claims carries no superuser or
// impersonation state at all, and none of the nine other orgId-taking
// resolvers have it either. This makes Go strictly MORE restrictive than
// Python (a superuser cannot cross-org query analytics via this path
// yet) -- a capability gap, not a vulnerability: nothing leaks, the
// restrictive direction is the safe one to diverge in on an authz
// boundary, and adding superuser support later is additive, never a
// revert.
func (r *queryResolver) Analytics(ctx context.Context, orgID string, batch model.AnalyticsRequestInput) (*model.AnalyticsResult, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "Authorization required",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}
	if claims.OrgID != orgID {
		return nil, &gqlerror.Error{
			Message: "cannot query analytics for a different organization",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	// The returned ctx carries the span; finish must run after Resolve
	// actually completes so the span measures the resolver's real work
	// (see startFeatureFlagsSpan's doc comment for the bug this fixes).
	spanCtx, finish := startAnalyticsSpan(ctx)
	result, err := analytics.Resolve(spanCtx, r.ClickHouse, orgID, batch)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("analytics: %w", err)
	}
	finish("ok")
	return result, nil
}

// ProductTelemetryDashboard is the resolver for the productTelemetryDashboard field.
func (r *queryResolver) ProductTelemetryDashboard(ctx context.Context, orgID string, input model.ProductTelemetryDashboardInput) (*model.ProductTelemetryDashboardType, error) {
	panic(fmt.Errorf("not implemented: ProductTelemetryDashboard - productTelemetryDashboard"))
}

// ProductTelemetryPlatformDashboard is the resolver for the productTelemetryPlatformDashboard field.
func (r *queryResolver) ProductTelemetryPlatformDashboard(ctx context.Context, input model.ProductTelemetryDashboardInput) (*model.ProductTelemetryPlatformDashboardType, error) {
	panic(fmt.Errorf("not implemented: ProductTelemetryPlatformDashboard - productTelemetryPlatformDashboard"))
}

// Home is the resolver for the home field.
func (r *queryResolver) Home(ctx context.Context, orgID string, filters *model.FilterInput) (*model.HomeResult, error) {
	panic(fmt.Errorf("not implemented: Home - home"))
}

// WorkGraphEdges is the resolver for the workGraphEdges field (CHAOS-4352
// Wave 4 Lane A / CHAOS-4504). Ports
// dev_health_ops.api.graphql.resolvers.work_graph.resolve_work_graph_edges
// via workgraph.ResolveEdges -- see that package's doc comment for the full
// parity contract, the CHAOS-4515 Go-side dedup fix (a DELIBERATE
// divergence from Python), and the resolve_work_graph_edges splice trap.
//
// Authorization mirrors resolve_work_graph_edges's ACTUAL behavior exactly,
// same "authorized org always wins" convention as ReviewEdges/CognitiveLoad
// above: Python's require_org_id(context) raises when the envelope has no
// org, then silently uses the authorized org for every query regardless of
// what the client sent as the orgId argument. This resolver reproduces that
// by construction: it passes claims.OrgID, never the orgID argument, to
// workgraph.ResolveEdges.
func (r *queryResolver) WorkGraphEdges(ctx context.Context, orgID string, filters *model.WorkGraphEdgeFilterInput) (*model.WorkGraphEdgesResult, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "org_id is required for all analytics queries",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	spanCtx, finish := startWorkGraphEdgesSpan(ctx)
	result, err := workgraph.ResolveEdges(spanCtx, r.ClickHouse, claims.OrgID, filters)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("workGraphEdges: %w", err)
	}
	if result.DegradedReason != nil {
		finish("degraded")
	} else {
		finish("ok")
	}
	return result, nil
}

// Pr is the resolver for the pr field.
func (r *queryResolver) Pr(ctx context.Context, orgID string, id string) (*model.PullRequestDetail, error) {
	panic(fmt.Errorf("not implemented: Pr - pr"))
}

// WorkGraphFlow is the resolver for the workGraphFlow field (CHAOS-4352
// Wave 4 Lane A / CHAOS-4504). Ports resolve_work_graph_flow via
// workgraph.ResolveFlow -- see workgraph package doc comment. Same
// "authorized org always wins" authorization convention as WorkGraphEdges
// above.
func (r *queryResolver) WorkGraphFlow(ctx context.Context, orgID string, filters *model.WorkGraphEdgeFilterInput) (*model.WorkGraphFlowResult, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "org_id is required for all analytics queries",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	spanCtx, finish := startWorkGraphFlowSpan(ctx)
	result, err := workgraph.ResolveFlow(spanCtx, r.ClickHouse, claims.OrgID, filters)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("workGraphFlow: %w", err)
	}
	if result.DegradedReason != nil {
		finish("degraded")
	} else {
		finish("ok")
	}
	return result, nil
}

// WorkGraphArtifacts is the resolver for the workGraphArtifacts field
// (CHAOS-4352 Wave 4 Lane A / CHAOS-4504). Ports
// resolve_work_graph_artifacts via workgraph.ResolveArtifacts -- see
// workgraph package doc comment. Same "authorized org always wins"
// authorization convention as WorkGraphEdges above.
func (r *queryResolver) WorkGraphArtifacts(ctx context.Context, orgID string, filters *model.WorkGraphEdgeFilterInput) (*model.WorkGraphArtifactsResult, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "org_id is required for all analytics queries",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	spanCtx, finish := startWorkGraphArtifactsSpan(ctx)
	result, err := workgraph.ResolveArtifacts(spanCtx, r.ClickHouse, claims.OrgID, filters)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("workGraphArtifacts: %w", err)
	}
	if result.DegradedReason != nil {
		finish("degraded")
	} else {
		finish("ok")
	}
	return result, nil
}

// FeatureFlags is the resolver for the featureFlags field (CHAOS-4367
// Wave 1 canary). Ports
// dev_health_ops.api.graphql.resolvers.feature_flags.resolve_feature_flags
// via featureflags.Resolve -- see that package's doc comment for the
// exact parity contract (WHERE clauses, argMax latest-row selection,
// ORDER BY, LIMIT clamp, missing-table degraded path).
//
// Authorization mirrors require_org_id's contract at the boundary this
// Go plane actually owns: query-api trusts the effective-principal
// envelope (plan §3), not an independent Postgres/Valkey lookup, so the
// check here is "does the envelope's org match the orgId argument the
// client is asking about" -- a caller cannot read another org's flags by
// passing a different orgId than their own envelope carries.
func (r *queryResolver) FeatureFlags(ctx context.Context, orgID string, provider *string, project *string, includeArchived *bool, limit int) (*model.FeatureFlagRegistryResult, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "Authorization required",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}
	if claims.OrgID != orgID {
		return nil, &gqlerror.Error{
			Message: "org_id is required for all analytics queries",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	includeArchivedValue := false
	if includeArchived != nil {
		includeArchivedValue = *includeArchived
	}

	// The returned ctx carries the span; finish must run after Resolve
	// actually completes so the span measures the resolver's real work
	// (see startFeatureFlagsSpan's doc comment for the bug this fixes).
	spanCtx, finish := startFeatureFlagsSpan(ctx)
	result, err := featureflags.Resolve(spanCtx, r.ClickHouse, orgID, provider, project, includeArchivedValue, limit)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("featureFlags: %w", err)
	}
	if result.DegradedReason != nil {
		finish("degraded")
	} else {
		finish("ok")
	}
	return result, nil
}

// FeatureFlagEvents is the resolver for the featureFlagEvents field.
func (r *queryResolver) FeatureFlagEvents(ctx context.Context, orgID string, flagKey *string, environment *string, limit int) (*model.FeatureFlagEventsResult, error) {
	panic(fmt.Errorf("not implemented: FeatureFlagEvents - featureFlagEvents"))
}

// WorkItemTeamAttributions is the resolver for the workItemTeamAttributions field.
func (r *queryResolver) WorkItemTeamAttributions(ctx context.Context, orgID string, workItemIds []string, teamID *string) ([]model.WorkItemTeamAttribution, error) {
	panic(fmt.Errorf("not implemented: WorkItemTeamAttributions - workItemTeamAttributions"))
}

// WorkUnitTeamAttributions is the resolver for the workUnitTeamAttributions field.
func (r *queryResolver) WorkUnitTeamAttributions(ctx context.Context, orgID string, workUnitIds []string, teamID *string) ([]model.WorkUnitTeamAttribution, error) {
	panic(fmt.Errorf("not implemented: WorkUnitTeamAttributions - workUnitTeamAttributions"))
}

// SecurityAlerts is the resolver for the securityAlerts field.
func (r *queryResolver) SecurityAlerts(ctx context.Context, orgID string, filters *model.SecurityAlertFilterInput, pagination *model.SecurityPaginationInput) (*model.SecurityAlertConnection, error) {
	panic(fmt.Errorf("not implemented: SecurityAlerts - securityAlerts"))
}

// SecurityOverview is the resolver for the securityOverview field.
func (r *queryResolver) SecurityOverview(ctx context.Context, orgID string, filters *model.SecurityAlertFilterInput) (*model.SecurityOverview, error) {
	panic(fmt.Errorf("not implemented: SecurityOverview - securityOverview"))
}

// SavedReports is the resolver for the savedReports field.
func (r *queryResolver) SavedReports(ctx context.Context, orgID string, limit int, offset int) (*model.SavedReportConnection, error) {
	panic(fmt.Errorf("not implemented: SavedReports - savedReports"))
}

// SavedReport is the resolver for the savedReport field.
func (r *queryResolver) SavedReport(ctx context.Context, orgID string, reportID string) (*model.SavedReportType, error) {
	panic(fmt.Errorf("not implemented: SavedReport - savedReport"))
}

// ReportRuns is the resolver for the reportRuns field.
func (r *queryResolver) ReportRuns(ctx context.Context, orgID string, reportID string, limit int) (*model.ReportRunConnection, error) {
	panic(fmt.Errorf("not implemented: ReportRuns - reportRuns"))
}

// CapacityForecast is the resolver for the capacityForecast field.
func (r *queryResolver) CapacityForecast(ctx context.Context, orgID string, input *model.CapacityForecastInput) (*model.CapacityForecast, error) {
	panic(fmt.Errorf("not implemented: CapacityForecast - capacityForecast"))
}

// CapacityForecasts is the resolver for the capacityForecasts field.
func (r *queryResolver) CapacityForecasts(ctx context.Context, orgID string, filters *model.CapacityForecastFilterInput) (*model.CapacityForecastConnection, error) {
	panic(fmt.Errorf("not implemented: CapacityForecasts - capacityForecasts"))
}

// ThroughputForecast is the resolver for the throughputForecast field.
func (r *queryResolver) ThroughputForecast(ctx context.Context, orgID string, input model.ThroughputForecastInput) (*model.ThroughputForecast, error) {
	panic(fmt.Errorf("not implemented: ThroughputForecast - throughputForecast"))
}

// OperatingReview is the resolver for the operatingReview field (CHAOS-4352
// Wave 4 Lane B, CHAOS-4505). Ports
// dev_health_ops.api.graphql.resolvers.operating_review.resolve_operating_review
// via operatingreview.Resolve -- see that package's doc comment for the
// full parity contract (ten-table dual-period fetch, per-table error
// isolation, and the one declared Go-side fix + expected dual-run
// divergence on ai_governance).
//
// The orgID parameter (from the schema's `operatingReview(orgId: String!,
// input: ...)`) is deliberately UNUSED for scoping, matching Python's
// ACTUAL behavior exactly: api/graphql/schema.py's operating_review field
// accepts the same org_id argument and never passes it to
// resolve_operating_review, which authorizes via require_org_id(context)
// alone -- the same "authorized org always wins, a client-supplied orgId
// is parsed but never trusted for scoping" behavior cognitiveload/
// reviewedges/hotspots already document. This resolver reproduces that by
// construction: it passes claims.OrgID, never orgID, to
// operatingreview.Resolve.
func (r *queryResolver) OperatingReview(ctx context.Context, orgID string, input model.OperatingReviewInput) (*model.OperatingReview, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "org_id is required for all analytics queries",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	// The returned ctx carries the span; finish must run after Resolve
	// actually completes so the span measures the resolver's real work
	// (same discipline startFeatureFlagsSpan's doc comment documents).
	spanCtx, finish := startOperatingReviewSpan(ctx)
	result, err := operatingreview.Resolve(spanCtx, r.ClickHouse, claims.OrgID, input.TeamID, input.WeekStart)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("operatingReview: %w", err)
	}
	finish("ok")
	return result, nil
}

// DataHealth is the resolver for the dataHealth field.
func (r *queryResolver) DataHealth(ctx context.Context, team string) (*model.DataHealth, error) {
	panic(fmt.Errorf("not implemented: DataHealth - dataHealth"))
}

// BusFactor is the resolver for the busFactor field.
func (r *queryResolver) BusFactor(ctx context.Context, orgID string, scope *model.BusFactorScopeInput) (*model.BusFactor, error) {
	panic(fmt.Errorf("not implemented: BusFactor - busFactor"))
}

// CompoundingRisk is the resolver for the compoundingRisk field.
func (r *queryResolver) CompoundingRisk(ctx context.Context, orgID string, filter *model.CompoundingRiskFilterInput) (*model.CompoundingRiskResult, error) {
	panic(fmt.Errorf("not implemented: CompoundingRisk - compoundingRisk"))
}

// TestopsRisk is the resolver for the testopsRisk field.
func (r *queryResolver) TestopsRisk(ctx context.Context, orgID string, input model.TestOpsRiskInput) (*model.TestOpsRiskResult, error) {
	panic(fmt.Errorf("not implemented: TestopsRisk - testopsRisk"))
}

// ComplexityTimeseries is the resolver for the complexityTimeseries field.
func (r *queryResolver) ComplexityTimeseries(ctx context.Context, input model.ComplexityTimeseriesInput) (*model.ComplexityTimeseriesResult, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "org_id is required for all analytics queries",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	// The returned ctx carries the span; finish must run after Resolve
	// actually completes so the span measures the resolver's real work
	// (same discipline startFeatureFlagsSpan's doc comment documents).
	spanCtx, finish := startComplexityTimeseriesSpan(ctx)
	result, err := complexitytimeseries.Resolve(spanCtx, r.ClickHouse, claims.OrgID, input.SinceUtc, input.UntilUtc, input.Granularity, input.Scope, input.RepoIds, input.Limit)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("complexityTimeseries: %w", err)
	}
	finish("ok")
	return result, nil
}

// Hotspots is the resolver for the hotspots field.
func (r *queryResolver) Hotspots(ctx context.Context, input model.HotspotsInput) (*model.HotspotsResult, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "org_id is required for all analytics queries",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	// The returned ctx carries the span; finish must run after Resolve
	// actually completes so the span measures the resolver's real work
	// (same discipline startFeatureFlagsSpan's doc comment documents).
	spanCtx, finish := startHotspotsSpan(ctx)
	result, err := hotspots.Resolve(spanCtx, r.ClickHouse, claims.OrgID, input.SinceUtc, input.UntilUtc, input.RepoIds, input.Limit)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("hotspots: %w", err)
	}
	finish("ok")
	return result, nil
}

// CognitiveLoad is the resolver for the cognitiveLoad field (CHAOS-4369
// Wave 3; extended to the ownership-gated team+repo path by CHAOS-4462
// after the CHAOS-4352 rebase lane took origin/main's CHAOS-4406 fix).
// Ports
// dev_health_ops.api.graphql.resolvers.cognitive_load.resolve_cognitive_load
// via cognitiveload.Resolve -- see that package's doc comment for the
// exact parity contract (the THREE read paths: single-team direct read,
// ownership-gated team+repo-combined, and org-wide merge).
//
// Authorization mirrors resolve_cognitive_load's/ReviewEdges's ACTUAL
// behavior exactly, not FeatureFlags's stricter Go-side equality check:
// Python's resolver calls require_org_id(context) (raises when the
// envelope has no org) and then, if input.org_id differs from the
// authorized org, does NOT error -- it logs a debug line and silently
// uses the authorized org for every query regardless of what the client
// sent. This resolver reproduces that "authorized org always wins,
// client-supplied orgId in the input is never trusted for scoping"
// behavior by construction: it passes claims.OrgID, never input.OrgID, to
// cognitiveload.Resolve.
func (r *queryResolver) CognitiveLoad(ctx context.Context, input model.CognitiveLoadInput) (*model.CognitiveLoadResult, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "org_id is required for all analytics queries",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	// The returned ctx carries the span; finish must run after Resolve
	// actually completes so the span measures the resolver's real work
	// (same discipline startFeatureFlagsSpan's doc comment documents).
	spanCtx, finish := startCognitiveLoadSpan(ctx)
	result, err := cognitiveload.Resolve(spanCtx, r.ClickHouse, claims.OrgID, input.SinceDate, input.UntilDate, input.TeamID, input.RepoID)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("cognitiveLoad: %w", err)
	}
	finish("ok")
	return result, nil
}

// ReviewEdges is the resolver for the reviewEdges field (CHAOS-4368 Wave
// 2). Ports
// dev_health_ops.api.graphql.resolvers.review_edges.resolve_review_edges
// via reviewedges.Resolve -- see that package's doc comment for the exact
// parity contract (dedup, deterministic ORDER BY tie-break, repo_ids
// filter, limit clamp, and the deliberate absence of a degraded-result
// path unlike FeatureFlags).
//
// Authorization mirrors resolve_review_edges's ACTUAL behavior exactly,
// not FeatureFlags's stricter Go-side equality check above: Python's
// resolver calls require_org_id(context) (raises when the envelope has no
// org) and then, if input.org_id differs from the authorized org, does
// NOT error -- it logs a debug line and silently uses the authorized org
// for the query regardless of what the client sent
// (review_edges.py's resolve_review_edges, "Ignoring GraphQL orgId ... in
// favor of authorized org"). This resolver reproduces that
// "authorized org always wins, client-supplied orgId in the input is
// never trusted for scoping" behavior by construction: it passes
// claims.OrgID, never input.OrgID, to reviewedges.Resolve.
func (r *queryResolver) ReviewEdges(ctx context.Context, input model.ReviewEdgesInput) (*model.ReviewEdgesResult, error) {
	claims, ok := authctx.FromContext(ctx)
	if !ok || claims.OrgID == "" {
		return nil, &gqlerror.Error{
			Message: "org_id is required for all analytics queries",
			Path:    graphql.GetPath(ctx),
			Extensions: map[string]interface{}{
				"code": "AUTHORIZATION_ERROR",
			},
		}
	}

	// The returned ctx carries the span; finish must run after Resolve
	// actually completes so the span measures the resolver's real work
	// (same discipline startFeatureFlagsSpan's doc comment documents).
	spanCtx, finish := startReviewEdgesSpan(ctx)
	result, err := reviewedges.Resolve(spanCtx, r.ClickHouse, claims.OrgID, input.SinceDate, input.UntilDate, input.RepoIds, input.Limit)
	if err != nil {
		finish("error")
		return nil, fmt.Errorf("reviewEdges: %w", err)
	}
	finish("ok")
	return result, nil
}

// Recommendations is the resolver for the recommendations field.
func (r *queryResolver) Recommendations(ctx context.Context, orgID string, team string, window model.WindowInput) ([]model.Recommendation, error) {
	panic(fmt.Errorf("not implemented: Recommendations - recommendations"))
}

// Experiments is the resolver for the experiments field.
func (r *queryResolver) Experiments(ctx context.Context, orgID string, filters *model.FilterInput) (*model.ExperimentsResult, error) {
	panic(fmt.Errorf("not implemented: Experiments - experiments"))
}

// AiImpactSummary is the resolver for the aiImpactSummary field.
func (r *queryResolver) AiImpactSummary(ctx context.Context, orgID string, dateRange model.AIDateRangeInput, scope *model.AIScopeInput) (*model.AIImpactSummary, error) {
	panic(fmt.Errorf("not implemented: AiImpactSummary - aiImpactSummary"))
}

// AiComparison is the resolver for the aiComparison field.
func (r *queryResolver) AiComparison(ctx context.Context, orgID string, dateRange model.AIDateRangeInput, scope *model.AIScopeInput) (*model.AIComparison, error) {
	panic(fmt.Errorf("not implemented: AiComparison - aiComparison"))
}

// AiReviewLoad is the resolver for the aiReviewLoad field.
func (r *queryResolver) AiReviewLoad(ctx context.Context, orgID string, dateRange model.AIDateRangeInput, scope *model.AIScopeInput) (*model.AIReviewLoadResult, error) {
	panic(fmt.Errorf("not implemented: AiReviewLoad - aiReviewLoad"))
}

// AiRiskBreakdown is the resolver for the aiRiskBreakdown field.
func (r *queryResolver) AiRiskBreakdown(ctx context.Context, orgID string, dateRange model.AIDateRangeInput, scope *model.AIScopeInput) (*model.AIRiskBreakdownResult, error) {
	panic(fmt.Errorf("not implemented: AiRiskBreakdown - aiRiskBreakdown"))
}

// AiOpportunities is the resolver for the aiOpportunities field.
func (r *queryResolver) AiOpportunities(ctx context.Context, orgID string, scope *model.AIScopeInput, limit int) (*model.AIOpportunitiesResult, error) {
	panic(fmt.Errorf("not implemented: AiOpportunities - aiOpportunities"))
}

// ImproveOpportunities is the resolver for the improveOpportunities field.
func (r *queryResolver) ImproveOpportunities(ctx context.Context, scope *model.AIScopeInput, limit int, windowDays int) (*model.ImproveOpportunitiesResult, error) {
	panic(fmt.Errorf("not implemented: ImproveOpportunities - improveOpportunities"))
}

// AiGovernanceSummary is the resolver for the aiGovernanceSummary field.
func (r *queryResolver) AiGovernanceSummary(ctx context.Context, orgID string, dateRange model.AIDateRangeInput, scope *model.AIScopeInput, violationLimit int) (*model.AIGovernanceSummary, error) {
	panic(fmt.Errorf("not implemented: AiGovernanceSummary - aiGovernanceSummary"))
}

// AiWorkflowDrilldown is the resolver for the aiWorkflowDrilldown field.
func (r *queryResolver) AiWorkflowDrilldown(ctx context.Context, orgID string, rootType model.AIWorkflowRootTypeInput, rootID string, depth int, limit int) (*model.AIWorkflowDrilldownResult, error) {
	panic(fmt.Errorf("not implemented: AiWorkflowDrilldown - aiWorkflowDrilldown"))
}

// AiAttributedPrs is the resolver for the aiAttributedPrs field.
func (r *queryResolver) AiAttributedPrs(ctx context.Context, orgID string, dateRange model.AIDateRangeInput, scope *model.AIScopeInput, limit int, offset int) (*model.AiAttributedPrsResult, error) {
	panic(fmt.Errorf("not implemented: AiAttributedPrs - aiAttributedPrs"))
}

// AiAttributionOverview is the resolver for the aiAttributionOverview field.
func (r *queryResolver) AiAttributionOverview(ctx context.Context, orgID string, dateRange model.AIDateRangeInput, scope *model.AIAttributionScopeInput, limit int, offset int) (*model.AIAttributionOverviewResult, error) {
	panic(fmt.Errorf("not implemented: AiAttributionOverview - aiAttributionOverview"))
}

// MetricsUpdated is the resolver for the metricsUpdated field.
func (r *subscriptionResolver) MetricsUpdated(ctx context.Context, orgID string) (<-chan *model.MetricsUpdate, error) {
	panic(fmt.Errorf("not implemented: MetricsUpdated - metricsUpdated"))
}

// TaskStatus is the resolver for the taskStatus field.
func (r *subscriptionResolver) TaskStatus(ctx context.Context, taskID string) (<-chan *model.TaskStatus, error) {
	panic(fmt.Errorf("not implemented: TaskStatus - taskStatus"))
}

// SyncProgress is the resolver for the syncProgress field.
func (r *subscriptionResolver) SyncProgress(ctx context.Context, orgID string) (<-chan *model.SyncProgress, error) {
	panic(fmt.Errorf("not implemented: SyncProgress - syncProgress"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
