package fixed

import (
	"context"
	"encoding/json"
	"errors"
	"github.com/full-chaos/dev-health-ops/internal/platform/health"
	"os"
	"slices"
	"strings"
	"testing"
	"time"

	schedulersync "github.com/full-chaos/dev-health-ops/internal/scheduler/sync"
	"github.com/google/uuid"
)

func errorsIsScheduledReportConflict(err error) bool {
	return errors.Is(err, ErrScheduledReportConflict)
}

// pythonScheduledReportOracle is generated by the REAL Python authorities, not
// hand-authored: testdata/python_scheduled_report_oracle.json comes out of
// reports.execution_trigger.scheduled_report_occurrence_identity and
// workers.task_utils.cron_next_run. Hand-writing the digests would test that Go
// agrees with itself.
type pythonScheduledReportOracle struct {
	GeneratedBy          string `json:"_generated_by"`
	IdentityVersion      string `json:"identity_version"`
	OccurrenceIdentities []struct {
		ReportID     string    `json:"report_id"`
		ScheduledFor time.Time `json:"scheduled_for"`
		OccurrenceID string    `json:"occurrence_id"`
	} `json:"occurrence_identities"`
	CronOccurrences []struct {
		Expression string    `json:"expression"`
		Base       time.Time `json:"base"`
		Timezone   string    `json:"timezone"`
		Next       time.Time `json:"next"`
	} `json:"cron_occurrences"`
}

// pythonOccurrenceID returns the Python-authored identity for one (report,
// due time) pair, from the checked-in oracle.
//
// Tests MUST use this rather than calling ScheduledReportOccurrenceID, which is
// the function under test. Two tests previously compared a Go-produced value with
// a second call to the same Go function, so a wrong derivation agreed with itself
// and passed while live Python derived something else.
func pythonOccurrenceID(t *testing.T, reportID string, scheduledFor time.Time) string {
	t.Helper()
	oracle := loadScheduledReportOracle(t)
	for _, entry := range oracle.OccurrenceIdentities {
		if entry.ReportID == reportID && entry.ScheduledFor.Equal(scheduledFor) {
			return entry.OccurrenceID
		}
	}
	t.Fatalf(
		"the Python oracle has no identity for report %s at %s; add the pair to "+
			"OCCURRENCE_INPUTS in scripts/generate_scheduled_report_oracle.py and "+
			"regenerate, do not compute it in Go",
		reportID, scheduledFor.Format(time.RFC3339),
	)
	return ""
}

func loadScheduledReportOracle(t *testing.T) pythonScheduledReportOracle {
	t.Helper()
	raw, err := os.ReadFile("testdata/python_scheduled_report_oracle.json")
	if err != nil {
		t.Fatal(err)
	}
	var oracle pythonScheduledReportOracle
	if err := json.Unmarshal(raw, &oracle); err != nil {
		t.Fatal(err)
	}
	if len(oracle.OccurrenceIdentities) == 0 || len(oracle.CronOccurrences) == 0 {
		t.Fatal("scheduled report oracle is empty")
	}
	// A fixture with no committed generator cannot be told apart from one someone
	// edited to make a test pass, so refuse to trust it.
	if oracle.GeneratedBy != "scripts/generate_scheduled_report_oracle.py" {
		t.Fatalf(
			"oracle declares generator %q; it must be produced by the checked-in "+
				"script so a change to it is reviewable", oracle.GeneratedBy,
		)
	}
	return oracle
}

// The occurrence identity is a cross-runtime wire value for the whole
// coexistence window: the Python dispatcher writes into the same
// scheduled_report_occurrences table, so a differing digest would let both
// runtimes claim one due time under two identities and execute a report twice.
func TestScheduledReportOccurrenceIdentityMatchesThePythonAuthority(t *testing.T) {
	oracle := loadScheduledReportOracle(t)
	if oracle.IdentityVersion != scheduledReportOccurrenceIdentityVersion {
		t.Fatalf(
			"identity version = %q, Python authority = %q",
			scheduledReportOccurrenceIdentityVersion, oracle.IdentityVersion,
		)
	}
	for _, expected := range oracle.OccurrenceIdentities {
		got := ScheduledReportOccurrenceID(expected.ReportID, expected.ScheduledFor)
		if got != expected.OccurrenceID {
			t.Errorf(
				"ScheduledReportOccurrenceID(%s, %s) = %s, Python = %s",
				expected.ReportID, expected.ScheduledFor.Format(time.RFC3339),
				got, expected.OccurrenceID,
			)
		}
	}
}

// The identity must depend on both inputs. Without this a derivation that
// ignored scheduled_for would still pass the oracle comparison for any single
// row, and every occurrence of one report would collapse onto one identity.
func TestScheduledReportOccurrenceIdentitySeparatesItsInputs(t *testing.T) {
	base := time.Date(2026, time.July, 25, 1, 5, 0, 0, time.UTC)
	first := ScheduledReportOccurrenceID("00000000-0000-4000-8000-000000000001", base)
	laterTime := ScheduledReportOccurrenceID("00000000-0000-4000-8000-000000000001", base.Add(time.Minute))
	otherReport := ScheduledReportOccurrenceID("00000000-0000-4000-8000-000000000002", base)
	if first == laterTime {
		t.Error("two due times collapsed onto one occurrence identity")
	}
	if first == otherReport {
		t.Error("two reports collapsed onto one occurrence identity")
	}
	// A non-UTC input must resolve to the same identity as its UTC instant:
	// Python normalizes with _as_utc before framing.
	zone, err := time.LoadLocation("America/New_York")
	if err != nil {
		t.Fatal(err)
	}
	shifted := ScheduledReportOccurrenceID("00000000-0000-4000-8000-000000000001", base.In(zone))
	if shifted != first {
		t.Error("identity changed with the input's location rather than its instant")
	}
}

// The producer resolves due-ness through the sync scheduler's croniter port
// rather than a second parser. This proves the evaluator it is wired to in
// production agrees with cron_next_run on the same inputs, including the
// timezone-sensitive and DST cases, so "which reports are due" matches Python's
// answer and not merely a self-consistent Go one.
func TestProductionCronEvaluatorMatchesThePythonAuthority(t *testing.T) {
	oracle := loadScheduledReportOracle(t)
	var evaluator ScheduledReportCronEvaluator = schedulersync.NextOccurrence
	for _, expected := range oracle.CronOccurrences {
		got, _, err := evaluator(expected.Expression, expected.Base, expected.Timezone)
		if err != nil {
			t.Errorf("evaluate %q in %s: %v", expected.Expression, expected.Timezone, err)
			continue
		}
		if !got.Equal(expected.Next) {
			t.Errorf(
				"next(%q, %s, %s) = %s, Python = %s",
				expected.Expression, expected.Base.Format(time.RFC3339), expected.Timezone,
				got.UTC().Format(time.RFC3339), expected.Next.Format(time.RFC3339),
			)
		}
	}
}

// The ReportRun identity must be a pure function of the occurrence identity.
//
// The occurrence primary key is what actually prevents a second run, so this
// property is defence in depth rather than the load-bearing guarantee — which is
// exactly why it needs its own assertion: no behavioral test can observe it,
// because a replay returns at the claim and never reaches run construction. A
// random identity here would leave a crashed-then-retried transaction free to
// allocate a second artifact identity for one due time.
func TestScheduledReportRunIdentityIsDerivedFromTheOccurrence(t *testing.T) {
	first := scheduledReportRunID("sha256:aaaa")
	if scheduledReportRunID("sha256:aaaa") != first {
		t.Fatal("the report run identity is not deterministic")
	}
	if scheduledReportRunID("sha256:bbbb") == first {
		t.Fatal("two occurrences derived one report run identity")
	}
	if _, err := uuid.Parse(first); err != nil {
		t.Fatalf("the derived report run identity is not a UUID: %v", err)
	}
}

func TestScheduledReportsProducerRequiresACronEvaluator(t *testing.T) {
	if _, err := NewScheduledReportsProducer(nil); err == nil {
		t.Fatal("a producer with no cron evaluator was constructed")
	}
	producer, err := NewScheduledReportsProducer(schedulersync.NextOccurrence)
	if err != nil {
		t.Fatal(err)
	}
	if producer.ID() != ProducerScheduledReports {
		t.Fatalf("producer id = %q, want %q", producer.ID(), ProducerScheduledReports)
	}
}

// A schedule owning two active reports is refused rather than fanned out.
// Alembic 0096 makes this unreachable in a current database. The guard remains
// an assertion for a partially migrated or manually drifted schema, where a
// join would silently produce two runs and advance next_run_at twice.
func TestAmbiguousReportScheduleIsRefused(t *testing.T) {
	candidates := []dueReportCandidate{
		{JobID: "job-a", ReportID: "report-1"},
		{JobID: "job-b", ReportID: "report-2"},
	}
	if err := rejectAmbiguousReportSchedules(candidates); err != nil {
		t.Fatalf("distinct schedules were refused: %v", err)
	}
	candidates = append(candidates, dueReportCandidate{JobID: "job-a", ReportID: "report-3"})
	err := rejectAmbiguousReportSchedules(candidates)
	if err == nil {
		t.Fatal("a schedule owning two active reports was accepted")
	}
	if !errorsIsScheduledReportConflict(err) {
		t.Fatalf("error = %v, want a scheduled report conflict", err)
	}
}

// A producer bound to the wrong schedule fails rather than sweeping anyway: the
// registry maps one producer to one schedule and a mismatch means the
// declaration table and this code disagree.
//
// The transaction is a stub rather than nil, and that is the whole point of the
// test. Passing nil made Produce return ErrProducerUnavailable from its
// dependency check BEFORE reaching the schedule-ID guard, so the test passed with
// the guard deleted — it asserted only that a nil transaction is rejected. The
// stub also proves the guard fires before any statement is issued: stubTx panics
// on QueryRow, so a guard that ran after the sweep would panic here instead of
// returning.
func TestScheduledReportsProducerRefusesAForeignSchedule(t *testing.T) {
	producer, err := NewScheduledReportsProducer(schedulersync.NextOccurrence)
	if err != nil {
		t.Fatal(err)
	}
	schedule := scheduleByID(t, "phone_home_heartbeat")
	occurrence := NewOccurrence(schedule, time.Now().UTC(), time.Now().UTC())
	_, err = producer.Produce(t.Context(), &stubTx{}, schedule, occurrence)
	if err == nil {
		t.Fatal("the producer swept a schedule it does not own")
	}
	if !errors.Is(err, ErrProducerUnavailable) {
		t.Fatalf("error = %v, want ErrProducerUnavailable", err)
	}
	if !strings.Contains(err.Error(), schedule.ID) {
		t.Fatalf("refusal does not name the foreign schedule: %v", err)
	}
}

// The declared schedule this producer serves must exist in the checked-in table
// under exactly the identifier the producer guards on, or the guard above turns
// into an unconditional failure at runtime.
func TestScheduledReportsProducerServesADeclaredSchedule(t *testing.T) {
	schedule := scheduleByID(t, scheduledReportsScheduleID)
	if schedule.ProducerID != ProducerScheduledReports {
		t.Fatalf(
			"schedule %s declares producer %q, want %q",
			schedule.ID, schedule.ProducerID, ProducerScheduledReports,
		)
	}
}

// The fairness order must be TOTAL, so two replicas agree without depending on the
// order their rows happened to arrive in.
//
// This is checked because the H2 fairness fix changed iteration order, and the two
// previous regressions in this producer both arrived inside the fix for a different
// finding. The specific hazard: two schedulers do NOT read the same rows — SKIP
// LOCKED gives each a different subset — so an order that is merely stable with
// respect to the SQL's ORDER BY would couple replica agreement to a clause in another
// function. Sorting shuffled permutations of the same set and demanding one identical
// result is what distinguishes a total order from a stable one.
//
// Removing the report id tie-break makes ties resolve by arrival order, and this test
// fails.
func TestFairnessOrderIsTotalAndReplicaStable(t *testing.T) {
	instant := func(minute int) time.Time {
		return time.Date(2026, time.July, 25, 6, minute, 0, 0, time.UTC)
	}
	// Deliberately tie-heavy: many reports share a cron and last run, so identical
	// due times are the common case rather than an edge case.
	entries := []dueEntry{
		{candidate: dueReportCandidate{ReportID: "dddddddd-0000-4000-8000-000000000001"}, scheduledFor: instant(10)},
		{candidate: dueReportCandidate{ReportID: "aaaaaaaa-0000-4000-8000-000000000002"}, scheduledFor: instant(5)},
		{candidate: dueReportCandidate{ReportID: "cccccccc-0000-4000-8000-000000000003"}, scheduledFor: instant(5)},
		{candidate: dueReportCandidate{ReportID: "bbbbbbbb-0000-4000-8000-000000000004"}, scheduledFor: instant(5)},
		{candidate: dueReportCandidate{ReportID: "eeeeeeee-0000-4000-8000-000000000005"}, scheduledFor: instant(1)},
	}

	order := func(input []dueEntry) []string {
		sortDueEntriesMostOverdueFirst(input)
		ids := make([]string, 0, len(input))
		for _, entry := range input {
			ids = append(ids, entry.candidate.ReportID)
		}
		return ids
	}

	canonical := order(append([]dueEntry(nil), entries...))

	// Most overdue first, ties by report id ascending.
	want := []string{
		"eeeeeeee-0000-4000-8000-000000000005",
		"aaaaaaaa-0000-4000-8000-000000000002",
		"bbbbbbbb-0000-4000-8000-000000000004",
		"cccccccc-0000-4000-8000-000000000003",
		"dddddddd-0000-4000-8000-000000000001",
	}
	if !slices.Equal(canonical, want) {
		t.Fatalf("order = %v, want most-overdue-first with id tie-break %v", canonical, want)
	}

	// Every permutation must collapse to the same order. With only a stable sort and
	// no tie-break, the three tied entries would come out in arrival order instead.
	permutations := [][]int{
		{4, 3, 2, 1, 0},
		{2, 0, 4, 1, 3},
		{1, 2, 3, 4, 0},
		{3, 1, 4, 0, 2},
	}
	for index, permutation := range permutations {
		shuffled := make([]dueEntry, 0, len(entries))
		for _, position := range permutation {
			shuffled = append(shuffled, entries[position])
		}
		if got := order(shuffled); !slices.Equal(got, canonical) {
			t.Fatalf(
				"permutation %d sorted to %v but the canonical order is %v; the order "+
					"depends on arrival sequence, so two replicas reading different "+
					"row subsets would disagree",
				index, got, canonical,
			)
		}
	}
}

// The fairness key must be a pure function of durable inputs, or replicas computing
// it independently could disagree even with a total order over it.
//
// scheduledFor comes from the cron expression, the timezone and the report's last run
// — all persisted — through the same evaluator the sync scheduler is shadow-compared
// against. This pins that the evaluation is repeatable, which is the premise the
// ordering rests on.
func TestFairnessKeyIsDeterministicForFixedInputs(t *testing.T) {
	producer, err := NewScheduledReportsProducer(schedulersync.NextOccurrence)
	if err != nil {
		t.Fatal(err)
	}
	concrete, ok := producer.(*ScheduledReportsProducer)
	if !ok {
		t.Fatalf("producer type = %T", producer)
	}
	candidate := dueReportCandidate{
		JobID:    "6b3c1d2e-4f50-4a6b-9c8d-0e1f2a3b4c5d",
		Cron:     "0 6 * * *",
		Timezone: "America/New_York",
		ReportID: "8d4e2f10-5a61-4b7c-8d9e-1f2a3b4c5d6e",
	}
	base := time.Date(2026, time.July, 24, 6, 0, 0, 0, time.UTC)

	first, err := concrete.nextRun(candidate, base)
	if err != nil {
		t.Fatal(err)
	}
	for attempt := 0; attempt < 5; attempt++ {
		again, err := concrete.nextRun(candidate, base)
		if err != nil {
			t.Fatal(err)
		}
		if !again.Equal(first) {
			t.Fatalf("nextRun is not deterministic: %s then %s", first, again)
		}
	}
	if first.Location() != time.UTC {
		t.Fatalf("fairness key is not normalised to UTC: %s", first.Location())
	}
}

// The STORED degraded reason must survive windows that did not evaluate, and must
// still clear when an evaluating window says the condition is gone.
//
// This asserts through the loop's exported metric rather than through the engine's
// returned ScheduleResult, and that distinction is the whole point. An earlier test
// checked only the Step return value, so it never reached Loop.record — the function
// that actually performs the overwrite — and a mutation restoring the unconditional
// assignment survived it. The metric is also what an operator actually alerts on, so
// it is the state the system exists to reach.
func TestStoredDegradedReasonSurvivesNonEvaluatingWindows(t *testing.T) {
	const scheduleID = "scheduled_reports_dispatch"
	schedule := scheduleByID(t, scheduleID)
	loop, err := NewLoop(
		staticStepper{schedules: []Schedule{schedule}},
		DefaultLoopConfig(health.NewRegistry(100*time.Millisecond)),
	)
	if err != nil {
		t.Fatal(err)
	}
	now := time.Date(2026, time.July, 25, 6, 5, 0, 0, time.UTC)

	degradedGauge := func() string {
		t.Helper()
		var out strings.Builder
		if err := loop.WritePrometheus(&out); err != nil {
			t.Fatal(err)
		}
		for _, line := range strings.Split(out.String(), "\n") {
			if strings.HasPrefix(line, "fixed_scheduler_schedule_degraded{schedule=\""+scheduleID+"\"") {
				return line
			}
		}
		t.Fatalf("no degraded gauge for %s in:\n%s", scheduleID, out.String())
		return ""
	}

	// An evaluating window observes the fault.
	loop.record(WindowResult{ObservedAt: now, Schedules: []ScheduleResult{{
		ScheduleID: scheduleID, Due: 1, Claimed: 1, Handoffs: 1,
		Evaluated: true, Degraded: DegradedScheduledReportsUndeliverable,
	}}}, now)
	raised := degradedGauge()
	if !strings.Contains(raised, DegradedScheduledReportsUndeliverable) || !strings.HasSuffix(raised, " 1") {
		t.Fatalf("after the evaluating window the gauge is %q, want the reason raised", raised)
	}

	// The polls in between: no occurrence due, so no verdict. These must not clear it.
	for poll := 1; poll <= 3; poll++ {
		loop.record(WindowResult{
			ObservedAt: now.Add(time.Duration(poll) * 15 * time.Second),
			Schedules:  []ScheduleResult{{ScheduleID: scheduleID}},
		}, now.Add(time.Duration(poll)*15*time.Second))
		if held := degradedGauge(); held != raised {
			t.Fatalf(
				"poll %d changed the gauge to %q; a window that did not evaluate the "+
					"schedule must not clear a reason it never observed", poll, held,
			)
		}
	}

	// An evaluating window that finds nothing wrong DOES clear it, or the signal would
	// latch forever and stop meaning anything.
	loop.record(WindowResult{
		ObservedAt: now.Add(5 * time.Minute),
		Schedules: []ScheduleResult{{
			ScheduleID: scheduleID, Due: 1, Claimed: 1, Handoffs: 1, Evaluated: true,
		}},
	}, now.Add(5*time.Minute))
	cleared := degradedGauge()
	if strings.Contains(cleared, DegradedScheduledReportsUndeliverable) || !strings.HasSuffix(cleared, " 0") {
		t.Fatalf("after a clean evaluating window the gauge is %q, want it cleared", cleared)
	}
}

// staticStepper is a Stepper that only declares schedules; record() is driven
// directly, so Step is never called.
type staticStepper struct{ schedules []Schedule }

func (stepper staticStepper) Step(context.Context, time.Time) (WindowResult, error) {
	return WindowResult{}, nil
}

func (stepper staticStepper) Schedules() []Schedule {
	return append([]Schedule(nil), stepper.schedules...)
}

// An ordinary SkipReason must NOT reach the degraded gauge.
//
// This pins the fix for a defect this change introduced into shared engine behaviour,
// affecting a producer it did not write. Because a degraded reason now persists until
// the schedule next evaluates, promoting a skip made it LATCH for a full period: the
// weekly remaining-metrics fan-out would show "no_active_organizations" for a week
// after organizations were added, and an operator would be looking at a fault that
// resolved days earlier.
//
// The distinction is the same one that motivated Evaluated in the first place, one
// level down. A skip reason describes THIS occurrence ("nothing was due"); a degraded
// reason describes ONGOING state. Only the second may persist.
func TestSkipReasonIsNotPromotedToTheDegradedGauge(t *testing.T) {
	const scheduleID = "capacity_forecast_weekly_fanout"
	schedule := scheduleByID(t, scheduleID)
	loop, err := NewLoop(
		staticStepper{schedules: []Schedule{schedule}},
		DefaultLoopConfig(health.NewRegistry(100*time.Millisecond)),
	)
	if err != nil {
		t.Fatal(err)
	}
	now := time.Date(2026, time.July, 27, 4, 0, 0, 0, time.UTC)

	// A window that skipped for a bounded reason and reported NO degraded condition:
	// exactly what the fan-out produces on an installation with no organizations.
	loop.record(WindowResult{ObservedAt: now, Schedules: []ScheduleResult{{
		ScheduleID: scheduleID, Due: 1, Claimed: 1, Skipped: 1, Evaluated: true,
	}}}, now)

	var exported strings.Builder
	if err := loop.WritePrometheus(&exported); err != nil {
		t.Fatal(err)
	}
	for _, line := range strings.Split(exported.String(), "\n") {
		if !strings.HasPrefix(line, `fixed_scheduler_schedule_degraded{schedule="`+scheduleID+`"`) {
			continue
		}
		if !strings.Contains(line, `reason="none"`) || !strings.HasSuffix(line, " 0") {
			t.Fatalf(
				"gauge = %q; an ordinary skip reason was promoted to the degraded gauge, "+
					"where it would latch until this weekly schedule next evaluates", line,
			)
		}
		// The skip is still visible where it belongs: as a counted occurrence outcome.
		if !strings.Contains(exported.String(),
			`fixed_scheduler_occurrences_total{schedule="`+scheduleID+`",result="skipped"} 1`) {
			t.Fatalf("the skip was not counted as an occurrence outcome:\n%s", exported.String())
		}
		return
	}
	t.Fatalf("no degraded gauge for %s in:\n%s", scheduleID, exported.String())
}
