package providersync

import (
	"fmt"
	"time"
)

// Shared case set for the three metric-triplet oracle pairs. One list, three
// pairs: the Python helper runs compute_work_item_metrics_daily once per case
// and each pair selects one of its three returned lists, so a case that is
// interesting for the group rollup is automatically also compared for the user
// rollup and the cycle-time records it produced.
//
// The UTC day under test is 2026-08-04, i.e. the half-open window
// [2026-08-04T00:00:00Z, 2026-08-05T00:00:00Z), whose trailing-7-day throughput
// window opens at 2026-07-29T00:00:00Z. Every boundary case below is written
// against those three instants deliberately.

const (
	githubWorkItemMetricOracleOrg    = "org-acme"
	githubWorkItemMetricOracleDay    = "2026-08-04"
	githubWorkItemMetricOracleNow    = "2026-08-04T12:00:00Z"
	githubWorkItemMetricOracleRepoID = "c7198fbc-1945-3717-05d8-eb78866b4e79"
)

func githubWorkItemMetricOracleItem(id string, fields map[string]any) map[string]any {
	row := map[string]any{
		"work_item_id": id, "provider": "github", "title": id,
		"type": "feature", "status": "todo", "status_raw": "open",
		"project_id": "acme/api", "assignees": []any{},
		"created_at": "2026-08-01T00:00:00Z", "updated_at": "2026-08-04T00:00:00Z",
		"org_id": githubWorkItemMetricOracleOrg,
	}
	for key, value := range fields {
		row[key] = value
	}
	return row
}

func githubWorkItemMetricOracleTransition(id, toStatus, occurredAt string) map[string]any {
	return map[string]any{
		"work_item_id": id, "provider": "github", "occurred_at": occurredAt,
		"from_status": "todo", "to_status": toStatus,
		"from_status_raw": nil, "to_status_raw": toStatus, "actor": nil,
		"org_id": githubWorkItemMetricOracleOrg,
	}
}

func githubWorkItemMetricOracleRepoFact(teamID, teamName string) map[string]any {
	return map[string]any{
		"Provider": "github", "TeamID": teamID, "TeamName": teamName,
		"RepoID": githubWorkItemMetricOracleRepoID, "RepoFullName": "acme/api",
		"IsPrimary": 1, "Specificity": 70, "Priority": 0,
		"UpdatedAt": githubWorkItemMetricOracleNow,
	}
}

func githubWorkItemMetricOracleCase(id string, input map[string]any) oracleCase {
	complete := map[string]any{
		"Day": githubWorkItemMetricOracleDay, "ComputedAt": githubWorkItemMetricOracleNow,
		"AsOf": githubWorkItemMetricOracleNow, "OrgID": githubWorkItemMetricOracleOrg,
	}
	for key, value := range input {
		complete[key] = value
	}
	return oracleCase{ID: id, Input: complete}
}

// githubWorkItemMetricFloatSweepCase is one case holding MANY independent
// groups, so a single comparison covers a wide slice of the floating-point
// input space instead of one hand-chosen point.
//
// Hand-picking timestamps cannot cover this. The Go compiler is free to
// contract `a*b + c*d`, and Python's duration and percentile arithmetic
// decompose differently from Go's; a measured sweep put the difference at
// roughly one interpolated percentile in nine, spread unpredictably across the
// input space. A case built from four pretty durations lands on an agreeing
// point most of the time and reports a pass. This one walks 24 work scopes of
// four completions each, with microsecond-precision durations and a wait
// transition inside every cycle, so the group and user percentiles, the
// duration-to-hours conversion and the flow-breakdown seconds are all compared
// at 24 independent points at once.
//
// Generated by a fixed integer PRNG so the JSON handed to Python is identical
// on every run -- a sweep that varied per run would be a flaky oracle, which is
// worse than a narrow one.
func githubWorkItemMetricFloatSweepCase() oracleCase {
	const scopes = 24
	seed := uint64(0x2545F4914F6CDD1D)
	next := func(bound uint64) uint64 {
		seed ^= seed << 13
		seed ^= seed >> 7
		seed ^= seed << 17
		return seed % bound
	}
	// Microsecond-resolution instants only: a Python datetime cannot hold
	// anything finer, so a nanosecond here would be silently truncated on one
	// side and compared against the untruncated value on the other.
	instant := func(base time.Time, micros uint64) string {
		return base.Add(time.Duration(micros) * time.Microsecond).
			UTC().Format("2006-01-02T15:04:05.000000Z")
	}
	dayStart := time.Date(2026, 8, 4, 0, 0, 0, 0, time.UTC)
	items := make([]any, 0, scopes*4)
	transitions := make([]any, 0, scopes*4)
	for scope := 0; scope < scopes; scope++ {
		scopeID := fmt.Sprintf("acme/sweep-%02d", scope)
		for index := 0; index < 4; index++ {
			id := fmt.Sprintf("gh:%s#%d", scopeID, index)
			// Completion inside the day, cycle length anywhere from minutes to
			// most of a week, so lo/hi brackets and fracs vary across scopes.
			completedMicros := 3*3600*1000000 + next(20*3600*1000000)
			cycleMicros := 60*1000000 + next(160*3600*1000000)
			completedAt := dayStart.Add(time.Duration(completedMicros) * time.Microsecond)
			startedAt := completedAt.Add(-time.Duration(cycleMicros) * time.Microsecond)
			items = append(items, githubWorkItemMetricOracleItem(id, map[string]any{
				"status": "done", "assignees": []any{"dev@example.com"},
				"project_id":   scopeID,
				"created_at":   instant(startedAt, 0-next(48*3600*1000000)-1),
				"started_at":   instant(startedAt, 0),
				"completed_at": instant(completedAt, 0),
			}))
			// One wait span strictly inside the cycle, at an awkward offset, so
			// the active/wait split is a sum of odd microsecond segments rather
			// than of whole hours.
			blockedAt := startedAt.Add(time.Duration(next(cycleMicros/3)+1) * time.Microsecond)
			resumedAt := blockedAt.Add(time.Duration(next(cycleMicros/3)+1) * time.Microsecond)
			transitions = append(transitions,
				githubWorkItemMetricOracleTransition(id, "blocked", instant(blockedAt, 0)),
				githubWorkItemMetricOracleTransition(id, "in_progress", instant(resumedAt, 0)))
		}
	}
	return githubWorkItemMetricOracleCase("float_arithmetic_sweep_across_many_groups",
		map[string]any{"WorkItems": items, "Transitions": transitions})
}

func githubWorkItemMetricTripletOracleCases() []oracleCase {
	cases := []oracleCase{
		// Active/wait split driven by real transitions: in_progress from
		// 00:00-02:00 and 05:00-10:00 (7h active), blocked 02:00-05:00 (3h
		// wait) over a 10h cycle, so flow_efficiency is 0.7 rather than 1.
		githubWorkItemMetricOracleCase("wait_transitions_split_the_flow_breakdown", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#1", map[string]any{
					"repo_id": githubWorkItemMetricOracleRepoID, "status": "done",
					"assignees": []any{"dev@example.com"}, "story_points": 3,
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T10:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#2", map[string]any{
					"repo_id": githubWorkItemMetricOracleRepoID, "status": "in_progress",
					"assignees": []any{"other@example.com"}, "created_at": "2026-08-02T00:00:00Z",
					"started_at": "2026-08-03T12:00:00Z",
				}),
			},
			"Transitions": []any{
				githubWorkItemMetricOracleTransition("gh:acme/api#1", "blocked", "2026-08-04T02:00:00Z"),
				githubWorkItemMetricOracleTransition("gh:acme/api#1", "in_progress", "2026-08-04T05:00:00Z"),
			},
			"Facts": map[string]any{"Repos": []any{
				githubWorkItemMetricOracleRepoFact("team-repo", "Repository Team"),
			}},
		}),
		// A started+completed item with no transitions at all. The breakdown is
		// entirely active -- but NOT via Python's explicit
		// "if calculated_active_h + calculated_wait_h == 0" fallback, which is
		// unreachable: the walk always closes with the segment from the last
		// transition (or the start) to completed_at, and that segment is
		// non-empty whenever the cycle is, which is exactly the condition under
		// which the breakdown runs at all. The fallback is ported because it is
		// in the source, and mutation M20 records that it cannot be observed.
		githubWorkItemMetricOracleCase("absent_transitions_are_fully_active", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#3", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T01:00:00Z", "completed_at": "2026-08-04T07:00:00Z",
				}),
			},
		}),
		// started_at == completed_at: the cycle is zero, so the flow breakdown
		// is not computed at all and all three flow fields stay null -- distinct
		// from "computed and found to be zero".
		githubWorkItemMetricOracleCase("zero_length_cycle_has_no_flow_breakdown", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#4", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T09:00:00Z", "completed_at": "2026-08-04T09:00:00Z",
				}),
			},
		}),
		// Four cycle times (1h, 2h, 4h, 8h) so both percentiles land BETWEEN
		// samples and must interpolate: p50 = 3.0, p90 = 4 + 0.7*(8-4).
		githubWorkItemMetricOracleCase("percentiles_interpolate_between_samples", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#10", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T01:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#11", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T02:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#12", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T04:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#13", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T08:00:00Z",
				}),
			},
		}),
		// An assignee list holding one EMPTY string. Python's user identity is
		// `assignee or "unassigned"` (falsy empty -> "unassigned") while its
		// unassigned COUNTERS test `assignee is None` (an empty string is not
		// None). Both items land in one "unassigned" user bucket, but only the
		// genuinely assignee-less one increments items_started_unassigned.
		githubWorkItemMetricOracleCase("empty_first_assignee_is_unassigned_identity_only", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#20", map[string]any{
					"status": "done", "assignees": []any{""},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T03:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#21", map[string]any{
					"status": "done", "assignees": []any{},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T05:00:00Z",
				}),
			},
		}),
		// Creation-day counters with nothing started or completed.
		githubWorkItemMetricOracleCase("creation_day_drives_the_defect_intro_rate", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#30", map[string]any{
					"type": "bug", "created_at": "2026-08-04T04:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#31", map[string]any{
					"created_at": "2026-08-04T05:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#32", map[string]any{
					"created_at": "2026-08-04T06:00:00Z",
				}),
			},
		}),
		// The trailing-7-day throughput window is DEAD CODE in the producer, and
		// this case is what pins that rather than pretending otherwise.
		//
		// compute_work_items.py:844 drops any item with no activity today before
		// line 900 ever tests the throughput window. An item completed one to six
		// days ago cannot pass that gate: it is not started, completed or created
		// today, and its terminal instant is before the window end so it is not
		// WIP either. So the only completions the window can ever see are today's,
		// and today is inside any window of a day or more. wip_congestion_ratio
		// is therefore really wip / max(1, items_completed_TODAY), not a
		// seven-day rate -- which is why mutations M11, M12 and M60 (moving or
		// shrinking that window, in Go and in Python alike) are declared
		// equivalent instead of being chased with a case that cannot exist.
		//
		// #40 sits exactly on the window's opening instant and #41 just outside
		// it; both are dropped by the relevance gate, and the oracle agreeing
		// that they contribute nothing IS the observation. The residual risk is
		// recorded in the PR body as a Python defect ported faithfully.
		githubWorkItemMetricOracleCase("weekly_throughput_window_is_left_inclusive", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#40", map[string]any{
					"status": "done", "created_at": "2026-07-20T00:00:00Z",
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-07-28T00:00:00Z", "completed_at": "2026-07-29T00:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#41", map[string]any{
					"status": "done", "created_at": "2026-07-20T00:00:00Z",
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-07-27T00:00:00Z", "completed_at": "2026-07-28T23:59:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#43", map[string]any{
					"status": "done", "created_at": "2026-07-20T00:00:00Z",
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-07-29T12:00:00Z", "completed_at": "2026-07-30T00:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#42", map[string]any{
					"status": "in_progress", "created_at": "2026-07-20T00:00:00Z",
					"assignees": []any{"dev@example.com"}, "started_at": "2026-08-01T00:00:00Z",
				}),
			},
		}),
		// closed_at, not completed_at, ends this item's WIP. #50 closes inside
		// the day with no completion, so it is neither WIP at end of day nor a
		// cycle-time record. #52 has BOTH instants set and they disagree: the
		// item was closed today and completed tomorrow, so the EARLIER of the
		// two ends its life and it is not WIP either. Without #52 the "earliest
		// of the two" rule is untested, because with only one instant set the
		// earliest and the latest are the same value. The surviving group row
		// must count exactly one WIP item.
		githubWorkItemMetricOracleCase("closed_at_ends_work_in_progress", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#50", map[string]any{
					"status": "cancelled", "created_at": "2026-08-01T00:00:00Z",
					"assignees": []any{"dev@example.com"}, "started_at": "2026-08-03T00:00:00Z",
					"closed_at": "2026-08-04T06:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#52", map[string]any{
					"status": "done", "created_at": "2026-08-01T00:00:00Z",
					"assignees": []any{"dev@example.com"}, "started_at": "2026-08-03T00:00:00Z",
					"closed_at": "2026-08-04T09:00:00Z", "completed_at": "2026-08-05T09:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#51", map[string]any{
					"status": "in_progress", "created_at": "2026-08-01T00:00:00Z",
					"assignees": []any{"dev@example.com"}, "started_at": "2026-08-03T00:00:00Z",
				}),
			},
		}),
		// Cross-provider inheritance: the GitHub item carries no attribution
		// fact of its own and reaches a Linear donor through an extkey edge, so
		// the two items split into two groups ordered by team_id.
		githubWorkItemMetricOracleCase("linked_donor_splits_the_group_by_team", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#60", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T02:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#61", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T03:00:00Z",
				}),
			},
			"Donors": []any{
				githubWorkItemMetricOracleItem("linear:CHAOS-42", map[string]any{
					"provider": "linear", "project_id": "linear-project",
				}),
			},
			"Dependencies": []any{map[string]any{
				"source_work_item_id": "gh:acme/api#60", "target_work_item_id": "extkey:CHAOS-42",
				"relationship_type": "external_issue_key", "relationship_type_raw": "closes",
				"relationship_semantics_version": "canonical-blocks.v2",
				"last_synced":                    githubWorkItemMetricOracleNow, "org_id": githubWorkItemMetricOracleOrg,
			}},
			"Facts": map[string]any{"Projects": []any{map[string]any{
				"Provider": "linear", "ProjectID": "linear-project", "TeamID": "team-linear",
				"TeamName": "Linear Team", "IsPrimary": 1, "Specificity": 80, "Priority": 0,
				"UpdatedAt": githubWorkItemMetricOracleNow,
			}}},
		}),
		// One completed bug with an estimate plus one completed feature without
		// one: bug_completed_ratio is 0.5 and story_points_completed sums only
		// the estimate that exists.
		githubWorkItemMetricOracleCase("bug_ratio_and_story_points_sum_completions", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#70", map[string]any{
					"type": "bug", "status": "done", "story_points": 5,
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T02:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#71", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T06:00:00Z",
				}),
			},
		}),
		// The same user on the same work scope, attributed to two different
		// teams by their native team keys. The compute grain keeps these apart;
		// the persisted natural key does NOT include team_id, so these two rows
		// collapse in ClickHouse. That residual risk is recorded in the PR body
		// rather than fixed in this parity lane -- this case is what makes the
		// two-row compute behavior observable and pinned.
		githubWorkItemMetricOracleCase("one_user_two_teams_stays_two_compute_rows", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#80", map[string]any{
					"native_team_key": "TEAMA", "status": "done",
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T02:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#81", map[string]any{
					"native_team_key": "TEAMB", "status": "done",
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T04:00:00Z",
				}),
			},
			"Facts": map[string]any{"Teams": []any{
				map[string]any{"TeamID": "team-a", "TeamName": "Team A", "ProjectKeys": []any{"TEAMA"}},
				map[string]any{"TeamID": "team-b", "TeamName": "Team B", "ProjectKeys": []any{"TEAMB"}},
			}},
		}),
		// The status a transition leaves the item in AT or BEFORE started_at
		// seeds the flow walk. "todo" and "backlog" are both re-seeded to
		// in_progress -- an item that has a start instant is by definition
		// working, whatever its last recorded transition said -- while any other
		// pre-start status is carried forward as-is. #200's pre-start
		// transition lands EXACTLY on started_at, which is also the inclusive
		// edge of the seeding scan and the exclusive edge of the accumulating
		// one, so a boundary that slips by one instant double-counts it.
		githubWorkItemMetricOracleCase("pre_start_status_seeds_the_flow_walk", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#200", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T02:00:00Z", "completed_at": "2026-08-04T08:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#201", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T02:00:00Z", "completed_at": "2026-08-04T06:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#202", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T02:00:00Z", "completed_at": "2026-08-04T05:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#203", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at": "2026-08-04T02:00:00Z", "completed_at": "2026-08-04T07:00:00Z",
				}),
			},
			"Transitions": []any{
				githubWorkItemMetricOracleTransition("gh:acme/api#200", "todo", "2026-08-04T02:00:00Z"),
				githubWorkItemMetricOracleTransition("gh:acme/api#200", "review_requested", "2026-08-04T04:00:00Z"),
				githubWorkItemMetricOracleTransition("gh:acme/api#201", "backlog", "2026-08-04T01:00:00Z"),
				// #202 is left in a genuine wait status before it starts, which
				// must NOT be re-seeded: the whole span to its next transition is
				// wait time, not active time.
				githubWorkItemMetricOracleTransition("gh:acme/api#202", "blocked", "2026-08-04T01:30:00Z"),
				githubWorkItemMetricOracleTransition("gh:acme/api#202", "in_progress", "2026-08-04T04:00:00Z"),
				// #203's wait status lands EXACTLY on started_at. A seeding scan
				// that stops one instant early misses it, falls back to
				// "unknown", and re-seeds to in_progress -- turning two hours of
				// wait into two hours of active work. #200's at-start transition
				// cannot catch that: `todo` is re-seeded to in_progress anyway,
				// so seeding from it and missing it give the same answer.
				githubWorkItemMetricOracleTransition("gh:acme/api#203", "blocked", "2026-08-04T02:00:00Z"),
				githubWorkItemMetricOracleTransition("gh:acme/api#203", "in_progress", "2026-08-04T04:00:00Z"),
			},
		}),
		// More than one assignee. Python takes assignees[0] and only
		// assignees[0]: the second name never becomes a user row, and never
		// counts toward anyone's cycle-time percentiles.
		githubWorkItemMetricOracleCase("only_the_first_assignee_becomes_a_user_row", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#210", map[string]any{
					"status":     "done",
					"assignees":  []any{"first@example.com", "second@example.com"},
					"started_at": "2026-08-04T00:00:00Z", "completed_at": "2026-08-04T02:00:00Z",
				}),
			},
			"Facts": map[string]any{"Members": []any{
				map[string]any{
					"Provider": "github", "TeamID": "team-second", "TeamName": "Second Team",
					"MemberID": "second@example.com", "IsPrimary": 1, "Specificity": 50,
					"Priority": 0, "UpdatedAt": githubWorkItemMetricOracleNow,
				},
			}},
		}),
		// Flow segments in the SECONDS band, where the two ways of turning a
		// duration into seconds actually disagree.
		//
		// Duration.Seconds() adds whole seconds to a nanosecond remainder;
		// timedelta.total_seconds() divides one microsecond count. Across
		// millisecond-aligned durations from 1s to 10s the two differ on 6.0% of
		// values -- 1.118s is the first -- while across the 1min..160h band they
		// differ on 0.0002%. An earlier version of this lane declared that
		// difference an equivalence on the strength of a 200,000-point sweep that
		// sampled only the wide band: exactly the shape of a measurement that
		// confirms whatever it was pointed at. Every gap below is a value measured
		// to diverge, so the seconds conversion is guarded rather than assumed.
		githubWorkItemMetricOracleCase("flow_segments_in_the_divergent_seconds_band", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#400", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at":   "2026-08-04T09:00:00.000000Z",
					"completed_at": "2026-08-04T09:00:08.616000Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#401", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"started_at":   "2026-08-04T10:00:00.000000Z",
					"completed_at": "2026-08-04T10:00:06.400000Z",
				}),
			},
			"Transitions": []any{
				githubWorkItemMetricOracleTransition("gh:acme/api#400", "blocked", "2026-08-04T09:00:01.118000Z"),
				githubWorkItemMetricOracleTransition("gh:acme/api#400", "in_progress", "2026-08-04T09:00:02.240000Z"),
				githubWorkItemMetricOracleTransition("gh:acme/api#401", "blocked", "2026-08-04T10:00:01.128000Z"),
				githubWorkItemMetricOracleTransition("gh:acme/api#401", "in_progress", "2026-08-04T10:00:02.260000Z"),
			},
		}),
		// An item STARTED today whose completion is six days old. This state is
		// what makes the trailing-7-day throughput window reachable at all.
		//
		// relevant_activity is a DISJUNCTION, and started_today imposes no
		// constraint whatsoever on completed_at -- so this row passes the gate at
		// compute_work_items.py:844 and then reaches the window test at 900
		// carrying a six-day-old completion. An earlier version of this lane
		// declared the window dead on the argument that no row could reach it.
		// That argument was wrong about the disjunction.
		//
		// The GitHub normalizer will not emit started_at > completed_at, but the
		// compute reads work_items straight out of ClickHouse and nothing enforces
		// that invariant there -- which is why the state is worth pinning rather
		// than assuming away. Tracked on CHAOS-3486.
		//
		// THREE in-window completions make the denominator observable: with one,
		// max(1, throughput) returns 1 whether it is counted or dropped, and a
		// window bound tested at the denominator floor tests nothing.
		githubWorkItemMetricOracleCase("throughput_window_is_reachable_via_started_today", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#500", map[string]any{
					"status": "done", "created_at": "2026-07-01T00:00:00Z",
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-08-04T08:00:00Z", "completed_at": "2026-07-29T00:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#501", map[string]any{
					"status": "done", "created_at": "2026-07-01T00:00:00Z",
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-08-04T08:00:00Z", "completed_at": "2026-07-29T12:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#502", map[string]any{
					"status": "done", "created_at": "2026-07-01T00:00:00Z",
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-08-04T08:00:00Z", "completed_at": "2026-07-31T00:00:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#503", map[string]any{
					"status": "done", "created_at": "2026-07-01T00:00:00Z",
					"assignees":  []any{"dev@example.com"},
					"started_at": "2026-08-04T08:00:00Z", "completed_at": "2026-07-28T23:59:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#504", map[string]any{
					"status": "in_progress", "created_at": "2026-07-01T00:00:00Z",
					"assignees": []any{"dev@example.com"}, "started_at": "2026-08-01T00:00:00Z",
				}),
			},
		}),
		// Unassigned work in progress, with two different ages so the WIP-age
		// percentiles interpolate rather than collapse onto one sample.
		// wip_unassigned_end_of_day is non-zero here and nowhere else in the batch,
		// so without this case that counter is only ever compared as zero against
		// zero -- which is not a comparison of the counter, only of its default.
		githubWorkItemMetricOracleCase("unassigned_work_in_progress_has_an_age_spread", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#600", map[string]any{
					"status": "in_progress", "assignees": []any{},
					"created_at": "2026-07-20T00:00:00Z", "started_at": "2026-08-01T05:17:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#601", map[string]any{
					"status": "in_progress", "assignees": []any{},
					"created_at": "2026-07-20T00:00:00Z", "started_at": "2026-08-03T19:43:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#602", map[string]any{
					"status": "in_progress", "assignees": []any{"dev@example.com"},
					"created_at": "2026-07-20T00:00:00Z", "started_at": "2026-08-02T11:29:00Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#603", map[string]any{
					"status": "in_progress", "assignees": []any{},
					"created_at": "2026-07-20T00:00:00Z", "started_at": "2026-08-04T06:00:00Z",
				}),
			},
		}),
		// A percentile that is sensitive in its LAST BIT. These four cycle
		// lengths were found by sweeping the production function against a
		// deliberately-contracted variant of the same expression and keeping a
		// set where p90 differs by one ulp: 12.558236330888889 against
		// 12.55823633088889. Ordinary durations cannot show this -- every case
		// above uses values where the two agree exactly -- so without a case
		// chosen for it, the interpolation could silently drift from Python on
		// roughly one group in nine and nothing would say so. The columns are
		// compared for equality on readback, so one ulp is a permanent conflict,
		// not a rounding curiosity.
		githubWorkItemMetricOracleCase("percentile_is_exact_to_the_last_bit", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#300", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"created_at":   "2026-07-01T00:00:00Z",
					"started_at":   "2026-08-04T00:42:41.713748Z",
					"completed_at": "2026-08-04T09:00:00.000000Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#301", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"created_at":   "2026-07-01T00:00:00Z",
					"started_at":   "2026-08-03T20:26:29.687695Z",
					"completed_at": "2026-08-04T09:01:00.000000Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#302", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"created_at":   "2026-07-01T00:00:00Z",
					"started_at":   "2026-08-03T20:30:51.892741Z",
					"completed_at": "2026-08-04T09:02:00.000000Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#303", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"created_at":   "2026-07-01T00:00:00Z",
					"started_at":   "2026-08-04T03:21:04.518494Z",
					"completed_at": "2026-08-04T09:03:00.000000Z",
				}),
			},
		}),
		// Microsecond-precision boundaries. Python reaches hours through
		// timedelta.total_seconds()/3600 (an integer microsecond count divided
		// twice) and Go through time.Duration.Hours() (an integer nanosecond
		// count divided once); the flow breakdown then accumulates SECONDS on
		// both sides and divides by 3600 at the end. Those are different
		// arithmetic paths to the same quantity, so at least one case has to
		// use durations that are not whole minutes -- otherwise every compared
		// duration is exactly representable and the paths cannot be told apart.
		githubWorkItemMetricOracleCase("sub_second_durations_agree_across_both_paths", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#100", map[string]any{
					"status": "done", "assignees": []any{"dev@example.com"},
					"created_at":   "2026-07-31T03:17:11.123456Z",
					"started_at":   "2026-08-04T01:02:03.456789Z",
					"completed_at": "2026-08-04T07:41:59.987654Z",
				}),
				githubWorkItemMetricOracleItem("gh:acme/api#101", map[string]any{
					"status": "in_progress", "assignees": []any{"dev@example.com"},
					"created_at": "2026-07-30T00:00:00Z",
					"started_at": "2026-08-02T11:13:17.001002Z",
				}),
			},
			"Transitions": []any{
				githubWorkItemMetricOracleTransition("gh:acme/api#100", "waiting", "2026-08-04T02:33:44.555666Z"),
				githubWorkItemMetricOracleTransition("gh:acme/api#100", "in_progress", "2026-08-04T04:05:06.070809Z"),
			},
		}),
		// created_at == end of the window. The item does not exist yet on this
		// day, so all three projections stay empty. The batch guard test asserts
		// this case really is silent, so "non-empty somewhere" cannot be met by
		// making every case produce rows.
		githubWorkItemMetricOracleCase("created_after_the_window_is_not_a_row", map[string]any{
			"WorkItems": []any{
				githubWorkItemMetricOracleItem("gh:acme/api#90", map[string]any{
					"created_at": "2026-08-05T00:00:00Z",
				}),
			},
		}),
	}
	// The float sweep leads so a divergence in the shared arithmetic is the
	// first subtest to fail, ahead of the narrower semantic cases.
	return append([]oracleCase{githubWorkItemMetricFloatSweepCase()}, cases...)
}
