package providersync

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// ENUMERATION (CHAOS-7265): every INSERT into project_membership_transitions or work_items in the Go
// tree names its columns and omits ingested_at, the server-stamped insert time. A writer that sends a
// value reintroduces a client stamp behind a reader cursor. Generated by scanning the source, not by
// a list kept here: a new writer is covered the day it appears.
func TestNoWriterOfTheIngestedAtTablesSendsIngestedAt(t *testing.T) {
	insert := regexp.MustCompile("INSERT INTO (project_membership_transitions|work_items)\\b[^`\"]*")
	var found []string
	root := filepath.Join("..", "..", "internal")
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return err
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		// A statement can be split across concatenated string literals (TransitionsInsert is).
		flat := regexp.MustCompile("[`\"] *\\+\\s*[`\"]").ReplaceAllString(string(data), "")
		for _, statement := range insert.FindAllString(flat, -1) {
			found = append(found, path+": "+statement)
			if !strings.Contains(statement, "(") {
				t.Errorf("%s: %q does not name its columns", path, statement)
			}
			if strings.Contains(statement, "ingested_at") {
				t.Errorf("%s: %q sends ingested_at; the server stamps it", path, statement)
			}
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(found) < 4 {
		t.Fatalf("the scan found %d INSERT statement(s), want at least the 4 work_items + 1 transitions writers: %v", len(found), found)
	}
}
