package providersync

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/full-chaos/dev-health-ops/internal/providerfoundation"
	"github.com/full-chaos/dev-health-ops/internal/testsupport/fakehttp"
)

// Pull requests 52..54 carry every input the detector reads: labels, author
// kind, trailers in the body, the head branch, and free body text. #54 carries
// none and must yield no row.
const (
	prAttributionDetail52 = `{
  "id": 9052, "number": 52, "title": "Agent change", "state": "open", "draft": false, "merged": false,
  "body": "Change.\nCo-authored-by: Claude <claude@anthropic.com>\nAI-Assisted-By: copilot",
  "user": {"login": "copilot[bot]", "type": "Bot"},
  "labels": [{"name": "ai-assisted"}, {"name": "unrelated"}],
  "created_at": "2026-07-10T09:00:00Z", "updated_at": "2026-07-22T00:00:00Z",
  "head": {"ref": "claude/feature-x"}, "base": {"ref": "main"},
  "additions": 1, "deletions": 1, "changed_files": 1, "comments": 0
}`
	prAttributionDetail53 = `{
  "id": 9053, "number": 53, "title": "Body only", "state": "open", "draft": false, "merged": false,
  "body": "This was generated by Claude.",
  "user": {"login": "someone[bot]", "type": "Bot"},
  "labels": [],
  "created_at": "2026-07-11T09:00:00Z", "updated_at": "2026-07-23T00:00:00Z",
  "head": {"ref": "plain-branch"}, "base": {"ref": "main"},
  "additions": 1, "deletions": 1, "changed_files": 1, "comments": 0
}`
	prAttributionDetail54 = `{
  "id": 9054, "number": 54, "title": "Human change", "state": "open", "draft": false, "merged": false,
  "body": "Plain description.",
  "user": {"login": "octocat", "type": "User"},
  "labels": [{"name": "bug"}],
  "created_at": "2026-07-12T09:00:00Z", "updated_at": "2026-07-24T00:00:00Z",
  "head": {"ref": "fix/typo"}, "base": {"ref": "main"},
  "additions": 1, "deletions": 1, "changed_files": 1, "comments": 0
}`
	prAttributionList = `[
  {"number": 54, "updated_at": "2026-07-24T00:00:00Z"},
  {"number": 53, "updated_at": "2026-07-23T00:00:00Z"},
  {"number": 52, "updated_at": "2026-07-22T00:00:00Z"}
]`
	prAttributionRepo = `{"id": 4567, "full_name": "Acme/API"}`
)

// ai_attribution.org_id is a UUID column, so the claim must carry one.
const prAttributionOrgID = "8f4c1d52-3b7a-4e21-9a0c-6d5e2f1b7a90"

func prAttributionClaim(provider, dataset string) Claim {
	claim := nativeTestClaim(provider, dataset)
	claim.OrgID = prAttributionOrgID
	return claim
}

func prAttributionNormalizedAt() time.Time {
	return time.Date(2026, 8, 4, 12, 0, 0, 123000000, time.UTC)
}

func prAttributionPRsEffect(t *testing.T) (CompleteRouteBatch, *gitHubPullRequestDoer) {
	t.Helper()
	doer := &gitHubPullRequestDoer{t: t, bodies: map[string]string{
		"/repos/acme/api":          prAttributionRepo,
		"/repos/acme/api/pulls":    prAttributionList,
		"/repos/acme/api/pulls/52": prAttributionDetail52,
		"/repos/acme/api/pulls/53": prAttributionDetail53,
		"/repos/acme/api/pulls/54": prAttributionDetail54,
	}}
	batch, err := (GitHubPullRequestRouteHandler{}).Collect(
		context.Background(), prAttributionClaim("github", "prs"),
		providerfoundation.Credential{},
		gitHubPullRequestClient(t, fakehttp.Client(doer), "https://api.github.com"),
		prAttributionNormalizedAt(),
	)
	if err != nil {
		t.Fatal(err)
	}
	return batch, doer
}

func prAttributionWorkItemsRows(t *testing.T) []githubAIAttributionRow {
	t.Helper()
	claim := githubWorkItemsRESTClaim()
	claim.OrgID = prAttributionOrgID
	claim.DatasetOptions["fetch_milestones"] = false
	doer := &githubWorkItemsRESTDoer{t: t, replies: map[string][]githubWorkItemsRESTReply{
		"/repos/acme/api":          {{body: prAttributionRepo}},
		"/repos/acme/api/issues":   {{body: `[]`}},
		"/repos/acme/api/pulls":    {{body: prAttributionList}},
		"/repos/acme/api/pulls/52": {{body: prAttributionDetail52}},
		"/repos/acme/api/pulls/53": {{body: prAttributionDetail53}},
		"/repos/acme/api/pulls/54": {{body: prAttributionDetail54}},
	}}
	result, err := (GitHubWorkItemsRESTCollector{}).Collect(
		context.Background(), claim,
		gitHubPullRequestClient(t, fakehttp.Client(doer), "https://api.github.com"),
		prAttributionNormalizedAt(),
	)
	if err != nil {
		t.Fatal(err)
	}
	var rows []githubAIAttributionRow
	for _, pull := range result.PullRequests {
		bundle, err := normalizeGitHubPullRequestBundle(
			claim, result.RepoFullName, result.RepoID, pull.Payload,
			nil, nil, nil, nil, prAttributionNormalizedAt(),
		)
		if err != nil {
			t.Fatal(err)
		}
		rows = append(rows, bundle.AIAttributions...)
	}
	return rows
}

func sortedAttributions(rows []githubAIAttributionRow) []githubAIAttributionRow {
	out := append([]githubAIAttributionRow(nil), rows...)
	sort.Slice(out, func(left, right int) bool {
		if out[left].SubjectID != out[right].SubjectID {
			return out[left].SubjectID < out[right].SubjectID
		}
		if out[left].Source != out[right].Source {
			return out[left].Source < out[right].Source
		}
		return out[left].RecordID.String() < out[right].RecordID.String()
	})
	return out
}

func attributionEffectRows(t *testing.T, batch CompleteRouteBatch) []githubAIAttributionRow {
	t.Helper()
	for _, effect := range batch.Effects {
		if effect.Destination == "ai_attribution" {
			rows, err := decodeEffectRows[githubAIAttributionRow](effect)
			if err != nil {
				t.Fatal(err)
			}
			return rows
		}
	}
	t.Fatalf("no ai_attribution effect among %d effects", len(batch.Effects))
	return nil
}

// TestGitHubPRsRouteAttributionEqualsWorkItemsRouteRowForRow pins the one
// invariant the two writers share: both routes write the same ai_attribution
// key, and the last writer wins, so they must never disagree. Both rows come
// from the real collectors fed the same /pulls/{n} bodies, through the real
// normalizers of each route.
func TestGitHubPRsRouteAttributionEqualsWorkItemsRouteRowForRow(t *testing.T) {
	t.Parallel()
	batch, _ := prAttributionPRsEffect(t)
	fromPRs := sortedAttributions(attributionEffectRows(t, batch))
	fromWorkItems := sortedAttributions(prAttributionWorkItemsRows(t))
	sources := map[string]bool{}
	subjects := map[string]bool{}
	for _, row := range fromWorkItems {
		sources[row.Source] = true
		subjects[row.SubjectID] = true
	}
	// Every detector input must be exercised by the fixture, or equality
	// proves nothing about it: label, author kind, trailer, branch, body text.
	for _, source := range []string{"pr_label", "bot_author", "commit_trailer", "branch_name", "pr_body"} {
		if !sources[source] {
			t.Fatalf("fixture never exercises source %s: %v", source, sources)
		}
	}
	if subjects["54"] || !subjects["52"] || !subjects["53"] {
		t.Fatalf("subjects=%v want 52 and 53 only", subjects)
	}
	// Compared as the bytes each route hands its effect: the prs rows crossed
	// an effect round trip, the work-items rows did not, and typed nils inside
	// the evidence map differ in memory but not on the wire.
	prsJSON, _ := json.Marshal(fromPRs)
	itemsJSON, _ := json.Marshal(fromWorkItems)
	if string(prsJSON) != string(itemsJSON) {
		at := 0
		for at < len(prsJSON) && at < len(itemsJSON) && prsJSON[at] == itemsJSON[at] {
			at++
		}
		lo := max(at-120, 0)
		t.Fatalf("prs route rows differ from work-items route rows at byte %d\nprs:   ...%s\nitems: ...%s",
			at, prsJSON[lo:min(at+160, len(prsJSON))], itemsJSON[lo:min(at+160, len(itemsJSON))])
	}
}

// TestGitHubPRsRouteAttributionCostsNoExtraRequest pins that the attribution
// rows come out of the responses the unit already fetched: repo, list, and one
// detail per pull request in the window.
func TestGitHubPRsRouteAttributionCostsNoExtraRequest(t *testing.T) {
	t.Parallel()
	batch, doer := prAttributionPRsEffect(t)
	want := []string{
		"/repos/acme/api", "/repos/acme/api/pulls",
		"/repos/acme/api/pulls/54", "/repos/acme/api/pulls/53", "/repos/acme/api/pulls/52",
	}
	if !reflect.DeepEqual(doer.requests, want) || batch.Evidence.Requests != len(want) {
		t.Fatalf("requests=%v evidence=%d want %v", doer.requests, batch.Evidence.Requests, want)
	}
	if len(batch.Effects) != 2 || batch.Effects[1].Destination != "ai_attribution" {
		t.Fatalf("effects=%d", len(batch.Effects))
	}
}

// TestGitHubPRsRouteWithoutSignalsStillEmitsTheAttributionDestination keeps
// the destination set of the unit constant, because the prepared-snapshot
// manifest compares the emitted destinations to the descriptor's.
func TestGitHubPRsRouteWithoutSignalsStillEmitsTheAttributionDestination(t *testing.T) {
	t.Parallel()
	doer := &gitHubPullRequestDoer{t: t, bodies: map[string]string{
		"/repos/acme/api":          prAttributionRepo,
		"/repos/acme/api/pulls":    `[{"number": 54, "updated_at": "2026-07-24T00:00:00Z"}]`,
		"/repos/acme/api/pulls/54": prAttributionDetail54,
	}}
	batch, err := (GitHubPullRequestRouteHandler{}).Collect(
		context.Background(), prAttributionClaim("github", "prs"),
		providerfoundation.Credential{},
		gitHubPullRequestClient(t, fakehttp.Client(doer), "https://api.github.com"),
		prAttributionNormalizedAt(),
	)
	if err != nil {
		t.Fatal(err)
	}
	if rows := attributionEffectRows(t, batch); len(rows) != 0 {
		t.Fatalf("rows=%d want none for a human pull request", len(rows))
	}
}

func TestPRAttributionSinkFencesRowsToTheUnitProvider(t *testing.T) {
	t.Parallel()
	batch, _ := prAttributionPRsEffect(t)
	var effect EffectBatch
	for _, candidate := range batch.Effects {
		if candidate.Destination == "ai_attribution" {
			effect = candidate
		}
	}
	lease := providerfoundation.LeaseGuardFunc(func(context.Context) error { return nil })
	claim := prAttributionClaim("github", "prs")
	if err := (GitHubPullRequestSocialClickHouseEffects{Lease: lease}).WriteEffect(
		context.Background(), claim, effect,
	); !errors.Is(err, ErrInvalidConfiguration) {
		// A real connection is required once rows exist; the fence accepted
		// the effect and the adapter reached its connection guard.
		t.Fatalf("github rows through the github sink: err=%v want the connection guard", err)
	}
	gitlabClaim := prAttributionClaim("gitlab", "prs")
	gitlabEffect := effect
	gitlabEffect.Rows = append([]json.RawMessage(nil), effect.Rows...)
	for index, raw := range gitlabEffect.Rows {
		gitlabEffect.Rows[index] = json.RawMessage(strings.Replace(string(raw), `"provider":"github"`, `"provider":"gitlab"`, 1))
	}
	rebuilt, err := BuildEffectBatch("ai_attribution", EffectReadbackRequired, gitlabEffect.Rows)
	if err != nil {
		t.Fatal(err)
	}
	// github rows inside a gitlab unit, and gitlab rows inside a github unit,
	// are refused before any connection is touched.
	if _, err := newPRAIAttributionEffectIdentity(gitlabClaim, effect); !errors.Is(err, ErrInvalidConfiguration) {
		t.Fatalf("github rows in a gitlab unit: err=%v", err)
	}
	if _, err := newPRAIAttributionEffectIdentity(claim, rebuilt); !errors.Is(err, ErrInvalidConfiguration) {
		t.Fatalf("gitlab rows in a github unit: err=%v", err)
	}
	if _, err := newPRAIAttributionEffectIdentity(claim, effect); err != nil {
		t.Fatalf("github rows in a github unit: %v", err)
	}
	var wrongSubject []json.RawMessage
	for _, raw := range effect.Rows {
		wrongSubject = append(wrongSubject, json.RawMessage(strings.Replace(
			string(raw), `"subject_type":"pull_request"`, `"subject_type":"issue"`, 1)))
	}
	issueEffect, err := BuildEffectBatch("ai_attribution", EffectReadbackRequired, wrongSubject)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := newPRAIAttributionEffectIdentity(claim, issueEffect); !errors.Is(err, ErrInvalidConfiguration) {
		t.Fatalf("an issue-subject row in a PR-social unit: err=%v", err)
	}
	tampered := effect
	tampered.Rows = append(append([]json.RawMessage(nil), effect.Rows...), effect.Rows[0])
	if _, err := newPRAIAttributionEffectIdentity(claim, tampered); !errors.Is(err, ErrInvalidConfiguration) {
		t.Fatalf("rows that no longer match the effect digest: err=%v", err)
	}
	workItemsClaim := prAttributionClaim("github", "work-items")
	if _, err := newPRAIAttributionEffectIdentity(workItemsClaim, effect); !errors.Is(err, ErrInvalidConfiguration) {
		t.Fatalf("a work-items unit is not a PR-social unit: err=%v", err)
	}
	bogus := claim
	bogus.Provider = "jira"
	if _, err := newPRAIAttributionEffectIdentity(bogus, effect); !errors.Is(err, ErrInvalidConfiguration) {
		t.Fatalf("a jira unit must not write pull request attribution: err=%v", err)
	}
}

// GitLab merge requests: the list response is the one payload both routes read.
const (
	glAttributionMRList = `[
  {"iid": 7, "title": "Agent MR", "description": "Change.\nAI-Assisted-By: copilot", "state": "opened",
   "author": {"username": "dev", "bot": false}, "labels": ["ai-assisted", "unrelated"],
   "created_at": "2026-07-10T09:00:00Z", "updated_at": "2026-07-22T10:00:00Z",
   "source_branch": "codex/feature-x", "target_branch": "main", "user_notes_count": 0},
  {"iid": 8, "title": "Bot MR", "description": "This was generated by Claude.", "state": "opened",
   "author": {"username": "copilot[bot]", "bot": true}, "labels": [],
   "created_at": "2026-07-11T09:00:00Z", "updated_at": "2026-07-23T10:00:00Z",
   "source_branch": "plain-branch", "target_branch": "main", "user_notes_count": 0},
  {"iid": 9, "title": "Human MR", "description": "Plain.", "state": "opened",
   "author": {"username": "alice", "bot": false}, "labels": ["bug"],
   "created_at": "2026-07-12T09:00:00Z", "updated_at": "2026-07-24T10:00:00Z",
   "source_branch": "fix/typo", "target_branch": "main", "user_notes_count": 0}
]`
	glAttributionProject = `{"id":123,"path":"api","path_with_namespace":"Acme/API","name":"api"}`
)

type glAttributionDoer struct {
	requests []string
	// list and project override the default fixtures when set.
	list, project string
}

func (doer *glAttributionDoer) Do(request *http.Request) (*http.Response, error) {
	path := request.URL.Path
	doer.requests = append(doer.requests, path)
	root := "/api/v4/projects/123"
	status, body := http.StatusOK, `[]`
	list, project := glAttributionMRList, glAttributionProject
	if doer.list != "" {
		list = doer.list
	}
	if doer.project != "" {
		project = doer.project
	}
	switch {
	case path == root:
		body = project
	case path == root+"/merge_requests":
		if page := request.URL.Query().Get("page"); page == "" || page == "1" {
			body = list
		}
	case strings.HasSuffix(path, "/approvals"):
		status, body = http.StatusNotFound, `{"message":"approvals unavailable"}`
	}
	return &http.Response{
		StatusCode: status, Header: http.Header{"Content-Type": []string{"application/json"}},
		Body: io.NopCloser(strings.NewReader(body)), Request: request,
	}, nil
}

type capturingGitLabDeriver struct{ rows gitlabWorkItemRows }

func (deriver *capturingGitLabDeriver) Derive(
	_ context.Context, claim Claim, rows gitlabWorkItemRows, _ time.Time,
) (GitLabWorkItemDerivedRows, error) {
	deriver.rows = rows
	return GitLabWorkItemDerivedRows{Watermark: claim.BeforeAt}, nil
}

func glAttributionClient(t *testing.T, doer providerfoundation.HTTPDoer) *providerfoundation.HTTPClient {
	t.Helper()
	return gitLabRepositoryClient(t, fakehttp.Client(doer), "https://gitlab.example")
}

func glAttributionPRsBatch(t *testing.T) (CompleteRouteBatch, *glAttributionDoer) {
	t.Helper()
	doer := &glAttributionDoer{}
	batch, err := (GitLabPullRequestRouteHandler{PerPage: 100}).Collect(
		context.Background(), prAttributionClaim("gitlab", "prs"),
		providerfoundation.Credential{}, glAttributionClient(t, doer), prAttributionNormalizedAt(),
	)
	if err != nil {
		t.Fatal(err)
	}
	return batch, doer
}

func glAttributionWorkItemsRows(t *testing.T) []githubAIAttributionRow {
	t.Helper()
	claim := prAttributionClaim("gitlab", "work-items")
	deriver := &capturingGitLabDeriver{}
	if _, err := (GitLabWorkItemsRouteHandler{
		StatusMapping: loadRealStatusMapping(t), PerPage: 100, MaxPages: 10, NestedMaxPages: 10,
	}).Collect(
		context.Background(), claim,
		providerfoundation.Credential{Provider: "gitlab", ID: claim.CredentialID},
		glAttributionClient(t, &glAttributionDoer{}), prAttributionNormalizedAt(),
	); err != nil {
		t.Fatal(err)
	}
	return deriver.rows.AIAttributions
}

// TestGitLabPRsRouteAttributionCostsNoExtraRequest pins that the merge request
// attribution rows come out of the list items the unit already fetched, and
// that the fixture exercises every detector input. Equality with the former
// work-items route output is TestPRsRouteAttributionEqualsTheRecordedWorkItemsRouteRows.
func TestGitLabPRsRouteAttributionCostsNoExtraRequest(t *testing.T) {
	batch, prsDoer := glAttributionPRsBatch(t)
	sources, subjects := map[string]bool{}, map[string]bool{}
	for _, row := range attributionEffectRows(t, batch) {
		sources[row.Source] = true
		subjects[row.SubjectID] = true
	}
	for _, source := range []string{"pr_label", "bot_author", "commit_trailer", "branch_name", "pr_body"} {
		if !sources[source] {
			t.Fatalf("fixture never exercises source %s: %v", source, sources)
		}
	}
	if subjects["9"] || !subjects["7"] || !subjects["8"] {
		t.Fatalf("subjects=%v want 7 and 8 only", subjects)
	}
	// Exactly the requests the unit made before attribution existed: the
	// project, the merge request list, and the approvals and notes of each
	// merge request. The attribution rows add none.
	root := "/api/v4/projects/123"
	wantRequests := []string{root, root + "/merge_requests"}
	for _, iid := range []string{"7", "8", "9"} {
		wantRequests = append(wantRequests,
			root+"/merge_requests/"+iid+"/approvals", root+"/merge_requests/"+iid+"/notes")
	}
	if !reflect.DeepEqual(prsDoer.requests, wantRequests) {
		t.Fatalf("gitlab prs requests=%q want %q", prsDoer.requests, wantRequests)
	}
}

// TestPRAttributionSinkAssertsTheLeaseBeforeWriting pins that the new
// destination is fenced by the unit lease like every other destination of the
// unit: a lost lease stops the write, with rows or without. The readback fence
// needs a connection and is pinned in the integration test.
func TestPRAttributionSinkAssertsTheLeaseBeforeWriting(t *testing.T) {
	t.Parallel()
	batch, _ := prAttributionPRsEffect(t)
	sink := GitHubPullRequestSocialClickHouseEffects{
		Lease: providerfoundation.LeaseGuardFunc(func(context.Context) error { return providerfoundation.ErrLeaseLost }),
	}
	claim := prAttributionClaim("github", "prs")
	if err := sink.WriteEffect(context.Background(), claim, batch.Effects[1]); !errors.Is(err, providerfoundation.ErrLeaseLost) {
		t.Fatalf("write with a lost lease: err=%v", err)
	}
	empty, err := effectBatchFromValues("ai_attribution", EffectReadbackRequired, []githubAIAttributionRow{})
	if err != nil {
		t.Fatal(err)
	}
	if err := sink.WriteEffect(context.Background(), claim, empty); !errors.Is(err, providerfoundation.ErrLeaseLost) {
		t.Fatalf("empty write with a lost lease: err=%v", err)
	}
}

// recordedWorkItemsRouteRows are the ai_attribution rows the work-items routes
// emitted for the same fixtures before the prs unit became the only writer,
// recorded from the real routes at that commit
// (testdata/prs_ai_attribution_work_items_route_recorded.json). The prs route
// must reproduce them row for row: same key, same content.
func recordedWorkItemsRouteRows(t *testing.T, provider string) []githubAIAttributionRow {
	t.Helper()
	raw, err := os.ReadFile("testdata/prs_ai_attribution_work_items_route_recorded.json")
	if err != nil {
		t.Fatal(err)
	}
	var recorded map[string][]githubAIAttributionRow
	if err := json.Unmarshal(raw, &recorded); err != nil {
		t.Fatal(err)
	}
	rows := recorded[provider]
	if len(rows) == 0 {
		t.Fatalf("recording has no %s rows", provider)
	}
	return sortedAttributions(rows)
}

// githubWorkItemsRouteAttributionRows runs the REAL github work-items route
// (collector, normalizers, route) over the same pull request responses and
// returns the rows of its ai_attribution effect.
func githubWorkItemsRouteAttributionRows(t *testing.T) []githubAIAttributionRow {
	t.Helper()
	claim := githubWorkItemsRESTClaim()
	claim.OrgID = prAttributionOrgID
	claim.DatasetOptions["fetch_milestones"] = false
	social := `{"data":{"repository":{"pr0":{"number":54,"comments":{"nodes":[],"pageInfo":{"hasNextPage":false,"endCursor":null}},"timelineItems":{"nodes":[],"pageInfo":{"hasNextPage":false,"endCursor":null}}},"pr1":{"number":53,"comments":{"nodes":[],"pageInfo":{"hasNextPage":false,"endCursor":null}},"timelineItems":{"nodes":[],"pageInfo":{"hasNextPage":false,"endCursor":null}}},"pr2":{"number":52,"comments":{"nodes":[],"pageInfo":{"hasNextPage":false,"endCursor":null}},"timelineItems":{"nodes":[],"pageInfo":{"hasNextPage":false,"endCursor":null}}}}}}`
	doer := &githubWorkItemsRouteDoer{
		t: t,
		rest: &githubWorkItemsRESTDoer{t: t, replies: map[string][]githubWorkItemsRESTReply{
			"/repos/acme/api":          {{body: prAttributionRepo}},
			"/repos/acme/api/issues":   {{body: `[]`}},
			"/repos/acme/api/pulls":    {{body: prAttributionList}},
			"/repos/acme/api/pulls/52": {{body: prAttributionDetail52}},
			"/repos/acme/api/pulls/53": {{body: prAttributionDetail53}},
			"/repos/acme/api/pulls/54": {{body: prAttributionDetail54}},
		}},
		graphqlReplies: []string{social},
	}
	handler := GitHubWorkItemsRouteHandler{
		Projects:                      &githubWorkItemsRouteProjectPolicy{},
		ProjectMembershipSnapshotDiff: githubProjectV2NoopSnapshotDiffReader{},
	}
	batch, err := handler.Collect(
		context.Background(), claim,
		providerfoundation.Credential{Provider: "github", ID: claim.CredentialID},
		gitHubPullRequestClient(t, fakehttp.Client(doer), "https://api.github.com"),
		prAttributionNormalizedAt(),
	)
	if err != nil {
		t.Fatal(err)
	}
	// The pull requests must have been collected, or an empty answer proves
	// nothing about attribution.
	pulls := 0
	for _, effect := range batch.Effects {
		if effect.Destination == "work_items" {
			pulls = len(effect.Rows)
		}
	}
	if pulls != 3 {
		t.Fatalf("work-items route collected %d pull requests, want 3", pulls)
	}
	return attributionEffectRows(t, batch)
}

// TestWorkItemsRoutesWriteNoPullRequestAttribution pins the one-writer rule:
// the work-items routes see the same pull requests and merge requests as the
// prs unit, and emit no pull-request ai_attribution row, so no key has two
// writers.
func TestWorkItemsRoutesWriteNoPullRequestAttribution(t *testing.T) {
	if rows := githubWorkItemsRouteAttributionRows(t); len(rows) != 0 {
		t.Fatalf("github work-items route emitted %d pull-request attribution rows", len(rows))
	}
	if rows := glAttributionWorkItemsRows(t); len(rows) != 0 {
		t.Fatalf("gitlab work-items route emitted %d merge-request attribution rows", len(rows))
	}
}

func TestPRsRouteAttributionEqualsTheRecordedWorkItemsRouteRows(t *testing.T) {
	for provider, collect := range map[string]func(*testing.T) []githubAIAttributionRow{
		"github": func(t *testing.T) []githubAIAttributionRow {
			batch, _ := prAttributionPRsEffect(t)
			return attributionEffectRows(t, batch)
		},
		"gitlab": func(t *testing.T) []githubAIAttributionRow {
			batch, _ := glAttributionPRsBatch(t)
			return attributionEffectRows(t, batch)
		},
	} {
		provider, collect := provider, collect
		t.Run(provider, func(t *testing.T) {
			got, _ := json.Marshal(sortedAttributions(collect(t)))
			want, _ := json.Marshal(recordedWorkItemsRouteRows(t, provider))
			if string(got) != string(want) {
				t.Fatalf("prs route rows differ from the recorded work-items route rows\nprs:      %s\nrecorded: %s", got, want)
			}
		})
	}
}
