package numerical

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// wellbeingExpectedRow decodes one golden "expected" row. It carries its own
// snake_case json tags rather than reusing TeamWellbeingMetric directly:
// TeamWellbeingMetric has no json tags (it is not a wire type), so decoding
// the golden's snake_case keys straight into it would silently leave every
// field zero instead of failing loudly.
type wellbeingExpectedRow struct {
	TeamID                 string  `json:"team_id"`
	TeamName               string  `json:"team_name"`
	CommitsCount           int     `json:"commits_count"`
	AfterHoursCommitsCount int     `json:"after_hours_commits_count"`
	WeekendCommitsCount    int     `json:"weekend_commits_count"`
	AfterHoursCommitRatio  float64 `json:"after_hours_commit_ratio"`
	WeekendCommitRatio     float64 `json:"weekend_commit_ratio"`
}

func (row wellbeingExpectedRow) asMetric() TeamWellbeingMetric {
	return TeamWellbeingMetric(row)
}

type wellbeingGoldenFixture struct {
	TeamWellbeing []struct {
		Label string `json:"label"`
		Day   string `json:"day"`
		Rows  []struct {
			RepoID        string  `json:"repo_id"`
			CommitHash    string  `json:"commit_hash"`
			AuthorEmail   *string `json:"author_email"`
			AuthorName    *string `json:"author_name"`
			CommitterWhen string  `json:"committer_when"`
		} `json:"rows"`
		RepoNamesByID      map[string]string      `json:"repo_names_by_id"`
		BusinessTimezone   string                 `json:"business_timezone"`
		BusinessHoursStart int                    `json:"business_hours_start"`
		BusinessHoursEnd   int                    `json:"business_hours_end"`
		Expected           []wellbeingExpectedRow `json:"expected"`
	} `json:"team_wellbeing"`
}

// wellbeingGoldenPath is the checked-in fixture generated by
// tests/fixtures/generate_daily_wellbeing_python_golden.py.
func wellbeingGoldenPath() string {
	return filepath.Join("..", "..", "..", "..", "tests", "fixtures", "daily_wellbeing_python_golden.json")
}

// dedupCommits mirrors compute_team_wellbeing_metrics_daily's in-memory
// dedup by (repo_id, commit_hash), keeping the FIRST row seen -- the fixture
// carries a case that deliberately exercises this (duplicate_commit_hash_dedup).
func dedupCommits(t *testing.T, rows []struct {
	RepoID        string  `json:"repo_id"`
	CommitHash    string  `json:"commit_hash"`
	AuthorEmail   *string `json:"author_email"`
	AuthorName    *string `json:"author_name"`
	CommitterWhen string  `json:"committer_when"`
}) []Commit {
	t.Helper()
	seen := make(map[string]struct{}, len(rows))
	commits := make([]Commit, 0, len(rows))
	for _, row := range rows {
		key := row.RepoID + "\x1f" + row.CommitHash
		if _, duplicate := seen[key]; duplicate {
			continue
		}
		seen[key] = struct{}{}
		when, err := time.Parse(time.RFC3339, row.CommitterWhen)
		if err != nil {
			t.Fatalf("parse committer_when %q: %v", row.CommitterWhen, err)
		}
		commits = append(commits, Commit{
			RepoID:        row.RepoID,
			AuthorEmail:   derefOrEmpty(row.AuthorEmail),
			AuthorName:    derefOrEmpty(row.AuthorName),
			CommitterWhen: when,
		})
	}
	return commits
}

func derefOrEmpty(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

// TestTeamWellbeingGoldenParity proves Go's ComputeTeamWellbeing reproduces
// the frozen Python golden (CHAOS-4276). The golden's repo-pattern and
// membership resolvers are baked into fixed team fixtures in the generator;
// this test rebuilds equivalent resolvers directly rather than importing the
// daily package's ClickHouse-backed loaders, keeping this package free of a
// daily-package (and therefore ClickHouse driver) dependency.
func TestTeamWellbeingGoldenParity(t *testing.T) {
	data, err := os.ReadFile(wellbeingGoldenPath())
	if err != nil {
		t.Fatal(err)
	}
	var fixture wellbeingGoldenFixture
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if len(fixture.TeamWellbeing) == 0 {
		t.Fatal("golden fixture has no team_wellbeing cases")
	}

	repoResolver := goldenRepoPatternResolver()
	memberResolver := goldenMemberResolver()

	for _, testCase := range fixture.TeamWellbeing {
		t.Run(testCase.Label, func(t *testing.T) {
			day, err := time.Parse("2006-01-02", testCase.Day)
			if err != nil {
				t.Fatal(err)
			}
			tz, err := time.LoadLocation(testCase.BusinessTimezone)
			if err != nil {
				t.Fatal(err)
			}
			commits := dedupCommits(t, testCase.Rows)
			got := ComputeTeamWellbeing(
				day, commits, testCase.RepoNamesByID,
				repoResolver, memberResolver, tz,
				testCase.BusinessHoursStart, testCase.BusinessHoursEnd,
			)
			want := make([]TeamWellbeingMetric, len(testCase.Expected))
			for index, row := range testCase.Expected {
				want[index] = row.asMetric()
			}
			if !equalJSON(got, want) {
				t.Fatalf("case %s:\n got=%#v\nwant=%#v", testCase.Label, got, want)
			}
		})
	}
}

// goldenRepoPatternResolver mirrors the generator's teams_data exact +
// wildcard repo_patterns (org/service-a -> team-repo, org/wild-* -> team-wild).
type goldenRepoResolverStub struct{}

func (goldenRepoResolverStub) ResolveRepo(repoName string) (string, string) {
	switch repoName {
	case "":
		return "", ""
	case "org/service-a":
		return "team-repo", "Repo Team"
	default:
		if len(repoName) >= len("org/wild-") && repoName[:len("org/wild-")] == "org/wild-" {
			return "team-wild", "Wildcard Team"
		}
		return "", ""
	}
}

func goldenRepoPatternResolver() RepoTeamResolver { return goldenRepoResolverStub{} }

// goldenMemberResolver mirrors the generator's TeamResolver membership map.
type goldenMemberResolverStub struct{}

func (goldenMemberResolverStub) ResolveMember(identity string) (string, string) {
	switch identity {
	case "dev@example.com", "Display Name":
		return "team-member", "Member Team"
	default:
		return "", ""
	}
}

func goldenMemberResolver() MemberTeamResolver { return goldenMemberResolverStub{} }
