package filehotspots

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"

	"github.com/full-chaos/dev-health-ops/internal/jobs/metrics/daily/repouser"
)

// See internal/jobs/metrics/numerical/fma_golden_test.go for the full
// explanation of this fixture and CHAOS-4818. hotspot_score =
// alpha*log1p(churn) + beta*contributors + gamma*commits is the same
// unguarded weighted-sum shape as ReleaseImpactConfidence; this exercises
// ComputeFileHotspots end-to-end (the formula has no standalone helper)
// against fma_hotspot_score_golden.json's rows, originally generated by
// IMPORTING and calling the real compute_file_hotspots over an equivalent
// synthetic window.
//
// CHAOS-5234/CHAOS-3092 (2026-09-06): this case used to live inside the
// shared fma_golden.json alongside release_confidence/percentile_float/
// percentile_int, which are all STILL live-Python-backed. compute_file_hotspots
// was deleted (file_hotspots is fully native now, no straddle), so this case
// was split out into its own frozen file -- byte-identical payload, extracted
// verbatim, nothing recomputed -- rather than either (a) leaving a dead key in
// fma_golden.json that generate_fma_golden.py can no longer reproduce (which
// broke internal/jobs/workgraph/units's generic
// TestEveryDiscoverableCorpusStillMatchesLivePython, a whole-document
// byte-for-byte auto-discovery guard with no per-key exception mechanism), or
// (b) teaching that shared, actively-maintained guard a one-off exception.
// There is no generator for this file any more -- it is frozen exactly the
// way tests/fixtures/file_hotspots_python_golden.json and its CHAOS-4277
// siblings are (their own generators were deleted whole-file in the same PR):
// this Go test is now the only regression guard, per chris's ruling that the
// frozen golden + the Go bit-exact test are the ongoing contract once Python
// is out of the loop.
func TestComputeFileHotspotsScoreMatchesLivePythonBitExact(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "..", "tests", "fixtures", "fma_hotspot_score_golden.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		HotspotScore []struct {
			Churn        int    `json:"churn"`
			Contributors int    `json:"contributors"`
			CommitsCount int    `json:"commits_count"`
			ExpectedBits string `json:"expected_bits"`
		} `json:"hotspot_score"`
	}
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if len(fixture.HotspotScore) == 0 {
		t.Fatal("fixture has no hotspot_score cases")
	}

	repoID := uuid.MustParse("00000000-0000-4000-8000-00000000000a")
	day := time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC)
	computedAt := time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC)

	mismatches := 0
	for _, testCase := range fixture.HotspotScore {
		windowStats := syntheticWindowStats(repoID, testCase.Churn, testCase.Contributors, testCase.CommitsCount)
		records := ComputeFileHotspots(repoID, windowStats)
		if len(records) != 1 {
			t.Fatalf("churn=%d contributors=%d commits=%d: got %d records, want 1", testCase.Churn, testCase.Contributors, testCase.CommitsCount, len(records))
		}
		record := records[0]
		if record.Churn != testCase.Churn || record.Contributors != testCase.Contributors || record.CommitsCount != testCase.CommitsCount {
			t.Fatalf("aggregation mismatch: got churn=%d contributors=%d commits=%d, want churn=%d contributors=%d commits=%d",
				record.Churn, record.Contributors, record.CommitsCount, testCase.Churn, testCase.Contributors, testCase.CommitsCount)
		}
		wantBits, err := strconv.ParseUint(strings.TrimPrefix(testCase.ExpectedBits, "0x"), 16, 64)
		if err != nil {
			t.Fatalf("parse expected_bits %q: %v", testCase.ExpectedBits, err)
		}
		gotBits := math.Float64bits(record.HotspotScore)
		if gotBits != wantBits {
			mismatches++
			if mismatches <= 10 {
				t.Errorf("hotspotScore(churn=%d, contributors=%d, commits=%d) = %v (bits %#x), want bits %#x (%v)",
					testCase.Churn, testCase.Contributors, testCase.CommitsCount,
					record.HotspotScore, gotBits, wantBits, math.Float64frombits(wantBits))
			}
		}
	}
	if mismatches > 10 {
		t.Errorf("... and %d more mismatches (total %d of %d cases)", mismatches-10, mismatches, len(fixture.HotspotScore))
	}
	_ = day
	_ = computedAt
}

// syntheticWindowStats mirrors generate_fma_golden.py's
// _synthetic_window_stats: one file, exactly `contributors` distinct authors
// and `commitsCount` distinct commits, with the full churn attributed to the
// first row (additions only) -- so ComputeFileHotspots's own aggregation
// reproduces exactly (churn, contributors, commitsCount).
func syntheticWindowStats(repoID uuid.UUID, churn, contributors, commitsCount int) []repouser.CommitStatRow {
	n := contributors
	if commitsCount > n {
		n = commitsCount
	}
	if n < 1 {
		n = 1
	}
	when := time.Date(2026, 9, 1, 0, 0, 0, 0, time.UTC)
	rows := make([]repouser.CommitStatRow, 0, n)
	for i := 0; i < n; i++ {
		additions := 0
		if i == 0 {
			additions = churn
		}
		rows = append(rows, repouser.CommitStatRow{
			RepoID:        repoID,
			CommitHash:    "c" + itoaFH(i%commitsCount),
			AuthorEmail:   "a" + itoaFH(i%contributors) + "@example.com",
			CommitterWhen: when,
			FilePath:      "src/hot.py",
			Additions:     additions,
			Deletions:     0,
		})
	}
	return rows
}

func itoaFH(value int) string {
	if value == 0 {
		return "0"
	}
	digits := ""
	for value > 0 {
		digits = string(rune('0'+value%10)) + digits
		value /= 10
	}
	return digits
}
