package filehotspots

import (
	"encoding/json"
	"math"
	"math/rand"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/google/uuid"

	"github.com/full-chaos/dev-health-ops/internal/jobs/metrics/daily/repouser"
)

// TestComputeFileRiskHotspotsOrderInvariantMatchesLivePythonBitExact is the
// CHAOS-4863 regression test: ComputeFileRiskHotspots' risk_score must not
// depend on the order its inputs are iterated in.
//
// tests/fixtures/risk_hotspots_order_golden.json was generated by running
// each case through CROSS_PROCESS_CONFIRMATIONS separate live `python3`
// invocations (fresh hash seed each time), each fed the SAME churn/
// complexity content through a DIFFERENT window_stats row permutation --
// the generator itself raises if Python's own output ever disagreed across
// those runs (see generate_risk_hotspots_order_golden.py's module doc
// comment for why: compute_file_risk_hotspots builds its file list from a
// Python SET, not a dict, so there is no fixed "Python's order" to
// replicate -- what this proves instead is that Python's compensated sum()
// is empirically order-invariant for this corpus, and that Go's own fix
// (sort the union of paths lexicographically, a canonical order
// independent of any source ordering) agrees with it).
//
// This test mirrors that discipline on the Go side: for each case, it
// builds windowStats/complexityMap in SEVERAL DIFFERENT orders (a fresh
// random permutation per repetition, on top of Go's own map iteration
// randomization) and asserts every repetition produces the bit-identical
// risk_score AND matches the frozen Python value -- proving the fix is
// order-invariant under both Go's and the input's own randomization, not
// merely "usually passes".
func TestComputeFileRiskHotspotsOrderInvariantMatchesLivePythonBitExact(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "..", "tests", "fixtures", "risk_hotspots_order_golden.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		Cases []struct {
			Case         string            `json:"case"`
			Churns       map[string]int    `json:"churns"`
			ExpectedBits map[string]string `json:"expected_bits"`
		} `json:"cases"`
	}
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if len(fixture.Cases) == 0 {
		t.Fatal("fixture has no cases")
	}

	repoID := uuid.MustParse("00000000-0000-4000-8000-00000000000d")
	const repetitionsPerCase = 8

	mismatches := 0
	for _, testCase := range fixture.Cases {
		paths := make([]string, 0, len(testCase.Churns))
		for path := range testCase.Churns {
			paths = append(paths, path)
		}

		rng := rand.New(rand.NewSource(int64(len(paths)) + int64(hashString(testCase.Case))))
		var firstBitsByPath map[string]uint64
		for rep := 0; rep < repetitionsPerCase; rep++ {
			order := append([]string(nil), paths...)
			rng.Shuffle(len(order), func(i, j int) { order[i], order[j] = order[j], order[i] })

			windowStats := make([]repouser.CommitStatRow, 0, len(order))
			complexityMap := make(map[string]ComplexitySnapshot, len(order))
			for i, path := range order {
				windowStats = append(windowStats, repouser.CommitStatRow{
					RepoID:      repoID,
					CommitHash:  "c" + strconv.Itoa(i),
					AuthorEmail: "a" + strconv.Itoa(i) + "@example.com",
					FilePath:    path,
					Additions:   testCase.Churns[path],
				})
				complexityMap[path] = ComplexitySnapshot{CyclomaticTotal: 5, CyclomaticAvg: 1.0}
			}

			records := ComputeFileRiskHotspots(repoID, windowStats, complexityMap, nil)
			gotBitsByPath := make(map[string]uint64, len(records))
			for _, r := range records {
				gotBitsByPath[r.FilePath] = math.Float64bits(r.RiskScore)
			}

			if rep == 0 {
				firstBitsByPath = gotBitsByPath
			} else {
				for _, path := range paths {
					if gotBitsByPath[path] != firstBitsByPath[path] {
						t.Errorf("case %s: risk_score(%s) varied across Go input permutations: rep0=%#x rep%d=%#x",
							testCase.Case, path, firstBitsByPath[path], rep, gotBitsByPath[path])
					}
				}
			}
		}

		for _, path := range paths {
			wantHex, ok := testCase.ExpectedBits[path]
			if !ok {
				t.Fatalf("case %s: no expected_bits for %s", testCase.Case, path)
			}
			wantBits, err := strconv.ParseUint(strings.TrimPrefix(wantHex, "0x"), 16, 64)
			if err != nil {
				t.Fatalf("case %s: parse expected_bits %q: %v", testCase.Case, wantHex, err)
			}
			gotBits := firstBitsByPath[path]
			if gotBits != wantBits {
				mismatches++
				if mismatches <= 10 {
					t.Errorf("case %s: risk_score(%s) = bits %#x, want bits %#x (%v)",
						testCase.Case, path, gotBits, wantBits, math.Float64frombits(wantBits))
				}
			}
		}
	}
	if mismatches > 10 {
		t.Errorf("... and %d more mismatches (total %d)", mismatches-10, mismatches)
	}
}

// hashString is a tiny deterministic (non-cryptographic) string hash, used
// only to seed this test's per-case PRNG so different cases don't all
// shuffle identically -- not a production algorithm, no relation to
// Python's hash randomization discussed in this test's doc comment.
func hashString(s string) uint64 {
	var h uint64 = 14695981039346656037 // FNV-1a offset basis
	for i := 0; i < len(s); i++ {
		h ^= uint64(s[i])
		h *= 1099511628211 // FNV-1a prime
	}
	return h
}
