#!/usr/bin/env python3
"""Render the generated tables in docs/go-migration-matrix.md.

Same shape as ``scripts/gen_python_go_ledger_docs.py`` (CHAOS-4433): the
mechanical facts (which datasets/families currently exist) are read straight
from their producers below; curated columns (citation/call-site text,
route-transport prose, ticket) are hand-authored in the ``*_LEDGER`` dicts in
this file. ``_consistency_guard`` refuses to render -- raises ``SystemExit``
-- the moment a family/dataset appears in a live producer with no curated row,
or a curated row no longer matches a live producer. That is what makes
``tests/docs/test_go_migration_matrix_drift.py`` fail loudly on drift instead
of the page quietly going stale (the exact failure mode CHAOS-4433 exists to
prevent, now extended past the sync/kind/route/worker-file surface that ledger
covers to the metrics-family and workgraph/investment surface this page adds).

Section 1 (provider sync) needs NO curated ledger at all: it is rendered
directly from ``contracts/provider-matrix/v1/matrix.json``, the frozen,
CI-verified provider x dataset parity contract (CUT-08) both
``internal/providersync/capability_matrix.go`` and
``src/dev_health_ops/workers/provider_unit_route.py`` already drift-test
against (``tests/workers/test_provider_matrix_contract.py``). There is
nothing for this generator to curate there -- it would just be re-typing an
already-authoritative, already-guarded source. chris, 2026-09-04 (via
team-lead): "there's already a matrix.json" -- do not write a parallel
hand-maintained table for sync.

Sections 2/3 (daily/remaining metrics families) read ``families.json``'s
family-name sets mechanically for coverage, but the EXECUTOR VERDICT itself
comes from ``contracts/native-families/v1/native-families.json``
(``load_native_families_artifact``) -- a Go-emitted, AST-derived artifact
``cmd/dev-health-worker/native_families_artifact_test.go`` regenerates
directly from ``daily.go``'s actual registration wiring (its own
``dailyNativeFamilyRegistrations`` map assignments for §2, and the
``metrics.remaining.*`` switch's ``addRemainingWorker`` calls for §3).
Neither ``families.json``'s own ``port``/``route`` fields nor a curated
Python dict may be the executor source of truth here (team-lead's 2026-09-04
ruling, after the earlier version of this generator used exactly that and
was correctly rejected as the same "told done" drift class CHAOS-4433
exists to prevent). ``DAILY_CITATION_LEDGER``/``REMAINING_EXECUTOR_LEDGER``
below carry ONLY citation/route/ticket prose now, never the executor value.

Section 4 (workgraph/investment) has no families.json equivalent at all
(``internal/jobs/families.json`` does not exist) -- WORKGRAPH_INVESTMENT_LEDGER
is the sole source, entirely hand-maintained, with no live producer to
drift-guard against mechanically. Adding a machine-readable registry for these
5 kinds is proposed as a follow-up ticket, not done in this change.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC_PATH = ROOT / "docs" / "go-migration-matrix.md"
MATRIX_JSON = ROOT / "contracts" / "provider-matrix" / "v1" / "matrix.json"
DAILY_FAMILIES_JSON = ROOT / "internal" / "jobs" / "metrics" / "daily" / "families.json"
REMAINING_FAMILIES_JSON = (
    ROOT / "internal" / "jobs" / "metrics" / "remaining" / "families.json"
)
NATIVE_FAMILIES_ARTIFACT = (
    ROOT / "contracts" / "native-families" / "v1" / "native-families.json"
)

PROVIDER_BEGIN = "<!-- BEGIN GENERATED PROVIDER SYNC MATRIX -->"
PROVIDER_END = "<!-- END GENERATED PROVIDER SYNC MATRIX -->"
DAILY_BEGIN = "<!-- BEGIN GENERATED DAILY METRICS MATRIX -->"
DAILY_END = "<!-- END GENERATED DAILY METRICS MATRIX -->"
REMAINING_BEGIN = "<!-- BEGIN GENERATED REMAINING METRICS MATRIX -->"
REMAINING_END = "<!-- END GENERATED REMAINING METRICS MATRIX -->"
WORKGRAPH_BEGIN = "<!-- BEGIN GENERATED WORKGRAPH INVESTMENT MATRIX -->"
WORKGRAPH_END = "<!-- END GENERATED WORKGRAPH INVESTMENT MATRIX -->"

# matrix.json's go_executor values, translated to this page's Executor legend.
# A value not in this dict is a genuinely new state the legend hasn't seen
# yet -- render_provider_sync_block refuses rather than guessing.
GO_EXECUTOR_TRANSLATION = {
    "native_go": "NATIVE",
}


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def load_matrix_pairs() -> list[dict]:
    return _load_json(MATRIX_JSON)["pairs"]


def load_daily_families() -> list[dict]:
    return _load_json(DAILY_FAMILIES_JSON)["families"]


def load_remaining_families() -> list[dict]:
    return _load_json(REMAINING_FAMILIES_JSON)["families"]


def load_native_families_artifact() -> dict:
    """The Go-emitted, AST-derived source of truth for §2/§3 executor verdicts.

    Regenerated by cmd/dev-health-worker/native_families_artifact_test.go
    (`UPDATE_NATIVE_FAMILIES_ARTIFACT=1 go test ./cmd/dev-health-worker/... -run
    TestNativeFamiliesArtifactUpToDate`) directly from daily.go's registration
    wiring -- no curated Python dict may substitute for this per team-lead's
    2026-09-04 ruling.
    """
    return _load_json(NATIVE_FAMILIES_ARTIFACT)


def _consistency_guard(
    label: str, live: set[str], curated: set[str], hint: str
) -> None:
    missing = live - curated
    extra = curated - live
    if missing:
        raise SystemExit(
            f"gen_go_migration_matrix_docs: {label} {sorted(missing)} exist in the live "
            f"producer but have no curated row in scripts/gen_go_migration_matrix_docs.py. {hint}"
        )
    if extra:
        raise SystemExit(
            f"gen_go_migration_matrix_docs: {label} {sorted(extra)} have a curated row but no "
            f"longer exist in the live producer -- remove the stale row (or, if renamed, update "
            f"it) in scripts/gen_go_migration_matrix_docs.py. {hint}"
        )


# ---------------------------------------------------------------------------
# CURATED: §2 citation/ticket text only, internal/jobs/metrics/daily/
# families.json (24 families as of e3e2e77c48a9e4902e48d962b8292f1b408bf47b).
# The Executor verdict comes from contracts/native-families/v1/native-families.json
# (load_native_families_artifact), NOT from families.json's own `port` field --
# see module docstring.
# ---------------------------------------------------------------------------
DAILY_CITATION_LEDGER: dict[str, dict[str, str]] = {
    "repo_user_commit": {
        "citation": "Go: `internal/jobs/metrics/daily/repouser/` (`RepoUserCommitExecutor`)",
        "ticket": "CHAOS-4275 (Done)",
    },
    "team_wellbeing": {
        "citation": "Go: `internal/jobs/metrics/daily/wellbeing_native_executor.go`",
        "ticket": "CHAOS-4276 (Done)",
    },
    "file_hotspots": {
        "citation": "Go: `internal/jobs/metrics/daily/file_hotspots_native_executor.go`",
        "ticket": "CHAOS-4277 (Done)",
    },
    "file_risk_hotspots": {
        "citation": "Go: `internal/jobs/metrics/daily/` (`FileRiskHotspotsExecutor`, `daily.go`)",
        "ticket": "CHAOS-4277 (Done)",
    },
    "work_item": {
        "citation": "Go: `internal/jobs/metrics/daily/work_item_native_executor.go` -- post_bridge, reuses `internal/jobs/metrics/workitemmetrics`'s pure compute (shared with the providersync sync-time deriver); ports `compute_work_items.py:1075 compute_work_item_metrics_daily`",
        "ticket": "CHAOS-4283",
    },
    "work_item_estimate": {
        "citation": "Go: `internal/jobs/metrics/daily/work_item_estimate_native_executor.go` -- post_bridge, same shared compute; ports `compute_work_items.py:1425 compute_estimate_coverage_metrics_daily`",
        "ticket": "CHAOS-4283",
    },
    "work_item_attribution": {
        "citation": "Python: `compute_work_items.py:1189 compute_work_item_team_attributions` (full daily compute -- distinct from §3's native staleness-only backstop of the same table)",
        "ticket": "CHAOS-4283",
    },
    "work_item_state": {
        "citation": "Go: `internal/jobs/metrics/daily/work_item_state_native_executor.go` -- post_bridge, runs AFTER the Python bridge (reads `work_item_team_attributions`, itself still Python-written)",
        "ticket": "CHAOS-4278 (Done)",
    },
    "review_edges": {
        "citation": "Python: `reviews.py:22 compute_review_edges_daily`",
        "ticket": "CHAOS-4279",
    },
    "cicd": {
        "citation": "Go: `internal/jobs/metrics/daily/cicd/`",
        "ticket": "CHAOS-4292 (Done)",
    },
    "testops_pipeline": {
        "citation": "Python: `compute_testops.py:105 compute_pipeline_metrics_daily`",
        "ticket": "CHAOS-4284",
    },
    "testops_test": {
        "citation": "Python: `compute_testops.py:207 compute_test_metrics_daily`",
        "ticket": "CHAOS-4284",
    },
    "testops_coverage": {
        "citation": "Python: `compute_testops.py:355 compute_coverage_metrics_daily`",
        "ticket": "CHAOS-4284",
    },
    "deploy": {
        "citation": "Go: `internal/jobs/metrics/daily/deploy_native_executor.go`",
        "ticket": "CHAOS-4293 (Done)",
    },
    "incident": {
        "citation": "Go: `internal/jobs/metrics/daily/incident_native_executor.go` (Python bridge was permanently zero-yield for this family, CHAOS-4269)",
        "ticket": "CHAOS-4295 (Done)",
    },
    "ai_governance": {
        "citation": "Python: `audit/ai_governance/loaders.py:113 build_governance_rows_for_day`",
        "ticket": "CHAOS-4285",
    },
    "ai_impact": {
        "citation": "Python: `ai_impact.py:312 compute_ai_impact_metrics_daily`",
        "ticket": "CHAOS-4280",
    },
    "ai_workflow": {
        "citation": "Python: `work_graph/extractors/ai_workflow.py:212 _extract_ai_workflow_for_day`",
        "ticket": "CHAOS-4286",
    },
    "work_graph_edges": {
        "citation": "Python: `ai_workflow.py extract_review_deployment_incident_edges`",
        "ticket": "CHAOS-4286",
    },
    "compounding_risk": {
        # CHAOS-4287: the ticket and this citation both said :502, which is
        # inside _repo_to_team_map_for_compounding_risk, not the writer. The
        # writer is :568 (REPO scope, post_bridge). TEAM scope is now its own
        # entry below, "compounding_risk_team" (CHAOS-5084) -- see that row
        # and internal/jobs/metrics/daily/families.json's phase_notes for both.
        "citation": "Python: `job_daily.py:568 _write_compounding_risk_for_day` (repo scope, native)",
        "ticket": "CHAOS-4287",
    },
    "compounding_risk_team": {
        # CHAOS-5084: the TEAM-scope half of compounding_risk, split into its
        # own family entry because it is a SEPARATE finalize-scope writer to
        # the SAME table (compounding_risk_daily) -- see the "compounding_risk"
        # row above and families.json's phase_notes for both.
        "citation": "Python: `job_daily.py:613 _write_compounding_risk_team_rows_for_day` (team scope, now native, finalize scope)",
        "ticket": "CHAOS-5084",
    },
    "team_cognitive_load": {
        "citation": "Python: `team_cognitive_load.py build_team_cognitive_load_rows_for_day` (finalize scope)",
        "ticket": "NONE found (per `.remember/remaining-python-compute-inventory-2026-09-01.md`)",
    },
    "testops_risk": {
        "citation": "Go: `internal/jobs/metrics/daily/testops_risk_native_executor.go`, reuses `internal/jobs/metrics/testops/compute.go`'s pure compute",
        "ticket": "CHAOS-4294 (Done)",
    },
    "benchmarking": {
        "citation": "Python: `benchmarking/runner.py:259 run_benchmarking_for_day`",
        "ticket": "CHAOS-4288",
    },
    "ic_finalize": {
        "citation": "Python: `compute_ic.py` (`compute_ic_metrics_daily`, `compute_ic_landscape_rolling`; finalize scope)",
        "ticket": "CHAOS-4290",
    },
}

# ---------------------------------------------------------------------------
# CURATED: §3 citation/ticket text only, internal/jobs/metrics/remaining/
# families.json (7 families). The Executor verdict itself comes from
# contracts/native-families/v1/native-families.json (load_native_families_artifact),
# NOT from this dict and NOT from the JSON's route field -- team-lead's
# 2026-09-04 ruling: no curated dict may be the source of truth for that.
# ---------------------------------------------------------------------------
REMAINING_EXECUTOR_LEDGER: dict[str, dict[str, str]] = {
    "dora": {
        "citation": "Go: `internal/jobs/metrics/remaining/dora_native.go`, `dora_native_clickhouse.go`",
        "route": "river, native (`daily.go:586-598`)",
        "ticket": "CHAOS-3092 R1 (Done)",
    },
    "capacity": {
        "citation": "Go: `internal/jobs/metrics/remaining/capacity_native.go`, `capacity_native_clickhouse.go`",
        "route": "river, native (`daily.go:571-581`)",
        "ticket": "CUT-20 R2 (Done)",
    },
    "recommendations": {
        "citation": "Go: `internal/jobs/metrics/remaining/recommendations_native.go`",
        "route": "river, native (`daily.go:610-620`)",
        "ticket": "CHAOS-4281/CHAOS-3092 (Done)",
    },
    "membership_backfill": {
        "citation": "Go: `internal/jobs/metrics/remaining/membership_native.go`",
        "route": "river, native (`daily.go:599-609`)",
        "ticket": "CHAOS-4282 (Done)",
    },
    "work_item_attribution": {
        "citation": "Go: `internal/jobs/metrics/remaining/work_item_attribution_native.go` -- CHAOS-3092 PR-B staleness-window backstop, NOT the full daily attribution compute (that's §2's `work_item_attribution` row, still COMPAT-Python)",
        "route": "river, native (`daily.go:625-634`)",
        "ticket": "CHAOS-3092 PR-B (Done)",
    },
    "complexity": {
        "citation": "Python: `metrics_extra.py` -> `job_complexity_db.py run_complexity_db_job`",
        "route": "river, bridge (`daily.go:582-585`, uses `compatibility` directly)",
        "ticket": "CHAOS-4291",
    },
    "release_impact": {
        "citation": "Python: `job_release_impact.py` -> `release_impact.py`",
        "route": "river, bridge (`daily.go:621-624`, uses `compatibility` directly)",
        "ticket": "CHAOS-4296",
    },
}

# ---------------------------------------------------------------------------
# CURATED: §4, no families.json equivalent exists. Entirely hand-maintained;
# see docs/go-migration-matrix.md's "Known gaps" section.
# ---------------------------------------------------------------------------
WORKGRAPH_INVESTMENT_LEDGER: dict[str, dict[str, str]] = {
    "workgraph.build": {
        "executor": "COMPAT-Python (narrow native pre/post-step)",
        "citation": (
            "Go: `internal/jobs/workgraph/prestep.go` (issue-PR edge mapping, runs BEFORE the "
            "bridge) + one `poststep.go` edge type (runs AFTER); Python: `worker_workgraph.py:367 "
            'execute` (LLM categorization -- "Python owns 100% of the compute" per prestep.go\'s '
            "own doc comment)"
        ),
        "route": "bridge -- `addWorkgraphWorker`'s `KindWorkGraphBuild` case still takes the HTTP `executor`",
        "ticket": "CHAOS-4924 (six remaining sub-builders + cutover)",
    },
    "investment.materialize": {
        "executor": "NATIVE",
        "citation": (
            "Go: `internal/jobs/investment/nativeexecutor.go` (implements the same "
            "`workgraph.CompatibilityExecutor` seam the bridge did) -> `materialize.go` "
            "orchestrator -> `chquery` fetch + `materializecomponent.go` assembly + "
            "`categorize` LLM plane + `chwrite` write. Python "
            "`materialize.py:1169-1854 materialize_investments()` is retained but no longer "
            "reached from the worker path (removal is CHAOS-4767)"
        ),
        "route": "river, native -- `addWorkgraphWorker`'s `KindInvestmentMaterialize` case takes `nativeInvestment`",
        "ticket": "CHAOS-4441 (cutover landed)",
    },
    "investment.dispatch": {
        "executor": "PYTHON-ONLY (dead Go shell)",
        "citation": "Go: wired, never invoked (`internal/jobs/workgraph/handler.go`); Python: Celery-only target, itself unreachable",
        "route": "bridge (dead in both directions)",
        "ticket": "CHAOS-4438 (dead-code removal, Backlog)",
    },
    "investment.chunk": {
        "executor": "PYTHON-ONLY (dead Go shell)",
        "citation": "Go: wired, never invoked (`internal/jobs/workgraph/handler.go`); Python: Celery-only target, itself unreachable",
        "route": "bridge (dead in both directions)",
        "ticket": "CHAOS-4438 (dead-code removal, Backlog)",
    },
    "investment.finalize": {
        "executor": "PYTHON-ONLY (dead Go shell)",
        "citation": "Go: wired, never invoked (`internal/jobs/workgraph/handler.go`); Python: Celery-only target, itself unreachable",
        "route": "bridge (dead in both directions)",
        "ticket": "CHAOS-4438 (dead-code removal, Backlog)",
    },
    "recommendations": {
        "executor": "NATIVE",
        "citation": "see §3",
        "route": "river, native",
        "ticket": "CHAOS-4281/CHAOS-3092 (Done)",
    },
    "DORA": {
        "executor": "NATIVE",
        "citation": "see §3",
        "route": "river, native",
        "ticket": "CHAOS-3092 R1 (Done)",
    },
    "cognitive load (team_cognitive_load)": {
        "executor": "COMPAT-Python",
        "citation": "see §2",
        "route": "bridge",
        "ticket": "NONE found",
    },
}


def render_provider_sync_block() -> str:
    pairs = load_matrix_pairs()
    unknown_executors = {p["go_executor"] for p in pairs} - set(GO_EXECUTOR_TRANSLATION)
    if unknown_executors:
        raise SystemExit(
            f"gen_go_migration_matrix_docs: matrix.json has go_executor value(s) "
            f"{sorted(unknown_executors)} not in GO_EXECUTOR_TRANSLATION -- add a legend mapping "
            "for it in scripts/gen_go_migration_matrix_docs.py before rendering."
        )
    lines = [
        PROVIDER_BEGIN,
        "| Provider | Dataset | Executor | Route destinations (tables written) | Route ready | Plannable |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for pair in sorted(pairs, key=lambda p: (p["provider"], p["dataset"])):
        executor = GO_EXECUTOR_TRANSLATION[pair["go_executor"]]
        destinations = ", ".join(f"`{d}`" for d in pair["route_destinations"]) or "--"
        lines.append(
            f"| {pair['provider']} | `{pair['dataset']}` | {executor} | {destinations} | "
            f"{pair['route_ready']} | {pair['plannable']} |"
        )
    lines.append(PROVIDER_END)
    return "\n".join(lines)


def render_daily_metrics_block() -> str:
    families = load_daily_families()
    live_names = {f["name"] for f in families}
    _consistency_guard(
        "daily metrics family(ies)",
        live_names,
        set(DAILY_CITATION_LEDGER),
        "Add a DAILY_CITATION_LEDGER row for it.",
    )
    artifact_daily = load_native_families_artifact()["daily"]
    unknown_artifact_names = set(artifact_daily) - live_names
    if unknown_artifact_names:
        raise SystemExit(
            f"gen_go_migration_matrix_docs: contracts/native-families/v1/native-families.json's "
            f'"daily" section names family(ies) {sorted(unknown_artifact_names)} that no longer '
            "exist in internal/jobs/metrics/daily/families.json -- regenerate the artifact "
            "(UPDATE_NATIVE_FAMILIES_ARTIFACT=1 go test ./cmd/dev-health-worker/... -run "
            "TestNativeFamiliesArtifactUpToDate)."
        )
    lines = [
        DAILY_BEGIN,
        "| Family | Executor | Citation | Ticket |",
        "| --- | --- | --- | --- |",
    ]
    for family in sorted(families, key=lambda f: f["name"]):
        name = family["name"]
        artifact_value = artifact_daily.get(name, "compat")
        executor = "COMPAT-Python" if artifact_value == "compat" else "NATIVE"
        if artifact_value == "post_bridge":
            executor += ", post_bridge"
        row = DAILY_CITATION_LEDGER[name]
        lines.append(f"| {name} | {executor} | {row['citation']} | {row['ticket']} |")
    lines.append(DAILY_END)
    return "\n".join(lines)


def render_remaining_metrics_block() -> str:
    families = load_remaining_families()
    live_names = {f["name"] for f in families}
    _consistency_guard(
        "remaining metrics family(ies)",
        live_names,
        set(REMAINING_EXECUTOR_LEDGER),
        "Add a REMAINING_EXECUTOR_LEDGER row for it (citation/ticket text; the Executor verdict "
        "comes from contracts/native-families/v1/native-families.json, not this dict).",
    )
    artifact_remaining = load_native_families_artifact()["remaining"]
    _consistency_guard(
        "remaining metrics family(ies) in native-families.json",
        set(artifact_remaining),
        live_names,
        "Regenerate the artifact (UPDATE_NATIVE_FAMILIES_ARTIFACT=1 go test "
        "./cmd/dev-health-worker/... -run TestNativeFamiliesArtifactUpToDate).",
    )
    lines = [
        REMAINING_BEGIN,
        "| Family | Executor | Citation | Route transport | Ticket |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name in sorted(REMAINING_EXECUTOR_LEDGER):
        executor = "NATIVE" if artifact_remaining[name] == "native" else "COMPAT-Python"
        if name == "work_item_attribution":
            executor += " (narrow: staleness backstop only)"
        row = REMAINING_EXECUTOR_LEDGER[name]
        lines.append(
            f"| {name} | {executor} | {row['citation']} | {row['route']} | {row['ticket']} |"
        )
    lines.append(REMAINING_END)
    return "\n".join(lines)


# Kinds in the ledger that the native-families artifact also records, and the
# ledger executor prefix each artifact label must agree with. The artifact is
# AST-derived from addWorkgraphWorker's dispatch switch, so it -- not this
# curated dict -- is the authority on native-vs-compat; the ledger keeps the
# prose (citation/route/ticket) the artifact has no room for.
_ARTIFACT_LABEL_TO_LEDGER_PREFIX: dict[str, tuple[str, ...]] = {
    "native": ("NATIVE",),
    "compat": ("COMPAT-Python", "PYTHON-ONLY"),
}


def _assert_ledger_matches_artifact() -> None:
    """Fail loudly when the curated §4 verdict disagrees with the wiring.

    This guard exists because CHAOS-4441 sat marked Done for a day while every
    workgraph/investment kind still dispatched to the Python bridge, and NO
    artifact in the tree could contradict the claim. The artifact now records
    the dispatch switch, so §4's executor column can be checked rather than
    trusted.
    """
    artifact = load_native_families_artifact().get("workgraph")
    if not artifact:
        raise SystemExit(
            "gen_go_migration_matrix_docs: contracts/native-families/v1/native-families.json "
            "has no `workgraph` section -- regenerate it with "
            "UPDATE_NATIVE_FAMILIES_ARTIFACT=1 go test ./cmd/dev-health-worker/... "
            "-run TestNativeFamiliesArtifactUpToDate"
        )
    for kind, label in sorted(artifact.items()):
        row = WORKGRAPH_INVESTMENT_LEDGER.get(kind)
        if row is None:
            raise SystemExit(
                f"gen_go_migration_matrix_docs: native-families artifact records kind {kind!r} "
                f"but WORKGRAPH_INVESTMENT_LEDGER has no entry for it -- add one."
            )
        expected = _ARTIFACT_LABEL_TO_LEDGER_PREFIX[label]
        if not row["executor"].startswith(expected):
            raise SystemExit(
                f"gen_go_migration_matrix_docs: kind {kind!r} is wired as {label!r} in "
                f"addWorkgraphWorker (per the native-families artifact) but the curated ledger "
                f"says {row['executor']!r}. The WIRING is authoritative -- fix the ledger."
            )


def render_workgraph_investment_block() -> str:
    _assert_ledger_matches_artifact()
    lines = [
        WORKGRAPH_BEGIN,
        "| Kind/area | Executor | Citation | Route transport | Ticket |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name in sorted(WORKGRAPH_INVESTMENT_LEDGER):
        row = WORKGRAPH_INVESTMENT_LEDGER[name]
        lines.append(
            f"| {name} | {row['executor']} | {row['citation']} | {row['route']} | {row['ticket']} |"
        )
    lines.append(WORKGRAPH_END)
    return "\n".join(lines)


def _replace_block(
    doc: str, begin: str, end: str, rendered: str, doc_path: Path
) -> str:
    start = doc.find(begin)
    stop = doc.find(end)
    if start == -1 or stop == -1 or stop < start:
        raise SystemExit(
            f"gen_go_migration_matrix_docs: markers {begin}/{end} not found in {doc_path}"
        )
    stop += len(end)
    return f"{doc[:start]}{rendered}{doc[stop:]}"


def update_doc() -> None:
    doc = DOC_PATH.read_text(encoding="utf-8")
    doc = _replace_block(
        doc, PROVIDER_BEGIN, PROVIDER_END, render_provider_sync_block(), DOC_PATH
    )
    doc = _replace_block(
        doc, DAILY_BEGIN, DAILY_END, render_daily_metrics_block(), DOC_PATH
    )
    doc = _replace_block(
        doc, REMAINING_BEGIN, REMAINING_END, render_remaining_metrics_block(), DOC_PATH
    )
    doc = _replace_block(
        doc,
        WORKGRAPH_BEGIN,
        WORKGRAPH_END,
        render_workgraph_investment_block(),
        DOC_PATH,
    )
    DOC_PATH.write_text(doc, encoding="utf-8")


if __name__ == "__main__":
    update_doc()
