"""Generate the investment-taxonomy golden for CHAOS-4441.

IMPORTS the canonical registry -- never restates it. A hand-copied list of 15
subcategories would pass on the day it was written and silently diverge the
first time someone adds one, which is the whole failure this corpus exists to
catch.

WHAT IS ACTUALLY AT RISK HERE
-----------------------------
The registry is two `set[str]` objects. Python set iteration order for strings
depends on PYTHONHASHSEED and therefore VARIES BETWEEN INTERPRETER RUNS. Go maps
are also deliberately randomised. So neither plane has a stable "natural" order,
and any ordered artifact built from these sets must be built from `sorted()` or
it is nondeterministic in BOTH planes independently.

Audited every consumer in the reference tree at the time of writing. Every
order-sensitive use goes through `sorted()`:

    categorization_prompts.py:88   ", ".join(sorted(SUBCATEGORIES))   <- the prompt
    analytics/work_units.py:35-36  tuple(sorted(THEMES)) / sorted(SUBCATEGORIES)
    api/queries/filters.py:120     sorted(THEMES) + sorted(SUBCATEGORIES)
    investment_segments.py:158-160 _normalize_scores(..., sorted(...))

One consumer is order-dependent and survives only by accident --
`api/queries/metrics.py:265-267` does `mappings.setdefault(leaf, ...)` while
iterating SUBCATEGORIES, and setdefault is first-writer-wins. It is safe today
ONLY because all 15 leaf names are distinct. Nothing asserts that. This
generator asserts it below, so the day someone adds a colliding leaf (say
`quality.support` against `operational.support`) the corpus fails here rather
than the API quietly emitting different SQL on different days.

The prompt ordering is the one that reaches this lane's port: prompt text feeds
categorization, and categorization feeds the input_hash that gates LLM spend.

Usage:
    uv run python tests/fixtures/generate_investment_taxonomy_golden.py [--stdout]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from dev_health_ops.investment_taxonomy import (
    SUBCATEGORIES,
    SUBCATEGORY_TO_THEME,
    THEMES,
    theme_of,
)

OUTPUT_PATH = Path(__file__).parent / "investment_taxonomy_python_golden.json"

# Keys theme_of() must map to the empty string rather than raising. The silent
# "" default is the behaviour a Go port is most likely to "improve" into an
# error return, so it is pinned explicitly.
UNKNOWN_KEYS = [
    "",
    "feature_delivery",  # a THEME, not a subcategory -> still ""
    "feature_delivery.",
    ".customer",
    "customer",  # a bare leaf -> ""
    "Feature_Delivery.Customer",  # case differs -> "" (no case folding)
    "feature_delivery.customer ",  # trailing space -> "" (no stripping)
    " feature_delivery.customer",
    "feature_delivery.customer.extra",
    "nonexistent.key",
    "feature_delivery/customer",  # wrong separator
]


def main() -> None:
    leaves = [key.rsplit(".", 1)[-1] for key in SUBCATEGORIES]
    if len(leaves) != len(set(leaves)):
        duplicates = sorted({leaf for leaf in leaves if leaves.count(leaf) > 1})
        raise SystemExit(
            "Subcategory LEAF names are no longer unique: "
            f"{duplicates}. api/queries/metrics.py:265-267 uses "
            "mappings.setdefault(leaf, ...) while iterating a set, which is "
            "first-writer-wins over a PYTHONHASHSEED-dependent order. With a "
            "collision, canonical_investment_theme_sql() emits different SQL on "
            "different interpreter runs. Fix that before regenerating."
        )

    # Every subcategory must agree with its own prefix, and with the derived map.
    for key in sorted(SUBCATEGORIES):
        prefix = key.split(".", 1)[0]
        assert prefix in THEMES, f"{key} has a prefix that is not a theme"
        assert SUBCATEGORY_TO_THEME[key] == prefix
        assert theme_of(key) == prefix

    payload = {
        "_comment": (
            "Generated by tests/fixtures/generate_investment_taxonomy_golden.py. "
            "Do not hand-edit."
        ),
        "_policy": (
            "THEMES and SUBCATEGORIES are Python sets, so their iteration order "
            "varies with PYTHONHASHSEED. Every ordered artifact in the reference "
            "is built with sorted(). The Go port must expose sorted slices, not "
            "map iteration, for the same reason."
        ),
        # Sorted, because that is the only order any consumer actually uses.
        "themes_sorted": sorted(THEMES),
        "subcategories_sorted": sorted(SUBCATEGORIES),
        "subcategory_to_theme": dict(sorted(SUBCATEGORY_TO_THEME.items())),
        # The exact string categorization_prompts.py:88 embeds in the prompt.
        # Pinned verbatim: prompt text feeds categorization, categorization feeds
        # the input_hash, and the input_hash gates whether the LLM is called at
        # all. A reordering here is a silent re-categorisation of every unit.
        "prompt_category_list": ", ".join(sorted(SUBCATEGORIES)),
        "theme_of_unknown": {key: theme_of(key) for key in UNKNOWN_KEYS},
        "leaf_names_sorted": sorted(leaves),
    }

    rendered = json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n"
    if "--stdout" in sys.argv[1:]:
        sys.stdout.write(rendered)
        return

    OUTPUT_PATH.write_text(rendered)
    print(f"wrote {OUTPUT_PATH}")
    print(f"  themes:        {len(THEMES)}")
    print(f"  subcategories: {len(SUBCATEGORIES)}")
    print(f"  leaf names:    {len(set(leaves))} unique")
    print(f"  unknown keys:  {len(UNKNOWN_KEYS)} pinned to ''")


if __name__ == "__main__":
    main()
