"""Emit CPython's decimal-digit accept set for int() (CHAOS-4441).

WHY THIS EXISTS
---------------
`parsePythonInt` originally accepted only ASCII '0'-'9'. CPython's `int()`
accepts far more: full-width digits, Arabic-Indic, Devanagari, N'Ko and 750-odd
others all parse.

    int("５６７") -> 567      int("١٢٣") -> 123      int("१२३") -> 123

So a value Python parses was being refused by the port, which for
INVESTMENT_MAX_COMPONENT_NODES means one plane uses the configured cap and the
other silently falls back to the default -- and therefore splits oversized
components differently, minting different work_unit_ids.

Measured: `int()`'s accept set is EXACTLY `str.isdecimal()`, which is Unicode
general category Nd. Not `str.isdigit()`, which is 128 code points wider and
includes superscripts (`²`) and circled digits (`①`) that `int()` REJECTS. The
two predicates are one letter apart in the source and differ by a whole class of
characters.

THE UNICODE-VERSION TRAP, WHICH IS WHY THE TABLE IS DERIVED AND NOT ASSUMED
--------------------------------------------------------------------------
Go's `unicode` tables and the reference interpreter's are versioned
INDEPENDENTLY. Go 1.27 ships Unicode 17; this interpreter reports Unicode 16.
A code point assigned Nd in one and unassigned in the other is accepted by one
plane and refused by the other, with nothing in either codebase changing.

So `unicode.IsDigit` must NOT be used as the oracle for what Python accepts.
The table is emitted from the deployed interpreter, the Go side compares against
THAT, and the version skew is reported so a guard can fail rather than skip when
the derived sets actually diverge.

Also emitted: each code point's DECIMAL VALUE. `int("５")` is 5, not the code
point -- the parser must map the character to its numeric value, and for the
non-ASCII ranges that mapping is not "subtract 0x30".

Usage:
    uv run python tests/fixtures/generate_python_decimal_digits_golden.py [--stdout]
"""

from __future__ import annotations

import json
import sys
import unicodedata
from pathlib import Path
from typing import Any

OUTPUT_PATH = Path(__file__).parent / "python_decimal_digits_python_golden.json"


def main() -> None:
    decimal_points: list[list[int]] = []
    digit_not_decimal: list[int] = []

    for code_point in range(0x110000):
        character = chr(code_point)
        if character.isdecimal():
            # unicodedata.decimal is the value int() uses -- for the non-ASCII
            # ranges it is not "code point minus 0x30".
            decimal_points.append([code_point, unicodedata.decimal(character)])
        elif character.isdigit():
            # isdigit() but not isdecimal(): superscripts, circled digits.
            # int() REJECTS these, so a port keyed on isdigit() would accept
            # values Python refuses.
            digit_not_decimal.append(code_point)

    # Prove the equivalence rather than assert it: int() on a single character
    # must succeed exactly when isdecimal() is true. Sampled across the whole
    # space plus every boundary of every Nd run, since an exhaustive int() call
    # over 1.1M code points is slow and the runs are contiguous.
    boundaries: set[int] = {0, 0x10FFFF}
    decimal_set = {point for point, _ in decimal_points}
    for point in decimal_set:
        boundaries.add(point - 1)
        boundaries.add(point)
        boundaries.add(point + 1)
    boundaries.update(digit_not_decimal)

    mismatches: list[dict[str, Any]] = []
    for code_point in sorted(p for p in boundaries if 0 <= p <= 0x10FFFF):
        character = chr(code_point)
        try:
            int(character)
            parses = True
        except ValueError:
            parses = False
        if parses != character.isdecimal():
            mismatches.append(
                {
                    "code_point": code_point,
                    "isdecimal": character.isdecimal(),
                    "int_parses": parses,
                }
            )

    payload = {
        "_comment": (
            "Generated by tests/fixtures/generate_python_decimal_digits_golden.py. "
            "Do not hand-edit."
        ),
        "_policy": (
            "int() accepts EXACTLY str.isdecimal() (Unicode category Nd), not "
            "str.isdigit(). The value used is unicodedata.decimal(c), which is not "
            "'code point minus 0x30' outside ASCII. Go's unicode tables are "
            "versioned independently of the interpreter's and must not be used as "
            "the oracle."
        ),
        "unidata_version": unicodedata.unidata_version,
        "int_max_str_digits": sys.get_int_max_str_digits(),
        # [code_point, decimal_value] pairs.
        "decimal_digits": decimal_points,
        "digit_but_not_decimal": digit_not_decimal,
        "int_vs_isdecimal_mismatches": mismatches,
        "boundaries_probed": len(boundaries),
    }

    rendered = json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n"
    if "--stdout" in sys.argv[1:]:
        sys.stdout.write(rendered)
        return

    # Emit the Go table too. Production code cannot read a test fixture, and
    # Go's own unicode tables are NOT usable as the source: they are versioned
    # independently (Go 1.27 ships Unicode 17 against this interpreter's 16, and
    # they already disagree on U+11DA0-U+11DA9). Deriving the ranges here is the
    # only way the Go side can hold the same set the reference does.
    #
    # Ranges rather than 760 individual entries, because Nd is laid out in
    # decades: within a run the value is simply the offset from its start. Runs
    # are NOT separated by gaps -- U+1D7CE..U+1D7FF is 50 contiguous digits, five
    # abutting decades -- which is why a "walk back until not-a-digit"
    # derivation is wrong and a table is required.
    runs: list[tuple[int, int]] = []
    for code_point, value in decimal_points:
        if value == 0:
            runs.append((code_point, code_point))
        elif runs and code_point == runs[-1][1] + 1:
            runs[-1] = (runs[-1][0], code_point)
        else:  # pragma: no cover - a non-decade run would be a Unicode change
            raise SystemExit(
                f"U+{code_point:04X} has value {value} but does not continue a run; "
                "the decade assumption no longer holds and decimalDigitValue "
                "needs rewriting, not regenerating"
            )
    for start, end in runs:
        if end - start != 9:
            raise SystemExit(
                f"run U+{start:04X}..U+{end:04X} is {end - start + 1} long, not 10"
            )

    lines = [
        "// Code generated by tests/fixtures/"
        "generate_python_decimal_digits_golden.py. DO NOT EDIT.",
        "",
        "package units",
        "",
        "// pythonDecimalRuns holds every run of Unicode category Nd as the",
        "// DEPLOYED CPython interpreter reports it -- the set int() accepts.",
        "//",
        "// Derived from the interpreter rather than from Go's unicode tables,",
        f"// which are versioned independently (this table: Unicode {unicodedata.unidata_version}).",
        "// Each run is exactly ten code points and the digit value is the offset",
        "// from the run's start.",
        "var pythonDecimalRuns = [...][2]rune{",
    ]
    lines += [f"\t{{0x{start:04X}, 0x{end:04X}}}," for start, end in runs]
    lines += ["}", ""]
    go_path = OUTPUT_PATH.parent.parent.parent / (
        "internal/jobs/workgraph/units/python_decimal_runs_generated.go"
    )
    go_path.write_text("\n".join(lines))

    OUTPUT_PATH.write_text(rendered)
    print(f"wrote {OUTPUT_PATH}")
    print(f"  unicodedata version:        {unicodedata.unidata_version}")
    print(f"  isdecimal code points:      {len(decimal_points)}")
    print(f"  isdigit but not isdecimal:  {len(digit_not_decimal)} (int() rejects)")
    print(f"  boundaries probed:          {len(boundaries)}")
    print(f"  int()/isdecimal mismatches: {len(mismatches)}")
    print(f"  Nd runs emitted to Go:      {len(runs)}")


if __name__ == "__main__":
    main()
