"""Generate the max_component_nodes magnitude golden for CHAOS-4441.

WHY A MAGNITUDE AXIS
--------------------
lane-4752-go's round 1 found a corpus whose largest positive id was 42, which
let a port that refused values above 2^31 pass for as long as the corpus ran.
Python's `int()` is UNBOUNDED; Go's `strconv.Atoi` returns ErrRange. Collapsing
"out of range" into "malformed" is a real divergence, and this fixture pins the
boundary.

WHAT IT CAUGHT HERE
-------------------
`INVESTMENT_MAX_COMPONENT_NODES` set to forty 1s parses in Python to 10^40 -- a
cap so large that NO component is ever split. The Go port treated the ErrRange
as unparseable and fell back to the default of 150, which splits aggressively.
The two planes then mint completely different work_unit_ids for any org with a
component above 150 nodes, which is precisely the CHAOS-2775 split the port
exists to reproduce.

The fix SATURATES rather than refusing, and saturation is EXACT rather than
approximate: a cap of 10^40 and a cap of MaxInt produce identical splitting
decisions, because no component can contain more than MaxInt nodes. Sign is
preserved so a huge NEGATIVE cap still fails the `>= 1` check on both planes.

Usage:
    uv run python tests/fixtures/generate_max_component_nodes_golden.py [--stdout]
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

from dev_health_ops.work_graph.investment.constants import (
    resolve_max_component_nodes,
)

OUTPUT_PATH = Path(__file__).parent / "max_component_nodes_python_golden.json"

RAW_VALUES = [
    # Ordinary.
    "150",
    "1",
    "42",
    "+42",
    "  1_000  ",
    "1_0_0",
    # Boundaries in both directions.
    "2147483647",
    "2147483648",
    "-2147483648",
    "-2147483649",
    "9223372036854775807",
    "9223372036854775808",
    "-9223372036854775808",
    "-9223372036854775809",
    # Magnitude: unbounded in Python, ErrRange in Go.
    "1" * 40,
    "9" * 40,
    "-" + "1" * 40,
    # 40 zeros is a silent zero, not a huge number -- lane-4752-go's case.
    "0" * 40,
    "0",
    "-0",
    "+0",
    # Non-positive, which both planes reject in favour of the default.
    "-1",
    "-150",
    # Malformed: PEP 515 underscore placement, and non-numeric.
    "_1",
    "1_",
    "1__0",
    "abc",
    "",
    "   ",
    "1.5",
    "0x10",
    "1e3",
    # Whitespace that str.strip() removes but int() REJECTS -- the two
    # different Python whitespace rules meeting in one value.
    "\x1c150",
    "150\x1f",
]


def main() -> None:
    cases: list[dict[str, Any]] = []
    previous = os.environ.get("INVESTMENT_MAX_COMPONENT_NODES")
    try:
        for raw in RAW_VALUES:
            os.environ["INVESTMENT_MAX_COMPONENT_NODES"] = raw
            resolved = resolve_max_component_nodes(None)
            cases.append(
                {
                    "raw_hex": raw.encode("utf-8").hex(),
                    # As a STRING: values above 2^63 cannot survive a JSON
                    # number round trip through Go's decoder.
                    "resolved": str(resolved),
                }
            )
    finally:
        if previous is None:
            os.environ.pop("INVESTMENT_MAX_COMPONENT_NODES", None)
        else:
            os.environ["INVESTMENT_MAX_COMPONENT_NODES"] = previous

    payload = {
        "_comment": (
            "Generated by tests/fixtures/generate_max_component_nodes_golden.py. "
            "Do not hand-edit."
        ),
        "_note": (
            "resolved is a STRING because Python's int() is unbounded and values "
            "above 2^63 cannot round-trip as JSON numbers. Go saturates to MaxInt "
            "for out-of-range POSITIVE values, which is behaviourally exact: no "
            "component can exceed MaxInt nodes, so a cap of 10^40 and a cap of "
            "MaxInt split identically."
        ),
        "cases": cases,
    }
    rendered = json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n"
    if "--stdout" in sys.argv[1:]:
        sys.stdout.write(rendered)
        return
    OUTPUT_PATH.write_text(rendered)
    print(f"wrote {OUTPUT_PATH}")
    print(f"  cases: {len(cases)}")


if __name__ == "__main__":
    main()
