"""Emit CPython's builtin sum() behaviour over floats (CHAOS-4441).

WHY THIS EXISTS
---------------
Since CPython 3.12 (gh-100425) `sum()` applies NEUMAIER COMPENSATED summation to
floats: it tracks the rounding error lost at each addition and folds it back at
the end. A `total += x` loop in Go is NOT equivalent.

    sum([0.1, 0.2, 0.3]) -> 0.6                 naive -> 0.6000000000000001
    sum([0.1] * 10)      -> 1.0                 naive -> 0.9999999999999999

Measured over 20,000 random inputs of 2-8 values, the two disagree on 3,202 --
16%. Over this fixture's corpus, 239 of 607.

THE AXIS THAT MAKES IT INVISIBLE
--------------------------------
With fewer than three summands the compensation is always zero, so a corpus
that varies VALUES exhaustively but keeps lists short proves nothing about
summation. That is exactly how it slipped past this lane's 2000-case evidence-
quality corpus, whose confidence lists all had 0-2 entries. The axis is the
NUMBER of summands, so this corpus sweeps lengths 0-11, 20, 50 and 100.

NOT math.fsum
-------------
fsum is Shewchuk's exactly-rounded algorithm, a DIFFERENT one from sum()'s
Neumaier compensation. They agreed on every sampled input here, but agreeing on
a sample is not being the same function, and the port must match `sum()` --
that is what _effort_from_work_unit and _edge_confidence actually call.

Usage:
    uv run python tests/fixtures/generate_python_sum_golden.py [--stdout]
"""

from __future__ import annotations

import json
import math
import random
import sys
from pathlib import Path
from typing import Any

OUTPUT_PATH = Path(__file__).parent / "python_sum_python_golden.json"

# Fixed seed: the corpus must be reproducible for the rot guard to diff it.
SEED = 20260902


def _enc(value: float) -> Any:
    if math.isnan(value):
        return "nan"
    if math.isinf(value):
        return "inf" if value > 0 else "-inf"
    return value


def main() -> None:
    random.seed(SEED)
    cases: list[dict[str, Any]] = []

    # The LENGTH axis is the point: below three summands the compensation is
    # always zero and naive accumulation is indistinguishable.
    for count in list(range(0, 12)) + [20, 50, 100]:
        for _ in range(40):
            style = random.choice(["uniform", "wide", "tiny", "mixed", "tenths"])
            if style == "uniform":
                values = [random.uniform(-1e3, 1e3) for _ in range(count)]
            elif style == "wide":
                # Mixed magnitudes are where compensation matters most: a large
                # running total swallows a small addend entirely without it.
                values = [
                    random.uniform(-1e12, 1e12)
                    if random.random() < 0.5
                    else random.uniform(-1e-12, 1e-12)
                    for _ in range(count)
                ]
            elif style == "tiny":
                values = [random.uniform(-1e-8, 1e-8) for _ in range(count)]
            elif style == "tenths":
                values = [0.1] * count
            else:
                values = [
                    random.choice([0.1, 0.2, 0.3, -0.1, 1e16, -1e16, 1.0])
                    for _ in range(count)
                ]
            cases.append(
                {"values": [_enc(v) for v in values], "sum": repr(sum(values))}
            )

    # Non-finite and cancellation, where the compensation itself goes bad.
    for values in [
        [math.inf, 1.0],
        [math.inf, -math.inf],
        [-math.inf, math.inf],
        [math.nan, 1.0],
        [1.0, math.nan],
        [math.inf, math.nan],
        [1e308, 1e308],
        [1e308, 1e308, -1e308],
        [-1e308, -1e308],
        [0.0, -0.0],
        [-0.0, -0.0],
        [1e16, 1.0, -1e16],
        [1.0, 1e16, -1e16],
    ]:
        cases.append({"values": [_enc(v) for v in values], "sum": repr(sum(values))})

    payload = {
        "_comment": (
            "Generated by tests/fixtures/generate_python_sum_golden.py. "
            "Do not hand-edit."
        ),
        "_policy": (
            "CPython's builtin sum() uses Neumaier compensated summation for floats "
            "since 3.12 (gh-100425). It is neither a naive accumulation nor "
            "math.fsum. The discriminating axis is the NUMBER of summands: below "
            "three, compensation is always zero."
        ),
        "seed": SEED,
        "cases": cases,
    }
    rendered = json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n"
    if "--stdout" in sys.argv[1:]:
        sys.stdout.write(rendered)
        return
    OUTPUT_PATH.write_text(rendered)

    naive_mismatches = 0
    for case in cases:
        values = [
            math.inf
            if v == "inf"
            else -math.inf
            if v == "-inf"
            else math.nan
            if v == "nan"
            else v
            for v in case["values"]
        ]
        running = 0.0
        for value in values:
            running += value
        expected = float(case["sum"])
        if not (running == expected or (math.isnan(running) and math.isnan(expected))):
            naive_mismatches += 1

    print(f"wrote {OUTPUT_PATH}")
    print(f"  cases: {len(cases)}")
    print(f"  naive accumulation would differ on: {naive_mismatches}")


if __name__ == "__main__":
    main()
