package units

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"testing"
)

const coercionGoldenFixture = "confidence_coercion_python_golden.json"

type coercionGolden struct {
	Note        string `json:"note"`
	StringCases []struct {
		Input    string `json:"input"`
		Expected string `json:"expected"`
	} `json:"string_cases"`
	// TypeCases carry the Python repr() of the input rather than the value:
	// the axis exists to vary the TYPE, and JSON would erase exactly that by
	// coercing True to true and () to [].
	TypeCases []struct {
		InputRepr string `json:"input_repr"`
		Expected  string `json:"expected"`
	} `json:"type_cases"`
}

// TestConfidenceFromStringMatchesPythonCorpus is the differential test for the
// string branch of ConfidenceFromValue.
//
// It exists because a HAND-WRITTEN matrix is not a sufficient instrument here
// and has now demonstrably failed twice on this one function: the first version
// missed whitespace stripping, the second missed C99 hex literals and ErrRange
// saturation. strconv.ParseFloat is not a drop-in for Python's float() in either
// direction, and the set of forms where they part company is not something to
// enumerate from memory. The corpus is generated by the interpreter
// (tests/fixtures/generate_confidence_coercion_python_golden.py) and every entry
// is an executed Python result.
//
// The stake is not cosmetic: the coerced confidence decides which edges the
// oversized-component split protects, which decides component membership, which
// decides work_unit_id -- and that id addresses rows in two tables written by
// two different jobs.
func loadCoercionGolden(t *testing.T) ([]byte, coercionGolden) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(repositoryRootPath(t), "tests", "fixtures", coercionGoldenFixture))
	if err != nil {
		t.Fatalf("read coercion golden: %v", err)
	}
	var golden coercionGolden
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatalf("decode coercion golden: %v", err)
	}
	return raw, golden
}

func TestConfidenceFromStringMatchesPythonCorpus(t *testing.T) {
	_, golden := loadCoercionGolden(t)

	if len(golden.StringCases) == 0 {
		t.Fatal("coercion golden is empty; the test would pass vacuously")
	}

	// Guard the corpus itself: if the distinguishing forms are dropped, every
	// assertion below still passes while the coverage that matters is gone.
	required := []string{"0x1p2", "1e309", "1e-400", " 1 ", "1_0", "nan", "infinity"}
	present := make(map[string]bool, len(golden.StringCases))
	for _, testCase := range golden.StringCases {
		present[testCase.Input] = true
	}
	for _, form := range required {
		if !present[form] {
			t.Errorf("corpus no longer contains the distinguishing form %q", form)
		}
	}

	// KNOWN, ACCEPTED DIVERGENCES -- kept IN the corpus rather than deleted from
	// it, so the value stays recorded and any change is loud in either
	// direction. Deleting the case would hide the divergence; asserting it pins
	// the boundary.
	//
	// Python's float() accepts non-ASCII decimal digits. Replicating Python's
	// full numeric grammar in Go is an unbounded and unverifiable commitment,
	// whereas the parity harness asserting that both planes coerced to the same
	// value is bounded and provable, and catches this residual along with any
	// other. See the same argument on parsePythonInt in constants.go.
	knownDivergence := map[string]string{
		"\u0661\u0662": "python accepts non-ASCII decimal digits (float(\"\u0661\u0662\") == 12.0); Go does not",
	}

	for _, testCase := range golden.StringCases {
		t.Run(strconv.Quote(testCase.Input), func(t *testing.T) {
			if reason, known := knownDivergence[testCase.Input]; known {
				got := ConfidenceFromValue(testCase.Input)
				if got != 0.0 {
					t.Fatalf(
						"documented divergence changed: ConfidenceFromValue(%q) = %v, was 0. "+
							"If Go now agrees with Python (%s), delete this entry; "+
							"otherwise the coercion moved and the parity harness needs re-checking",
						testCase.Input, got, testCase.Expected,
					)
				}
				t.Skipf("known divergence: %s", reason)
			}
			expected, ok := parsePythonRendering(testCase.Expected)
			if !ok {
				t.Fatalf("golden holds an unrenderable expectation %q", testCase.Expected)
			}
			got := ConfidenceFromValue(testCase.Input)

			// Compared as VALUES, not as text: Python's repr() and Go's
			// FormatFloat pick different exponent thresholds, so a text
			// comparison would fail on formatting rather than on the number and
			// would need its own correctness argument. Exact equality is the
			// right bar -- this is a port, not an approximation -- with NaN
			// handled explicitly since it is never equal to itself.
			if math.IsNaN(expected) {
				if !math.IsNaN(got) {
					t.Errorf("ConfidenceFromValue(%q) = %v, python = nan", testCase.Input, got)
				}
				return
			}
			if got != expected {
				t.Errorf("ConfidenceFromValue(%q) = %v, python = %v", testCase.Input, got, expected)
			}
		})
	}
}

// parsePythonRendering turns the generator's rendered expectation back into a
// float64. The generator emits repr() for finite values and the bare words for
// the non-finite ones, which have no JSON representation.
func parsePythonRendering(rendered string) (float64, bool) {
	switch rendered {
	case "nan":
		return math.NaN(), true
	case "inf":
		return math.Inf(1), true
	case "-inf":
		return math.Inf(-1), true
	}
	parsed, err := strconv.ParseFloat(rendered, 64)
	return parsed, err == nil
}

// pythonReprToGo maps each type_cases entry to the Go value a ClickHouse driver
// would hand ConfidenceFromValue for that Python type.
//
// The MAPPING is hand-written -- it has to be, since Go and Python types are not
// the same set -- but the EXPECTATIONS are not: those come from calling
// _edge_confidence itself. That split is the point. A hand-written expectation
// encodes what the author believes; a hand-written mapping only says "this Go
// value corresponds to that Python one", and the assertion still measures the
// reference.
//
// An entry mapped to `unrepresentable` is one with no meaningful Go analogue on
// this path. Those are listed EXPLICITLY rather than skipped silently, so the
// corpus cannot grow a case that quietly tests nothing.
var pythonReprToGo = map[string]struct {
	value           any
	unrepresentable string
}{
	// The reason this axis exists: bool subclasses int in Python, so
	// _edge_confidence checks isinstance(value, bool) FIRST and True is 0.0,
	// not 1.0. Go's type switch treats bool and the numerics as unrelated, so
	// the ordering has to be reproduced deliberately.
	"True":  {value: true},
	"False": {value: false},

	"0":  {value: 0},
	"1":  {value: 1},
	"-3": {value: -3},

	"0.0": {value: 0.0},
	"0.5": {value: 0.5},
	"1.0": {value: 1.0},

	"inf":  {value: math.Inf(1)},
	"-inf": {value: math.Inf(-1)},
	"nan":  {value: math.NaN()},

	"None": {value: nil},

	"[]":                  {value: []any{}},
	"[1.0]":               {value: []any{1.0}},
	"{}":                  {value: map[string]any{}},
	"{'confidence': 1.0}": {value: map[string]any{"confidence": 1.0}},

	// A Python tuple has no ClickHouse-driver analogue that could reach this
	// function; Go's nearest equivalent would be a struct or array, neither of
	// which the driver produces for a Float32 column. Listed so the row is
	// accounted for rather than dropped.
	"()": {unrepresentable: "no ClickHouse driver value corresponds to a Python tuple on this path"},

	"'0.5'": {value: "0.5"},
}

// TestConfidenceFromValueMatchesPythonTypeAxis closes the axis gap recorded in
// CHAOS-4803: before this, the string branch had a generated corpus and every
// other branch had only a hand-written Go table -- including the bool case,
// which is the one a port written from the type signature gets backwards.
func TestConfidenceFromValueMatchesPythonTypeAxis(t *testing.T) {
	_, golden := loadCoercionGolden(t)

	if len(golden.TypeCases) == 0 {
		t.Fatal("type axis is empty; the test would pass vacuously")
	}
	for _, required := range []string{"True", "False", "1", "None", "nan"} {
		found := false
		for _, testCase := range golden.TypeCases {
			if testCase.InputRepr == required {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("type corpus no longer contains %q, the axis's distinguishing case", required)
		}
	}

	for _, testCase := range golden.TypeCases {
		t.Run(testCase.InputRepr, func(t *testing.T) {
			mapped, known := pythonReprToGo[testCase.InputRepr]
			if !known {
				t.Fatalf(
					"type corpus grew %q with no Go mapping. Add one, or mark it "+
						"unrepresentable with a reason -- an unmapped row tests nothing",
					testCase.InputRepr,
				)
			}
			if mapped.unrepresentable != "" {
				t.Skipf("no Go analogue: %s", mapped.unrepresentable)
			}

			expected, ok := parsePythonRendering(testCase.Expected)
			if !ok {
				t.Fatalf("unrenderable expectation %q", testCase.Expected)
			}
			got := ConfidenceFromValue(mapped.value)

			if math.IsNaN(expected) {
				if !math.IsNaN(got) {
					t.Errorf("ConfidenceFromValue(%s) = %v, python = nan", testCase.InputRepr, got)
				}
				return
			}
			if got != expected {
				t.Errorf(
					"ConfidenceFromValue(%s) = %v, python = %v",
					testCase.InputRepr, got, expected,
				)
			}
		})
	}
}
