// Package units is the Go port of the shared work-graph work-unit primitives
// (CHAOS-4441): connected-component grouping over work_graph_edges, the
// CHAOS-2775 oversized-component split, and the work_unit_id hash.
//
// # WHY THIS IS A SHARED PACKAGE AND NOT PRIVATE TO ONE JOB
//
// work_unit_id is a SHA256 over a component's node SET, and two different jobs
// address rows by that hash: investment.materialize writes
// work_unit_investments, and metrics.remaining.membership_backfill writes
// work_unit_membership. Python enforces the invariant by making both import one
// module (src/dev_health_ops/work_graph/investment/components.py:1-27) and says
// so in terms (work_graph/investment/backfill.py:113-127): sharing the grouping
// implementation is "REQUIRED for correctness ... if this path grouped nodes
// even slightly differently ... the projected membership would target
// non-existent unit ids". The failure mode is SILENT data corruption -- no
// crash, no error row, just two tables addressing different ids -- so this
// package exists to give the Go side the same single implementation, and both
// ported jobs MUST call it rather than re-deriving grouping locally.
//
// # FIDELITY CONTRACT
//
// This is a bit-exact port of the CURRENT Python behaviour, deliberately
// including behaviour that is known to be wrong. CHAOS-4758 (the oversized
// split DELETES the highest-degree nodes instead of partitioning them, dropping
// 242 real nodes on org 70d529e0 today) is NOT fixed here: a port that changed
// behaviour could not be proven correct against the only parity instrument that
// exists, and a grouping divergence is exactly the silent corruption described
// above. The correction lands separately, on one plane at a time, with its own
// before/after evidence, after parity is proven.
//
// Proven by tests/fixtures/workgraph_components_split_python_golden.json --
// 1,601 components from real synced data, generated by the deployed Python.
package units

import (
	"crypto/sha256"
	"encoding/hex"
	"sort"
	"strings"
)

// NodeKey identifies one node in the work graph.
//
// The node universe is NOT issue/pr/commit only: org 70d529e0 also carries
// feature_flag, incident, incident_timeline_event, escalation_policy and
// operational_service nodes, and every one of them enters the hashed node set.
// They are NOT recorded in work_unit_investments.structural_evidence_json,
// which is therefore a LOSSY projection of the hashed set -- any code that
// needs a unit's node set must rebuild it from work_graph_edges, never from
// stored evidence.
type NodeKey struct {
	Type string
	ID   string
}

// token renders the node in the exact form work_unit_id hashes.
func (node NodeKey) token() string { return node.Type + ":" + node.ID }

// WorkUnitID is the port of utils/normalization.py:34-37 work_unit_id.
//
//	sha256_hex("|".join(sorted(f"{node_type}:{node_id}" for ...)))
//
// UTF-8 bytes, lowercase hex, no salt and no length prefix, over the
// component's FULL node set. Sorting the tokens is what makes the id
// independent of node order, so callers need not pre-sort.
//
// Verified against production data by lane-4752-go: every stored
// work_unit_investments row on org 70d529e0 recomputes to its own id,
// 3480/3480, 0 mismatches.
//
// The sort is over the rendered "type:id" tokens, NOT over (type, id) pairs.
// For every node type currently in use the two orderings happen to agree, so
// the choice is unobservable TODAY: the types that share a prefix here
// ("incident" / "incident_timeline_event") continue with '_' (0x5F), which
// sorts above the ':' separator (0x3A), giving pair order and token order the
// same answer. The divergence is latent rather than absent -- it needs a type
// whose next character sorts BELOW ':', i.e. a digit. "incident" vs
// "incident0" token-sorts as [incident0:a, incident:z] but pair-sorts as
// [incident:z, incident0:a]: different join order, different digest, every
// affected unit silently re-addressed. Pinned by
// TestWorkUnitIDSortsRenderedTokensNotPairs so a future numeric-suffixed node
// type cannot introduce it unnoticed.
func WorkUnitID(nodes []NodeKey) string {
	tokens := make([]string, 0, len(nodes))
	for _, node := range nodes {
		tokens = append(tokens, node.token())
	}
	sort.Strings(tokens)
	sum := sha256.Sum256([]byte(strings.Join(tokens, "|")))
	return hex.EncodeToString(sum[:])
}
