# Deterministic, cost-balanced shard of the venue-oracles registry's `run` rows
# for `check_go.sh venue-oracles SHARD COUNT` and `venue-oracle-plan COUNT`
# (CHAOS-6891). Reads registry run rows "<package dir> <test>" on stdin.
#
#   awk -v shard=K -v count=N -v weights=<tsv> -v defw=<seconds> [-v plan=1] \
#       -f ci/venue_oracle_shard.awk < rows
#
# Default: prints "<package dir> <test>" for the rows of shard K of N (both
# 1-based), in input order. With plan=1: prints every row as
# "<package dir> <test> <shard> <weight>" and, last, one "#leg <shard> <rows>
# <seconds>" line per shard.
#
# Longest-processing-time assignment, exactly as ci/go_race_shard.awk: rows
# sorted by (weight desc, package asc, test asc), each handed to the currently
# lightest shard (lowest index on a tie). With every weight equal that is the
# old round-robin (row index mod N). The result is a PARTITION of the input for
# a given (input, weights, count) whatever the weights say: a wrong weight only
# unbalances the shards, it can never drop or duplicate a test. The weights
# are measured seconds of one test (ci/venue_oracle_weights.d/, regenerated by
# ci/venue_oracle_weights.py from a saved run log); a row without one weighs
# defw.
BEGIN {
  FS = "\t"
  if (weights != "") {
    while ((getline line < weights) > 0) {
      if (line ~ /^[[:space:]]*(#|$)/) continue
      split(line, f, "\t")
      w[f[1] SUBSEP f[2]] = f[3] + 0
    }
    close(weights)
  }
  if (defw == "") defw = 60
}
{
  n++
  pkg[n] = $1
  name[n] = $2
  key = $1 SUBSEP $2
  weight[n] = (key in w) ? w[key] : defw + 0
}
END {
  for (i = 1; i <= n; i++) order[i] = i
  for (i = 2; i <= n; i++) {
    v = order[i]
    j = i - 1
    while (j >= 1 && (weight[order[j]] < weight[v] || (weight[order[j]] == weight[v] && (pkg[order[j]] > pkg[v] || (pkg[order[j]] == pkg[v] && name[order[j]] > name[v]))))) {
      order[j + 1] = order[j]
      j--
    }
    order[j + 1] = v
  }
  for (s = 1; s <= count; s++) { load[s] = 0; rows[s] = 0 }
  for (i = 1; i <= n; i++) {
    k = order[i]
    best = 1
    for (s = 2; s <= count; s++) if (load[s] < load[best]) best = s
    load[best] += weight[k]
    rows[best]++
    owner[k] = best
  }
  for (k = 1; k <= n; k++) {
    if (plan) printf "%s\t%s\t%d\t%d\n", pkg[k], name[k], owner[k], weight[k]
    else if (owner[k] == shard) printf "%s\t%s\n", pkg[k], name[k]
  }
  if (plan) for (s = 1; s <= count; s++) printf "#leg\t%d\t%d\t%d\n", s, rows[s], load[s]
}
