package pythonparity

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// TestEdgeShapesGoldenMatchesLivePython is the rot guard for
// tests/fixtures/evidence_json_edge_shapes_python_golden.json.
//
// Like the band golden, this drives the REAL producer -- it builds a
// Recommendation and calls recommendation_to_record -- so a diff here is a
// change in what the evidence_json column contains, not in a test helper.
//
// It guards a different axis from the band golden, though. The band pins FLOAT
// RENDERING across the notation window. This pins the STRING and TOKEN
// spellings: ensure_ascii over non-ASCII, CJK, emoji and astral text, the short
// escapes, C0 controls including NUL, the bare -Infinity token, signed zero and
// the empty list. A Python-side change to any of those -- most plausibly
// someone "fixing" the column by passing ensure_ascii=False or allow_nan=False
// -- would leave the band golden perfectly green.
//
// The generator needs only the standard library, verified by running it on an
// interpreter with no third-party packages installed, so a failure here is
// always a real behaviour change and never a missing dependency.
func TestEdgeShapesGoldenMatchesLivePython(t *testing.T) {
	if os.Getenv("DEV_HEALTH_LIVE_PYTHON_ORACLES") != "1" {
		t.Skip("live Python oracles run only through ci/check_go.sh live-python-oracles")
	}
	proofDirectory := os.Getenv("DEV_HEALTH_LIVE_PYTHON_ORACLE_PROOF_DIR")
	if proofDirectory == "" {
		t.Fatal("DEV_HEALTH_LIVE_PYTHON_ORACLE_PROOF_DIR is required")
	}

	repoRoot := parityRepositoryRoot(t)
	python := parityLivePython(t, repoRoot)
	generator := filepath.Join(
		repoRoot, "tests", "fixtures",
		"generate_evidence_json_edge_shapes_golden.py",
	)
	if info, err := os.Stat(generator); err != nil || !info.Mode().IsRegular() {
		t.Fatalf("golden generator is missing at %s: %v", generator, err)
	}

	command := exec.Command(python, generator, "--stdout")
	command.Env = append(os.Environ(), "PYTHONPATH="+filepath.Join(repoRoot, "src"))
	rendered, err := command.Output()
	if err != nil {
		var stderr []byte
		if exitErr, ok := err.(*exec.ExitError); ok {
			stderr = exitErr.Stderr
		}
		t.Fatalf("run the golden generator against live Python: %v: %s", err, stderr)
	}

	frozen, err := os.ReadFile(filepath.Join(
		repoRoot, "tests", "fixtures",
		"evidence_json_edge_shapes_python_golden.json",
	))
	if err != nil {
		t.Fatal(err)
	}

	if string(frozen) == string(rendered) {
		if writeErr := os.WriteFile(
			filepath.Join(proofDirectory, "evidence-json-edge-shapes-golden"),
			[]byte("executed"), 0o644,
		); writeErr != nil {
			t.Fatalf("write live-python-oracle proof: %v", writeErr)
		}
		return
	}
	t.Error(
		"live Python no longer reproduces the frozen edge-shapes golden.\n" +
			"tests/fixtures/evidence_json_edge_shapes_python_golden.json was generated by\n" +
			"driving the REAL producer (recommendation_to_record -> json.dumps), so a diff\n" +
			"here is a change in what the evidence_json column actually contains -- not a\n" +
			"change in a test helper. Look first at the evidence dict literal in\n" +
			"recommendations/loader.py (key set and ORDER), then at the rounding depth on\n" +
			"the `value=` sites, then at EvidenceRef's fields.\n" +
			"Regenerate with\n" +
			"    PYTHONPATH=src python tests/fixtures/generate_evidence_json_edge_shapes_golden.py\n" +
			"and port the change into internal/pythonparity in the SAME change set.\n" +
			"The generator is deterministic (seeded) and needs only the standard\n" +
			"library, so a diff is a real behaviour change rather than a missing\n" +
			"dependency. It is NOT a claim that a diff can never be environmental:\n" +
			"this fixture froze interpreter metadata once, and a macOS build string\n" +
			"versus a Linux one was reported here as ROT pointing at loader.py. The\n" +
			"metadata is no longer frozen; if a future diff is confined to something\n" +
			"other than the case data, suspect the document shape before the port.",
	)
}
