package pythonparity

import (
	"encoding/json"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

// The golden is generated by
// internal/pythonparity/testdata/generate_float_text_golden.py against the
// shipped interpreter. Values travel as hex float literals so no decimal
// rounding happens between CPython and this test -- a corpus of Python float
// parity that was itself serialised through decimal text could not distinguish
// the bugs it exists to catch.
type floatTextGolden struct {
	Marker                string `json:"_marker"`
	GeneratingInterpreter struct {
		PythonVersion  string `json:"python_version"`
		Implementation string `json:"implementation"`
		UnicodeVersion string `json:"unicode_version"`
		Machine        string `json:"machine"`
		FloatReprStyle string `json:"float_repr_style"`
	} `json:"generating_interpreter"`
	Rounds []struct {
		ValueHex    string `json:"value_hex"`
		NDigits     int    `json:"ndigits"`
		ResultHex   string `json:"result_hex"`
		ResultIsNaN bool   `json:"result_is_nan"`
		Raises      string `json:"raises"`
	} `json:"rounds"`
	Reprs []struct {
		ValueHex string `json:"value_hex"`
		IsNaN    bool   `json:"is_nan"`
		Repr     string `json:"repr"`
		Str      string `json:"str"`
	} `json:"reprs"`
	Formats []struct {
		ValueHex  string `json:"value_hex"`
		IsNaN     bool   `json:"is_nan"`
		Precision int    `json:"precision"`
		Text      string `json:"text"`
	} `json:"formats"`
}

func loadFloatTextGolden(t *testing.T) floatTextGolden {
	t.Helper()
	raw, err := os.ReadFile("testdata/float_text_golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var golden floatTextGolden
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatalf("decode golden: %v", err)
	}
	if golden.Marker != "recommendations-float-text-golden" {
		t.Fatalf("golden marker is %q; wrong file or a regeneration changed its identity", golden.Marker)
	}
	// A measurement that did not happen must fail loudly rather than read as
	// coverage: an empty or truncated corpus would otherwise pass every
	// assertion below by having nothing to assert.
	if len(golden.Rounds) == 0 || len(golden.Reprs) == 0 || len(golden.Formats) == 0 {
		t.Fatalf("golden is empty (rounds=%d reprs=%d formats=%d); regenerate it",
			len(golden.Rounds), len(golden.Reprs), len(golden.Formats))
	}
	return golden
}

// parsePythonFloatHex reads CPython's float.hex() output, plus the bare
// "inf"/"-inf"/"nan" spellings the generator writes for the non-finite values
// that float.hex() renders that way.
func parsePythonFloatHex(t *testing.T, text string) float64 {
	t.Helper()
	switch text {
	case "inf":
		return math.Inf(1)
	case "-inf":
		return math.Inf(-1)
	case "nan":
		return math.NaN()
	}
	// Go's ParseFloat accepts the same hexadecimal-float grammar CPython's
	// float.hex() emits, except that CPython writes "0x1.8p+1" style with the
	// exponent always present, which Go requires too.
	value, err := strconv.ParseFloat(text, 64)
	if err != nil {
		t.Fatalf("parse python float hex %q: %v", text, err)
	}
	return value
}

func TestRoundMatchesLivePythonGolden(t *testing.T) {
	golden := loadFloatTextGolden(t)

	checked := 0
	for _, entry := range golden.Rounds {
		if entry.Raises != "" {
			// The generator records a raising case rather than a value; the Go
			// mirror has no exception channel, so such a case would need its
			// own contract. None exist in the current corpus and the assertion
			// below proves that stays true.
			t.Fatalf("golden contains a raising round case (%s at ndigits=%d) that Round has no contract for",
				entry.ValueHex, entry.NDigits)
		}
		value := parsePythonFloatHex(t, entry.ValueHex)
		got := Round(value, entry.NDigits)

		if entry.ResultIsNaN {
			if !math.IsNaN(got) {
				t.Errorf("Round(%s, %d) = %v; python produced nan", entry.ValueHex, entry.NDigits, got)
			}
			checked++
			continue
		}

		want := parsePythonFloatHex(t, entry.ResultHex)
		// Bit-for-bit, not ==: +0.0 and -0.0 compare equal under ==, and the
		// sign of zero is exactly one of the things this mirror must preserve
		// (it survives into str() output as "-0.0").
		if math.Float64bits(got) != math.Float64bits(want) {
			t.Errorf("Round(%s, %d) = %v (bits %#016x); python = %v (bits %#016x)",
				entry.ValueHex, entry.NDigits, got, math.Float64bits(got),
				want, math.Float64bits(want))
		}
		checked++
	}
	t.Logf("round cases checked: %d", checked)
}

func TestReprMatchesLivePythonGolden(t *testing.T) {
	golden := loadFloatTextGolden(t)

	for _, entry := range golden.Reprs {
		value := parsePythonFloatHex(t, entry.ValueHex)
		if got := Repr(value); got != entry.Repr {
			t.Errorf("Repr(%s) = %q; python repr() = %q", entry.ValueHex, got, entry.Repr)
		}
		// str() and repr() have been the same for floats since Python 3.1;
		// asserting both keeps the corpus honest if that ever diverges.
		if entry.Repr != entry.Str {
			t.Errorf("golden disagrees with itself for %s: repr=%q str=%q", entry.ValueHex, entry.Repr, entry.Str)
		}
	}
}

func TestFormatFixedMatchesLivePythonGolden(t *testing.T) {
	golden := loadFloatTextGolden(t)

	for _, entry := range golden.Formats {
		value := parsePythonFloatHex(t, entry.ValueHex)
		if got := FormatFixed(value, entry.Precision); got != entry.Text {
			t.Errorf("FormatFixed(%s, %d) = %q; python format(x, '.%df') = %q",
				entry.ValueHex, entry.Precision, got, entry.Precision, entry.Text)
		}
	}
}

// TestGoNativeRoundingDisagreesWithPython is a discriminating test, not a
// redundant one. It pins the reason this package exists: if a future Go
// release made math.Round agree with CPython on these inputs, the mirror would
// still be correct but its justification would have changed, and whoever reads
// Round's doc comment deserves to find out from a failing test rather than by
// assuming.
//
// It also protects against the likeliest wrong "simplification" of this file:
// replacing Round's body with math.Round(x*p)/p.
func TestGoNativeRoundingDisagreesWithPython(t *testing.T) {
	cases := []struct {
		value       float64
		ndigits     int
		python      float64
		naiveIsSame bool
	}{
		{2.675, 2, 2.67, false},
		{0.125, 2, 0.12, false},
		{2.5, 0, 2.0, false},
		{0.5, 0, 0.0, false},
		{-0.125, 2, -0.12, false},
	}

	for _, testCase := range cases {
		if got := Round(testCase.value, testCase.ndigits); got != testCase.python {
			t.Errorf("Round(%v, %d) = %v; python = %v", testCase.value, testCase.ndigits, got, testCase.python)
		}

		scale := math.Pow(10, float64(testCase.ndigits))
		naive := math.Round(testCase.value*scale) / scale
		if (naive == testCase.python) != testCase.naiveIsSame {
			t.Errorf("math.Round-style rounding of %v at %d digits gave %v (python %v): "+
				"the documented disagreement no longer holds, so Round's rationale needs rewriting",
				testCase.value, testCase.ndigits, naive, testCase.python)
		}
	}
}

// TestReprDisagreesWithGoNativeFormatting pins the second documented
// divergence -- the one that changes stored rationale text -- for the same
// reason as above.
func TestReprDisagreesWithGoNativeFormatting(t *testing.T) {
	for _, value := range []float64{0.0, 24.0, 1.0, -1.0} {
		goNative := strconv.FormatFloat(value, 'g', -1, 64)
		mirrored := Repr(value)
		if mirrored == goNative {
			t.Errorf("Repr(%v) = %q now equals Go's own 'g' formatting; "+
				"the integral-suffix divergence this mirror exists for is gone", value, mirrored)
		}
		if !strings.HasSuffix(mirrored, ".0") {
			t.Errorf("Repr(%v) = %q; python keeps a .0 suffix on integral floats", value, mirrored)
		}
	}
}
