// Measured from CPython 3.14.7 (unicodedata 16.0.0), the same reference
// pythonint_table.go's pythonNdRuns was measured from: every codepoint
// where `str.isdigit()` is True but the codepoint's Unicode general
// category is NOT Nd (decimal digit) -- superscripts, subscripts, circled
// and parenthesized digits, and a handful of other scripts' own digit
// characters that Unicode classifies as "Numeric_Type=Digit" rather than
// "Numeric_Type=Decimal". str.isdigit() is true for the union of this set
// and pythonNdRuns; str.isalpha() has zero divergence from Go's
// unicode.IsLetter (measured, category L* both ways), so it needs no
// table of its own.

package pythonparity

// pythonDigitNotDecimalRuns holds every codepoint (as inclusive [lo, hi]
// rune-pair runs) where CPython's str.isdigit() is True and the
// codepoint's category is not Nd. Generated by enumerating every rune 0..
// 0x10FFFF and comparing str.isdigit() against unicodedata.category(ch) ==
// 'Nd'.
var pythonDigitNotDecimalRuns = [...][2]rune{
	{0xb2, 0xb3},
	{0xb9, 0xb9},
	{0x1369, 0x1371},
	{0x19da, 0x19da},
	{0x2070, 0x2070},
	{0x2074, 0x2079},
	{0x2080, 0x2089},
	{0x2460, 0x2468},
	{0x2474, 0x247c},
	{0x2488, 0x2490},
	{0x24ea, 0x24ea},
	{0x24f5, 0x24fd},
	{0x24ff, 0x24ff},
	{0x2776, 0x277e},
	{0x2780, 0x2788},
	{0x278a, 0x2792},
	{0x10a40, 0x10a43},
	{0x10e60, 0x10e68},
	{0x11052, 0x1105a},
	{0x1f100, 0x1f10a},
}
