package pythonparity

import "testing"

// TestMarshalPythonJSONCompactMatchesPythonGolden pins MarshalPythonJSONCompact
// against values taken from a live CPython run of
//
//	json.dumps(value, sort_keys=True, separators=(",", ":"))
//
// The package convention is one golden per encoder, so this exists even though
// the encoder is also exercised end-to-end by the work_graph_edges live oracle
// (internal/jobs/metrics/workgraphedges). The two catch different things: the
// oracle proves the encoder is the RIGHT one for that family's payloads, this
// proves the encoding itself across shapes that family never produces.
//
// Every expected string below was generated by running the dumps() call above,
// not written by hand. Do not "fix" a failure by editing an expectation --
// regenerate it from CPython, and if CPython disagrees with what is here, that
// is the finding.
func TestMarshalPythonJSONCompactMatchesPythonGolden(t *testing.T) {
	for _, testCase := range []struct {
		name  string
		value any
		want  string
	}{
		{"empty object", map[string]any{}, `{}`},
		{"one key", map[string]any{"a": "b"}, `{"a":"b"}`},
		{
			// sort_keys=True, and no space after the comma -- the whole point
			// of this encoder versus MarshalPythonJSONSorted.
			"two keys sort by code point",
			map[string]any{"b": 1, "a": 2},
			`{"a":2,"b":1}`,
		},
		{"null value", map[string]any{"state": nil}, `{"state":null}`},
		{
			// The distinction the work_graph_edges port turns on: an empty
			// string is NOT null.
			"empty string is not null",
			map[string]any{"state": ""},
			`{"state":""}`,
		},
		{
			"nested object and array",
			map[string]any{"z": map[string]any{"y": "x", "w": "v"}, "a": []any{1, 2, 3}},
			`{"a":[1,2,3],"z":{"w":"v","y":"x"}}`,
		},
		{
			"bool and float",
			map[string]any{"t": true, "f": false, "n": 1.5},
			`{"f":false,"n":1.5,"t":true}`,
		},
		{
			// ensure_ascii=True is CPython's default, so non-ASCII is escaped
			// rather than emitted raw. Go's encoding/json would emit the raw
			// bytes here and diverge.
			"non-ascii is escaped, not raw",
			map[string]any{"k": "café ☃"},
			`{"k":"caf\u00e9 \u2603"}`,
		},
		{
			"quote and backslash",
			map[string]any{"k": `a"b\c`},
			`{"k":"a\"b\\c"}`,
		},
		{"empty list", map[string]any{"a": []any{}}, `{"a":[]}`},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			encoded, err := MarshalPythonJSONCompact(testCase.value)
			if err != nil {
				t.Fatalf("MarshalPythonJSONCompact: %v", err)
			}
			if string(encoded) != testCase.want {
				t.Errorf("\n got %s\nwant %s", encoded, testCase.want)
			}
		})
	}
}

// TestCompactAndDefaultSeparatorEncodersDisagree is the non-vacuity proof for
// the whole file: if MarshalPythonJSONCompact were quietly delegating to the
// default-separator encoder, every golden above would still need to change,
// but nothing would state WHY two encoders exist. This asserts the difference
// directly, on a payload with more than one key (single-key payloads encode
// identically under both, which is why the goldens above are not enough).
func TestCompactAndDefaultSeparatorEncodersDisagree(t *testing.T) {
	value := map[string]any{"a": 1, "b": 2}

	compact, err := MarshalPythonJSONCompact(value)
	if err != nil {
		t.Fatalf("compact: %v", err)
	}
	spaced, err := MarshalPythonJSONSorted(value)
	if err != nil {
		t.Fatalf("sorted: %v", err)
	}
	if string(compact) == string(spaced) {
		t.Fatalf("the two encoders must differ on a multi-key payload; both gave %s", compact)
	}
	if want := `{"a":1,"b":2}`; string(compact) != want {
		t.Errorf("compact:\n got %s\nwant %s", compact, want)
	}
	if want := `{"a": 1, "b": 2}`; string(spaced) != want {
		t.Errorf("default separators:\n got %s\nwant %s", spaced, want)
	}
}

// TestMarshalPythonJSONCompactRefusesUnsupportedTypes mirrors the sibling
// encoders' refusal contract: an unsupported type is a hard error, never a
// best-effort encoding, so a caller that starts passing a time.Time gets a
// failure rather than a silently divergent payload.
func TestMarshalPythonJSONCompactRefusesUnsupportedTypes(t *testing.T) {
	if _, err := MarshalPythonJSONCompact(map[string]any{"k": float32(1.5)}); err == nil {
		t.Error("float32 must be refused, not coerced")
	}
	if _, err := MarshalPythonJSONCompact(map[string]any{"k": uint64(1)}); err == nil {
		t.Error("uint64 must be refused, not coerced")
	}
}
