package pythonparity

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"sort"
	"testing"
)

const insertionOrderGoldenPath = "../../tests/fixtures/python_json_insertion_order_python_golden.json"

type insertionOrderCase struct {
	Name      string `json:"name"`
	InputRepr string `json:"input_repr"`
	Expected  string `json:"expected"`
}

type insertionOrderGolden struct {
	Cases []insertionOrderCase `json:"cases"`
}

// evidenceRow mirrors the literal in recommendations/loader.py:425-434,
// IN THE REFERENCE'S ORDER.
//
// That order is the point. Sorted, `field` would lead; here `team_id` does, and
// the two spellings produce different bytes from the same data.
func evidenceRow(value any) []OrderedObject {
	return []OrderedObject{{
		{Key: "team_id", Value: "70d529e0-3c06-4597-8480-794fd02328b6"},
		{Key: "metric_table", Value: "dora_deployments"},
		{Key: "window_start", Value: "2026-08-01T00:00:00+00:00"},
		{Key: "window_end", Value: "2026-08-31T00:00:00+00:00"},
		{Key: "field", Value: "deployment_frequency"},
		{Key: "value", Value: value},
	}}
}

// insertionOrderInputs is the Go side of the corpus, keyed by the fixture's
// case name.
//
// The INPUTS live here and the EXPECTED BYTES live in the fixture, generated by
// live CPython. Neither side can be edited into agreement with the other: the
// name sets are compared for equality below, so adding a Go case without a
// Python one (or the reverse) fails rather than silently shrinking coverage.
func insertionOrderInputs() map[string]any {
	return map[string]any{
		// The shape this encoder exists for, including the non-finite values
		// that are LIVE on the evidence path.
		"evidence: ordinary float":                                   evidenceRow(1.5),
		"evidence: integral float keeps .0":                          evidenceRow(24.0),
		"evidence: +Infinity (reachable: _safe_float passes it)":     evidenceRow(math.Inf(1)),
		"evidence: -Infinity (reachable)":                            evidenceRow(math.Inf(-1)),
		"evidence: NaN (unreachable via _safe_float; pinned anyway)": evidenceRow(math.NaN()),
		"evidence: null value":                                       evidenceRow(nil),

		"key order is insertion, not sorted": OrderedObject{
			{Key: "zebra", Value: 1}, {Key: "alpha", Value: 2}, {Key: "mango", Value: 3},
		},

		"float: zero": 0.0,
		// NOT the literal -0.0: in Go, constant `-0.0` is exactly +0.0, so
		// writing it here would silently test the wrong value and pass against
		// the wrong expectation. Copysign is the only way to spell it.
		"float: negative zero":             math.Copysign(0, -1),
		"float: 0.1 repr":                  0.1,
		"float: 1e10 stays positional":     1e10,
		"float: 1e16 switches to exponent": 1e16,
		"float: 1e-5 positional":           1e-05,
		"float: 1e-6 switches":             1e-06,
		"float: smallest subnormal":        5e-324,
		"float: max":                       1.7976931348623157e308,
		"float: 2**53":                     9007199254740992.0,

		"int":           42,
		"int: negative": -7,
		"bool true":     true,
		"bool false":    false,
		"null":          nil,
		"empty object":  OrderedObject{},
		"empty list":    []any{},
		"nested list of objects": []any{
			OrderedObject{{Key: "b", Value: 1}, {Key: "a", Value: []any{2, 3}}},
			OrderedObject{{Key: "c", Value: nil}},
		},

		"string: ascii": OrderedObject{{Key: "k", Value: "plain"}},
		"string: accented escapes under ensure_ascii": OrderedObject{{Key: "k", Value: "café"}},
		"string: astral becomes a surrogate pair":     OrderedObject{{Key: "k", Value: "\U0001F600"}},
		"string: control characters":                  OrderedObject{{Key: "k", Value: "a\tb\nc\x00d"}},
		"string: DEL is escaped":                      OrderedObject{{Key: "k", Value: "a\x7fb"}},
		"string: quote and backslash":                 OrderedObject{{Key: "k", Value: "a\"b\\c"}},
		"string: solidus stays unescaped":             OrderedObject{{Key: "k", Value: "a/b"}},

		"separators: multi-key object":   OrderedObject{{Key: "a", Value: 1}, {Key: "b", Value: 2}},
		"separators: multi-element list": []any{1, 2, 3},
	}
}

func loadInsertionOrderGolden(t *testing.T) insertionOrderGolden {
	t.Helper()
	raw, err := os.ReadFile(filepath.Clean(insertionOrderGoldenPath))
	if err != nil {
		t.Fatalf("read golden: %v (regenerate with: uv run python "+
			"tests/fixtures/generate_python_json_insertion_order_golden.py)", err)
	}
	var golden insertionOrderGolden
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(golden.Cases) == 0 {
		t.Fatal("golden contains no cases")
	}
	return golden
}

// TestMarshalPythonJSONInsertionOrderMatchesCPython is the parity test proper.
func TestMarshalPythonJSONInsertionOrderMatchesCPython(t *testing.T) {
	golden := loadInsertionOrderGolden(t)
	inputs := insertionOrderInputs()

	for _, testCase := range golden.Cases {
		value, ok := inputs[testCase.Name]
		if !ok {
			continue // reported as a set difference below, with both sides named
		}
		t.Run(testCase.Name, func(t *testing.T) {
			encoded, err := MarshalPythonJSONInsertionOrder(value)
			if err != nil {
				t.Fatalf("encode: %v", err)
			}
			if got := string(encoded); got != testCase.Expected {
				t.Errorf("bytes differ from CPython json.dumps(value)\n"+
					"  input:  %s\n  python: %s\n  go:     %s",
					testCase.InputRepr, testCase.Expected, got)
			}
			// ensure_ascii=True is total, not per-case: CPython's output is
			// pure ASCII for every input. Asserting it corpus-wide catches a
			// non-ASCII leak even in cases whose expected bytes happen not to
			// exercise the escape path.
			for offset, b := range encoded {
				if b >= 0x80 {
					t.Fatalf("byte %d is 0x%02x; ensure_ascii output must be "+
						"pure ASCII: %q", offset, b, encoded)
				}
			}
		})
	}
}

// TestInsertionOrderCorpusCoversBothSides makes the corpus non-shrinkable.
//
// Without this, deleting a Go input would skip its case and still go green: the
// suite would report success for a corpus that had quietly lost coverage. The
// set comparison is what converts that into a failure, and it names which side
// is missing so the fix is obvious.
func TestInsertionOrderCorpusCoversBothSides(t *testing.T) {
	golden := loadInsertionOrderGolden(t)
	inputs := insertionOrderInputs()

	fixtureNames := make(map[string]bool, len(golden.Cases))
	for _, testCase := range golden.Cases {
		fixtureNames[testCase.Name] = true
	}

	var missingGo, missingPython []string
	for name := range fixtureNames {
		if _, ok := inputs[name]; !ok {
			missingGo = append(missingGo, name)
		}
	}
	for name := range inputs {
		if !fixtureNames[name] {
			missingPython = append(missingPython, name)
		}
	}
	sort.Strings(missingGo)
	sort.Strings(missingPython)

	if len(missingGo) > 0 {
		t.Errorf("%d fixture case(s) have no Go input, so they never ran: %v",
			len(missingGo), missingGo)
	}
	if len(missingPython) > 0 {
		t.Errorf("%d Go input(s) have no CPython expectation, so nothing pins "+
			"their bytes: %v\n  regenerate: uv run python "+
			"tests/fixtures/generate_python_json_insertion_order_golden.py",
			len(missingPython), missingPython)
	}
}

// TestNonFiniteTokensAreBareAndUnquoted pins the allow_nan=True contract at the
// token level, independently of the corpus.
//
// These three tokens are NOT valid JSON. Go's encoding/json refuses to produce
// them and refuses to parse them, so this is the one place the two encoders can
// never converge -- and a reader of such a column must not use encoding/json.
// The decoder half is asserted here too, so the constraint is proven rather
// than promised in a comment.
func TestNonFiniteTokensAreBareAndUnquoted(t *testing.T) {
	for _, testCase := range []struct {
		name  string
		value float64
		token string
	}{
		{name: "positive infinity", value: math.Inf(1), token: "Infinity"},
		{name: "negative infinity", value: math.Inf(-1), token: "-Infinity"},
		{name: "not a number", value: math.NaN(), token: "NaN"},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			encoded, err := MarshalPythonJSONInsertionOrder(testCase.value)
			if err != nil {
				t.Fatalf("encode: %v", err)
			}
			if string(encoded) != testCase.token {
				t.Errorf("got %q, want the bare token %q", encoded, testCase.token)
			}

			// The consequence, asserted: stdlib JSON cannot read this back.
			var sink any
			if err := json.Unmarshal(encoded, &sink); err == nil {
				t.Errorf("encoding/json parsed %q, but these tokens are not "+
					"valid JSON; if this ever succeeds, the reader-side warning "+
					"in the doc comment is wrong and should be corrected", encoded)
			}
		})
	}
}

// TestOrderedObjectSliceMatchesAnySlice pins that the two ways of spelling a
// list of objects agree. []OrderedObject exists as a convenience for callers
// building evidence rows; a convenience that encoded differently from the
// general path would be a trap rather than a convenience.
func TestOrderedObjectSliceMatchesAnySlice(t *testing.T) {
	typed := evidenceRow(1.5)
	general := make([]any, len(typed))
	for index, row := range typed {
		general[index] = row
	}

	fromTyped, err := MarshalPythonJSONInsertionOrder(typed)
	if err != nil {
		t.Fatalf("encode []OrderedObject: %v", err)
	}
	fromGeneral, err := MarshalPythonJSONInsertionOrder(general)
	if err != nil {
		t.Fatalf("encode []any: %v", err)
	}
	if string(fromTyped) != string(fromGeneral) {
		t.Errorf("the two list spellings disagree\n  []OrderedObject: %s\n  []any:           %s",
			fromTyped, fromGeneral)
	}
}

// TestInsertionOrderRefusesMaps pins the refusal that protects the whole
// contract.
//
// A Go map has no order. Accepting one would mean choosing an order, and every
// available choice is wrong: sorting is the OTHER encoder's reference, and
// native iteration is randomized per run. Encoding a map would therefore
// produce plausible bytes that differ from CPython's -- and, for a map, differ
// between two runs of the same binary. An error is visible; those bytes are not.
func TestInsertionOrderRefusesMaps(t *testing.T) {
	for _, testCase := range []struct {
		name  string
		value any
	}{
		{name: "map[string]any", value: map[string]any{"k": 1}},
		{name: "map[string]string", value: map[string]string{"k": "v"}},
		{name: "nested map inside an OrderedObject", value: OrderedObject{
			{Key: "k", Value: map[string]string{"inner": "v"}},
		}},
		{name: "nested map inside a slice", value: []any{map[string]any{"k": 1}}},
		{name: "float32 is not float64", value: float32(1.5)},
		{name: "struct", value: struct{ K int }{K: 1}},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			if _, err := MarshalPythonJSONInsertionOrder(testCase.value); err == nil {
				t.Errorf("expected a refusal for %T, got a silent encoding",
					testCase.value)
			}
		})
	}
}
