package pythonparity

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// TestReprBandGoldenMatchesLivePython is the rot guard for
// tests/fixtures/evidence_json_repr_band_python_golden.json.
//
// This fixture has a DIFFERENT producer from the other two JSON goldens, which
// is why it gets its own guard and its own marker rather than riding on theirs.
// The other two call json.dumps directly. This one drives the real application
// path -- it builds a Recommendation and calls recommendation_to_record, so its
// bytes come out of loader.py:448 itself.
//
// That makes it sensitive to changes the direct-json guards cannot see: a key
// added to or reordered in the evidence dict literal, a changed rounding depth
// at a `value=` site, or an EvidenceRef field rename. Any of those would leave
// the direct-json goldens perfectly green while the column's real bytes moved.
//
// The generator needs only the standard library. Verified by running it on an
// interpreter with no third-party packages installed at all: byte-identical
// output. So this guard cannot fail for a missing dependency, and a failure
// here is always a real behaviour change.
func TestReprBandGoldenMatchesLivePython(t *testing.T) {
	if os.Getenv("DEV_HEALTH_LIVE_PYTHON_ORACLES") != "1" {
		t.Skip("live Python oracles run only through ci/check_go.sh live-python-oracles")
	}
	proofDirectory := os.Getenv("DEV_HEALTH_LIVE_PYTHON_ORACLE_PROOF_DIR")
	if proofDirectory == "" {
		t.Fatal("DEV_HEALTH_LIVE_PYTHON_ORACLE_PROOF_DIR is required")
	}

	repoRoot := parityRepositoryRoot(t)
	python := parityLivePython(t, repoRoot)
	generator := filepath.Join(
		repoRoot, "tests", "fixtures",
		"generate_evidence_json_repr_band_golden.py",
	)
	if info, err := os.Stat(generator); err != nil || !info.Mode().IsRegular() {
		t.Fatalf("golden generator is missing at %s: %v", generator, err)
	}

	command := exec.Command(python, generator, "--stdout")
	command.Env = append(os.Environ(), "PYTHONPATH="+filepath.Join(repoRoot, "src"))
	rendered, err := command.Output()
	if err != nil {
		var stderr []byte
		if exitErr, ok := err.(*exec.ExitError); ok {
			stderr = exitErr.Stderr
		}
		t.Fatalf("run the golden generator against live Python: %v: %s", err, stderr)
	}

	frozen, err := os.ReadFile(filepath.Join(
		repoRoot, "tests", "fixtures",
		"evidence_json_repr_band_python_golden.json",
	))
	if err != nil {
		t.Fatal(err)
	}

	// Compare the PAYLOAD, not the whole document: provenance fields such as
	// `environment` record an interpreter that drifts without anyone deciding
	// anything, and freezing that inside the comparison already produced one
	// false "has ROTTED" pointing at loader.py. See comparePayload.
	if err := comparePayload(frozen, rendered, "cases", "distinct_input_values"); err == nil {
		if writeErr := os.WriteFile(
			filepath.Join(proofDirectory, "evidence-json-repr-band-golden"),
			[]byte("executed"), 0o644,
		); writeErr != nil {
			t.Fatalf("write live-python-oracle proof: %v", writeErr)
		}
		return
	}
	t.Error(
		"live Python no longer reproduces the frozen band golden.\n" +
			"tests/fixtures/evidence_json_repr_band_python_golden.json was generated by\n" +
			"driving the REAL producer (recommendation_to_record -> json.dumps), so a diff\n" +
			"here is a change in what the evidence_json column actually contains -- not a\n" +
			"change in a test helper. Look first at the evidence dict literal in\n" +
			"recommendations/loader.py (key set and ORDER), then at the rounding depth on\n" +
			"the `value=` sites, then at EvidenceRef's fields.\n" +
			"Regenerate with\n" +
			"    PYTHONPATH=src python tests/fixtures/generate_evidence_json_repr_band_golden.py\n" +
			"and port the change into internal/pythonparity in the SAME change set.\n" +
			"The generator is deterministic (seeded) and needs only the standard\n" +
			"library, so a diff is a real behaviour change rather than a missing\n" +
			"dependency. It is NOT a claim that a diff can never be environmental:\n" +
			"this fixture froze interpreter metadata once, and a macOS build string\n" +
			"versus a Linux one was reported here as ROT pointing at loader.py. The\n" +
			"metadata is no longer frozen; if a future diff is confined to something\n" +
			"other than the case data, suspect the document shape before the port.",
	)
}
