package pythonparity

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// TestWhitespaceGoldenMatchesLivePython is the rot guard for
// tests/fixtures/python_whitespace_python_golden.json.
//
// Its own guard and its own marker, per the convention the workgraph-components
// and confidence-coercion guards established, because it has a DIFFERENT
// producer from the json.dumps golden next to it: this one is generated by the
// interpreter's Unicode tables via str.isspace(), not by any code in this
// repository. That producer changes on a Python upgrade, silently, without any
// diff in src/ for a reviewer to notice.
//
// What a failure here means: the set of code points CPython calls whitespace
// has moved. Every TrimSpace/Fields decision in the port was made against the
// old set, so the correct response is to re-audit those call sites, not to
// regenerate the fixture and move on. The delta is currently exactly four
// separators (0x1c-0x1f) and IsSpace hard-codes that range; a fifth would make
// the hard-coding wrong.
func TestWhitespaceGoldenMatchesLivePython(t *testing.T) {
	if os.Getenv("DEV_HEALTH_LIVE_PYTHON_ORACLES") != "1" {
		t.Skip("live Python oracles run only through ci/check_go.sh live-python-oracles")
	}
	proofDirectory := os.Getenv("DEV_HEALTH_LIVE_PYTHON_ORACLE_PROOF_DIR")
	if proofDirectory == "" {
		t.Fatal("DEV_HEALTH_LIVE_PYTHON_ORACLE_PROOF_DIR is required")
	}

	repoRoot := parityRepositoryRoot(t)
	python := parityLivePython(t, repoRoot)
	generator := filepath.Join(
		repoRoot, "tests", "fixtures", "generate_python_whitespace_golden.py",
	)
	if info, err := os.Stat(generator); err != nil || !info.Mode().IsRegular() {
		t.Fatalf("whitespace generator is missing at %s: %v", generator, err)
	}

	command := exec.Command(python, generator, "--stdout")
	command.Env = append(os.Environ(), "PYTHONPATH="+filepath.Join(repoRoot, "src"))
	rendered, err := command.Output()
	if err != nil {
		var stderr []byte
		if exitErr, ok := err.(*exec.ExitError); ok {
			stderr = exitErr.Stderr
		}
		t.Fatalf("run the whitespace generator against live Python: %v: %s", err, stderr)
	}

	frozen, err := os.ReadFile(filepath.Join(
		repoRoot, "tests", "fixtures", "python_whitespace_python_golden.json",
	))
	if err != nil {
		t.Fatal(err)
	}

	if string(frozen) == string(rendered) {
		if writeErr := os.WriteFile(
			filepath.Join(proofDirectory, "python-whitespace-golden"), []byte("executed"), 0o644,
		); writeErr != nil {
			t.Fatalf("write live-python-oracle proof: %v", writeErr)
		}
		return
	}
	t.Error(
		"live Python's whitespace predicate no longer matches the frozen golden.\n" +
			"This is almost certainly a Python/Unicode upgrade rather than a code change,\n" +
			"which is exactly why it is guarded: nothing in src/ would have shown a diff.\n" +
			"Regenerate with\n" +
			"    PYTHONPATH=src python tests/fixtures/generate_python_whitespace_golden.py\n" +
			"and then RE-AUDIT, do not just accept: pythonparity.IsSpace hard-codes the\n" +
			"0x1c-0x1f delta, str.strip()/split()/rstrip() call sites assume that set, and\n" +
			"the numeric parsers (parsePythonInt, confidenceFromString) deliberately use\n" +
			"Go's narrower TrimSpace because int()/float() REJECT those separators. A change\n" +
			"here can move any of those three independently.",
	)
}
