package lizardcc

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
	"unicode"
)

// The parity contract for this package is numeric equality with lizard
// 1.23.0, not resemblance -- the same contract pycc holds with radon, and
// for the same reason: BuildFileResult (compute.go) derives every stored
// field from these raw numbers, so "close" is simply wrong.
//
//   - TestGoMatchesLizardGolden runs offline on every CI leg and compares
//     the Go implementation to a checked-in golden.
//   - TestLizardGoldenIsNotStale re-derives the golden from real lizard and
//     fails if the checked-in bytes have drifted, mirroring pycc's
//     TestRadonGoldenIsNotStale. As of this PR that test is gated behind
//     DEV_HEALTH_LIVE_PYTHON_ORACLE exactly as pycc's is, and -- like
//     pycc's -- is not yet wired into any check_go.sh verb; see that
//     package's own test for the identical, pre-existing gap.

type oracleFunction struct {
	Name       string `json:"name"`
	LongName   string `json:"long_name"`
	Lineno     int    `json:"lineno"`
	Complexity int    `json:"complexity"`
}

type oracleFile struct {
	LOC                        int              `json:"loc"`
	FunctionsCount             int              `json:"functions_count"`
	CyclomaticTotal            int              `json:"cyclomatic_total"`
	CyclomaticAvg              float64          `json:"cyclomatic_avg"`
	HighComplexityFunctions    int              `json:"high_complexity_functions"`
	VeryHighComplexityFunction int              `json:"very_high_complexity_functions"`
	Functions                  []oracleFunction `json:"functions"`
}

type oracleDoc struct {
	LizardVersion string                `json:"lizard_version"`
	Files         map[string]oracleFile `json:"files"`
}

func goldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "lizard_cc_golden.json")
}

func corpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus")
}

func loadGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(goldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		// A golden that parses but describes nothing would let every
		// assertion below pass vacuously.
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

// lockedLizardVersion reads the resolved lizard pin out of uv.lock, mirroring
// pycc's lockedRadonVersion for the same reason: pyproject.toml's
// `lizard>=1.17.10` is a FLOOR, and only the lock says which version these
// numbers were actually derived from.
func lockedLizardVersion(t *testing.T) string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "..", "uv.lock"))
	if err != nil {
		t.Fatalf("read uv.lock: %v", err)
	}
	lines := strings.Split(string(raw), "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) != `name = "lizard"` {
			continue
		}
		for _, follow := range lines[i+1 : min(i+5, len(lines))] {
			trimmed := strings.TrimSpace(follow)
			if strings.HasPrefix(trimmed, "version = ") {
				return strings.Trim(strings.TrimPrefix(trimmed, "version = "), `"`)
			}
		}
	}
	t.Fatalf("no lizard entry in uv.lock; the oracle has no version of record")
	return ""
}

func TestGoldenPinnedToLockedLizard(t *testing.T) {
	golden := loadGolden(t)
	locked := lockedLizardVersion(t)
	if golden.LizardVersion != locked {
		t.Fatalf("golden was generated by lizard %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a lizard upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.LizardVersion, locked)
	}
}

func TestGoMatchesLizardGolden(t *testing.T) {
	doc := loadGolden(t)

	entries, err := os.ReadDir(corpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(corpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			complexities, skipped, err := Analyze(name, string(src))
			if err != nil {
				t.Fatalf("lizard analysed %s but Go failed: %v", name, err)
			}
			if skipped {
				t.Fatalf("Go skipped %s but the fixture is expected to analyse", name)
			}

			if got := len(complexities); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, lizard %d\n%s",
					got, expected.FunctionsCount, complexityDiff(complexities, expected.Functions))
			}
			total := 0
			high, veryHigh := 0, 0
			for _, c := range complexities {
				total += c
				if c > 15 {
					high++
				}
				if c > 25 {
					veryHigh++
				}
			}
			if total != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, lizard %d\n%s",
					total, expected.CyclomaticTotal, complexityDiff(complexities, expected.Functions))
			}
			if high != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, lizard %d", high, expected.HighComplexityFunctions)
			}
			if veryHigh != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, lizard %d", veryHigh, expected.VeryHighComplexityFunction)
			}

			// Per-function comparison as a MULTISET of complexities, in the
			// order each function's body closed. Both sides append to their
			// respective lists at exactly the same point (a function's
			// closing brace / PopNesting's end_of_function), so an ordered
			// comparison is the strongest check available and, unlike
			// matching by name, needs no name-tracking on the Go side at
			// all (this package deliberately drops names -- see counter.go).
			wantOrdered := make([]int, len(expected.Functions))
			for i, f := range expected.Functions {
				wantOrdered[i] = f.Complexity
			}
			if !sameOrdered(complexities, wantOrdered) {
				t.Errorf("ordered complexities: got %v, lizard %v (by declaration order: %s)",
					complexities, wantOrdered, complexityDiff(complexities, expected.Functions))
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

func sameOrdered(got, want []int) bool {
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}
	return true
}

func complexityDiff(got []int, want []oracleFunction) string {
	var b strings.Builder
	b.WriteString("  go complexities (declaration order): ")
	b.WriteString(itoaSlice(got))
	b.WriteString("\n  lizard functions:\n")
	sorted := append([]oracleFunction(nil), want...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Lineno < sorted[j].Lineno })
	for _, f := range sorted {
		b.WriteString("    " + f.LongName + " = " + itoa(f.Complexity) + "\n")
	}
	return b.String()
}

func itoaSlice(vals []int) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = itoa(v)
	}
	return "[" + strings.Join(parts, " ") + "]"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var digits []byte
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	if neg {
		return "-" + string(digits)
	}
	return string(digits)
}

// TestLizardGoldenIsNotStale re-runs the real lizard and compares its
// output to the checked-in golden, mirroring pycc's TestRadonGoldenIsNotStale.
//
// STRENGTHENED (CHAOS-5156, codex round r1 on #2253, finding #6): this used
// to compare only CyclomaticTotal/FunctionsCount per file, which a
// COORDINATED corpus+golden mutation can satisfy while every per-function
// name/lineno/complexity value silently drifts (codex's construction:
// mutate a fixture and its golden together, in a way that preserves the
// per-file totals but not the per-function detail). assertGoldenBytesMatch
// now byte-diffs the regenerated JSON against the checked-in file directly
// -- the oracle script's own docstring promises stable, sorted, indent=2
// output specifically so this comparison is meaningful -- which catches
// every per-function field, not just the two that used to be checked.
//
// This does NOT by itself close the narrower attack codex's finding #6
// also named (remove every `case` arm from the corpus AND from
// `conditions` AND regenerate the golden -- real lizard's output on the
// mutated corpus is then genuinely, correctly unaffected by `case`'s
// absence, so no comparison against regenerated output can ever catch it).
// That gap needs an INDEPENDENT fixture manifest (a static assertion that
// the corpus exercises every condition keyword), tracked separately.
func TestLizardGoldenIsNotStale(t *testing.T) {
	assertGoldenBytesMatchLiveOracle(t, corpusDir(t), goldenPath(t))
}

// assertGoldenBytesMatchLiveOracle is the shared golden-staleness guard
// every corpus in this package uses (cfamily's own corpus, and go-rust's/
// jvm-swift's/java's own parity test files) -- ONE mechanism, not a
// per-corpus copy, per CHAOS-5156's codex round r1 ruling. It re-runs the
// checked-in Python oracle against corpusDir and fails unless its output is
// BYTE-IDENTICAL to the checked-in golden at goldenPath.
func assertGoldenBytesMatchLiveOracle(t *testing.T, corpusDir, goldenPath string) {
	t.Helper()
	if os.Getenv("DEV_HEALTH_LIVE_PYTHON_ORACLE") == "" {
		t.Skip("live Python oracle runs only through the uncached live-oracle gate")
	}

	python := os.Getenv("DEV_HEALTH_PYTHON")
	if python == "" {
		python = "python3"
	}
	script := filepath.Join("testdata", "python_lizard_cc_oracle.py")
	command := exec.Command(python, script, corpusDir)
	live, err := command.Output()
	if err != nil {
		t.Fatalf("lizard oracle failed: %v", err)
	}

	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}

	if string(live) != string(want) {
		var liveDoc, wantDoc oracleDoc
		_ = json.Unmarshal(live, &liveDoc)
		_ = json.Unmarshal(want, &wantDoc)
		if liveDoc.LizardVersion != "" && wantDoc.LizardVersion != "" &&
			liveDoc.LizardVersion != wantDoc.LizardVersion {
			t.Fatalf("lizard version moved: golden %q, installed %q. Regenerate the "+
				"golden and re-review the numbers -- a version bump can legitimately "+
				"change complexity, and that change must be seen, not absorbed.",
				wantDoc.LizardVersion, liveDoc.LizardVersion)
		}
		t.Fatalf("golden at %s is stale: regenerate it from the real lizard "+
			"oracle and re-review every changed number before committing "+
			"(byte diff, not just totals -- see this test's own doc)."+
			"\n--- live oracle ---\n%s\n--- checked-in golden ---\n%s",
			goldenPath, live, want)
	}
}

// TestEveryConditionIsExercisedByTheCorpus closes the narrower half of
// codex round r1's finding #6 that assertGoldenBytesMatchLiveOracle
// cannot: a coordinated mutation removing `case` from BOTH the corpus and
// `conditions` (regenerating the golden to match) produces a genuinely
// correct golden for the mutated corpus -- no comparison against
// regenerated output can ever catch that, because real lizard's measured
// behavior on the mutated corpus really is unaffected by `case`'s absence.
// This is a DIFFERENT, static check: does at least one fixture in the
// corpus actually CONTAIN each condition keyword at all? If `case`
// vanished from both the map and the corpus together, this test would
// immediately report `case` as unexercised in the (by-then-empty) corpus.
func TestEveryConditionIsExercisedByTheCorpus(t *testing.T) {
	assertEveryConditionExercisedByCorpus(t, conditions, corpusDir(t))
}

// assertEveryConditionExercisedByCorpus is the shared coverage-manifest
// mechanism every corpus in this package uses (cfamily's own corpus, and
// go-rust's/jvm-swift's/java's own parity test files, each with their own
// conditions map) -- ONE mechanism, not a per-corpus copy, matching
// assertGoldenBytesMatchLiveOracle's own "one shared guard" shape. It
// exists to catch an ACCIDENTALLY unexercised condition keyword (exactly
// what caught #2266's missing Rust `where` fixture), not to certify
// tokenization correctness.
//
// BUG FIXED HERE (CHAOS-5156, codex round r2 on #2253, finding #3): two
// gaps in the original version, both closed by this rewrite:
//  1. It iterated every KEY in the conditions map without checking the
//     VALUE -- a coordinated mutation setting `"case": false` (still
//     present as a map key, just inert) would report `case` as covered
//     regardless. Fixed: skip any key whose value is not true.
//  2. It scanned RAW CORPUS TEXT for a keyword match, so an English
//     WORD inside a COMMENT (a real instance found by codex: the
//     phrase "switch-case" already present in a fixture's own comment)
//     counted as coverage for the literal keyword "case" even with
//     every real `case` statement removed from the corpus. Fixed:
//     TOKENIZE the corpus with this package's own shared tokenizer
//     (cLikeTokenPattern -- a real token stream, not a text scan) and
//     check for an EXACT token match, skipping every comment token
//     (isComment) and every string-literal token (isStringLikeToken) --
//     a coordinated mutation now has nowhere left to hide the keyword
//     except inside genuinely executable code.
//
// BUG FIXED HERE (CHAOS-5156, found live wiring #2268's own invocation,
// before any codex round -- moved here from #2268's own copy once
// #2253's r3 fix needed another commit anyway): the shared
// cLikeTokenPattern used for this scan has no per-language ADDITION
// (e.g. csharp.go's `??`), so a compound symbolic operator not in the
// base pattern gets split into separate single-char tokens ("??"
// tokenizes here as two "?" tokens) and never matches as one exact
// token, even though the real fixture genuinely uses it
// (basic.cs.txt:51's `x ?? -1`).
//
// BUG FIXED HERE (CHAOS-5156, cfamily confirmation pass, team-lead's
// ruling): the FIRST fix for that gap re-joined every surviving token
// into one string and used strings.Contains as a fallback for symbolic
// (non-alphabetic) keywords -- a workable idea, but string
// concatenation is not the same claim as token ADJACENCY. Two concrete
// gaps that shape allowed, both closed by replacing it with a per-file
// TOKEN SEQUENCE and a direct adjacency check instead:
//  1. C++ raw-string tokens (`R"(...)"`, optionally prefixed
//     u8/u/U/L) start with `R"`, not `"` or `'` -- isStringLikeToken
//     now also recognises this shape, so a `?` living only inside a
//     raw string's CONTENTS (e.g. `R"(?)"`) no longer satisfies
//     coverage for the `?` condition. Verified directly: a corpus
//     containing ONLY `R"(?)"` (no real ternary anywhere) used to pass
//     assertEveryConditionExercisedByCorpus(t, {"?":true}, dir).
//  2. A COMMENT sitting between two otherwise-adjacent symbolic
//     tokens (e.g. `? /* x */ ?`) used to be silently dropped from the
//     concatenation (comments are excluded), so the two `?` tokens
//     looked adjacent in the rebuilt string even though real source
//     had a comment between them -- a coordinated mutation could
//     "cover" `??` this way despite lizard's own tokenizer never
//     gluing across a comment. Now: comment/string tokens leave a
//     SENTINEL in the per-file sequence rather than vanishing, so
//     adjacency is checked against the position they actually held.
func assertEveryConditionExercisedByCorpus(t *testing.T, conditions map[string]bool, corpusDir string) {
	t.Helper()
	entries, err := os.ReadDir(corpusDir)
	if err != nil {
		t.Fatalf("read corpus dir: %v", err)
	}
	seen := map[string]bool{}
	var adjacentPairs = map[string]bool{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(corpusDir, entry.Name()))
		if err != nil {
			t.Fatalf("read %s: %v", entry.Name(), err)
		}
		var seq []string
		for _, tok := range cLikeTokenPattern.FindAllString(string(raw), -1) {
			if isComment(tok) || isStringLikeToken(tok) {
				seq = append(seq, "\x00") // sentinel: breaks adjacency, never matches anything
				continue
			}
			seen[tok] = true
			seq = append(seq, tok)
		}
		for i := 0; i+1 < len(seq); i++ {
			adjacentPairs[seq[i]+seq[i+1]] = true
		}
	}

	keys := make([]string, 0, len(conditions))
	for k, v := range conditions {
		if v {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)

	isAlphabetic := func(k string) bool {
		for _, r := range k {
			if !(unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_') {
				return false
			}
		}
		return k != ""
	}

	var uncovered []string
	for _, k := range keys {
		if seen[k] {
			continue
		}
		if !isAlphabetic(k) && adjacentPairs[k] {
			continue
		}
		uncovered = append(uncovered, k)
	}
	if len(uncovered) > 0 {
		t.Fatalf("condition keyword(s) never exercised by any corpus fixture in %s: %v -- "+
			"add a fixture using each one (a real lizard-measured golden entry, not a "+
			"hand-derived number) so a future regression in that specific keyword's "+
			"handling has something to catch it", corpusDir, uncovered)
	}
}

// assertEveryConditionExercisedByFilteredCorpus is
// assertEveryConditionExercisedByCorpus narrowed to fixtures whose name
// ends with suffix -- for a corpus dir SHARED by more than one language
// (go-rust's testdata/corpus_go_rust holds both .go.txt and .rs.txt
// fixtures side by side), the unfiltered version lets one language's
// keyword be satisfied by the OTHER language's fixture, since both share
// the same cLikeTokenPattern token stream and the same directory.
//
// BUG FIXED HERE (CHAOS-5156, codex round r2 on #2266): exactly this --
// TestEveryConditionIsExercisedByTheGoRustCorpus scanned the whole mixed
// corpus for both goConditions and rustConditions, so Rust's "catch"
// condition was silently satisfied by a Go-only fixture
// (catch_token_coverage.go.txt, no Rust code at all). Verified directly:
// deleting "catch": true from rustConditions entirely left every existing
// guard passing (golden staleness, coverage, no-unexpected-disabled,
// golden comparator) while the ACTUAL Rust behavior silently regressed
// (measured got=[1] vs lizard's real [2] for a bare `catch` identifier in
// a Rust fn, completely undetected).
//
// BUG FIXED HERE (CHAOS-5156, codex round r3 on #2266): this used
// cLikeTokenPattern (the plain base pattern) for EVERY suffix, but
// cLikeTokenPattern has no per-language addition -- it does not know Go's
// backtick raw strings, Rust's lifetimes, C#'s `??`, etc. A `?` inside a
// Go backtick string (basic.go.txt's own negative-test fixture,
// deliberately containing "if"/"&&"/"||"/"?" as a string literal so a
// real miscount would be caught) is glued into ONE token by Go's own
// goTokenPattern (correctly excluded from coverage) but split into
// separate real-looking tokens by cLikeTokenPattern, so the coverage
// scan falsely counted goConditions["?"] as covered by a STRING LITERAL,
// not real code -- confirmed directly: a synthetic corpus containing
// ONLY a backtick string with a "?" inside (no other "?" anywhere)
// passed the coverage check before this fix. Fixed: pick each suffix's
// OWN token pattern (matching what that language's real analyzer uses),
// falling back to cLikeTokenPattern only for an unrecognised suffix.
// BUG FIXED HERE (CHAOS-5156, go-rust confirmation pass): this used to
// FAIL OPEN for any suffix not in the switch (`default: return
// cLikeTokenPattern`) -- a future PR adding a new suffix without adding
// a case here would silently tokenize that language's fixtures with the
// PLAIN base pattern, reopening the exact backtick/raw-string/lifetime
// class of bug this whole mechanism exists to close, with no test
// failure to catch the omission (the comment warned about this but
// enforced nothing). Fixed: fail CLOSED -- an unregistered suffix is a
// test-authoring bug, not a legitimate "use the generic pattern" signal,
// so it fails loudly via t.Fatalf instead of silently choosing a
// pattern that might be wrong for that language.
//
// NOTE for downstream PRs (#2268/#2269): add a case here for each new
// suffix a later PR's own corpus introduces
// (.cs.txt/.kt.txt/.scala.txt/.swift.txt/.java.txt), pointing at that
// language's OWN *TokenPattern var -- ALWAYS, with NO exception, even
// when that language's own addition is the empty string (e.g. Scala's
// scalaTokenPattern = buildTokenPattern("")). "No addition" does NOT
// mean "identical to cLikeTokenPattern": cLikeTokenPattern itself is
// buildTokenPattern(cLikeAddition), where cLikeAddition is NON-empty
// (the C/C++ raw-string pattern) -- substituting cLikeTokenPattern for
// a language whose real analyzer tokenizes with a DIFFERENT pattern
// var is exactly the bug this function's own identity test below
// exists to catch (found in #2268's confirmation-pass round: the
// .scala.txt case below used to return cLikeTokenPattern by this
// exact wrong reasoning). If a language genuinely needs cLikeTokenPattern
// verbatim, its own *TokenPattern var must be DEFINED as
// buildTokenPattern("") (or whatever matches its real analyzer) and
// THAT var referenced here -- never a different language's pattern
// var, no matter how "equivalent" it looks.
func filteredCorpusTokenPattern(t *testing.T, suffix string) *regexp.Regexp {
	t.Helper()
	switch suffix {
	case ".go.txt":
		return goTokenPattern
	case ".rs.txt":
		return rustTokenPattern
	case ".cs.txt":
		return csharpTokenPattern
	case ".kt.txt":
		return kotlinTokenPattern
	case ".swift.txt":
		return swiftTokenPattern
	case ".scala.txt":
		return scalaTokenPattern
	default:
		t.Fatalf("filteredCorpusTokenPattern: no token pattern registered for suffix %q -- "+
			"add a case pointing at that language's own *TokenPattern var (see this "+
			"function's doc); do not let an unregistered suffix fall through silently", suffix)
		return nil
	}
}

// TestFilteredCorpusTokenPatternMatchesAnalyzerTokenizer closes the class
// #2268's confirmation-pass round found: filteredCorpusTokenPattern's
// .scala.txt case returned cLikeTokenPattern while AnalyzeScala's real
// tokenizer is scalaTokenPattern -- a DIFFERENT *regexp.Regexp (Scala's own
// addition is empty, but cLikeTokenPattern carries its own non-empty
// cLikeAddition, so the two patterns are not interchangeable). A coverage
// scan using the wrong pattern can disagree with what the real analyzer
// actually tokenizes, silently certifying "coverage" for tokens the real
// analyzer never reaches that way (or vice versa).
//
// This is a table-driven IDENTITY check (pointer equality on the package's
// global *regexp.Regexp vars -- valid and exact here, since
// filteredCorpusTokenPattern returns the SAME global var an Analyze*
// function calls FindAllString on, never a copy): for every suffix this
// package's coverage-manifest mechanism filters on, across every stack
// (go-rust, jvm-swift), assert the switch returns EXACTLY the *TokenPattern
// var its corresponding Analyze* function tokenizes with. This closes the
// class for good -- a future suffix case pointing at the wrong var fails
// this test immediately, rather than waiting for an adversarial reviewer
// to construct the right fixture.
func TestFilteredCorpusTokenPatternMatchesAnalyzerTokenizer(t *testing.T) {
	cases := []struct {
		suffix   string
		expected *regexp.Regexp
	}{
		{".go.txt", goTokenPattern},       // AnalyzeGo (go_lang.go)
		{".rs.txt", rustTokenPattern},     // AnalyzeRust (rust.go)
		{".cs.txt", csharpTokenPattern},   // AnalyzeCSharp (csharp.go)
		{".kt.txt", kotlinTokenPattern},   // AnalyzeKotlin (kotlin.go)
		{".swift.txt", swiftTokenPattern}, // AnalyzeSwift (swift.go)
		{".scala.txt", scalaTokenPattern}, // AnalyzeScala (scala.go)
	}
	for _, tc := range cases {
		t.Run(tc.suffix, func(t *testing.T) {
			got := filteredCorpusTokenPattern(t, tc.suffix)
			if got != tc.expected {
				t.Errorf("filteredCorpusTokenPattern(%q) returned a DIFFERENT *regexp.Regexp than "+
					"the analyzer actually tokenizes with (got %q, want %q) -- the coverage-manifest "+
					"scan and the real analyzer can now disagree on what a fixture's tokens are",
					tc.suffix, got.String(), tc.expected.String())
			}
		})
	}
}

// TestScalaCoverageScanDivergesFromCLikePatternOnRawStringShapedInput
// executes codex's exact #2268 confirmation-pass repro scenario directly
// (a Scala-suffixed file containing a C++-raw-string-SHAPED token that
// spans across a real condition keyword) and proves the RED/GREEN split
// this fix closes:
//
//   - RED (the OLD, buggy .scala.txt case): cLikeTokenPattern's raw-string
//     alternative (`(?:u8|u|U|L)?R"\(.*?\)"`) swallows the entire
//     `R"(a"if(x>0)"` span as ONE token -- "if" never appears as its own
//     token, so a coverage scan using cLikeTokenPattern would silently
//     certify NO coverage for "if" from this fixture even though the
//     source text plainly contains it.
//   - GREEN (the FIXED .scala.txt case): scalaTokenPattern has no
//     raw-string alternative at all (Scala's real tokenizer doesn't either
//     -- confirmed from lizard's Python source), so it tokenizes the same
//     input piecewise and "if" DOES appear as its own token.
//
// Verified empirically (bigboy scratch probe) before writing this in:
// FindAllString on this exact source under cLikeTokenPattern contains no
// "if" element; under scalaTokenPattern it does. This is a permanent
// regression test, not a one-off repro -- it fails again immediately if
// filteredCorpusTokenPattern's .scala.txt case (or scalaTokenPattern's own
// definition) ever regresses back toward cLikeTokenPattern's behavior.
func TestScalaCoverageScanDivergesFromCLikePatternOnRawStringShapedInput(t *testing.T) {
	const src = `R"(a"if(x>0)"b)" 1 else 0`

	hasToken := func(tokens []string, want string) bool {
		for _, tok := range tokens {
			if tok == want {
				return true
			}
		}
		return false
	}

	oldWrongTokens := cLikeTokenPattern.FindAllString(src, -1)
	if hasToken(oldWrongTokens, "if") {
		t.Fatalf("cLikeTokenPattern found \"if\" as a standalone token in %q -- this fixture no "+
			"longer demonstrates the RED case (the raw-string alternative used to swallow it); "+
			"pick a new repro string before trusting this test's GREEN half means anything", src)
	}

	fixedTokens := scalaTokenPattern.FindAllString(src, -1)
	if !hasToken(fixedTokens, "if") {
		t.Fatalf("scalaTokenPattern -- the FIXED, correct pattern for .scala.txt -- failed to find "+
			"\"if\" as a standalone token in %q; got tokens %#v -- the GREEN case is not actually "+
			"green", src, fixedTokens)
	}

	// Confirm filteredCorpusTokenPattern itself now routes .scala.txt to
	// the GREEN pattern, not the RED one -- this is the actual production
	// code path assertEveryConditionExercisedByFilteredCorpus calls.
	if got := filteredCorpusTokenPattern(t, ".scala.txt"); got != scalaTokenPattern {
		t.Fatalf("filteredCorpusTokenPattern(\".scala.txt\") = %q, want scalaTokenPattern (%q) -- "+
			"the coverage-manifest scan is not using the pattern this test just proved is correct",
			got.String(), scalaTokenPattern.String())
	}
}

func assertEveryConditionExercisedByFilteredCorpus(t *testing.T, conditions map[string]bool, corpusDir, suffix string) {
	t.Helper()
	entries, err := os.ReadDir(corpusDir)
	if err != nil {
		t.Fatalf("read corpus dir: %v", err)
	}
	pattern := filteredCorpusTokenPattern(t, suffix)
	seen := map[string]bool{}
	matched := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), suffix) {
			continue
		}
		matched++
		raw, err := os.ReadFile(filepath.Join(corpusDir, entry.Name()))
		if err != nil {
			t.Fatalf("read %s: %v", entry.Name(), err)
		}
		for _, tok := range pattern.FindAllString(string(raw), -1) {
			if isComment(tok) || isStringLikeToken(tok) {
				continue
			}
			seen[tok] = true
		}
	}
	if matched == 0 {
		t.Fatalf("no fixture in %s matches suffix %q; this test proved nothing", corpusDir, suffix)
	}

	keys := make([]string, 0, len(conditions))
	for k, v := range conditions {
		if v {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)

	var uncovered []string
	for _, k := range keys {
		if !seen[k] {
			uncovered = append(uncovered, k)
		}
	}
	if len(uncovered) > 0 {
		t.Fatalf("condition keyword(s) never exercised by any %q fixture in %s: %v -- "+
			"add a fixture (in THIS language, not a sibling sharing the same corpus dir) "+
			"using each one (a real lizard-measured golden entry, not a hand-derived "+
			"number) so a future regression in that specific keyword's handling has "+
			"something to catch it", suffix, corpusDir, uncovered)
	}
}

// rawStringPrefixPattern matches a C++ raw-string token's OPENING shape
// (tokenize.go's cLikeAddition: `(?:u8|u|U|L)?R"\(`) -- enough to
// recognise the token as a string literal without re-deriving the whole
// raw-string regex here.
var rawStringPrefixPattern = regexp.MustCompile(`^(?:u8|u|U|L)?R"\(`)

// isStringLikeToken reports whether tok is a string/char-literal token
// that assertEveryConditionExercisedByCorpus (and its filtered sibling,
// assertEveryConditionExercisedByFilteredCorpus) must exclude from
// coverage -- a condition keyword's TEXT appearing only inside a string
// literal is not the keyword being exercised as a real token. Ordinary
// `"..."`/`'...'` tokens are covered by their literal opening character;
// a C++ raw string opens with `R"` (or a u8/u/U/L prefix before it,
// which neither prefix check catches), and Go's backtick-quoted string
// opens with a backtick, which also needs its own check -- MERGED here
// (during go-rust's confirmation-pass merge-forward from cfamily) so
// both the shared and the filtered variant use the SAME literal-shape
// check instead of two copies that can drift apart.
func isStringLikeToken(tok string) bool {
	return strings.HasPrefix(tok, `"`) || strings.HasPrefix(tok, "'") ||
		strings.HasPrefix(tok, "`") || rawStringPrefixPattern.MatchString(tok)
}

// TestNoUnexpectedDisabledConditions closes the residual gap codex round
// r2's finding #3 disclosed: assertEveryConditionExercisedByCorpus's
// value==true check means a keyword set to `false` is silently EXCLUDED
// from coverage checking rather than flagged -- correct when a keyword is
// GENUINELY, deliberately disabled, but that also means a stealth
// `"case": false` edit (codex's own construction) passes every existing
// test without comment. This test closes it the same way this
// repository's own battery closes an equivalent gap with
// EXPECTED_SURVIVORS: any `false` value in `conditions` must be an entry
// in expectedDisabledConditions, each one argued in its own comment
// naming the specific lizard behavior that requires it disabled. The
// allowlist is EMPTY by default -- every lizard condition keyword this
// package knows about is active, so a silent disable has nowhere to hide
// without a reviewed allowlist edit.
func TestNoUnexpectedDisabledConditions(t *testing.T) {
	assertNoUnexpectedDisabledConditions(t, conditions, expectedDisabledConditions)
}

// expectedDisabledConditions is the reviewed allowlist for cfamily's own
// `conditions` map -- see TestNoUnexpectedDisabledConditions's doc. Empty:
// no condition keyword this package knows about is deliberately disabled
// today. Adding an entry here is a REVIEWED code change, not a silent one.
var expectedDisabledConditions = map[string]bool{}

// assertNoUnexpectedDisabledConditions is the shared mechanism every
// conditions map in this package uses (cfamily's own map here, and
// go-rust's/jvm-swift's/java's own per-language maps in their own parity
// test files, each with their own allowlist) -- ONE mechanism, matching
// this file's other two shared guards' "one mechanism, many invocations"
// shape.
func assertNoUnexpectedDisabledConditions(t *testing.T, conditions, allowlist map[string]bool) {
	t.Helper()
	keys := make([]string, 0, len(conditions))
	for k := range conditions {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var unexpected []string
	for _, k := range keys {
		if !conditions[k] && !allowlist[k] {
			unexpected = append(unexpected, k)
		}
	}
	if len(unexpected) > 0 {
		t.Fatalf("condition keyword(s) disabled (value false) with no matching entry in "+
			"the reviewed allowlist: %v -- either re-enable them, or add each one to the "+
			"allowlist with a comment naming the specific lizard behavior that requires "+
			"it disabled", unexpected)
	}
}

// TestConditionKeySetIsPinned closes codex round r3's finding #5 (on
// #2253): assertEveryConditionExercisedByCorpus only iterates keys
// PRESENT in the conditions map (skipping value==false ones), and
// assertNoUnexpectedDisabledConditions only inspects keys with value
// false -- neither one notices a key REMOVED from the map entirely. A
// coordinated attack deleting the `"case": true` entry, removing every
// real case-statement from the corpus, and regenerating the golden
// passes every other guard here: the mutation is internally consistent
// (real lizard genuinely has nothing to disagree with on the mutated
// corpus, and neither guard has a key left to complain about).
//
// Closed the same way the repository's own EXPECTED_SURVIVORS pattern
// closes an equivalent gap: the exact SET of keys a conditions map is
// allowed to have is pinned and reviewed. Adding OR removing a condition
// keyword now requires a reviewed edit to the pinned set in the SAME
// change, not just to the map.
func TestConditionKeySetIsPinned(t *testing.T) {
	assertConditionKeySetIsPinned(t, conditions, pinnedConditionKeys)
}

// pinnedConditionKeys is the reviewed, exact set of condition keywords
// cfamily's own `conditions` map (this file) is expected to contain --
// see TestConditionKeySetIsPinned's doc.
var pinnedConditionKeys = map[string]bool{
	"if": true, "for": true, "while": true, "catch": true,
	"&&": true, "||": true,
	"case": true,
	"?":    true,
}

// assertConditionKeySetIsPinned is the shared mechanism every conditions
// map in this package uses (cfamily's own map here, and
// go-rust's/jvm-swift's/java's own per-language maps in their own parity
// test files, each with their own pinned set) -- ONE mechanism, matching
// this file's other shared guards' "one mechanism, many invocations"
// shape.
func assertConditionKeySetIsPinned(t *testing.T, conditions map[string]bool, pinned map[string]bool) {
	t.Helper()
	var missing, unexpected []string
	for k := range pinned {
		if _, ok := conditions[k]; !ok {
			missing = append(missing, k)
		}
	}
	for k := range conditions {
		if _, ok := pinned[k]; !ok {
			unexpected = append(unexpected, k)
		}
	}
	sort.Strings(missing)
	sort.Strings(unexpected)
	if len(missing) > 0 {
		t.Errorf("condition keyword(s) pinned but missing from the map: %v -- "+
			"if removing one is deliberate, update the pinned set in the SAME reviewed "+
			"change, with a comment naming why lizard no longer needs it", missing)
	}
	if len(unexpected) > 0 {
		t.Errorf("condition keyword(s) present in the map but not in the pinned set: %v -- "+
			"add a fixture exercising it AND add it to the pinned set in the SAME "+
			"reviewed change", unexpected)
	}
}
