package lizardcc

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// This file mirrors clike_parity_test.go's contract for the two readers
// this PR adds: Go and Rust. It reuses that file's oracleDoc/oracleFile/
// oracleFunction JSON shape, complexityDiff/itoa helpers, and
// sameMultiset from jvmswift_parity_test.go -- only the corpus directory,
// golden path, and per-extension dispatch differ.

func goRustGoldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "lizard_cc_golden_go_rust.json")
}

func goRustCorpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus_go_rust")
}

func loadGoRustGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(goRustGoldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

// TestLizardGoldenIsNotStaleGoRust closes codex round r1 finding #6 (the
// P2 raised specifically against this PR: "no live-lizard staleness guard
// on the go-rust golden") by calling the shared mechanism cfamily's
// clike_parity_test.go defines -- ONE mechanism, this PR's own invocation.
func TestLizardGoldenIsNotStaleGoRust(t *testing.T) {
	assertGoldenBytesMatchLiveOracle(t, goRustCorpusDir(t), goRustGoldenPath(t))
}

// TestEveryConditionIsExercisedByTheGoRustCorpus is this PR's own
// invocation of the shared coverage-manifest mechanism (finding #6's
// narrower half) -- this is the generic check that would have caught the
// missing Rust `where` fixture (now added, testdata/corpus_go_rust/
// where_clause.rs.txt) without needing a codex round to spot it by hand.
// goConditions and rustConditions are asserted separately since a keyword
// unique to one language (e.g. Rust's "where") legitimately never appears
// in the other's fixtures.
// BUG FIXED HERE (CHAOS-5156, codex round r2 on #2266): this used to call
// the unfiltered assertEveryConditionExercisedByCorpus for BOTH
// languages against the same shared corpus_go_rust directory -- Rust's
// "catch" coverage was silently satisfied by a Go-only fixture that
// contains no Rust code at all. Fixed: each language's own suffix-filtered
// invocation, so a keyword can only be satisfied by a fixture actually
// written in that language.
func TestEveryConditionIsExercisedByTheGoRustCorpus(t *testing.T) {
	assertEveryConditionExercisedByFilteredCorpus(t, goConditions, goRustCorpusDir(t), ".go.txt")
	assertEveryConditionExercisedByFilteredCorpus(t, rustConditions, goRustCorpusDir(t), ".rs.txt")
}

func TestGoldenPinnedToLockedLizardGoRust(t *testing.T) {
	golden := loadGoRustGolden(t)
	locked := lockedLizardVersion(t)
	if golden.LizardVersion != locked {
		t.Fatalf("golden was generated by lizard %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a lizard upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.LizardVersion, locked)
	}
}

func TestGoMatchesLizardGoldenGoRust(t *testing.T) {
	doc := loadGoRustGolden(t)

	entries, err := os.ReadDir(goRustCorpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++
		realName := strings.TrimSuffix(name, ".txt")
		var analyze func(string, string) ([]int, bool, error)
		switch {
		case strings.HasSuffix(realName, ".go"):
			analyze = AnalyzeGo
		case strings.HasSuffix(realName, ".rs"):
			analyze = AnalyzeRust
		default:
			t.Fatalf("%s: no analyzer registered for this extension", realName)
		}

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(goRustCorpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			complexities, skipped, err := analyze(realName, string(src))
			if err != nil {
				t.Fatalf("lizard analysed %s but Go failed: %v", name, err)
			}
			if skipped {
				t.Fatalf("Go skipped %s but the fixture is expected to analyse", name)
			}

			if got := len(complexities); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, lizard %d\n%s",
					got, expected.FunctionsCount, complexityDiff(complexities, expected.Functions))
			}
			total, high, veryHigh := 0, 0, 0
			for _, c := range complexities {
				total += c
				if c > 15 {
					high++
				}
				if c > 25 {
					veryHigh++
				}
			}
			if total != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, lizard %d\n%s",
					total, expected.CyclomaticTotal, complexityDiff(complexities, expected.Functions))
			}
			if high != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, lizard %d", high, expected.HighComplexityFunctions)
			}
			if veryHigh != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, lizard %d", veryHigh, expected.VeryHighComplexityFunction)
			}

			// Multiset, not declaration order -- same reasoning as
			// jvmswift_parity_test.go: GoLikeStates' clone-based body
			// tracking can close functions in an order that does not
			// match their source position (e.g. a closure defined
			// before, but closing after, code that follows it).
			want := make([]int, len(expected.Functions))
			for i, f := range expected.Functions {
				want[i] = f.Complexity
			}
			if !sameMultiset(complexities, want) {
				t.Errorf("complexities (multiset): got %v, lizard %v (by declaration order: %s)",
					complexities, want, complexityDiff(complexities, expected.Functions))
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

// TestNoUnexpectedDisabledGoRustConditions is this PR's own invocation of
// the shared allowlist mechanism (cfamily's TestNoUnexpectedDisabledConditions
// doc) -- empty allowlists for both maps: no condition keyword either
// reader knows about is deliberately disabled today.
func TestNoUnexpectedDisabledGoRustConditions(t *testing.T) {
	assertNoUnexpectedDisabledConditions(t, goConditions, map[string]bool{})
	assertNoUnexpectedDisabledConditions(t, rustConditions, map[string]bool{})
}

// pinnedGoConditionKeys/pinnedRustConditionKeys and
// TestGoRustConditionKeySetIsPinned are this PR's own invocation of the
// shared key-set-pinning mechanism cfamily's clike_parity_test.go defines
// (see TestConditionKeySetIsPinned's doc there for the deletion attack it
// closes) -- proactively wired here rather than waiting for a codex round
// to find the same gap against goConditions/rustConditions specifically.
var pinnedGoConditionKeys = map[string]bool{
	"if": true, "for": true, "while": true, "catch": true,
	"&&": true, "||": true,
	"case": true,
	"?":    true,
}

var pinnedRustConditionKeys = map[string]bool{
	"if": true, "for": true, "while": true, "catch": true,
	"match": true, "where": true,
	"&&": true, "||": true,
	"?": true,
}

func TestGoRustConditionKeySetIsPinned(t *testing.T) {
	assertConditionKeySetIsPinned(t, goConditions, pinnedGoConditionKeys)
	assertConditionKeySetIsPinned(t, rustConditions, pinnedRustConditionKeys)
}
