package lizardcc

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// This file mirrors clike_parity_test.go's contract for Java, reusing that
// file's oracleDoc/oracleFile/oracleFunction JSON shape and
// complexityDiff/itoa helpers, and jvmswift_parity_test.go's sameMultiset
// (order is not a safe invariant here either -- see this file's own test
// for why).

func javaGoldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "lizard_cc_golden_java.json")
}

func javaCorpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus_java")
}

func loadJavaGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(javaGoldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

func TestGoldenPinnedToLockedLizardJava(t *testing.T) {
	golden := loadJavaGolden(t)
	locked := lockedLizardVersion(t)
	if golden.LizardVersion != locked {
		t.Fatalf("golden was generated by lizard %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a lizard upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.LizardVersion, locked)
	}
}

// TestGoMatchesLizardGoldenJava proves numeric equality with real lizard
// 1.23.0 for this package's Java analyzer, the same contract every other
// reader in this port holds. Complexities are compared as a MULTISET, not
// declaration order, for the same reason jvmswift_parity_test.go does:
// javaMachine's sub_state recursion (java.go) can close a nested function
// (an anonymous class's method, a local class's method) before or after
// its enclosing one depending on where the NEXT unrelated brace happens to
// fall, not strictly by source position.
func TestGoMatchesLizardGoldenJava(t *testing.T) {
	doc := loadJavaGolden(t)

	entries, err := os.ReadDir(javaCorpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++
		realName := strings.TrimSuffix(name, ".txt")

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(javaCorpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			complexities, skipped, err := AnalyzeJava(realName, string(src))
			if err != nil {
				t.Fatalf("lizard analysed %s but Go failed: %v", name, err)
			}
			if skipped {
				t.Fatalf("Go skipped %s but the fixture is expected to analyse", name)
			}

			if got := len(complexities); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, lizard %d\n%s",
					got, expected.FunctionsCount, complexityDiff(complexities, expected.Functions))
			}
			total, high, veryHigh := 0, 0, 0
			for _, c := range complexities {
				total += c
				if c > 15 {
					high++
				}
				if c > 25 {
					veryHigh++
				}
			}
			if total != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, lizard %d\n%s",
					total, expected.CyclomaticTotal, complexityDiff(complexities, expected.Functions))
			}
			if high != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, lizard %d", high, expected.HighComplexityFunctions)
			}
			if veryHigh != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, lizard %d", veryHigh, expected.VeryHighComplexityFunction)
			}

			want := make([]int, len(expected.Functions))
			for i, f := range expected.Functions {
				want[i] = f.Complexity
			}
			if !sameMultiset(complexities, want) {
				t.Errorf("complexities (multiset): got %v, lizard %v (by declaration order: %s)",
					complexities, want, complexityDiff(complexities, expected.Functions))
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

// TestLizardGoldenIsNotStaleJava closes codex round r1 finding #6 (the P2
// raised specifically against this PR: no live-lizard staleness guard on
// the java golden) by calling the shared mechanism cfamily's
// clike_parity_test.go defines -- ONE mechanism, this PR's own invocation.
func TestLizardGoldenIsNotStaleJava(t *testing.T) {
	assertGoldenBytesMatchLiveOracle(t, javaCorpusDir(t), javaGoldenPath(t))
}

// TestEveryConditionIsExercisedByTheJavaCorpus is this PR's own invocation
// of the shared coverage-manifest mechanism (finding #6's narrower half).
// Java has no conditions map of its own -- AnalyzeJava reuses clike.go's
// shared `conditions` map directly -- so this asserts against that one.
func TestEveryConditionIsExercisedByTheJavaCorpus(t *testing.T) {
	assertEveryConditionExercisedByCorpus(t, conditions, javaCorpusDir(t))
}
