package lizardcc

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// This file mirrors clike_parity_test.go's contract exactly (numeric
// equality with real lizard 1.23.0, not resemblance) for the four readers
// PR2b adds: C#, Kotlin, Scala, Swift. It reuses that file's oracleDoc/
// oracleFile/oracleFunction JSON shape and complexityDiff/itoa helpers --
// only the corpus directory, golden path, and per-extension dispatch to
// the right AnalyzerFunc differ.

func jvmSwiftGoldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "lizard_cc_golden_jvm_swift.json")
}

func jvmSwiftCorpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus_jvm_swift")
}

func loadJVMSwiftGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(jvmSwiftGoldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

// analyzerForExt dispatches a corpus filename's REAL extension (the
// segment before the corpus convention's trailing ".txt") to the
// AnalyzerFunc this test is proving parity for.
func analyzerForExt(t *testing.T, realName string) func(string, string) ([]int, bool, error) {
	t.Helper()
	switch {
	case strings.HasSuffix(realName, ".cs"):
		return AnalyzeCSharp
	case strings.HasSuffix(realName, ".kt"):
		return AnalyzeKotlin
	case strings.HasSuffix(realName, ".scala"):
		return AnalyzeScala
	case strings.HasSuffix(realName, ".swift"):
		return AnalyzeSwift
	}
	t.Fatalf("%s: no analyzer registered for this extension", realName)
	return nil
}

// sameMultiset reports whether got and want hold the same values, any
// order -- see this file's doc comment on why order isn't asserted for
// this family.
func sameMultiset(got, want []int) bool {
	if len(got) != len(want) {
		return false
	}
	counts := map[int]int{}
	for _, v := range got {
		counts[v]++
	}
	for _, v := range want {
		counts[v]--
	}
	for _, c := range counts {
		if c != 0 {
			return false
		}
	}
	return true
}

func TestGoldenPinnedToLockedLizardJVMSwift(t *testing.T) {
	golden := loadJVMSwiftGolden(t)
	locked := lockedLizardVersion(t)
	if golden.LizardVersion != locked {
		t.Fatalf("golden was generated by lizard %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a lizard upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.LizardVersion, locked)
	}
}

func TestGoMatchesLizardGoldenJVMSwift(t *testing.T) {
	doc := loadJVMSwiftGolden(t)

	entries, err := os.ReadDir(jvmSwiftCorpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++
		realName := strings.TrimSuffix(name, ".txt")
		analyze := analyzerForExt(t, realName)

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(jvmSwiftCorpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			complexities, skipped, err := analyze(realName, string(src))
			if err != nil {
				t.Fatalf("lizard analysed %s but Go failed: %v", name, err)
			}
			if skipped {
				t.Fatalf("Go skipped %s but the fixture is expected to analyse", name)
			}

			if got := len(complexities); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, lizard %d\n%s",
					got, expected.FunctionsCount, complexityDiff(complexities, expected.Functions))
			}
			total, high, veryHigh := 0, 0, 0
			for _, c := range complexities {
				total += c
				if c > 15 {
					high++
				}
				if c > 25 {
					veryHigh++
				}
			}
			if total != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, lizard %d\n%s",
					total, expected.CyclomaticTotal, complexityDiff(complexities, expected.Functions))
			}
			if high != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, lizard %d", high, expected.HighComplexityFunctions)
			}
			if veryHigh != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, lizard %d", veryHigh, expected.VeryHighComplexityFunction)
			}

			// Multiset comparison, NOT declaration order: unlike CLikeReader
			// (clike_parity_test.go asserts exact append order), a
			// GoLikeStates expression-bodied function's clone can span
			// past every sibling that follows it in the source (measured
			// directly: a Kotlin `fun a(...) = expr` followed by a
			// brace-bodied `fun b`, both inside one class, appends b
			// BEFORE a -- a closes only when the CLASS's own brace does).
			// The golden's "functions" list is sorted by source line for
			// readability (python_lizard_cc_oracle.py), which is exactly
			// the order this reordering breaks, so only the multiset is a
			// safe cross-implementation invariant here.
			want := make([]int, len(expected.Functions))
			for i, f := range expected.Functions {
				want[i] = f.Complexity
			}
			if !sameMultiset(complexities, want) {
				t.Errorf("complexities (multiset): got %v, lizard %v (by declaration order: %s)",
					complexities, want, complexityDiff(complexities, expected.Functions))
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

// TestLizardGoldenIsNotStaleJVMSwift closes codex round r1 finding #6 (the
// P2 raised specifically against this PR: no live-lizard staleness guard
// on the jvm-swift golden) by calling the shared mechanism cfamily's
// clike_parity_test.go defines -- ONE mechanism, this PR's own invocation.
func TestLizardGoldenIsNotStaleJVMSwift(t *testing.T) {
	assertGoldenBytesMatchLiveOracle(t, jvmSwiftCorpusDir(t), jvmSwiftGoldenPath(t))
}

// TestEveryConditionIsExercisedByTheJVMSwiftCorpus is this PR's own
// invocation of the shared coverage-manifest mechanism (finding #6's
// narrower half) -- the generic check that would catch a condition
// keyword accidentally left unexercised by any fixture, the same class as
// #2266's missing Rust `where` and go-rust's missing `catch` coverage.
//
// BUG FIXED HERE (CHAOS-5156, codex round r3 on #2268): this used the
// UNFILTERED assertEveryConditionExercisedByCorpus for all four maps
// against the SAME mixed corpus_jvm_swift directory -- the exact class
// #2266 r2 found for go-rust (Rust's "catch" satisfied by a Go-only
// fixture). Verified directly: deleting `"?": true` from swiftConditions
// left every existing guard passing (no Swift fixture has a genuine `?`
// at all; only C#'s basic.cs.txt:19 does) while the ACTUAL Swift
// behavior would silently regress. Fixed: each language's own
// suffix-filtered invocation, matching go-rust's own fix.
func TestEveryConditionIsExercisedByTheJVMSwiftCorpus(t *testing.T) {
	assertEveryConditionExercisedByFilteredCorpus(t, csharpConditions, jvmSwiftCorpusDir(t), ".cs.txt")
	assertEveryConditionExercisedByFilteredCorpus(t, kotlinConditions, jvmSwiftCorpusDir(t), ".kt.txt")
	assertEveryConditionExercisedByFilteredCorpus(t, scalaConditions, jvmSwiftCorpusDir(t), ".scala.txt")
	assertEveryConditionExercisedByFilteredCorpus(t, swiftConditions, jvmSwiftCorpusDir(t), ".swift.txt")
}

// TestNoUnexpectedDisabledJVMSwiftConditions is this PR's own invocation
// of the shared allowlist mechanism (cfamily's
// TestNoUnexpectedDisabledConditions doc) -- empty allowlists for all
// four maps: no condition keyword any of these four readers knows about
// is deliberately disabled today.
func TestNoUnexpectedDisabledJVMSwiftConditions(t *testing.T) {
	assertNoUnexpectedDisabledConditions(t, csharpConditions, map[string]bool{})
	assertNoUnexpectedDisabledConditions(t, kotlinConditions, map[string]bool{})
	assertNoUnexpectedDisabledConditions(t, scalaConditions, map[string]bool{})
	assertNoUnexpectedDisabledConditions(t, swiftConditions, map[string]bool{})
}

// pinnedCSharpConditionKeys/pinnedKotlinConditionKeys/
// pinnedScalaConditionKeys/pinnedSwiftConditionKeys and
// TestJVMSwiftConditionKeySetIsPinned are this PR's own invocation of the
// shared key-set-pinning mechanism cfamily's clike_parity_test.go defines
// (see TestConditionKeySetIsPinned's doc there for the deletion attack it
// closes) -- fixed alongside the filtered-coverage fix above (codex round
// r3 on #2268), since the two guards work as defense-in-depth (a deleted
// key makes the filtered-coverage check pass vacuously, but the pinned
// key-set check still catches it).
var pinnedCSharpConditionKeys = map[string]bool{
	"if": true, "for": true, "while": true, "catch": true,
	"&&": true, "||": true,
	"case": true,
	"?":    true, "??": true,
}

var pinnedKotlinConditionKeys = map[string]bool{
	"if": true, "for": true, "while": true, "catch": true,
	"&&": true, "||": true,
	"?:": true,
}

var pinnedScalaConditionKeys = map[string]bool{
	"if": true, "for": true, "while": true, "catch": true, "do": true,
	"&&": true, "||": true,
	"case": true,
	"?":    true,
}

var pinnedSwiftConditionKeys = map[string]bool{
	"if": true, "for": true, "while": true, "catch": true, "guard": true,
	"&&": true, "||": true,
	"case": true,
	"?":    true,
}

func TestJVMSwiftConditionKeySetIsPinned(t *testing.T) {
	assertConditionKeySetIsPinned(t, csharpConditions, pinnedCSharpConditionKeys)
	assertConditionKeySetIsPinned(t, kotlinConditions, pinnedKotlinConditionKeys)
	assertConditionKeySetIsPinned(t, scalaConditions, pinnedScalaConditionKeys)
	assertConditionKeySetIsPinned(t, swiftConditions, pinnedSwiftConditionKeys)
}
