package lizardcc

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// This file mirrors ruby_parity_test.go's contract for Lua, reusing that
// file's shared oracleDoc/oracleFile/oracleFunction JSON shape,
// complexityDiff/itoa helpers, and jvmswift_parity_test.go's sameMultiset:
// luaMachine wraps rubyMachine (lua.go), which sub_states into nested
// clones the exact same way plain Ruby does, so a nested function/block
// can close before or after an unrelated sibling depending on where the
// next brace/keyword falls, not strictly by source position -- the same
// justification ruby_parity_test.go's own doc gives.

func luaGoldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "lizard_cc_golden_lua.json")
}

func luaCorpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus_lua")
}

func loadLuaGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(luaGoldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

func TestGoldenPinnedToLockedLizardLua(t *testing.T) {
	golden := loadLuaGolden(t)
	locked := lockedLizardVersion(t)
	if golden.LizardVersion != locked {
		t.Fatalf("golden was generated by lizard %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a lizard upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.LizardVersion, locked)
	}
}

// TestGoMatchesLizardGoldenLua proves numeric equality with real lizard
// 1.23.0 for this package's Lua analyzer.
func TestGoMatchesLizardGoldenLua(t *testing.T) {
	doc := loadLuaGolden(t)

	entries, err := os.ReadDir(luaCorpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++
		realName := strings.TrimSuffix(name, ".txt")

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(luaCorpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			complexities, skipped, err := AnalyzeLua(realName, string(src))
			if err != nil {
				t.Fatalf("lizard analysed %s but Go failed: %v", name, err)
			}
			if skipped {
				t.Fatalf("Go skipped %s but the fixture is expected to analyse", name)
			}

			if got := len(complexities); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, lizard %d\n%s",
					got, expected.FunctionsCount, complexityDiff(complexities, expected.Functions))
			}
			total, high, veryHigh := 0, 0, 0
			for _, c := range complexities {
				total += c
				if c > 15 {
					high++
				}
				if c > 25 {
					veryHigh++
				}
			}
			if total != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, lizard %d\n%s",
					total, expected.CyclomaticTotal, complexityDiff(complexities, expected.Functions))
			}
			if high != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, lizard %d", high, expected.HighComplexityFunctions)
			}
			if veryHigh != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, lizard %d", veryHigh, expected.VeryHighComplexityFunction)
			}

			want := make([]int, len(expected.Functions))
			for i, f := range expected.Functions {
				want[i] = f.Complexity
			}
			if !sameMultiset(complexities, want) {
				t.Errorf("complexities (multiset): got %v, lizard %v (by declaration order: %s)",
					complexities, want, complexityDiff(complexities, expected.Functions))
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

// TestLizardGoldenIsNotStaleLua reuses clike_parity_test.go's shared
// live-oracle staleness gate (DEV_HEALTH_LIVE_PYTHON_ORACLE-gated, not run
// by default).
func TestLizardGoldenIsNotStaleLua(t *testing.T) {
	assertGoldenBytesMatchLiveOracle(t, luaCorpusDir(t), luaGoldenPath(t))
}

// TestEveryConditionIsExercisedByTheLuaCorpus is this PR's own invocation
// of the shared coverage-manifest mechanism: every member of rubyConditions
// (ruby.go -- reused unmodified by Lua, see lua.go's AnalyzeLua doc) must
// appear at least once in this corpus.
func TestEveryConditionIsExercisedByTheLuaCorpus(t *testing.T) {
	assertEveryConditionExercisedByCorpus(t, rubyConditions, luaCorpusDir(t))
}
