package lizardcc

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// This file mirrors clike_parity_test.go's contract for Objective-C,
// reusing that file's oracleDoc/oracleFile/oracleFunction JSON shape,
// complexityDiff/itoa helpers, and sameOrdered: like plain CLikeReader
// (and unlike every subMachine-based reader in this package), objcMachine
// never sub_states -- nesting is tracked entirely by nestingStates'
// brace-depth stack (shared with clike.go/csharp.go), so functions always
// close in exactly declaration order, the strongest comparison available.

func objcGoldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "lizard_cc_golden_objc.json")
}

func objcCorpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus_objc")
}

func loadObjCGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(objcGoldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

func TestGoldenPinnedToLockedLizardObjC(t *testing.T) {
	golden := loadObjCGolden(t)
	locked := lockedLizardVersion(t)
	if golden.LizardVersion != locked {
		t.Fatalf("golden was generated by lizard %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a lizard upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.LizardVersion, locked)
	}
}

// TestGoMatchesLizardGoldenObjC proves numeric equality with real lizard
// 1.23.0 for this package's Objective-C analyzer, including
// const_qualifier_quirk.m.txt -- a deliberately isolated fixture proving
// ObjCStates' own restart-on-any-non-brace-token bug (objc.go's
// stateDecToImp doc) is reproduced exactly: the real "realFn" declaration
// is discarded, replaced by a single bogus function named after the
// "const" qualifier.
func TestGoMatchesLizardGoldenObjC(t *testing.T) {
	doc := loadObjCGolden(t)

	entries, err := os.ReadDir(objcCorpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++
		realName := strings.TrimSuffix(name, ".txt")

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(objcCorpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			complexities, skipped, err := AnalyzeObjC(realName, string(src))
			if err != nil {
				t.Fatalf("lizard analysed %s but Go failed: %v", name, err)
			}
			if skipped {
				t.Fatalf("Go skipped %s but the fixture is expected to analyse", name)
			}

			if got := len(complexities); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, lizard %d\n%s",
					got, expected.FunctionsCount, complexityDiff(complexities, expected.Functions))
			}
			total, high, veryHigh := 0, 0, 0
			for _, c := range complexities {
				total += c
				if c > 15 {
					high++
				}
				if c > 25 {
					veryHigh++
				}
			}
			if total != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, lizard %d\n%s",
					total, expected.CyclomaticTotal, complexityDiff(complexities, expected.Functions))
			}
			if high != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, lizard %d", high, expected.HighComplexityFunctions)
			}
			if veryHigh != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, lizard %d", veryHigh, expected.VeryHighComplexityFunction)
			}

			wantOrdered := make([]int, len(expected.Functions))
			for i, f := range expected.Functions {
				wantOrdered[i] = f.Complexity
			}
			if !sameOrdered(complexities, wantOrdered) {
				t.Errorf("ordered complexities: got %v, lizard %v (by declaration order: %s)",
					complexities, wantOrdered, complexityDiff(complexities, expected.Functions))
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

// TestLizardGoldenIsNotStaleObjC reuses clike_parity_test.go's shared
// live-oracle staleness gate (DEV_HEALTH_LIVE_PYTHON_ORACLE-gated, not run
// by default).
func TestLizardGoldenIsNotStaleObjC(t *testing.T) {
	assertGoldenBytesMatchLiveOracle(t, objcCorpusDir(t), objcGoldenPath(t))
}

// TestEveryConditionIsExercisedByTheObjCCorpus is this PR's own invocation
// of the shared coverage-manifest mechanism: every member of clike.go's
// shared `conditions` map (ObjCReader defines no condition-category
// override of its own, so AnalyzeObjC reuses it directly, same as Java)
// must appear at least once in this corpus.
func TestEveryConditionIsExercisedByTheObjCCorpus(t *testing.T) {
	assertEveryConditionExercisedByCorpus(t, conditions, objcCorpusDir(t))
}
