package lizardcc

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// This file mirrors java_parity_test.go's contract for PHP, reusing that
// file's oracleDoc/oracleFile/oracleFunction JSON shape and
// complexityDiff/itoa helpers. Complexities are compared by DECLARATION
// ORDER, not as a multiset -- unlike every subMachine-based reader in this
// package, phpMachine (php.go) is FLAT: it never sub_states, so functions
// always close in exactly the order lizard itself reports them.

func phpGoldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "lizard_cc_golden_php.json")
}

func phpCorpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus_php")
}

func loadPHPGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(phpGoldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

func TestGoldenPinnedToLockedLizardPHP(t *testing.T) {
	golden := loadPHPGolden(t)
	locked := lockedLizardVersion(t)
	if golden.LizardVersion != locked {
		t.Fatalf("golden was generated by lizard %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a lizard upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.LizardVersion, locked)
	}
}

// TestGoMatchesLizardGoldenPHP proves numeric equality with real lizard
// 1.23.0 for this package's PHP analyzer, including
// interface_return_type_quirk.php.txt -- a deliberately isolated fixture
// proving PHPLanguageStates' own stuck-state bug (php.go's
// stateFunctionBodyOrReturnType doc) is reproduced exactly, down to
// reporting ZERO functions for that file.
func TestGoMatchesLizardGoldenPHP(t *testing.T) {
	doc := loadPHPGolden(t)

	entries, err := os.ReadDir(phpCorpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++
		realName := strings.TrimSuffix(name, ".txt")

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(phpCorpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			complexities, skipped, err := AnalyzePHP(realName, string(src))
			if err != nil {
				t.Fatalf("lizard analysed %s but Go failed: %v", name, err)
			}
			if skipped {
				t.Fatalf("Go skipped %s but the fixture is expected to analyse", name)
			}

			if got := len(complexities); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, lizard %d\n%s",
					got, expected.FunctionsCount, complexityDiff(complexities, expected.Functions))
			}
			total, high, veryHigh := 0, 0, 0
			for _, c := range complexities {
				total += c
				if c > 15 {
					high++
				}
				if c > 25 {
					veryHigh++
				}
			}
			if total != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, lizard %d\n%s",
					total, expected.CyclomaticTotal, complexityDiff(complexities, expected.Functions))
			}
			if high != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, lizard %d", high, expected.HighComplexityFunctions)
			}
			if veryHigh != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, lizard %d", veryHigh, expected.VeryHighComplexityFunction)
			}

			if len(complexities) != len(expected.Functions) {
				t.Fatalf("complexity count mismatch, cannot compare by order: got %d, lizard %d",
					len(complexities), len(expected.Functions))
			}
			for i, f := range expected.Functions {
				if complexities[i] != f.Complexity {
					t.Errorf("complexities (declaration order): got %v, lizard %v (function #%d %q: got %d, lizard %d)",
						complexities, expected.Functions, i, f.Name, complexities[i], f.Complexity)
					break
				}
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

// TestLizardGoldenIsNotStalePHP reuses clike_parity_test.go's shared
// live-oracle staleness gate (DEV_HEALTH_LIVE_PYTHON_ORACLE-gated, not run
// by default).
func TestLizardGoldenIsNotStalePHP(t *testing.T) {
	assertGoldenBytesMatchLiveOracle(t, phpCorpusDir(t), phpGoldenPath(t))
}

// TestEveryConditionIsExercisedByThePHPCorpus is this PR's own invocation
// of the shared coverage-manifest mechanism: every member of phpConditions
// (php.go) must appear at least once in the corpus, or a coordinated
// mutation removing it from both the map and the corpus would pass
// silently.
func TestEveryConditionIsExercisedByThePHPCorpus(t *testing.T) {
	assertEveryConditionExercisedByCorpus(t, phpConditions, phpCorpusDir(t))
}

// TestPHPHeredocScanIgnoresLtLtLtInsideOrdinaryStrings is CHAOS-5328 r1's
// F1 regression: an ordinary PHP string literal whose content happens to
// start with "<<<" (a plausible real-world shape, e.g. building SQL/shell
// text) must never be mistaken for a heredoc/nowdoc opener. Before the
// fix, phpExtractHeredocs (php_tokenize.go) scanned RAW code text for a
// bare "<<<" BEFORE tokenization, found it inside this string, and split
// the string's raw text in half at that point -- the string's own closing
// quote survived with no partner, corrupting every token for the REST OF
// THE FILE and silently dropping every function that followed (0
// functions found instead of 1). Confirmed against real lizard 1.23.0:
// expected complexity [2] (function f, one `if`).
func TestPHPHeredocScanIgnoresLtLtLtInsideOrdinaryStrings(t *testing.T) {
	src := "<?php\n$s = '<<<SQL if';\nfunction f() { if (true) { return 1; } }\n"
	complexities, skipped, err := AnalyzePHP("regression_string_lt3.php", src)
	if err != nil {
		t.Fatalf("AnalyzePHP: %v", err)
	}
	if skipped {
		t.Fatalf("expected the file to be analysed, got skipped")
	}
	if want := []int{2}; !reflect.DeepEqual(complexities, want) {
		t.Fatalf("got %v, want %v (lizard 1.23.0 reference)", complexities, want)
	}
}

// TestPHPRealHeredocStillExtractedAfterTheStringAwareFix is the negative
// control for the fix above: a GENUINE heredoc must still be spliced as
// one opaque token by the now string/comment-aware scan, not broken by
// making the scan too conservative in the other direction.
func TestPHPRealHeredocStillExtractedAfterTheStringAwareFix(t *testing.T) {
	src := "<?php\n$s = <<<EOT\nhello world\nEOT;\nfunction f() { if (true) { return 1; } }\n"
	complexities, skipped, err := AnalyzePHP("regression_real_heredoc.php", src)
	if err != nil {
		t.Fatalf("AnalyzePHP: %v", err)
	}
	if skipped {
		t.Fatalf("expected the file to be analysed, got skipped")
	}
	if want := []int{2}; !reflect.DeepEqual(complexities, want) {
		t.Fatalf("got %v, want %v (lizard 1.23.0 reference)", complexities, want)
	}
}
