package lizardcc

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// This file mirrors java_parity_test.go's contract for JavaScript/
// TypeScript, reusing clike_parity_test.go's oracleDoc/oracleFile/
// oracleFunction JSON shape, complexityDiff/itoa helpers,
// assertGoldenBytesMatchLiveOracle/assertEveryConditionExercisedByCorpus,
// and jvmswift_parity_test.go's sameMultiset -- sub_state recursion here
// (a nested arrow/method literal) can close a nested function before or
// after its enclosing one depending on where the next unrelated brace
// falls, not strictly by source position, so complexities are compared as
// a MULTISET, not declaration order, same as every other GoLikeStates-
// shaped reader in this package.

func jsTSGoldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "lizard_cc_golden_js_ts.json")
}

func jsTSCorpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus_js_ts")
}

func loadJSTSGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(jsTSGoldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

func TestGoldenPinnedToLockedLizardJSTS(t *testing.T) {
	golden := loadJSTSGolden(t)
	locked := lockedLizardVersion(t)
	if golden.LizardVersion != locked {
		t.Fatalf("golden was generated by lizard %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a lizard upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.LizardVersion, locked)
	}
}

// analyzerForCorpusFile routes a corpus file to AnalyzeTypeScript or
// AnalyzeJavaScript by its embedded extension, matching
// compute.go's languageByExtension split for "typescript" (.ts/.tsx) vs
// "javascript" (.js/.jsx/.mjs/.cjs) -- exercising BOTH entry points against
// ONE shared golden/corpus, since both are the identical function under
// Python's inheritance (see typescript.go's AnalyzeJavaScript doc).
func analyzerForCorpusFile(realName string) func(path, source string) ([]int, bool, error) {
	if strings.HasSuffix(realName, ".js") {
		return AnalyzeJavaScript
	}
	return AnalyzeTypeScript
}

// TestGoMatchesLizardGoldenJSTS proves numeric equality with real lizard
// 1.23.0 for this package's TypeScript/JavaScript analyzer.
func TestGoMatchesLizardGoldenJSTS(t *testing.T) {
	doc := loadJSTSGolden(t)

	entries, err := os.ReadDir(jsTSCorpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++
		realName := strings.TrimSuffix(name, ".txt")
		analyze := analyzerForCorpusFile(realName)

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(jsTSCorpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			complexities, skipped, err := analyze(realName, string(src))
			if err != nil {
				t.Fatalf("lizard analysed %s but Go failed: %v", name, err)
			}
			if skipped {
				t.Fatalf("Go skipped %s but the fixture is expected to analyse", name)
			}

			if got := len(complexities); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, lizard %d\n%s",
					got, expected.FunctionsCount, complexityDiff(complexities, expected.Functions))
			}
			total, high, veryHigh := 0, 0, 0
			for _, c := range complexities {
				total += c
				if c > 15 {
					high++
				}
				if c > 25 {
					veryHigh++
				}
			}
			if total != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, lizard %d\n%s",
					total, expected.CyclomaticTotal, complexityDiff(complexities, expected.Functions))
			}
			if high != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, lizard %d", high, expected.HighComplexityFunctions)
			}
			if veryHigh != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, lizard %d", veryHigh, expected.VeryHighComplexityFunction)
			}

			want := make([]int, len(expected.Functions))
			for i, f := range expected.Functions {
				want[i] = f.Complexity
			}
			if !sameMultiset(complexities, want) {
				t.Errorf("complexities (multiset): got %v, lizard %v (by declaration order: %s)",
					complexities, want, complexityDiff(complexities, expected.Functions))
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

// TestLizardGoldenIsNotStaleJSTS reuses clike_parity_test.go's shared
// live-oracle staleness gate (DEV_HEALTH_LIVE_PYTHON_ORACLE-gated, not run
// by default).
func TestLizardGoldenIsNotStaleJSTS(t *testing.T) {
	assertGoldenBytesMatchLiveOracle(t, jsTSCorpusDir(t), jsTSGoldenPath(t))
}

// TestEveryConditionIsExercisedByTheJSTSCorpus is this PR's own invocation
// of the shared coverage-manifest mechanism: every member of tsConditions
// (typescript.go) must appear at least once in the corpus, or a
// coordinated mutation removing it from both the map and the corpus would
// pass silently.
func TestEveryConditionIsExercisedByTheJSTSCorpus(t *testing.T) {
	assertEveryConditionExercisedByCorpus(t, tsConditions, jsTSCorpusDir(t))
}

// TestInterfaceAndTypeAliasContributeNoFunctions pins a TypeScript-specific
// behaviour lizard measures that has no C-family/GoLike-family analogue:
// an `interface` body and a `type X = ...` alias are both skipped entirely
// by TypeScriptStates (typescript.py:171-233) -- neither's method
// signatures nor arrow-typed fields are runtime functions. types_interfaces.ts.txt
// is built specifically to exercise this: only its two real function
// declarations/object-literal methods should be counted, never the
// interface's or type alias's own signatures.
func TestInterfaceAndTypeAliasContributeNoFunctions(t *testing.T) {
	doc := loadJSTSGolden(t)
	expected, ok := doc.Files["types_interfaces.ts.txt"]
	if !ok {
		t.Fatalf("golden missing types_interfaces.ts.txt -- corpus/golden drifted apart")
	}
	// Golden proof: lizard itself (not just this port) treats interface
	// method signatures and type-alias arrow types as non-functions --
	// makeGreeter's OWN two object-literal methods (greet/farewell),
	// useHandler, and withGeneric are the ONLY real functions; Greeter's
	// two interface method signatures and Handler's arrow-typed alias
	// contribute nothing, on the REAL tool's own measurement.
	if expected.FunctionsCount != 4 {
		t.Fatalf("fixture assumption drifted: lizard now reports %d functions for "+
			"types_interfaces.ts.txt, expected 4 (greet, farewell, useHandler, "+
			"withGeneric) -- update this test's expectation only after reviewing why",
			expected.FunctionsCount)
	}

	src, err := os.ReadFile(filepath.Join(jsTSCorpusDir(t), "types_interfaces.ts.txt"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	complexities, skipped, err := AnalyzeTypeScript("types_interfaces.ts", string(src))
	if err != nil {
		t.Fatalf("AnalyzeTypeScript: %v", err)
	}
	if skipped {
		t.Fatalf("AnalyzeTypeScript skipped the fixture unexpectedly")
	}
	if len(complexities) != 4 {
		t.Errorf("got %d functions, want 4 (interface/type-alias bodies must contribute none): %v",
			len(complexities), complexities)
	}
}
