package lizardcc

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// This file mirrors typescript_parity_test.go's contract for Vue, reusing
// clike_parity_test.go's shared oracleDoc/oracleFile/oracleFunction JSON
// shape, complexityDiff/itoa helpers, and jvmswift_parity_test.go's
// sameMultiset -- VueReader runs the exact same TypeScriptStates
// (typescript.go) unmodified, so the same sub_state-recursion-can-close-
// out-of-source-order justification applies.

func vueGoldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "lizard_cc_golden_vue.json")
}

func vueCorpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus_vue")
}

func loadVueGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(vueGoldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

func TestGoldenPinnedToLockedLizardVue(t *testing.T) {
	golden := loadVueGolden(t)
	locked := lockedLizardVersion(t)
	if golden.LizardVersion != locked {
		t.Fatalf("golden was generated by lizard %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a lizard upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.LizardVersion, locked)
	}
}

// TestGoMatchesLizardGoldenVue proves numeric equality with real lizard
// 1.23.0 for this package's Vue analyzer, including two_script_blocks.vue.txt
// -- a fixture proving BOTH a plain <script> and a <script setup> block in
// the same Single-File-Component are captured independently (vue.go's
// vuePreprocess), and that <template>/<style> content contributes nothing
// at all.
func TestGoMatchesLizardGoldenVue(t *testing.T) {
	doc := loadVueGolden(t)

	entries, err := os.ReadDir(vueCorpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++
		realName := strings.TrimSuffix(name, ".txt")

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(vueCorpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			complexities, skipped, err := AnalyzeVue(realName, string(src))
			if err != nil {
				t.Fatalf("lizard analysed %s but Go failed: %v", name, err)
			}
			if skipped {
				t.Fatalf("Go skipped %s but the fixture is expected to analyse", name)
			}

			if got := len(complexities); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, lizard %d\n%s",
					got, expected.FunctionsCount, complexityDiff(complexities, expected.Functions))
			}
			total, high, veryHigh := 0, 0, 0
			for _, c := range complexities {
				total += c
				if c > 15 {
					high++
				}
				if c > 25 {
					veryHigh++
				}
			}
			if total != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, lizard %d\n%s",
					total, expected.CyclomaticTotal, complexityDiff(complexities, expected.Functions))
			}
			if high != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, lizard %d", high, expected.HighComplexityFunctions)
			}
			if veryHigh != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, lizard %d", veryHigh, expected.VeryHighComplexityFunction)
			}

			want := make([]int, len(expected.Functions))
			for i, f := range expected.Functions {
				want[i] = f.Complexity
			}
			if !sameMultiset(complexities, want) {
				t.Errorf("complexities (multiset): got %v, lizard %v (by declaration order: %s)",
					complexities, want, complexityDiff(complexities, expected.Functions))
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

// TestLizardGoldenIsNotStaleVue reuses clike_parity_test.go's shared
// live-oracle staleness gate (DEV_HEALTH_LIVE_PYTHON_ORACLE-gated, not run
// by default).
func TestLizardGoldenIsNotStaleVue(t *testing.T) {
	assertGoldenBytesMatchLiveOracle(t, vueCorpusDir(t), vueGoldenPath(t))
}

// TestEveryConditionIsExercisedByTheVueCorpus is this PR's own invocation
// of the shared coverage-manifest mechanism: every member of tsConditions
// (typescript.go -- reused unmodified by Vue, see vue.go's AnalyzeVue doc)
// must appear at least once in this corpus.
func TestEveryConditionIsExercisedByTheVueCorpus(t *testing.T) {
	assertEveryConditionExercisedByCorpus(t, tsConditions, vueCorpusDir(t))
}
