package operational

import (
	"embed"
	"errors"
	"fmt"
	"os"
	"strings"
)

// CHAOS-5353: the seven billing email bodies, ported verbatim from the Python
// `src/dev_health_ops/templates/email/` copies that `billing_emails.py`
// rendered. They are embedded rather than read from disk so the worker binary
// carries its own bodies and cannot silently render a different revision than
// the one its golden fixtures were frozen against.
//
// The Python renderer was `EmailService.render_template`, i.e. plain
// `str.format(**context)` over the file text -- NOT Jinja. Every one of the
// seven files was verified brace-clean (each `{` opens a bare `{identifier}`
// placeholder; no `{{`/`}}` escapes, no format specs, no indices), so
// `formatTemplate` below reproduces it byte-for-byte. The
// `testdata/billing_email/*.json` fixtures were generated by running the real
// Python path once, before it was deleted, and are the frozen proof of that.
//
//go:embed templates/*.html
var billingTemplates embed.FS

// ErrUnknownEmailType is a permanent, data-shaped condition: a stored
// notification_type outside the seven this handler renders. Retrying cannot
// change a stored value, so callers classify it as a permanent drop -- the
// same outcome Python's `_PermanentBillingDrop("unknown_email_type")` had.
var ErrUnknownEmailType = errors.New("operational billing email type is unsupported")

// ErrTemplatePlaceholder reports a template placeholder that has no value in
// the render context, mirroring the KeyError `str.format` raised.
var ErrTemplatePlaceholder = errors.New("operational billing email template placeholder is unresolved")

// The seven notification_type values `billing_emails.py` dispatched on.
const (
	EmailTypeInvoiceReceipt       = "invoice_receipt"
	EmailTypePaymentFailed        = "payment_failed"
	EmailTypeSubscriptionChanged  = "subscription_changed"
	EmailTypeSubscriptionCanceled = "subscription_cancelled"
	EmailTypeTrialStarted         = "trial_started"
	EmailTypeTrialExpiring        = "trial_expiring"
	EmailTypeTrialExpired         = "trial_expired"
)

// BillingAttributes is the decoded `billing_notifications.attributes` JSONB
// payload. Field defaults match Python's `attributes.get(name, default)` calls
// in `system_ops.send_billing_notification`, so a key absent from the stored
// row renders exactly as it did there.
type BillingAttributes struct {
	AmountCents   int64
	Currency      string
	InvoiceURL    string
	AttemptCount  int64
	OldTier       string
	NewTier       string
	Tier          string
	DaysRemaining int64
	TrialEndDate  string
}

// OwnerContact is the organization owner row `get_org_owner_email` resolved.
// FullName carries Python's "there" fallback for a NULL/empty users.full_name.
type OwnerContact struct {
	Email    string
	FullName string
	OrgName  string
}

// RenderedEmail is one fully-resolved message, ready for a provider.
type RenderedEmail struct {
	Subject string
	HTML    string
}

// RenderBillingEmail builds the subject and HTML body for one notification.
//
// It is a pure function of its inputs (appBaseURL is passed rather than read
// from the environment) so the golden fixtures can pin every byte.
func RenderBillingEmail(
	emailType string,
	attributes BillingAttributes,
	owner OwnerContact,
	appBaseURL string,
) (RenderedEmail, error) {
	base := normalizeAppBaseURL(appBaseURL)
	context := map[string]string{
		"full_name": owner.FullName,
		"org_name":  owner.OrgName,
	}
	var subject string
	switch emailType {
	case EmailTypeInvoiceReceipt:
		subject = "Invoice receipt"
		context["amount"] = formatAmountCents(attributes.AmountCents)
		context["currency"] = strings.ToUpper(attributes.Currency)
		context["invoice_url"] = attributes.InvoiceURL
	case EmailTypePaymentFailed:
		subject = "Invoice payment failed"
		context["amount"] = formatAmountCents(attributes.AmountCents)
		context["currency"] = strings.ToUpper(attributes.Currency)
		context["attempt_count"] = fmt.Sprintf("%d", attributes.AttemptCount)
	case EmailTypeSubscriptionChanged:
		subject = "Subscription changed"
		context["old_tier"] = attributes.OldTier
		context["new_tier"] = attributes.NewTier
	case EmailTypeSubscriptionCanceled:
		subject = "Subscription cancelled"
		context["tier"] = attributes.Tier
	case EmailTypeTrialStarted:
		tier := displayTier(attributes.Tier)
		subject = fmt.Sprintf("Your %s trial has started", tier)
		context["tier"] = tier
		context["trial_end_date"] = attributes.TrialEndDate
		context["dashboard_url"] = base + "/"
	case EmailTypeTrialExpiring:
		tier := displayTier(attributes.Tier)
		subject = fmt.Sprintf("Your %s trial ends in %d days", tier, attributes.DaysRemaining)
		context["tier"] = tier
		context["days_remaining"] = fmt.Sprintf("%d", attributes.DaysRemaining)
		context["trial_end_date"] = attributes.TrialEndDate
		context["upgrade_url"] = base + "/billing"
	case EmailTypeTrialExpired:
		tier := displayTier(attributes.Tier)
		subject = fmt.Sprintf("Your %s trial has ended", tier)
		context["tier"] = tier
		context["upgrade_url"] = base + "/billing"
	default:
		return RenderedEmail{}, fmt.Errorf("%w: %q", ErrUnknownEmailType, emailType)
	}

	raw, err := billingTemplates.ReadFile("templates/" + emailType + ".html")
	if err != nil {
		// Unreachable while the embed and the switch agree; a mismatch is a
		// build-time defect, not a data condition, so it is reported rather
		// than silently rendering an empty body.
		return RenderedEmail{}, fmt.Errorf("operational billing email template is missing: %w", err)
	}
	html, err := formatTemplate(string(raw), context)
	if err != nil {
		return RenderedEmail{}, err
	}
	return RenderedEmail{Subject: subject, HTML: html}, nil
}

// SupportedEmailType reports whether RenderBillingEmail can render the type.
func SupportedEmailType(emailType string) bool {
	switch emailType {
	case EmailTypeInvoiceReceipt, EmailTypePaymentFailed, EmailTypeSubscriptionChanged,
		EmailTypeSubscriptionCanceled, EmailTypeTrialStarted, EmailTypeTrialExpiring,
		EmailTypeTrialExpired:
		return true
	default:
		return false
	}
}

// displayTier ports `billing_emails._display_tier`: a blank or
// whitespace-only tier renders as "Team".
func displayTier(tier string) string {
	trimmed := strings.TrimSpace(tier)
	if trimmed == "" {
		return "Team"
	}
	return trimmed
}

// normalizeAppBaseURL ports `billing_emails._app_base_url`: APP_BASE_URL with
// trailing slashes stripped, defaulting to https://example.com.
func normalizeAppBaseURL(raw string) string {
	if raw == "" {
		raw = "https://example.com"
	}
	return strings.TrimRight(raw, "/")
}

// AppBaseURLFromEnv reads the same APP_BASE_URL variable Python read. Kept
// separate from normalizeAppBaseURL so rendering itself stays pure.
func AppBaseURLFromEnv() string {
	return normalizeAppBaseURL(os.Getenv("APP_BASE_URL"))
}

// formatAmountCents ports `f"{Decimal(amount_cents) / 100:.2f}"`.
//
// Decimal(int)/100 is exact -- it never rounds -- so integer arithmetic
// reproduces it for every int64 without any float64 in the path. The sign is
// taken before the split so -5 renders "-0.05", not "-0.-5".
func formatAmountCents(cents int64) string {
	sign := ""
	magnitude := cents
	if magnitude < 0 {
		sign = "-"
		// Negating math.MinInt64 overflows; its magnitude is handled by
		// converting through the unsigned range instead.
		if magnitude == -9223372036854775808 {
			return "-92233720368547758.08"
		}
		magnitude = -magnitude
	}
	return fmt.Sprintf("%s%d.%02d", sign, magnitude/100, magnitude%100)
}

// formatTemplate reproduces Python `str.format(**context)` for the subset the
// seven billing templates use: literal text, `{{`/`}}` escapes, and bare
// `{identifier}` replacement fields.
//
// Anything richer -- a format spec, conversion, index, or attribute access --
// is REJECTED rather than guessed at. That is deliberate: the point of this
// function is byte-parity with a renderer that no longer exists, so a template
// that grows a construct this does not model must fail loudly at the first
// render instead of quietly diverging from its frozen golden fixture.
func formatTemplate(template string, context map[string]string) (string, error) {
	var out strings.Builder
	out.Grow(len(template))
	for index := 0; index < len(template); {
		char := template[index]
		if char == '}' {
			if index+1 < len(template) && template[index+1] == '}' {
				out.WriteByte('}')
				index += 2
				continue
			}
			return "", fmt.Errorf(
				"%w: single '}' at offset %d", ErrTemplatePlaceholder, index)
		}
		if char != '{' {
			out.WriteByte(char)
			index++
			continue
		}
		if index+1 < len(template) && template[index+1] == '{' {
			out.WriteByte('{')
			index += 2
			continue
		}
		end := strings.IndexByte(template[index+1:], '}')
		if end < 0 {
			return "", fmt.Errorf(
				"%w: unterminated placeholder at offset %d", ErrTemplatePlaceholder, index)
		}
		name := template[index+1 : index+1+end]
		if !plainFieldName(name) {
			return "", fmt.Errorf(
				"%w: unsupported replacement field %q", ErrTemplatePlaceholder, name)
		}
		value, ok := context[name]
		if !ok {
			// Python raised KeyError here. Same class of failure: the
			// template asked for a value the caller never supplied.
			return "", fmt.Errorf("%w: %q", ErrTemplatePlaceholder, name)
		}
		out.WriteString(value)
		index += end + 2
	}
	return out.String(), nil
}

// plainFieldName accepts only a non-empty ASCII identifier, which is the whole
// vocabulary the seven templates use.
func plainFieldName(name string) bool {
	if name == "" {
		return false
	}
	for index := 0; index < len(name); index++ {
		char := name[index]
		switch {
		case char >= 'a' && char <= 'z':
		case char >= 'A' && char <= 'Z':
		case char == '_':
		case char >= '0' && char <= '9' && index > 0:
		default:
			return false
		}
	}
	return true
}
