package pycc

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// The parity contract for this package is numeric equality with radon
// 6.0.1, not resemblance. Two tests enforce it from opposite directions:
//
//   - TestGoMatchesRadonGolden runs offline on every CI leg and compares
//     the Go implementation to a checked-in golden.
//   - TestRadonGoldenIsNotStale re-derives the golden from the real radon
//     and fails if the checked-in bytes have drifted. Without it the
//     golden could be silently regenerated FROM the Go side, at which
//     point the parity test would be comparing Go to itself -- the exact
//     failure mode that makes an oracle worthless.

type oracleBlock struct {
	Name       string `json:"name"`
	Kind       string `json:"kind"`
	Lineno     int    `json:"lineno"`
	ColOffset  int    `json:"col_offset"`
	Complexity int    `json:"complexity"`
}

type oracleFile struct {
	Skipped                    bool          `json:"skipped"`
	Reason                     string        `json:"reason"`
	LOC                        int           `json:"loc"`
	FunctionsCount             int           `json:"functions_count"`
	CyclomaticTotal            int           `json:"cyclomatic_total"`
	CyclomaticAvg              float64       `json:"cyclomatic_avg"`
	HighComplexityFunctions    int           `json:"high_complexity_functions"`
	VeryHighComplexityFunction int           `json:"very_high_complexity_functions"`
	Blocks                     []oracleBlock `json:"blocks"`
}

type oracleDoc struct {
	RadonVersion string                `json:"radon_version"`
	Files        map[string]oracleFile `json:"files"`
}

func goldenPath(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "radon_cc_golden.json")
}

func corpusDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "corpus")
}

func loadGolden(t *testing.T) oracleDoc {
	t.Helper()
	raw, err := os.ReadFile(goldenPath(t))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var doc oracleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(doc.Files) == 0 {
		// A golden that parses but describes nothing would let every
		// assertion below pass vacuously.
		t.Fatalf("golden describes no files; it cannot prove parity")
	}
	return doc
}

func kindName(k BlockKind) string {
	switch k {
	case BlockFunction:
		return "function"
	case BlockClass:
		return "class"
	case BlockMethod:
		return "method"
	}
	return "unknown"
}

// lockedRadonVersion reads the resolved radon pin out of uv.lock.
//
// uv.lock is the authority, not an installed interpreter: pyproject.toml
// declares `radon>=6.0.1`, a FLOOR, so "whatever is importable" can drift
// above the version these numbers were derived from without anything
// noticing. Reading the lock also keeps this test honest about WHERE the
// pin came from -- an earlier revision of this work took the version from
// a developer's own virtualenv, which is both unreproducible and a tree
// this lane has no business reading.
func lockedRadonVersion(t *testing.T) string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "..", "uv.lock"))
	if err != nil {
		t.Fatalf("read uv.lock: %v", err)
	}
	lines := strings.Split(string(raw), "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) != `name = "radon"` {
			continue
		}
		for _, follow := range lines[i+1 : min(i+5, len(lines))] {
			trimmed := strings.TrimSpace(follow)
			if strings.HasPrefix(trimmed, "version = ") {
				return strings.Trim(strings.TrimPrefix(trimmed, "version = "), `"`)
			}
		}
	}
	t.Fatalf("no radon entry in uv.lock; the oracle has no version of record")
	return ""
}

func TestGoldenPinnedToLockedRadon(t *testing.T) {
	golden := loadGolden(t)
	locked := lockedRadonVersion(t)
	if golden.RadonVersion != locked {
		t.Fatalf("golden was generated by radon %q but uv.lock pins %q. "+
			"Regenerate the golden under the locked version and re-review the "+
			"numbers -- a radon upgrade can legitimately change complexity, and "+
			"that change must be seen rather than absorbed.",
			golden.RadonVersion, locked)
	}
}

func TestGoMatchesRadonGolden(t *testing.T) {
	doc := loadGolden(t)

	entries, err := os.ReadDir(corpusDir(t))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	seen := 0
	for _, entry := range entries {
		// The corpus is named *.py.txt, not *.py, so no Python tool treats it
		// as source. ruff-format rewrote all three when they were committed as
		// .py -- expanding one-line suites and collapsing continuations -- and
		// every test still passed, because formatting does not change
		// complexity. The corpus silently stopped exercising the lexical
		// shapes it exists for. A ruff `exclude` does not prevent this:
		// `exclude` governs discovery, and lefthook hands ruff an explicit
		// staged-file list, which bypasses it without `force-exclude`.
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".py.txt") {
			continue
		}
		name := entry.Name()
		expected, ok := doc.Files[name]
		if !ok {
			t.Fatalf("corpus file %s has no golden entry -- regenerate the golden", name)
		}
		seen++

		t.Run(name, func(t *testing.T) {
			src, err := os.ReadFile(filepath.Join(corpusDir(t), name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			blocks, err := Visit(string(src), Options{})

			if expected.Skipped {
				if err == nil {
					t.Fatalf("radon skipped %s (%s) but Go parsed it; a file the "+
						"oracle drops must produce NO row on either side",
						name, expected.Reason)
				}
				return
			}
			if err != nil {
				t.Fatalf("radon analysed %s but Go failed: %v", name, err)
			}

			if got := LineCount(string(src)); got != expected.LOC {
				t.Errorf("loc: got %d, radon %d", got, expected.LOC)
			}
			if got := len(blocks); got != expected.FunctionsCount {
				t.Errorf("functions_count: got %d, radon %d\n%s",
					got, expected.FunctionsCount, blockDiff(blocks, expected.Blocks))
			}
			if got := TotalComplexity(blocks); got != expected.CyclomaticTotal {
				t.Errorf("cyclomatic_total: got %d, radon %d\n%s",
					got, expected.CyclomaticTotal, blockDiff(blocks, expected.Blocks))
			}
			if got := CountAbove(blocks, 15); got != expected.HighComplexityFunctions {
				t.Errorf("high_complexity_functions: got %d, radon %d",
					got, expected.HighComplexityFunctions)
			}
			if got := CountAbove(blocks, 25); got != expected.VeryHighComplexityFunction {
				t.Errorf("very_high_complexity_functions: got %d, radon %d",
					got, expected.VeryHighComplexityFunction)
			}

			// Per-block comparison by NAME rather than by position: a
			// whole-list diff would report every block as wrong the
			// moment one is missing, hiding which rule actually broke.
			byName := map[string][]int{}
			for _, b := range blocks {
				byName[b.Name] = append(byName[b.Name], b.Complexity)
			}
			for _, want := range expected.Blocks {
				got, ok := byName[want.Name]
				if !ok {
					t.Errorf("block %q (%s, radon complexity %d) missing from Go output",
						want.Name, want.Kind, want.Complexity)
					continue
				}
				found := false
				for _, c := range got {
					if c == want.Complexity {
						found = true
						break
					}
				}
				if !found {
					t.Errorf("block %q (%s): Go %v, radon %d",
						want.Name, want.Kind, got, want.Complexity)
				}
			}
		})
	}
	if seen == 0 {
		t.Fatalf("no corpus files found; this test proved nothing")
	}
}

func blockDiff(got []Block, want []oracleBlock) string {
	var b strings.Builder
	b.WriteString("  go blocks:\n")
	sorted := append([]Block(nil), got...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Line < sorted[j].Line })
	for _, blk := range sorted {
		b.WriteString("    " + kindName(blk.Kind) + " " + blk.Name + " = " +
			itoa(blk.Complexity) + "\n")
	}
	b.WriteString("  radon blocks:\n")
	for _, blk := range want {
		b.WriteString("    " + blk.Kind + " " + blk.Name + " = " +
			itoa(blk.Complexity) + "\n")
	}
	return b.String()
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var digits []byte
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	if neg {
		return "-" + string(digits)
	}
	return string(digits)
}

// TestRadonGoldenIsNotStale re-runs the real radon and compares its output
// to the checked-in golden. It is skipped unless the live-oracle gate is
// set, matching internal/synccoverage's convention -- radon must be
// importable, which is true in the gate's environment and not guaranteed on
// every CI leg.
func TestRadonGoldenIsNotStale(t *testing.T) {
	if os.Getenv("DEV_HEALTH_LIVE_PYTHON_ORACLE") == "" {
		t.Skip("live Python oracle runs only through the uncached live-oracle gate")
	}

	python := os.Getenv("DEV_HEALTH_PYTHON")
	if python == "" {
		python = "python3"
	}
	script := filepath.Join("testdata", "python_radon_cc_oracle.py")
	command := exec.Command(python, script, corpusDir(t))
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("radon oracle failed: %v\n%s", err, output)
	}

	var live oracleDoc
	if err := json.Unmarshal(output, &live); err != nil {
		t.Fatalf("parse oracle output: %v\n%s", err, output)
	}
	golden := loadGolden(t)

	if live.RadonVersion != golden.RadonVersion {
		t.Fatalf("radon version moved: golden %q, installed %q. Regenerate the "+
			"golden and re-review the numbers -- a version bump can legitimately "+
			"change complexity, and that change must be seen, not absorbed.",
			golden.RadonVersion, live.RadonVersion)
	}
	for name, want := range live.Files {
		got, ok := golden.Files[name]
		if !ok {
			t.Errorf("corpus file %s missing from golden", name)
			continue
		}
		if got.CyclomaticTotal != want.CyclomaticTotal ||
			got.FunctionsCount != want.FunctionsCount {
			t.Errorf("golden stale for %s: golden total=%d count=%d, radon total=%d count=%d",
				name, got.CyclomaticTotal, got.FunctionsCount,
				want.CyclomaticTotal, want.FunctionsCount)
		}
	}
}
