package daily

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"

	"github.com/full-chaos/dev-health-ops/internal/jobs/metrics/testops"
)

// TestComputePipelineStabilityMatchesLivePythonBitExact is the CHAOS-4818
// regression test for the tenth site found by codex round 3 on PR #2106
// (P1, EXECUTED): computePipelineStability's successRate7d/num/den
// compound-assignment accumulators (`successRate7d += m.SuccessRate *
// weights[i]`, `num += (...)*( ...)`, `den += (...)*(...)`) were unguarded
// -- `go tool objdump` showed live FMADDD/FMSUBD instructions there, a
// per-step FMA fusion distinct from the CHAOS-4824 compensated-sum() issue
// already deferred to PR #2107 on this same accumulator.
//
// Expectations come from tests/fixtures/pipeline_stability_fma_golden.json,
// originally generated by IMPORTING and calling the live production
// compute_pipeline_stability -- never hand-derived. CHAOS-5245 deleted
// compute_testops_risk.py (and with it the standalone live-Python generator
// script this fixture used to be regenerated from, plus
// TestPipelineStabilityFMAGoldenMatchesLivePython, the rot guard that re-ran
// that generator every CI run to catch the frozen file drifting from Python)
// -- the native Go executor has no Python fallback left to drift against, so
// this FROZEN file plus this test are now the permanent contract. Tests the
// STORED (4-decimal-rounded) SuccessRate7d/
// SuccessRateTrend fields, matching what computePipelineStability itself
// returns.
func TestComputePipelineStabilityMatchesLivePythonBitExact(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "tests", "fixtures", "pipeline_stability_fma_golden.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		PipelineStability []struct {
			SuccessRates         []float64 `json:"success_rates"`
			SuccessRate7dBits    string    `json:"success_rate_7d_bits"`
			SuccessRateTrendBits string    `json:"success_rate_trend_bits"`
		} `json:"pipeline_stability"`
	}
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if len(fixture.PipelineStability) == 0 {
		t.Fatal("fixture has no pipeline_stability cases")
	}

	repoID := uuid.MustParse("00000000-0000-4000-8000-00000000000a")
	day := time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC)
	computedAt := time.Date(2026, 9, 2, 0, 0, 0, 0, time.UTC)

	mismatches := 0
	for _, testCase := range fixture.PipelineStability {
		dayEntries := make([]testops.PipelineMetric, len(testCase.SuccessRates))
		for i, rate := range testCase.SuccessRates {
			dayEntries[i] = testops.PipelineMetric{
				RepoID:         repoID,
				PipelinesCount: 10,
				SuccessCount:   8,
				FailureCount:   1,
				CancelledCount: 1,
				SuccessRate:    rate,
				FailureRate:    0.1,
				CancelRate:     0.1,
				RerunRate:      0.0,
			}
		}
		row := computePipelineStability(repoID, day, dayEntries, computedAt)
		if row == nil {
			t.Fatalf("computePipelineStability(%v) returned nil", testCase.SuccessRates)
		}
		wantRate := parseBitsHexDaily(t, testCase.SuccessRate7dBits)
		gotRate := math.Float64bits(row.SuccessRate7d)
		if gotRate != wantRate {
			mismatches++
			t.Errorf("SuccessRate7d(%v) = %v (bits %#x), want bits %#x (%v)",
				testCase.SuccessRates, row.SuccessRate7d, gotRate, wantRate, math.Float64frombits(wantRate))
		}
		wantTrend := parseBitsHexDaily(t, testCase.SuccessRateTrendBits)
		gotTrend := math.Float64bits(row.SuccessRateTrend)
		if gotTrend != wantTrend {
			mismatches++
			t.Errorf("SuccessRateTrend(%v) = %v (bits %#x), want bits %#x (%v)",
				testCase.SuccessRates, row.SuccessRateTrend, gotTrend, wantTrend, math.Float64frombits(wantTrend))
		}
	}
	if mismatches > 0 {
		t.Errorf("%d mismatches across %d cases", mismatches, len(fixture.PipelineStability))
	}
}

func parseBitsHexDaily(t *testing.T, hex string) uint64 {
	t.Helper()
	value, err := strconv.ParseUint(strings.TrimPrefix(hex, "0x"), 16, 64)
	if err != nil {
		t.Fatalf("parse bits %q: %v", hex, err)
	}
	return value
}
