package daily

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/google/uuid"

	"github.com/full-chaos/dev-health-ops/internal/jobs/metrics/numerical"
)

// wellbeingMultiRepoGoldenExpectedRow decodes one expected row of the
// "team_wellbeing_multi_repo_partition" golden section -- see
// wellbeingExpectedRow's sibling comment in wellbeing_parity_test.go (a
// different package) for why this needs its own json-tagged struct rather
// than reusing numerical.TeamWellbeingMetric directly.
type wellbeingMultiRepoGoldenExpectedRow struct {
	TeamID                 string  `json:"team_id"`
	TeamName               string  `json:"team_name"`
	CommitsCount           int     `json:"commits_count"`
	AfterHoursCommitsCount int     `json:"after_hours_commits_count"`
	WeekendCommitsCount    int     `json:"weekend_commits_count"`
	AfterHoursCommitRatio  float64 `json:"after_hours_commit_ratio"`
	WeekendCommitRatio     float64 `json:"weekend_commit_ratio"`
}

func (row wellbeingMultiRepoGoldenExpectedRow) asMetric() numerical.TeamWellbeingMetric {
	return numerical.TeamWellbeingMetric(row)
}

type wellbeingMultiRepoGoldenFixture struct {
	TeamWellbeingMultiRepoPartition []struct {
		Label          string   `json:"label"`
		Day            string   `json:"day"`
		RepoIDsInOrder []string `json:"repo_ids_in_order"`
		Rows           []struct {
			RepoID        string  `json:"repo_id"`
			CommitHash    string  `json:"commit_hash"`
			AuthorEmail   *string `json:"author_email"`
			AuthorName    *string `json:"author_name"`
			CommitterWhen string  `json:"committer_when"`
		} `json:"rows"`
		RepoNamesByID      map[string]string                     `json:"repo_names_by_id"`
		BusinessTimezone   string                                `json:"business_timezone"`
		BusinessHoursStart int                                   `json:"business_hours_start"`
		BusinessHoursEnd   int                                   `json:"business_hours_end"`
		Expected           []wellbeingMultiRepoGoldenExpectedRow `json:"expected"`
	} `json:"team_wellbeing_multi_repo_partition"`
}

// TestComputeWellbeingPerRepoMatchesMultiRepoPartitionGolden is the ORACLE
// regression test for CHAOS-4276 codex round-1 finding 2 (team-lead's
// follow-up: a unit test on the executor's own logic is not an oracle).
//
// tests/fixtures/daily_wellbeing_python_golden.json's
// "team_wellbeing_multi_repo_partition" section is generated by REALLY
// calling compute_team_wellbeing_metrics_daily once per repo_id
// (generate_daily_wellbeing_python_golden.py's _multi_repo_partition_case,
// mirroring worker_metrics.py's `for repo_id in repo_ids` loop) and
// concatenating the results -- exactly what production Python does for a
// partition with more than one repo. This test feeds the SAME
// (undivided) commit rows through computeWellbeingPerRepo -- the Go
// grouping+per-repo loop the bug actually lived in -- and asserts the
// output matches that genuinely-Python-produced expectation. Before the
// finding-2 fix, computeWellbeingPerRepo's predecessor called
// numerical.ComputeTeamWellbeing ONCE over every repo's commits combined,
// which this case's fixture (two repos, deliberately different commit
// counts and after-hours splits) would have caught: an aggregate call
// produces ONE row with commits_count=3, not the two golden rows below.
//
// This is covered by the SAME rot guard as the rest of the file
// (TestTeamWellbeingGoldenMatchesLivePython, internal/jobs/metrics/numerical)
// -- it diffs the generator's entire stdout against the frozen file, so this
// section rots exactly like every other case in it.
func TestComputeWellbeingPerRepoMatchesMultiRepoPartitionGolden(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "tests", "fixtures", "daily_wellbeing_python_golden.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fixture wellbeingMultiRepoGoldenFixture
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if len(fixture.TeamWellbeingMultiRepoPartition) == 0 {
		t.Fatal("golden fixture has no team_wellbeing_multi_repo_partition cases")
	}

	for _, testCase := range fixture.TeamWellbeingMultiRepoPartition {
		t.Run(testCase.Label, func(t *testing.T) {
			day, err := time.Parse("2006-01-02", testCase.Day)
			if err != nil {
				t.Fatal(err)
			}
			tz, err := time.LoadLocation(testCase.BusinessTimezone)
			if err != nil {
				t.Fatal(err)
			}

			repoIDs := make([]uuid.UUID, len(testCase.RepoIDsInOrder))
			for index, raw := range testCase.RepoIDsInOrder {
				repoIDs[index] = uuid.MustParse(raw)
			}

			commits := make([]numerical.Commit, len(testCase.Rows))
			for index, row := range testCase.Rows {
				when, err := time.Parse(time.RFC3339, row.CommitterWhen)
				if err != nil {
					t.Fatalf("parse committer_when %q: %v", row.CommitterWhen, err)
				}
				commits[index] = numerical.Commit{
					RepoID:        row.RepoID,
					AuthorEmail:   derefWellbeingString(row.AuthorEmail),
					AuthorName:    derefWellbeingString(row.AuthorName),
					CommitterWhen: when,
				}
			}

			// The golden's teams_data (generate_daily_wellbeing_python_golden.py's
			// _team_wellbeing_multi_repo_partition): one team, repo-pattern only
			// (no members), owning both repos in this case by exact pattern.
			teams := []WellbeingTeam{
				{ID: "team-repo", Name: "Repo Team", RepoPatterns: []string{"org/service-a", "org/service-b"}},
			}
			repoResolver := NewRepoPatternResolver(teams)
			memberResolver := NewMemberResolver(teams)

			got := computeWellbeingPerRepo(
				day, repoIDs, commits, testCase.RepoNamesByID, repoResolver, memberResolver,
				tz, testCase.BusinessHoursStart, testCase.BusinessHoursEnd,
			)

			want := make([]numerical.TeamWellbeingMetric, len(testCase.Expected))
			for index, row := range testCase.Expected {
				want[index] = row.asMetric()
			}

			gotJSON, _ := json.Marshal(got)
			wantJSON, _ := json.Marshal(want)
			if string(gotJSON) != string(wantJSON) {
				t.Fatalf("case %s:\n got=%s\nwant=%s", testCase.Label, gotJSON, wantJSON)
			}
		})
	}
}
