package remaining

import (
	"encoding/json"
	"math"
	"os"
	"strconv"
	"testing"
)

// Loader post-processing parity, against a corpus generated by driving the real
// ClickHouseMetricsLoader with an injected fake ClickHouse client
// (testdata/generate_recommendations_loader_golden.py).
//
// SCOPE, STATED SO IT IS NOT OVERREAD: this pins the post-processing -- null
// handling, the complexity denominator floor, the absent-versus-zero churn
// decision, gini, and the two list builds. It does NOT pin the SQL text, and it
// does not prove the loader's own composition of these helpers, because the
// helpers are called here in the same order the loader calls them rather than
// through the loader itself. The SQL and the wiring need a real ClickHouse and
// are covered by the Testcontainers test.

type loaderTable struct {
	Columns []string `json:"columns"`
	Rows    [][]any  `json:"rows"`
}

type loaderSnapshot struct {
	WIPByDay               []string `json:"wip_by_day"`
	ThroughputByCycle      []string `json:"throughput_by_cycle"`
	ReviewLatencyP75Hours  *string  `json:"review_latency_p75_hours"`
	ReviewerGini           *string  `json:"reviewer_gini"`
	ReworkChurnRatio       *string  `json:"rework_churn_ratio"`
	AfterHoursRatio        *string  `json:"after_hours_ratio"`
	CycleTimeByDay         []string `json:"cycle_time_by_day"`
	HotspotComplexityDelta *string  `json:"hotspot_complexity_delta"`
	HotspotChurnOverlap    *string  `json:"hotspot_churn_overlap"`
	CompoundingRiskScore   *string  `json:"compounding_risk_score"`
	CompoundingRiskSever   *string  `json:"compounding_risk_severity"`
}

type loaderCase struct {
	Name     string                 `json:"name"`
	Tables   map[string]loaderTable `json:"tables"`
	Snapshot loaderSnapshot         `json:"snapshot"`
}

type loaderDocument struct {
	Environment goldenEnvironment `json:"environment"`
	Cases       []loaderCase      `json:"cases"`
}

func loadLoaderGolden(t *testing.T) loaderDocument {
	t.Helper()
	raw, err := os.ReadFile("testdata/recommendations_loader_golden.json")
	if err != nil {
		t.Fatalf("read loader corpus: %v", err)
	}
	var document loaderDocument
	if err := json.Unmarshal(raw, &document); err != nil {
		t.Fatalf("decode loader corpus: %v", err)
	}
	return document
}

// cellFloat decodes one table cell into the *float64 the loader's scan would
// have produced: JSON null becomes nil, a hex bit pattern becomes the exact
// double. Bits rather than a decimal spelling, for the reason the rule corpus
// records: float.hex() and any decimal form are lossy for NaN.
func cellFloat(t *testing.T, cell any) *float64 {
	t.Helper()
	if cell == nil {
		return nil
	}
	text, ok := cell.(string)
	if !ok {
		t.Fatalf("expected a bit pattern or null, got %T (%v)", cell, cell)
	}
	raw, err := strconv.ParseUint(text, 16, 64)
	if err != nil {
		t.Fatalf("parse bit pattern %q: %v", text, err)
	}
	value := math.Float64frombits(raw)
	return &value
}

// sameFloat64 is the parity comparison for every float in this package's
// corpora: bit-identical, EXCEPT that any two NaNs compare equal.
//
// # WHY NaN IS EXEMPTED, AND WHY ONLY NaN
//
// The NaN SIGN BIT is architecture-dependent. `inf - inf`, `inf / inf` and
// `0.0 / 0.0` all produce the hardware's default quiet NaN, and that default
// differs:
//
//	arm64  (this lane's machine)  0x7ff8000000000000   sign clear
//	x86-64 (the CI runner)        0xfff8000000000000   sign set
//
// CPython does not paper over this -- it uses the same hardware default -- so
// the reference produces the x86 spelling on x86 and the arm spelling on arm,
// exactly as Go does. Parity therefore HOLDS per architecture; what does not
// travel is a corpus that froze one machine's NaN and compared it bitwise
// somewhere else. That is what turned #2142's Go quality run red on seven cases
// whose only defect was having been generated on the wrong CPU.
//
// The sign is also not part of the stored contract: `json.dumps` writes the
// bare token `NaN`, which carries neither sign nor payload, so no downstream
// consumer can observe the difference this comparison is ignoring.
//
// Only NaN is exempted. Everything else stays strictly bit-identical, which
// keeps +0.0 and -0.0 distinct -- they ARE observable (`repr` renders `-0.0`)
// and round() deliberately preserves the sign of zero.
func sameFloat64(got, want float64) bool {
	if math.IsNaN(got) && math.IsNaN(want) {
		return true
	}
	return math.Float64bits(got) == math.Float64bits(want)
}

func wantFloat(t *testing.T, encoded *string) (float64, bool) {
	t.Helper()
	if encoded == nil {
		return 0, false
	}
	raw, err := strconv.ParseUint(*encoded, 16, 64)
	if err != nil {
		t.Fatalf("parse expected bit pattern %q: %v", *encoded, err)
	}
	return math.Float64frombits(raw), true
}

func compareOptional(t *testing.T, caseName, field string, got float64, gotKnown bool, encoded *string) {
	t.Helper()
	want, wantKnown := wantFloat(t, encoded)
	if gotKnown != wantKnown {
		t.Errorf("case %q %s: present=%v, want present=%v (got %v)",
			caseName, field, gotKnown, wantKnown, got)
		return
	}
	if !wantKnown {
		return
	}
	if !sameFloat64(got, want) {
		t.Errorf("case %q %s: %v (%#016x), want %v (%#016x)",
			caseName, field, got, math.Float64bits(got), want, math.Float64bits(want))
	}
}

func compareList(t *testing.T, caseName, field string, got []float64, encoded []string) {
	t.Helper()
	if len(got) != len(encoded) {
		t.Errorf("case %q %s: length %d, want %d -- a length difference means the "+
			"null handling diverged, and length decides the `len(x) < 2` rule guards",
			caseName, field, len(got), len(encoded))
		return
	}
	for index, text := range encoded {
		raw, err := strconv.ParseUint(text, 16, 64)
		if err != nil {
			t.Fatalf("parse %q: %v", text, err)
		}
		want := math.Float64frombits(raw)
		if !sameFloat64(got[index], want) {
			t.Errorf("case %q %s[%d]: %v (%#016x), want %v (%#016x)",
				caseName, field, index, got[index], math.Float64bits(got[index]),
				want, math.Float64bits(want))
		}
	}
}

// column returns the index of a named column, so the test reads cells by name
// rather than by position -- a positional read would silently pair the wrong
// value with the wrong field if the generator's column order ever changed.
func column(t *testing.T, table loaderTable, name string) int {
	t.Helper()
	for index, candidate := range table.Columns {
		if candidate == name {
			return index
		}
	}
	t.Fatalf("column %q not present in %v", name, table.Columns)
	return -1
}

func TestLoaderPostProcessingMatchesTheReference(t *testing.T) {
	document := loadLoaderGolden(t)
	if len(document.Cases) == 0 {
		t.Fatal("empty loader corpus; this test would prove nothing")
	}

	var checked int
	for _, testCase := range document.Cases {
		checked++

		// --- wip / throughput: NULLs KEPT as 0.0 ---
		wipTable := testCase.Tables["wip_throughput"]
		wipRaw := make([]*float64, 0, len(wipTable.Rows))
		throughputRaw := make([]*float64, 0, len(wipTable.Rows))
		if len(wipTable.Rows) > 0 {
			wipIndex := column(t, wipTable, "wip_total")
			throughputIndex := column(t, wipTable, "tp_total")
			for _, row := range wipTable.Rows {
				wipRaw = append(wipRaw, cellFloat(t, row[wipIndex]))
				throughputRaw = append(throughputRaw, cellFloat(t, row[throughputIndex]))
			}
		}
		wip, throughput := wipThroughputFrom(wipRaw, throughputRaw)

		// --- cycle time: NULLs DROPPED ---
		cycleTable := testCase.Tables["cycle_time"]
		cycleRaw := make([]*float64, 0, len(cycleTable.Rows))
		if len(cycleTable.Rows) > 0 {
			cycleIndex := column(t, cycleTable, "avg_ct")
			for _, row := range cycleTable.Rows {
				cycleRaw = append(cycleRaw, cellFloat(t, row[cycleIndex]))
			}
		}
		cycleTimes := cycleTimesFrom(cycleRaw)

		// --- single-row scalars through safeFloat ---
		firstScalar := func(key, columnName string) (float64, bool) {
			table := testCase.Tables[key]
			if len(table.Rows) == 0 {
				return 0, false
			}
			return safeFloat(cellFloat(t, table.Rows[0][column(t, table, columnName)]))
		}
		latency, latencyKnown := firstScalar("latency", "avg_p75")
		rework, reworkKnown := firstScalar("rework", "avg_rework")
		afterHours, afterHoursKnown := firstScalar("team_metrics_daily", "avg_ratio")

		// --- gini over the review loads ---
		giniTable := testCase.Tables["user_metrics_daily"]
		loads := make([]float64, 0, len(giniTable.Rows))
		if len(giniTable.Rows) > 0 {
			reviewIndex := column(t, giniTable, "total_reviews")
			for _, row := range giniTable.Rows {
				loads = append(loads, nullableToZero(cellFloat(t, row[reviewIndex])))
			}
		}
		gini, giniKnown := Gini(loads)

		// --- complexity delta and the churn-overlap decision ---
		var complexityDelta float64
		var complexityKnown bool
		complexityTable := testCase.Tables["repo_complexity_daily"]
		if len(complexityTable.Rows) > 0 {
			firstIndex := column(t, complexityTable, "first_half")
			secondIndex := column(t, complexityTable, "second_half")
			complexityDelta, complexityKnown = complexityDeltaFrom(
				cellFloat(t, complexityTable.Rows[0][firstIndex]),
				cellFloat(t, complexityTable.Rows[0][secondIndex]),
			)
		}
		var totalHotspots uint64
		hotspotTable := testCase.Tables["file_hotspot_daily"]
		if len(hotspotTable.Rows) > 0 {
			raw, ok := hotspotTable.Rows[0][column(t, hotspotTable, "total")].(float64)
			if !ok {
				t.Fatalf("case %q: hotspot total is %T, want a number",
					testCase.Name, hotspotTable.Rows[0][0])
			}
			totalHotspots = uint64(raw)
		}
		churnOverlap, churnKnown := churnOverlapFrom(complexityDelta, complexityKnown, totalHotspots)

		// --- persisted composite ---
		var score float64
		var scoreKnown bool
		severity := ""
		compositeTable := testCase.Tables["compounding_risk_daily"]
		if len(compositeTable.Rows) > 0 {
			row := compositeTable.Rows[0]
			score, scoreKnown = safeFloat(cellFloat(t, row[column(t, compositeTable, "score")]))
			if raw, ok := row[column(t, compositeTable, "severity")].(string); ok {
				severity = raw
			}
		}

		compareList(t, testCase.Name, "wip_by_day", wip, testCase.Snapshot.WIPByDay)
		compareList(t, testCase.Name, "throughput_by_cycle", throughput, testCase.Snapshot.ThroughputByCycle)
		compareList(t, testCase.Name, "cycle_time_by_day", cycleTimes, testCase.Snapshot.CycleTimeByDay)
		compareOptional(t, testCase.Name, "review_latency_p75_hours", latency, latencyKnown, testCase.Snapshot.ReviewLatencyP75Hours)
		compareOptional(t, testCase.Name, "reviewer_gini", gini, giniKnown, testCase.Snapshot.ReviewerGini)
		compareOptional(t, testCase.Name, "rework_churn_ratio", rework, reworkKnown, testCase.Snapshot.ReworkChurnRatio)
		compareOptional(t, testCase.Name, "after_hours_ratio", afterHours, afterHoursKnown, testCase.Snapshot.AfterHoursRatio)
		compareOptional(t, testCase.Name, "hotspot_complexity_delta", complexityDelta, complexityKnown, testCase.Snapshot.HotspotComplexityDelta)
		compareOptional(t, testCase.Name, "hotspot_churn_overlap", churnOverlap, churnKnown, testCase.Snapshot.HotspotChurnOverlap)
		compareOptional(t, testCase.Name, "compounding_risk_score", score, scoreKnown, testCase.Snapshot.CompoundingRiskScore)

		wantSeverity := ""
		if testCase.Snapshot.CompoundingRiskSever != nil {
			wantSeverity = *testCase.Snapshot.CompoundingRiskSever
		}
		if severity != wantSeverity {
			t.Errorf("case %q compounding_risk_severity: %q, want %q",
				testCase.Name, severity, wantSeverity)
		}
	}

	t.Logf("compared %d loader scenarios", checked)
}

// TestLoaderCorpusCoversTheDivergentBehaviours asserts the corpus actually
// contains the cases this port's comments claim are load-bearing.
//
// Each of these was verified against the live reference and each would be
// invisible to a corpus of ordinary values. A corpus that lost them would keep
// passing while proving far less, so they are pinned by outcome rather than by
// name -- a renamed case still counts, a deleted behaviour does not.
func TestLoaderCorpusCoversTheDivergentBehaviours(t *testing.T) {
	document := loadLoaderGolden(t)

	var (
		wipKeptNull      bool // a null wip row survives as 0.0, preserving length
		cycleDroppedNull bool // a null cycle row is dropped, shortening the list
		churnAbsent      bool // no hotspots -> overlap ABSENT
		churnZero        bool // hotspots + non-positive delta -> overlap 0.0
		negativeFirst    bool // denominator floor on a negative first half
	)
	for _, testCase := range document.Cases {
		snapshot := testCase.Snapshot

		wipTable := testCase.Tables["wip_throughput"]
		if len(wipTable.Rows) > 0 && len(snapshot.WIPByDay) == len(wipTable.Rows) {
			for _, row := range wipTable.Rows {
				if row[column(t, wipTable, "wip_total")] == nil {
					wipKeptNull = true
				}
			}
		}
		cycleTable := testCase.Tables["cycle_time"]
		if len(cycleTable.Rows) > len(snapshot.CycleTimeByDay) {
			cycleDroppedNull = true
		}
		if snapshot.HotspotComplexityDelta != nil && snapshot.HotspotChurnOverlap == nil {
			churnAbsent = true
		}
		if overlap, known := wantFloat(t, snapshot.HotspotChurnOverlap); known && overlap == 0 {
			churnZero = true
		}
		if delta, known := wantFloat(t, snapshot.HotspotComplexityDelta); known && delta == 4.0 {
			negativeFirst = true
		}
	}

	for _, required := range []struct {
		present bool
		what    string
	}{
		{wipKeptNull, "a NULL wip row kept as 0.0 (length preserved)"},
		{cycleDroppedNull, "a NULL cycle-time row dropped (length shortened)"},
		{churnAbsent, "churn overlap ABSENT because there are no hotspots"},
		{churnZero, "churn overlap 0.0 because hotspots exist but complexity is not rising"},
		{negativeFirst, "the denominator floor applied to a negative first half"},
	} {
		if !required.present {
			t.Errorf("the corpus no longer exercises: %s -- this behaviour is asserted "+
				"in a comment on the port and is now pinned by nothing", required.what)
		}
	}
}
