package remaining

import (
	"encoding/json"
	"os"
	"testing"
	"time"
)

// Engine parity, against a corpus generated by driving the real
// RuleEngine.evaluate_state through its own injected loader
// (testdata/generate_recommendations_engine_golden.py).
//
// The tombstones are the reason this file exists. See recommendations_engine.go
// for why they are correctness rather than bookkeeping, and why their fields
// come from a different source than the fired rows'.

type engineRecord struct {
	TeamID           string `json:"team_id"`
	OrgID            string `json:"org_id"`
	RuleID           string `json:"rule_id"`
	RuleVersion      string `json:"rule_version"`
	WindowStart      string `json:"window_start"`
	WindowEnd        string `json:"window_end"`
	Fired            bool   `json:"fired"`
	Severity         string `json:"severity"`
	Title            string `json:"title"`
	Rationale        string `json:"rationale"`
	SuccessCriterion string `json:"success_criterion"`
	EvidenceJSON     string `json:"evidence_json"`
	ComputedAt       string `json:"computed_at"`
}

type engineSnapshot struct {
	WIPByDay               []string `json:"wip_by_day"`
	ThroughputByCycle      []string `json:"throughput_by_cycle"`
	ReviewLatencyP75Hours  *string  `json:"review_latency_p75_hours"`
	ReviewerGini           *string  `json:"reviewer_gini"`
	ReworkChurnRatio       *string  `json:"rework_churn_ratio"`
	AfterHoursRatio        *string  `json:"after_hours_ratio"`
	CycleTimeByDay         []string `json:"cycle_time_by_day"`
	HotspotComplexityDelta *string  `json:"hotspot_complexity_delta"`
	HotspotChurnOverlap    *string  `json:"hotspot_churn_overlap"`
	CompoundingRiskScore   *string  `json:"compounding_risk_score"`
	CompoundingRiskSever   *string  `json:"compounding_risk_severity"`
}

type engineCase struct {
	Name       string         `json:"name"`
	Snapshot   engineSnapshot `json:"snapshot"`
	Now        string         `json:"now"`
	WindowDays int            `json:"window_days"`
	Records    []engineRecord `json:"records"`
}

type engineDocument struct {
	Environment  goldenEnvironment `json:"environment"`
	RecordCounts struct {
		Total      int `json:"total"`
		Fired      int `json:"fired"`
		Tombstones int `json:"tombstones"`
	} `json:"record_counts"`
	Cases []engineCase `json:"cases"`
}

func loadEngineGolden(t *testing.T) engineDocument {
	t.Helper()
	raw, err := os.ReadFile("testdata/recommendations_engine_golden.json")
	if err != nil {
		t.Fatalf("read engine corpus: %v", err)
	}
	var document engineDocument
	if err := json.Unmarshal(raw, &document); err != nil {
		t.Fatalf("decode engine corpus: %v", err)
	}
	return document
}

func TestEvaluateStateMatchesTheReference(t *testing.T) {
	document := loadEngineGolden(t)
	if len(document.Cases) == 0 {
		t.Fatal("empty engine corpus; this test would prove nothing")
	}

	var compared, fired, tombstones int
	for _, testCase := range document.Cases {
		now, err := time.Parse(time.RFC3339, testCase.Now)
		if err != nil {
			t.Fatalf("case %q: corpus `now` %q unparseable: %v", testCase.Name, testCase.Now, err)
		}
		// The engine derives the window from `now`, exactly as the reference
		// does: window_end is now's UTC date, window_start is that minus the
		// window length. Rebuilt here rather than read from the corpus, so a
		// port that derived it differently diverges instead of inheriting.
		windowEnd := time.Date(now.UTC().Year(), now.UTC().Month(), now.UTC().Day(), 0, 0, 0, 0, time.UTC)
		windowStart := windowEnd.AddDate(0, 0, -testCase.WindowDays)

		if len(testCase.Records) == 0 {
			t.Fatalf("case %q has no records", testCase.Name)
		}
		// Replayed from the corpus's recorded INPUTS, not reconstructed from
		// its outputs. A test that inferred the snapshot from the results it
		// is checking would agree with them by construction.
		snapshot := decodeEngineSnapshot(t, testCase.Snapshot)
		snapshot.TeamID = testCase.Records[0].TeamID
		snapshot.OrgID = testCase.Records[0].OrgID
		snapshot.WindowStart = windowStart
		snapshot.WindowEnd = windowEnd

		got, evalErr := EvaluateState(snapshot, now, testCase.Records[0].RuleVersion)
		if evalErr != nil {
			t.Fatalf("case %q: EvaluateState failed: %v", testCase.Name, evalErr)
		}

		if len(got) != len(testCase.Records) {
			t.Errorf("case %q: %d records, want %d -- one row per REGISTERED RULE is the "+
				"contract; a missing tombstone leaves a recovered rule surfacing stale guidance",
				testCase.Name, len(got), len(testCase.Records))
			continue
		}

		for index, want := range testCase.Records {
			have := got[index]
			compared++
			if want.Fired {
				fired++
			} else {
				tombstones++
			}

			if have.RuleID != want.RuleID {
				t.Errorf("case %q position %d: rule_id %q, want %q -- emission ORDER is "+
					"part of the contract", testCase.Name, index, have.RuleID, want.RuleID)
				continue
			}
			label := "fired"
			if !want.Fired {
				label = "TOMBSTONE"
			}
			check := func(field, gotValue, wantValue string) {
				t.Helper()
				if gotValue != wantValue {
					t.Errorf("case %q rule %q (%s): %s\n  got:  %q\n  want: %q",
						testCase.Name, want.RuleID, label, field, gotValue, wantValue)
				}
			}
			if have.Fired != want.Fired {
				t.Errorf("case %q rule %q: fired=%v, want %v",
					testCase.Name, want.RuleID, have.Fired, want.Fired)
			}
			check("severity", have.Severity, want.Severity)
			check("title", have.Title, want.Title)
			check("rationale", have.Rationale, want.Rationale)
			check("success_criterion", have.SuccessCriterion, want.SuccessCriterion)
			check("evidence_json", have.EvidenceJSON, want.EvidenceJSON)
			check("team_id", have.TeamID, want.TeamID)
			check("org_id", have.OrgID, want.OrgID)
			check("rule_version", have.RuleVersion, want.RuleVersion)
			check("window_start", have.WindowStart.Format("2006-01-02"), want.WindowStart)
			check("window_end", have.WindowEnd.Format("2006-01-02"), want.WindowEnd)

			wantComputedAt, parseErr := time.Parse(time.RFC3339, want.ComputedAt)
			if parseErr != nil {
				t.Fatalf("corpus computed_at %q unparseable: %v", want.ComputedAt, parseErr)
			}
			if !have.ComputedAt.Equal(wantComputedAt) {
				t.Errorf("case %q rule %q: computed_at %s, want %s",
					testCase.Name, want.RuleID,
					have.ComputedAt.Format(time.RFC3339Nano), wantComputedAt.Format(time.RFC3339Nano))
			}
		}
	}

	if compared == 0 {
		t.Fatal("no records compared; the corpus is empty and this test proved nothing")
	}
	// Both row types must be present. A corpus of all-fired rows would leave
	// the registry-sourced tombstone fields entirely unchecked, which is the
	// one thing this file exists for.
	if fired == 0 {
		t.Error("no FIRED records in the corpus; the evaluator-sourced fields are unchecked")
	}
	if tombstones == 0 {
		t.Error("no TOMBSTONE records in the corpus; the registry-sourced fields are unchecked, " +
			"which is the entire point of this test")
	}
	t.Logf("compared %d records across %d cases: %d fired, %d tombstones",
		compared, len(document.Cases), fired, tombstones)
}

// TestTombstoneFieldsDifferFromTheEvaluators pins the ASYMMETRY itself.
//
// The parity test above would still pass if the registry and the evaluators
// happened to agree -- it compares against recorded output, so it cannot tell
// "correctly took the registry's value" from "took the evaluator's value, which
// is the same". This asserts they are genuinely different, so a port that read
// the wrong source would have somewhere to fail.
func TestTombstoneFieldsDifferFromTheEvaluators(t *testing.T) {
	document := loadEngineGolden(t)

	firedTitles := map[string]map[string]bool{}
	tombTitles := map[string]map[string]bool{}
	for _, testCase := range document.Cases {
		for _, record := range testCase.Records {
			target := tombTitles
			if record.Fired {
				target = firedTitles
			}
			if target[record.RuleID] == nil {
				target[record.RuleID] = map[string]bool{}
			}
			target[record.RuleID][record.Title] = true
		}
	}

	for _, evaluator := range orderedRuleEvaluators {
		fired, tomb := firedTitles[evaluator.id], tombTitles[evaluator.id]
		if len(fired) == 0 || len(tomb) == 0 {
			t.Errorf("rule %q lacks a fired row or a tombstone in the corpus, so the "+
				"asymmetry is unexercised for it", evaluator.id)
			continue
		}
		for title := range tomb {
			if fired[title] {
				t.Errorf("rule %q: tombstone title %q also appears on a FIRED row. The two "+
					"sources have converged, so this corpus can no longer catch a tombstone "+
					"built from the evaluator instead of the registry.", evaluator.id, title)
			}
		}
	}

	// sustainability-risk is the sharpest case and is asserted by name: its
	// tombstone is CRITICAL while its fired row is WARNING. Anyone "tidying"
	// the tombstone to reuse the evaluator's severity inverts it.
	for _, testCase := range document.Cases {
		for _, record := range testCase.Records {
			if record.RuleID != "sustainability-risk" {
				continue
			}
			want := "critical"
			if record.Fired {
				want = "warning"
			}
			if record.Severity != want {
				t.Errorf("sustainability-risk (fired=%v): severity %q, want %q -- the "+
					"tombstone takes CRITICAL from the registry while the fired row takes "+
					"WARNING from the evaluator, and that inversion is deliberate",
					record.Fired, record.Severity, want)
			}
		}
	}
}

func decodeEngineSnapshot(t *testing.T, encoded engineSnapshot) MetricsSnapshot {
	t.Helper()
	latency, latencyKnown := parseOptional(t, encoded.ReviewLatencyP75Hours)
	gini, giniKnown := parseOptional(t, encoded.ReviewerGini)
	churn, churnKnown := parseOptional(t, encoded.ReworkChurnRatio)
	afterHours, afterHoursKnown := parseOptional(t, encoded.AfterHoursRatio)
	complexity, complexityKnown := parseOptional(t, encoded.HotspotComplexityDelta)
	overlap, overlapKnown := parseOptional(t, encoded.HotspotChurnOverlap)
	score, scoreKnown := parseOptional(t, encoded.CompoundingRiskScore)

	severity := ""
	if encoded.CompoundingRiskSever != nil {
		severity = *encoded.CompoundingRiskSever
	}
	return MetricsSnapshot{
		WIPByDay:                    parseList(t, encoded.WIPByDay),
		ThroughputByCycle:           parseList(t, encoded.ThroughputByCycle),
		ReviewLatencyP75Hours:       latency,
		ReviewLatencyP75HoursKnown:  latencyKnown,
		ReviewerGini:                gini,
		ReviewerGiniKnown:           giniKnown,
		ReworkChurnRatio:            churn,
		ReworkChurnRatioKnown:       churnKnown,
		AfterHoursRatio:             afterHours,
		AfterHoursRatioKnown:        afterHoursKnown,
		CycleTimeByDay:              parseList(t, encoded.CycleTimeByDay),
		HotspotComplexityDelta:      complexity,
		HotspotComplexityDeltaKnown: complexityKnown,
		HotspotChurnOverlap:         overlap,
		HotspotChurnOverlapKnown:    overlapKnown,
		CompoundingRiskScore:        score,
		CompoundingRiskScoreKnown:   scoreKnown,
		CompoundingRiskSeverity:     severity,
	}
}
